### ISSUE TITLE
为什么推荐是centos8呢？是因为内核的原因么？

### ISSUE THREAD

**Issue by luciferhs** [opencurve/curve#10]
为什么推荐是centos8呢？是因为内核的原因么？

**Comment by aspirer** [comment]
你好 @luciferhs ，推荐centos8主要是我们这边在这个版本上验证过安装部署流程，并且考虑到外面用户使用的也比较多一些，跟内核版本关系不太大，如果你那边在安装部署过程中遇到了什么问题，可以加我们的微信交流群咨询，多谢~
https://github.com/opencurve/opencurve.github.io/blob/master/image/curve-wechat.jpeg
群人数过多，无法直接扫码加入，先加下这个微信号拉你进去。
