### ISSUE TITLE
Background data deletion fails when s3 is nos

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1000]
**Describe the bug (描述bug)**
Background data deletion fails when s3 is nos

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
fix merge to master #997
fix merge to fs-release0.2.0 #1016

change s3.enableDeleteObjects from True to False
