### ISSUE TITLE
curveadm umount did not wait for fuse to finish flushing the hard disk cache data

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1015]
**Describe the bug (描述bug)**
curveadm umount did not wait for fuse to finish flushing the hard disk cache data

**To Reproduce (复现方法)**
1、fsd=fsd1,anchor=/home/nbs/failover/test1,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
#fsd=fsd6,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,80,4k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=144000,interval=1
2、ls root@pubbeta2-curve2:/mnt/curvefs_disk_cache/1/cache/cachewrite
3、stop vdbench , 
4、sudo /home/nbs/.curveadm/bin/curveadm umount /home/nbs/failover/test1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* upgrade curveadm to v0.0.13
```
$ curveadm -u
```
> NOTE: if the curveadm version lower than `v0.0.12`, you should upgrade twice.

* try mount and umount again
