### ISSUE TITLE
After the cluster io is stuck for a long time, an input output error appears in the file

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1027]
**Describe the bug (描述bug)**
nbs@pubbeta2-curve2:~/failover/test8/#test-dir.0$ ls -lR| grep "^-" | wc -l
ls: cannot access './mdtest_tree.0/mdtest_tree.1/mdtest_tree.15/mdtest_tree.159/mdtest_tree.1593/file.mdtest.0.15937518': Input/output error

fuse: root      319342  319302 60 Jan17 ?        1-06:32:36 /curvefs/client/sbin/curve-fuse -f -o default_permissions -o allow_other -o fsname=test8 -o fstype=s3 -o user=curvefs -o conf=/curvefs/client/conf/client.conf /curvefs/client/mnt

log: nbs@pubbeta2-curve2:/data/logs/curvefs$  *.319342

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
Gāi wèntí zài hòuxù bǎnběn yǐjīng jiějué
12 / 5,000
翻译结果
This issue has been resolved in subsequent versions
