### ISSUE TITLE
truncate may result in data corruption

### ISSUE THREAD

**Issue by h0hmj** [opencurve/curve#1048]
**Describe the bug (描述bug)**
situation:

Assume:
each s3chunkinfo's end == next s3chunkinfo's begin, no overlap
each s3chunkinfo size = 1 for id 0~7
s3compact threshold = 5

State 0: len 8
chunkIndex 0
s3info chunkid [0,1,2,3]
chunkIndex 1
s3info chunkid [4,5,6,7]

Action 1:
truncate -s 1
will change inode len only

State 1: len 1
chunkIndex 0
s3info chunkid [0,1,2,3]
chunkIndex 1
s3info chunkid [4,5,6,7]

Action 2:
truncate -s 8
will add new zero s3chunkinfo to list with same chunkid  <- root cause
chunkid is not unique globally

State 2: len 8
chunkIndex 0
s3info chunkid [0,1,2,3,8]
chunkIndex 1
s3info chunkid [4,5,6,7,8]

Action 3:
meet s3compact threshold
merge all s3info to one with the largest chunkid, and write s3

State 3
chunkIndex 0
s3info chunkid [8]
chunkIndex 1
s3info chunkid [8]

current s3objname rule is
fsid + inodeid + chunkid + blockindex_in_a_chunk + compaction

metadata in State 3 will get same s3objname
result in data corruption

**Expected behavior (期望行为)**

chunkid should be unique, only used by one s3chunkinfo, rather than different s3chunkinfo share the same chunkid

ps: block index in s3obj naming rule is not meaningful. we cannot get data location from name. Using offset of the file will be better, we can calculate chunkindex and blockindex. offset = chunkindex*chunksize + blockindex*blocksize

**Comment by h0hmj** [comment]
ping @baijiaruo @ilixiaocui @Cyber-SiKu

**Comment by baijiaruo** [comment]
This problem still exists, and mds needs to provide an interface to obtain multiple chunkids
