### ISSUE TITLE
Coredump appears when running vdbench

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1050]
**Describe the bug (描述bug)**
Coredump appears when running vdbench

**To Reproduce (复现方法)**

1、fsd=fsd1,anchor=/home/nbs/failover/test1,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test3,depth=1,width=10,files=100,sizes=(1m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test4,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test6,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
#fsd=fsd6,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=144000,interval=1
2、fs  :test3 coredump
![image](https://user-images.githubusercontent.com/67582932/150483682-99b0e797-451b-4a67-9ca8-cdcb313357f0.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/153529107-af56e55c-3ed2-44bb-a071-f10ecb8ff340.png)

**Comment by baijiaruo** [comment]
I found that when the DataCache was released, the corresponding chunkCacheManager had been released, and the dataCachemap was empty. I guess that the read datacache was eliminated by lru to the asynchronous release queue, and it was deleted before it was released, and delete would cause the dataCacheMap to clean up the corresponding dataCache, and at this time the dataCacheMap of the chunkCacheManager was empty, so the chunkCacheManager was also released, and finally appeared the above core dump
