### ISSUE TITLE
vdbench test stability data appears

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1054]
**Describe the bug (描述bug)**

vdbench test stability data appears
![image](https://user-images.githubusercontent.com/67582932/150750141-32b6a67c-5b5c-4a4c-b8e2-3769d4631908.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
Added crc check for read and write data；It is found that the crc of the written object is consistent with the crc of the object on s3, but the crc of the read data is consistent with the crc calculated by all 0；

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/157599019-3a4da990-ed15-4828-adc3-7fae419facdd.png)
![image](https://user-images.githubusercontent.com/7495307/157599029-86834607-16e1-4269-8660-a9c7a710f6ea.png)
2 times the same operation, found that the read data is not the same

**Comment by baijiaruo** [comment]
So the conclusion is that there is a problem with the download of NOS
