### ISSUE TITLE
CurveBS: GetOrAllocateSegment the condition for determining whether a logicalpool is allocatable needs to be optimized

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1058]
https://github.com/opencurve/curve/blob/f85a8131fb45be3a72ef6b83587c05f87a08c070/src/mds/topology/topology_chunk_allocator.cpp#L180

The size of chunkfilepool should be used instead of diskCapacity * poolUsagePercentLimit_

**Comment by yuxubinchen** [comment]
@ilixiaocui 我可做，可以分配给我吗

**Comment by ilixiaocui** [comment]
> @ilixiaocui 我可做，可以分配给我吗

非常欢迎！

**Comment by ilixiaocui** [comment]
> @ilixiaocui 我可做，可以分配给我吗

欢迎提交pr！

**Comment by yuxubinchen** [comment]
我感觉这里逻辑好像没有问题，diskCapacity=diskCapacity * poolUsagePercentLimit_，而chunkfilepool中的chunk可以重新分配

**Comment by yuxubinchen** [comment]
我感觉这里逻辑好像没有问题，diskCapacity=diskCapacity * poolUsagePercentLimit_，而chunkfilepool中的chunk可以重新分配，所以不应该采用chunkfilepool的size吧？

**Comment by yuxubinchen** [comment]
关于这部分对于chunkfilepool的大小，现有情况下只能通过遍历该localpool中chunkserver取出chunkfilepool的大小，chunkserver的统计信息在src/mds/topology/topology_stat.cpp中GetChunkServerStat获得chunkeserver信息，或者可以在TopologyStat维护一个map用于统计，每个local对应chunkfilepool的大小,每次在UpdateChunkServerStat调用时更新,这部分模块是根据heartbeat进行的更新，比metric能够较好一点

**Comment by ilixiaocui** [comment]
> 关于这部分对于chunkfilepool的大小，现有情况下只能通过遍历该localpool中chunkserver取出chunkfilepool的大小，chunkserver的统计信息在src/mds/topology/topology_stat.cpp中GetChunkServerStat获得chunkeserver信息，或者可以在TopologyStat维护一个map用于统计，每个local对应chunkfilepool的大小,每次在UpdateChunkServerStat调用时更新,这部分模块是根据heartbeat进行的更新，比metric能够较好一点


可以的新增map用于记录的。metric主要是用于暴露给promehtues做可视化统计的。

**Comment by yuxubinchen** [comment]
好的，非常感谢

**Comment by yuxubinchen** [comment]
现在遇到情况是有个测试点是直接调用topology进行addlogicalpool的，然后直接调用ChooseSingleLogicalPool，进行分配，然而对于维护chunksizepool的map，是基于topology_stat类的是要等待心跳来update的，所以会产生问题，对于上面情况有必要可以修改测试添加调用topology_stat的update方法来进行心跳模拟

**Comment by xu-chaojie** [comment]
可以依赖心跳，最新的代码在chunkserver启动时总是去注册，你可以修改代码在注册时就把容量带上去
