### ISSUE TITLE
CurveBS: the volume creation should fail when the CurveBS cluster capacity reaches a certain watermark

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1059]

**Comment by yuxubinchen** [comment]
主体思路是在createfile里添加判断，当前分配的容量和剩余大小进行比较，对于剩余size,可以从mds的统计模块可以从metric的模块中拿取，其中metric中不能直接获得LotalLeftSize,只能从LogicalPoolMetric类中 chunkSizeLeftBytes来拿取每个localpools的Leftsize,要遍历整个localpools来进行取和。

**Comment by yuxubinchen** [comment]
@xu-chaojie

**Comment by yuxubinchen** [comment]
或者给TopologyMetricService添加字段TotalLeftSize,来进行统计集群中剩余容量

**Comment by yuxubinchen** [comment]
@xu-chaojie

**Comment by xu-chaojie** [comment]
思路不对，不要用TopologyMetricService中的字段，那里的数据不是实时的，要从src/mds/nameserver2/allocstatistic/alloc_statistic.h中的AllocStatistic对象去拿，参考GetOrAllocSegment函数相关的分配逻辑去做

**Comment by yuxubinchen** [comment]
知道了

**Comment by yuxubinchen** [comment]
遍历localpools算出剩余空间的大小，然后localpool剩余的空间与filesize比较，如可剩余空间大则直接退出循环，否则则进行下一个localpool的判断。对于localpool如何计算出剩余空间，可以从AllocStatistic对象拿每个localpool分配的空间，全部空间大小用所有chunkserver的chunkfilepool的大小之和,这部分需遍历该localpool中chunkserver取出chunkfilepool的大小，chunkserver的统计信息在src/mds/topology/topology_stat.cpp中GetChunkServerStat获得chunkeserver信息,或者直接用物理池*限制大小

**Comment by yuxubinchen** [comment]
@xu-chaojie

**Comment by yuxubinchen** [comment]
主要是感觉遍历localpool通过topology_stat获得每个chunkserver的chunkfilepool的大小，计算较大

**Comment by xu-chaojie** [comment]
遍历是不行的性能不行，先直接用物理池*限制大小吧，后续再修改
