### ISSUE TITLE
chunkserver并发应用模型下得一致性读

### ISSUE THREAD

**Issue by locallocal** [opencurve/curve#1065]
## General Question
chunkserver在处理客户端得读请求时，如代码注释所述会将IO放入并发层处理：
![1643508757(1)](https://user-images.githubusercontent.com/55235286/151684067-b8490e5d-2bad-4c54-8036-84c078c64bc3.png)

但是并发层得读写是分离的，由不同的读写线程处理处理各自的读写队列：
![1643509009(1)](https://user-images.githubusercontent.com/55235286/151684154-eb10efdc-0d3e-42bf-bacc-f4154964e580.png)

所以读请求和和写请求会放在不同的读写队列中，这种情况下一致性读是不是得不到保证？

**Comment by ilixiaocui** [comment]
这里注释没有更新，成为leader提供服务之前，会将所有并发队列中的请求都apply
https://github.com/opencurve/curve/blob/badfe9511ed86061aec19fc8ee2cd3cef64762a9/src/chunkserver/copyset_node.cpp#L450

**Comment by ilixiaocui** [comment]
> ## General Question
> chunkserver在处理客户端得读请求时，如代码注释所述会将IO放入并发层处理： ![1643508757(1)](https://user-images.githubusercontent.com/55235286/151684067-b8490e5d-2bad-4c54-8036-84c078c64bc3.png)
> 
> 但是并发层得读写是分离的，由不同的读写线程处理处理各自的读写队列： ![1643509009(1)](https://user-images.githubusercontent.com/55235286/151684154-eb10efdc-0d3e-42bf-bacc-f4154964e580.png)
> 
> 所以读请求和和写请求会放在不同的读写队列中，这种情况下一致性读是不是得不到保证？

**Comment by aspirer** [comment]
如有其他问题，欢迎添加opencurve微信号，邀请你进群沟通。
