### ISSUE TITLE
UT failed on curvefs test

### ISSUE THREAD

**Issue by aspirer** [opencurve/curve#1092]
**Describe the bug (描述bug)**
fixes two typos, ut test failed, first check two tests failed:
http://59.111.91.248:8080/job/curve_untest_job/3496/console
[  FAILED  ] MetaserverTest.register_to_mds_success
[  FAILED  ] MetaserverTest.test2

other failed tests after recheck:
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] UmountfsToolTest.test_umount_success
[  FAILED  ] UmountfsToolTest.test_umount_failed
[  FAILED  ] UmountfsToolTest.test_umount_connect_failed
[  FAILED  ] UmountfsToolTest.test_umount_init_name
[  FAILED  ] UmountfsToolTest.test_umount_invalid_mountpoint
[  FAILED  ] UmountfsToolTest.test_umount_tool_init
http://59.111.91.248:8080/job/curve_untest_job/3497/console

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by aspirer** [comment]
http://59.111.91.248:8080/job/curve_untest_job/3498/console
[ FAILED ] MetaserverTest.register_to_mds_success
[ FAILED ] MetaserverTest.test2

**Comment by aspirer** [comment]
other failed tests after recheck:
[ FAILED ] 6 tests, listed below:
[ FAILED ] UmountfsToolTest.test_umount_success
[ FAILED ] UmountfsToolTest.test_umount_failed
[ FAILED ] UmountfsToolTest.test_umount_connect_failed
[ FAILED ] UmountfsToolTest.test_umount_init_name
[ FAILED ] UmountfsToolTest.test_umount_invalid_mountpoint
[ FAILED ] UmountfsToolTest.test_umount_tool_init
http://59.111.91.248:8080/job/curve_untest_job/3497/console

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/154909593-7b0ce4be-192e-45f0-a799-1ec2fe7e4295.png)

**Comment by cw123** [comment]
the port 16700 is conflict.

curve/curvefs/test/metaserver/metaserver_test.cpp
```
namespace curvefs {
namespace metaserver {
class MetaserverTest : public ::testing::Test {
 protected:
    void SetUp() override {
        metaserverListenAddr_ = "127.0.0.1:16702";
        topologyServiceAddr_ = "127.0.0.1:16700";
        ASSERT_EQ(0, server_.AddService(&mockTopologyService_,
                                        brpc::SERVER_DOESNT_OWN_SERVICE));
        ASSERT_EQ(0, server_.AddService(&mockHeartbeatService_,
                                        brpc::SERVER_DOESNT_OWN_SERVICE));
        ASSERT_EQ(0, server_.Start(topologyServiceAddr_.c_str(), nullptr));
    }
```
