### ISSUE TITLE
read chunk 的stale read 问题

### ISSUE THREAD

**Issue by lkkey80** [opencurve/curve#111]
阅读代码发现ReadChunkRequest::Process 和 CopysetNode::on_apply 都使用了ConcurrentApplyModule。但是ConcurrentApplyModule对于属于同一个chunk读请求和写请求是分别用不同的任务队列（不同线程）处理的，感觉这样无法保证ReadChunkRequest::Process 描述的可以解决stale read问题。

**Comment by demiaowu** [comment]
对同一个chunk的读写请求会按照chunk id映射到同一个队列里面去

**Comment by lkkey80** [comment]
ConcurrentApplyModule 的Push接口会根据READ和WRITE类型区分不同的读写队列，即使是同一个chunk读请求会统一hash到同一个读队列，但是写请求会进入到另外一个写队列。不是同一个队列。

**Comment by lkkey80** [comment]
@demiaowu

**Comment by xu-chaojie** [comment]
这个一致性保证已经使用其他的方法实现了，具体的方法是：
"为了解决leader切换时导致的问题，考虑到leader切换时，会产生一条NOOP的log来确保配置变更时，提交该条日志保证之前已经applied的log都已经apply，该条日志apply时会调用on_leader_start接口，所以我们可以在该接口调用的时候通过flush并发层来保证一致性。"
“在on_leader_start接口实现中，调用ConcurrentApplyModule的flush接口，保证leader切换时，之前leader上已经apply的数据全部落盘；在on_leader_start调用成功之前，不允许读请求处理。”

**Comment by lkkey80** [comment]
没看到on_leader_start代码里有相关flush操作，代码没同步到github上？
void CopysetNode::on_leader_start(int64_t term) {
    leaderTerm_.store(term, std::memory_order_release);
    ChunkServerMetric::GetInstance()->IncreaseLeaderCount();
    LOG(INFO) << "Copyset: " << GroupIdString()
              << ", peer id: " << peerId_.to_string()
              << " become leader, term is: " << leaderTerm_;
}

**Comment by lkkey80** [comment]
@xu-chaojie

**Comment by ilixiaocui** [comment]
代码已更新上来
