### ISSUE TITLE
coredump appears during vdbench test

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1125]
**Describe the bug (描述bug)**

coredump appears during vdbench test
**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/156483898-2ec19409-5d68-4ddd-90f2-1b698b789f47.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/156487916-e241375b-1b5a-4c97-9e35-1fed62e4d575.png)
![image](https://user-images.githubusercontent.com/7495307/156487947-0d4f0b43-e3d2-4b68-b5f8-b56f16c5b03c.png)
I think there are some bug fixes that haven't been incorporated

**Comment by xu-chaojie** [comment]
this bug has fixed by issue  https://github.com/opencurve/curve/issues/1067,  cherry-pick pr : https://github.com/opencurve/curve/pull/1126
