### ISSUE TITLE
Data inconsistency in ci dailybuild

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1134]
**Describe the bug (描述bug)**
Data inconsistency in ci dailybuild

**To Reproduce (复现方法)**
http://59.111.91.248:8080/job/curve_fs_failover_test/440/

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
resolved
