### ISSUE TITLE
curvefs support listxattr

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#1148]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
The curvefs sholud support listxattr to show all the xattr at a time.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
<img width="548" alt="截屏2022-03-08 下午1 55 00" src="https://user-images.githubusercontent.com/13496900/157175845-8e3d3e09-06c8-4301-85a0-212454229fdf.png">

**Comment by Cyber-SiKu** [comment]
recheck
