### ISSUE TITLE
maybe a bug in BucketInitial

### ISSUE THREAD

**Issue by DyungWang** [opencurve/curve#1175]
```c++
void LeakyBucket::Bucket::BucketInitial(bool burst) {
    if (burst) {
        if (std::fabs(burstLevel) < 0.1) {
            burstBucketEmptyTimes++;
            if (burstBucketEmptyTimes >= FLAGS_bucketEmptyTimes) {
                burstLevelInitial = true;
                burstLevel = burst - static_cast<double>(burst) *
                  FLAGS_bucketLeakIntervalMs /
                    TimeUtility::MilliSecondsPerSecond;
                burstBucketEmptyTimes = 0;
            }
        }
    } else {
        // ...
    }
}
```
local bool burst used for calculate burstLevel, which should be member variable burst ?

**Comment by Cyber-SiKu** [comment]
@wuhongsong

**Comment by wuhongsong** [comment]
> ```c++
> void LeakyBucket::Bucket::BucketInitial(bool burst) {
>     if (burst) {
>         if (std::fabs(burstLevel) < 0.1) {
>             burstBucketEmptyTimes++;
>             if (burstBucketEmptyTimes >= FLAGS_bucketEmptyTimes) {
>                 burstLevelInitial = true;
>                 burstLevel = burst - static_cast<double>(burst) *
>                   FLAGS_bucketLeakIntervalMs /
>                     TimeUtility::MilliSecondsPerSecond;
>                 burstBucketEmptyTimes = 0;
>             }
>         }
>     } else {
>         // ...
>     }
> }
> ```
> 
> local bool burst used for calculate burstLevel, which should be member variable burst ?

@DyungWang   Thanks for your suggestion, could you help to have a pr to correct it ?

**Comment by DyungWang** [comment]
just read source code of this project, and I have no environment to compile project.  @wuhongsong
