### ISSUE TITLE
【CI】df of mountpoint block

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1188]
df of mount point is blocked.
Log as follows：
root@pubbeta2-curve3:/data/logs/curvefs# less curve-fuse.log.INFO.20220318-041637.1242332 | grep "W 2022"
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/15689619/158925477-7c353bfe-868c-4a4a-a4cc-6df2bff0e36c.png">

**Comment by cw123** [comment]
please add branch and commit id

**Comment by cw123** [comment]
https://github.com/opencurve/curve/pull/1184

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/158930527-af129ed4-533c-42e9-9478-6f12711faf1a.png)

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/158930548-6ff63d03-acfb-4c32-b08e-16ef065ccdb6.png)
