### ISSUE TITLE
Initially created copies data is not balanced

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1196]
**Describe the bug (描述bug)**
Initially created copies data is not balanced

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
自测结果，使用这个配置
    mds.topology.PartitionNumberInCopyset: 2
    mds.topology.CreateCopysetNumber: 10
    mds.topology.CreatePartitionNumber: 3

创建fs：
topology_metric_metaserver_id_1_copyset_num 6
topology_metric_metaserver_id_1_partition_num 2
topology_metric_metaserver_id_2_copyset_num 4
topology_metric_metaserver_id_2_partition_num 1
topology_metric_metaserver_id_3_copyset_num 8
topology_metric_metaserver_id_3_partition_num 3
topology_metric_metaserver_id_4_copyset_num 2
topology_metric_metaserver_id_4_partition_num 0
topology_metric_metaserver_id_5_copyset_num 4
topology_metric_metaserver_id_5_partition_num 1
topology_metric_metaserver_id_6_copyset_num 6
topology_metric_metaserver_id_6_partition_num 2
topology_metric_pool_default_pool_copyset_num 10
topology_metric_pool_default_pool_dentry_num 0
topology_metric_pool_default_pool_inode_num 1
topology_metric_pool_default_pool_metaserver_num 6
topology_metric_pool_default_pool_partition_num 3

**Comment by cw123** [comment]
1、优化了copyset的创建算法，copyset的创建分为两个场景：
场景一：集群第一次创建copyset，为每个copyset随机选择metaserver；
场景二：集群已有copyset，继续创建copyset的场景，根据metaserver的资源使用率，选择使用率低的metaserver创建copyset。
2、优化了partition选择copyset的算法，为每个partition都选择一次copyset。
