### ISSUE TITLE
Other files of MD5sum are stuck due to RANDOM I/O write

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1197]
**Describe the bug (描述bug)**
Other files of MD5sum are stuck due to RANDOM I/O write

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Attention: Running just one FIO round will not reproduce the problem. During the actual test, the FIO is run using Supervisor.

I observed that MD5 was stuck: the file was not read yet, but the client did not receive any more read requests, and all existing read requests were processed normally. A preliminary conclusion can be drawn from this phenomenon: Kernel Fuse stops sending down read requests in certain states.
![image](https://user-images.githubusercontent.com/15689619/160319809-766bb68b-b86e-44ee-a27d-214ed8a426ac.png)
![image](https://user-images.githubusercontent.com/15689619/160319827-610f8d74-b1ed-4cae-8df9-dcf7ce08d401.png)

Next observation: there were a lot of requests that didn't return FusOpRelease between the start of the test and the time it got stuck：
![image](https://user-images.githubusercontent.com/15689619/160319862-02e83021-4a4f-42d4-8849-38ed8e82a39f.png)

Combining the above two phenomena, we conclude that read requests are blocked by inflight requests. Let's test this conclusion. Add sleep(600) to FuseOpRelease to make the call stuck. Then use cat to read the existing files. We found that executing cat after a few times would get stuck. When FuseOpRelease is complete, the stuck cat request is complete.
![image](https://user-images.githubusercontent.com/15689619/160319894-055519c8-4790-40df-9977-3759407f9078.png)
This test also found that the call to FuseOpRelease in Close is asynchronous and we have also confirmed this through following data：
![image](https://user-images.githubusercontent.com/15689619/160319931-8a8c196f-fc72-4b47-8399-55c436e0f4c6.png)

**Comment by ilixiaocui** [comment]
Solution：one way is to make FuseOpRelease a synchronous call，but this way depends on the kernel version. Another way is to make the execution time of FuseOpRelease shorter. I chose the second way, let FuseOpFlush handle the logic in FuseOpRelease.
![image](https://user-images.githubusercontent.com/15689619/160319960-74447549-ca8a-4631-abbb-b90971ff9e9f.png)
