### ISSUE TITLE
is there a CSI plugin for Kubernetes?

### ISSUE THREAD

**Issue by calvinyv** [opencurve/curve#12]
## General Question
Just as the title, how to integrate Curve with K8s?

**Comment by aspirer** [comment]
Hi @calvinyv , we have make a patch on CSI plugin for k8s in our internal product envs, we will push the patch to our github repo soon, thanks.

**Comment by spyyang** [comment]
> ## General Question
> Just as the title, how to integrate Curve with K8s?

The curve csi plugin has been released: https://github.com/opencurve/curve-csi
