### ISSUE TITLE
When cto is turned on, mdtest and fio run in parallel, fuse is stuck

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1201]
**Describe the bug (描述bug)**
When cto is turned on, mdtest and fio run in parallel, fuse is stuck

**To Reproduce (复现方法)**
1、mount same fs to  test1 and test9
2、mdtest -C -F -L -z 4 -b 10 -I 10000 -d /home/nbs/failover/test9 -w 1024
3、[global]
rw=randwrite
direct=1
numjobs=1
ioengine=libaio
bsrange=4k-4k
group_reporting
size=10G
fallocate=none
write_iops_log=str

[disk01]
filename=/home/nbs/failover/test9/1.txt
4、ls fuse stuck

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Attention: Running just one FIO round will not reproduce the problem. During the actual test, the FIO is run using Supervisor.

I observed that MD5 was stuck: the file was not read yet, but the client did not receive any more read requests, and all existing read requests were processed normally.
![image](https://user-images.githubusercontent.com/15689619/160317803-9b6b8163-dfcc-4e5d-b0c1-3b56f5382dbe.png)
![image](https://user-images.githubusercontent.com/15689619/160317822-58d4d505-fad4-4abb-8876-df35c69cc70d.png)

**Comment by ilixiaocui** [comment]
Solution：one way is to make FuseOpRelease a synchronous call，but this way depends on the kernel version. Another way is to make the execution time of FuseOpRelease shorter. I chose the second way, let FuseOpFlush handle the logic in FuseOpRelease.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/15689619/160319580-b9ae0829-152a-4614-95fb-bf6b6572da4f.png">

**Comment by ilixiaocui** [comment]
The reason is the same as this issue： https://github.com/opencurve/curve/issues/1197
