### ISSUE TITLE
mdtest\ mkdir\ touch Create files not synchronized on other multi-mounted FUSE

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1205]
**Describe the bug (描述bug)**

![image](https://user-images.githubusercontent.com/67582932/159834982-aebcd1cb-8454-45a4-ae29-969d9ee906eb.png)
![image](https://user-images.githubusercontent.com/67582932/159835005-691e17ed-1e83-4882-a7bd-09f55244338c.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Mount the same filesystem on another machine, the number of files in ls is correct
![image](https://user-images.githubusercontent.com/15689619/160320952-630eaa35-15f1-4899-b9c1-8d19773136f7.png)
![image](https://user-images.githubusercontent.com/15689619/160320965-64a37bab-a005-443b-9143-a5b055216d5d.png)

ls corresponds to the underlying request is ListDentry. The request log of the problem and the correct ListDentry are as follows：
`I 2022-03-24T15:38:27.438580+0800 2140650 metaserver_client.cpp:211] ListDentry done, request: poolId: 1
I 2022-03-24T15:38:27.438609+0800 2140650 dentry_cache_manager.cpp:120] ListDentry fsId = 1, parent = 1, last = , count = 65536, onlyDir = 0, ret = 0, part.size() = 12

I 2022-03-24T15:38:27.438580+0800 2140650 metaserver_client.cpp:211] ListDentry done, request: poolId: 1
copysetId: 1
partitionId: 1
fsId: 1
dirInodeId: 1
**txId: 0**
last: ""
count: 65536
onlyDir: false
response: statusCode: OK
dentrys {
fsId: 1
inodeId: 18260888
parentInodeId: 1
name: "000.log"
txId: 0
type: TYPE_S3
}`

**Comment by ilixiaocui** [comment]
Solution: For operations related to dentry, we need to get the latest txid from mds.
