### ISSUE TITLE
An Input /output error occurs on files created by operating other mount points in multi-mount mode

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1206]
**Describe the bug (描述bug)**
An Input /output error occurs on files created by operating other mount points in multi-mount mode
![image](https://user-images.githubusercontent.com/67582932/159857646-393ea71a-3b92-441f-86ae-4330f7eb455a.png)

![image](https://user-images.githubusercontent.com/67582932/159857685-9cd89f82-d2c0-4720-93ee-66bb245488a9.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by xu-chaojie** [comment]
Same problem as  issue: https://github.com/opencurve/curve/issues/1205

**Comment by xu-chaojie** [comment]
after rm source and destination of rename in different mount point,  cause this problem:
![POPO20220324-165327](https://user-images.githubusercontent.com/5245004/159878920-ab575b5f-f8e0-4679-a782-02a5631eea0a.jpg)
