### ISSUE TITLE
Multiple mount directory Other mount paths are not updated after files are deleted

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1209]
**Describe the bug (描述bug)**
1、test4和test10 挂了同样的文件系统
2、test10 跑mdtest 结束
3、test4里去rm -rf 
4、test10里去创建报错还存在

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Dentry is cached in fuse-client.
Soluntion: if enableCto is on, get dentry from metaserver.
