### ISSUE TITLE
[request help] Curve v2.1 read error for release modle

### ISSUE THREAD

**Issue by Wine93** [opencurve/curve#1210]
# Problem

If we build project with relase modle for Curve `v2.1`, it will report error when reading data.

# Reproduce

* build project with release modle
```
$ make build only=//curvefs/src release=1
```

* deploy cluster and mount filesystem

```
$ curveadm deploy
...
```

* enter mounpoint
```
$ cd /path/to/mountpoint
```

* generate file
```
$ seq 1 100000000 > file
```

* calculate MD5
```
$ md5sum file
```

It will report error which is `Bad File Description`.

**Comment by Cyber-SiKu** [comment]
https://github.com/opencurve/curve/pull/1103

**Comment by Cyber-SiKu** [comment]
[pr](https://github.com/opencurve/curve/pull/1103) (has rebase master)
Triggered step:
1. fio write*4
2. fio randwrite*4
3. fio read *4
4. fio randread *4

all fio read report Bad file Description

but when remount some read wouldn't report  Bad file Description, but when run command again, still report.

**Comment by cw123** [comment]
mount，fio write ok， fio read fail， remount， fio read ok， fio read fail
