### ISSUE TITLE
Failed to restart Metaserver after upgrading metaserver

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1212]
**Describe the bug (描述bug)**
Failed to restart Metaserver after upgrading metaserver

1、image is  harbor.cloud.netease.com/curve/curvefs:citest
2、curveadm upgrade
3、metaserver start fail 
![image](https://user-images.githubusercontent.com/67582932/160074351-34912082-5357-43cd-b700-f0281ac6adf6.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
cto修复之前的版本
