### ISSUE TITLE
Description Echo data is corrupted after being transferred to multiple mounted files

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1213]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
1、mount test1 and test10
2、vdbench test test1
3、run test.sh
#/bin/bash
for i in `seq 1 100`;do 
	echo "test $i" >> /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test10/cyh
	sleep 0.5
	echo "test $i" >> /home/nbs/failover/test10/cyh
	cat /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test10/cyh
	sleep 0.5
done
4、cyh is :
![image](https://user-images.githubusercontent.com/67582932/160079316-23eacc6a-9c73-4aaa-a989-fed37f92422d.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
FuseOpRelease is asynchronously

<img width="808" alt="image" src="https://user-images.githubusercontent.com/15689619/160326345-ff421c28-4ae1-44d5-9ac4-e0b37d6010c2.png">

Solution: same as https://github.com/opencurve/curve/issues/1197
Let FuseOpFlush handle the logic in FuseOpRelease.

**Comment by YunhuiChen** [comment]
This is normal in the Curvebs + Curvefs scenario

![image](https://user-images.githubusercontent.com/67582932/168982278-13f1fc7f-008b-40ad-b214-89febe3ae0d9.png)

**Comment by ilixiaocui** [comment]
mountpoint1: 
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/15689619/180411051-e91d0bed-daf2-495c-9a9b-ddc62c66ee43.png">
mountpoint2:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/15689619/180411084-71965faa-6b92-44aa-ba00-dac2e80a64be.png">

**Comment by ilixiaocui** [comment]
Interface calls corresponding to open and close：
```
I 2022-07-28T10:14:00.800768+0800 1435874 fuse_client.cpp:776] FuseOpGetAttr ino = 1
I 2022-07-28T10:14:00.801374+0800 1451587 fuse_client.cpp:286] FuseOpLookup parent: 1, name: test62
I 2022-07-28T10:14:00.802011+0800 1453049 fuse_client.cpp:776] FuseOpGetAttr ino = 7340752
I 2022-07-28T10:14:00.802593+0800 1452993 fuse_client.cpp:318] FuseOpOpen, ino: 7340752
I 2022-07-28T10:14:00.804301+0800 1452776 fuse_s3_client.cpp:298] FuseOpFlush, ino: 7340752
I 2022-07-28T10:14:00.804888+0800 1435875 fuse_client.cpp:1175] FuseOpRelease, ino: 7340752
```
