### ISSUE TITLE
metaserver's snapshot may have subsequent requests' metadata after snapshot point or broken metadata

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1228]
## General Question

when raft snapshot is triggered, metastore should dump current metadata into disk, but current implement may have some defects.

### snapshot may have subsequent requests' metadata after snapshot point

`MetaStoreImpl::Save` holds the read lock firstly, starts a separate thread to do actual works, and then returns true to the caller which is `CopysetNode::on_snapshot_save`.

After that, raft can apply the client's requests that will query or modify metadata. And, in the separate thread, it builds iterators that point to all current metadata.

These two things can process parallelly, which will lead to snapshot contains subsequent requests' metadata after the snapshot point.

### snapshot may have broken metadata

After the separate thread build iterators, it starts a child process through fork, and all the things are done by the child process.

But in the fork point, there may exist some background tasks that will modify metadata, and this will cause the iterator points to broken or garbage metadata, or invalidate the iterator because the pointed data may be deleted.

**Comment by Wine93** [comment]
agree! 

* for rocksdb storage, i had solve it by using rocksdb's snapshot feature which is a sequence number only.
* for memory storage, maybe we should hold write lock in parent process until child process forked. it's a choice to let child process to notify parent process it's ready by communication such as `socketpair`.
