### ISSUE TITLE
When testing vdbench, the kernel prints an error, and io gets stuck for a few minutes

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1230]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/160959605-5efb9e9f-2a9c-4f45-a8d4-339e58bc6674.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
It may be caused by the existence of unreturned requests (it did not recur later), and now related metrics are added.
