### ISSUE TITLE
copyset.max_inflight_requests not belong to copyset

### ISSUE THREAD

**Issue by xu-chaojie** [opencurve/curve#1255]
copyset.max_inflight_requests not belong to copyset， please change the config name

**Comment by yuxubinchen** [comment]
copyset.max_inflight_requests 不属于 copyset，是应该属于chunkserver吗

**Comment by yuxubinchen** [comment]
@xu-chaojie

**Comment by yuxubinchen** [comment]
copyset.max_inflight_requests 应该属于QoS settings吗？
