### ISSUE TITLE
curvefs/mds/curvefs_mds_test will stuck in GetLeader

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#1259]
**Describe the bug (描述bug)**

curvefs/mds/curvefs_mds_test will deadlock in GetLeader

![image](https://user-images.githubusercontent.com/15775037/162400577-1c4ed91f-4eea-424e-b0c9-56ea619fb560.png)

![image](https://user-images.githubusercontent.com/15775037/162400618-1cff5899-0c9c-4887-ab9e-8689ce1d545d.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: denian10
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
It is not a deadlock just retry lots of times, because the some fields don't inited in option.
