### ISSUE TITLE
Clean up warnings in code compilation

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1264]

**Comment by HehuaTang** [comment]
i want to solve this issue

**Comment by cw123** [comment]
@HehuaTang 你好, 这个任务现在进展如何啦？Developer Activities 将于本周结束。 Hello, how is this task going? Developer Activities will end this week.

**Comment by cw123** [comment]
@HehuaTang 你好, 这个任务现在进展如何啦？  Hello, how is this task going? Do you need help with this task?

**Comment by jiengup** [comment]
Hi, I'm considering to take Curve GSoC23 project. Maybe I can solve this issue while learning the codebase.

**Comment by Alipebt** [comment]
I will try to do this .Please assign me.

**Comment by Alipebt** [comment]
I ' ve encountered a lot of unused variable while cleaning up 
 warnings . Should I just change the compile option to mask it ? Or should I just ignore the warning ?

**Comment by ilixiaocui** [comment]
Would you consider removing these variables if possible？

**Comment by ilixiaocui** [comment]
> I don ' t know if unused variable will be used in the future , but I think I ' ll delete it . thank you.

Generally not, these should be manufactured with irregular coding.

**Comment by Cyber-SiKu** [comment]
@Alipebt Are you still interested in this issue?

**Comment by Alipebt** [comment]
> @Alipebt你还对这个问题感兴趣吗？

Sorry, I can't handle it

**Comment by MizukiCry** [comment]
Hi, I want to try this. 🙂

**Comment by ilixiaocui** [comment]
> Hi, I want to try this. 🙂

Welcome!

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by MizukiCry** [comment]
@ilixiaocui I've noticed that there are some warnings from external libraries, do I need to clean them? If necessary, how to do it?
