### ISSUE TITLE
The fuse log shows that FuseOpGetXattr log print too much

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1276]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/163307963-25c26849-b235-49fd-bb12-6b5a4a774926.png)

![image](https://user-images.githubusercontent.com/67582932/163307974-3b43477c-ddba-4703-b4f2-097074d85034.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
There are same phenomenon when test on cephfs, the write operation will trigger the getxattr operation. Here are the call stack information of curvefs and cephfs.
![POPO20220418-164711](https://user-images.githubusercontent.com/13496900/163904605-68919127-7a49-4d83-b522-f4c88b6fc4d1.jpg)
![POPO20220418-164717](https://user-images.githubusercontent.com/13496900/163904613-d2c12e47-83a4-4643-90d1-25aa90ac3c81.jpg)

**Comment by SeanHai** [comment]
No noticeable change in performance after test on branch/perftest.  enable_xattr vs notenable_xattr

**Comment by SeanHai** [comment]
https://github.com/mar-file-system/marfs/issues/205
