### ISSUE TITLE
Open-only read cache write data is not cached

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1280]
**Describe the bug (描述bug)**

Open-only read cache write data is not cached

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
![image](https://user-images.githubusercontent.com/67582932/163536521-656b9436-5702-4fb0-a74b-871dec6b72c0.png)

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@wuhongsong

**Comment by caoxianfei1** [comment]
@wuhongsong Is it still going on?
