### ISSUE TITLE
Run mk-tar.sh failed on Ubuntu 20

### ISSUE THREAD

**Issue by surpassly** [opencurve/curve#1281]
**Describe the bug (描述bug)**
bash mk-tar.sh

### problem 1: the name 'analysis_test_transition' is not defined
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/12962169/163543147-a2123ac5-0500-4b7b-8c77-f1f1d545b18a.png">

> Solved by update bazel from 0.17.2  to 4.2.2

### problem 2: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/12962169/163543531-ae3252ae-578d-4610-bce8-40ac304b6fb3.png">

> Solved by add bazel flags "--incompatible_blacklisted_protos_requires_proto_info=false --cxxopt -Wno-error=format-security"
```
 if [ `gcc -dumpversion | awk -F'.' '{print $1}'` -le 6 ]
 then
     bazelflags=''
 else
-    bazelflags='--copt -faligned-new'
+    bazelflags='--copt -faligned-new --incompatible_blacklisted_protos_requires_proto_info=false --cxxopt -Wno-error=format-security'
 fi
```

### problem 3: can't find head file of RocksDB
> Solved by add this snippet from ut.sh to install rocksdb
```
################################################################ __ROCKSDB__
g_build_opts=()
kernel_version=`uname -r | awk -F . '{print $1 * 1000 + $2}'`
if [ $kernel_version -gt 5001 ]; then
    g_build_opts+=("--define IO_URING_SUPPORT=1")
fi
g_rocksdb_root="${PWD}/thirdparties/rocksdb"
(cd ${g_rocksdb_root} && make build && make install prefix=${g_rocksdb_root})
################################################################ __ROCKSDB__
```

### problem 4: error: may be used uninitialized in this function [-Werror=maybe-uninitialized]
> Solved by add "--cxxopt -Wno-error=maybe-uninitialized" to bazelflags

**Versions (各种版本)**
OS: ubuntu 20
Compiler: gcc 9
> commit be911ef4a6e8bfa42224b3b904f9758363868488 (HEAD -> master, origin/master, origin/HEAD)
Author: hzwuhongsong@corp.netease.com <hzwuhongsong@corp.netease.com>
Date:   Tue Mar 22 10:51:29 2022 +0800

Since the mk-tar.sh is way too outdated, maybe you can update it and related document as well.

**Comment by Cyber-SiKu** [comment]
problem 1: the name 'analysis_test_transition' is not defined

**Comment by Cyber-SiKu** [comment]
> **Describe the bug (描述bug)** bash mk-tar.sh
> 
> ### problem 1: the name 'analysis_test_transition' is not defined
> <img alt="image" width="1321" src="https://user-images.githubusercontent.com/12962169/163543147-a2123ac5-0500-4b7b-8c77-f1f1d545b18a.png">
> 
> > Solved by update bazel from 0.17.2  to 4.2.2
> 
> ### problem 2: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
> <img alt="image" width="1333" src="https://user-images.githubusercontent.com/12962169/163543531-ae3252ae-578d-4610-bce8-40ac304b6fb3.png">
> 
> > Solved by add bazel flags "--incompatible_blacklisted_protos_requires_proto_info=false --cxxopt -Wno-error=format-security"
> 
> ```
>  if [ `gcc -dumpversion | awk -F'.' '{print $1}'` -le 6 ]
>  then
>      bazelflags=''
>  else
> -    bazelflags='--copt -faligned-new'
> +    bazelflags='--copt -faligned-new --incompatible_blacklisted_protos_requires_proto_info=false --cxxopt -Wno-error=format-security'
>  fi
> ```
> 
> ### problem 3: can't find head file of RocksDB
> > Solved by add this snippet from ut.sh to install rocksdb
> 
> ```
> ################################################################ __ROCKSDB__
> g_build_opts=()
> kernel_version=`uname -r | awk -F . '{print $1 * 1000 + $2}'`
> if [ $kernel_version -gt 5001 ]; then
>     g_build_opts+=("--define IO_URING_SUPPORT=1")
> fi
> g_rocksdb_root="${PWD}/thirdparties/rocksdb"
> (cd ${g_rocksdb_root} && make build && make install prefix=${g_rocksdb_root})
> ################################################################ __ROCKSDB__
> ```
> 
> ### problem 4: error: may be used uninitialized in this function [-Werror=maybe-uninitialized]
> > Solved by add "--cxxopt -Wno-error=maybe-uninitialized" to bazelflags
> 
> **Versions (各种版本)** OS: ubuntu 20 Compiler: gcc 9
> 
> > commit [be911ef](https://github.com/opencurve/curve/commit/be911ef4a6e8bfa42224b3b904f9758363868488) (HEAD -> master, origin/master, origin/HEAD)
> > Author: [hzwuhongsong@corp.netease.com](mailto:hzwuhongsong@corp.netease.com) [hzwuhongsong@corp.netease.com](mailto:hzwuhongsong@corp.netease.com)
> > Date:   Tue Mar 22 10:51:29 2022 +0800
> 
> Since the mk-tar.sh is way too outdated, maybe you can update it and related document as well.

problem 1: the name 'analysis_test_transition' is not defined

**Comment by surpassly** [comment]
这是来自QQ邮箱的自动回复邮件。

**Comment by Cyber-SiKu** [comment]
problem 2: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.

**Comment by Cyber-SiKu** [comment]
you can be compiled in the mirror opencurvedocker/curve-base:build-debian9

**Comment by surpassly** [comment]
这是来自QQ邮箱的自动回复邮件。
