### ISSUE TITLE
performance reduction after enable sumindir

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#1287]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
curve-fuse: perftest-055b65c

container_image: harbor.cloud.netease.com/curve/curvefs:perftest-055b65c
container_pid: host

log_dir: /data/logs/client
client.loglevel: 8
fuseClient.cto: false
data_dir: /data/curvefs/etcd/clienttaos

diskCache.avgFlushBytes: 0
diskCache.burstFlushBytes: 0
diskCache.avgReadFileBytes: 0
diskCache.diskCacheType: 2
enableSumInDir: false
mdsOpt.rpcRetryOpt.addrs: 10.166.16.60:6700,10.166.16.61:6700,10.166.16.62:6700
core_dir: /core
s3.throttle.iopsTotalLimit: 2500
s3.throttle.bpsTotalMB: 5000
diskCache.threads: 15
s3.chunkFlushThreads: 15

diskCache.maxUsableSpaceBytes: 214748364800

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
curvefs version: branch perftest
3 server 3 metaserver(each on one ssd)
mataserve_log_leverl = 0; client_log_level = 0; cto = false
The result is there is a little drop. 444MB -> 411MB

<img width="1435" alt="截屏2022-04-22 16 32 14" src="https://user-images.githubusercontent.com/13496900/164651956-61a1a0c0-0088-4d5e-a7ef-1891c3188432.png">
<img width="1438" alt="截屏2022-04-22 16 37 07" src="https://user-images.githubusercontent.com/13496900/164651973-f8098100-9116-4124-b4ba-4d597ef4afbe.png">

**Comment by wuhongsong** [comment]
enableSumInDir: false
![image](https://user-images.githubusercontent.com/13897133/165213965-d2eb9d4c-06f0-4ba5-8f8e-78aa826e7bfb.png)

enableSumInDir: true
![image](https://user-images.githubusercontent.com/13897133/165213892-d95ecd13-5544-4d6c-988e-97d2a7ab8cd1.png)

**Comment by wuhongsong** [comment]
![image](https://user-images.githubusercontent.com/13897133/165214084-7f4a5729-9d59-4dec-8c53-994944855c2a.png)
as you can see, write start after last write end may wait a moment.

**Comment by wuhongsong** [comment]
![image](https://user-images.githubusercontent.com/13897133/165214847-f2322c2f-b16d-4daf-9b53-03a0f002f589.png)

**Comment by SeanHai** [comment]
Actually the write performance drops when enable enableSumInDir. IOPS dropped from about 2900 to 1900.

The reason why this problem has not been found before is fio filesize=10G and runtime=180, so there are a lot of overwrites behind and overwrites will not update summary xattr. 

After test when add some metrics, the reason for the performance drop is asynchronous RPC requests need to guarantee sequentiality and the next request need to wait until the last request completes. So it is normal in this case.

![截屏2022-04-26 14 49 04](https://user-images.githubusercontent.com/13496900/165245987-f1272bd2-8b76-4b7a-af8e-f781fec9fdfa.png)
![截屏2022-04-26 14 49 51](https://user-images.githubusercontent.com/13496900/165246003-d14dd35c-df80-4178-b85b-bbbf9ec70dae.png)
![截屏2022-04-26 14 50 16](https://user-images.githubusercontent.com/13496900/165246020-a3f61d86-25ea-4a02-a592-020663190334.png)
