### ISSUE TITLE
请问，访问接口支持POSIX吗？

### ISSUE THREAD

**Issue by heliteng** [opencurve/curve#13]

**Comment by aspirer** [comment]
你好 @heliteng ，curve目前不支持POSIX，我们提供的是类似的接口如open、close等，基于这些接口我们开发了块存储服务，大家也可以基于这些接口开发其他存储服务如对象存储等。

**Comment by heliteng** [comment]
> 你好 @heliteng ，curve目前不支持POSIX，我们提供的是类似的接口如open、close等，基于这些接口我们开发了块存储服务，大家也可以基于这些接口开发其他存储服务如对象存储等。

@aspirer 谢谢！后续会考虑支持POSIX吗？我感觉这个功能挺实用的。
