### ISSUE TITLE
`fusermount3 -u mountpoint` cause curve-fuse aborted

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1303]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10327590/164000646-cbf6f6e3-8a16-4937-9550-ecad8b7bf3dc.png">

I am doing some tests based on branch release2.2, and after mounting curve-fuse through command line, and umount by `fusermount3`, the curve-fuse is directly aborted.

**Comment by baijiaruo** [comment]
test umount without core dump problem，Exit normally
![image](https://user-images.githubusercontent.com/7495307/167062834-c275cf36-dc4e-4a6b-82c1-6ec24f84ebb5.png)

**Comment by wu-hanqing** [comment]
might be fixed by #1415
