### ISSUE TITLE
Disk cache statistics are inaccurate

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1316]
**Describe the bug (描述bug)**
<img width="319" alt="image" src="https://user-images.githubusercontent.com/15689619/164215926-27a18184-c473-429c-8bc9-02ec9ba70710.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/15689619/164216083-4c37cf65-6ead-419a-b106-cc59ddd90439.png">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
diskcache use the  common lru algorithm.
so diskcache_cache_counts is put counts, diskcache_cache_bytes is put bytes.
