### ISSUE TITLE
Disk cache will not be trimmed after using 90%

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1331]
**Describe the bug (描述bug)**

Disk cache will not be trimmed after using 90%
**To Reproduce (复现方法)**
1、test vdbench
fsd=fsd7,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(10m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=120000,interval=1
2、
![image](https://user-images.githubusercontent.com/67582932/164626840-787cb003-4ea4-495d-b6a8-6e525451af11.png)
3、
![image](https://user-images.githubusercontent.com/67582932/164627141-57d3fc93-c3ce-42b1-8c23-c47e5215210a.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
The possible reasons for this phenomenon are the speed is slow upload to S3。  so after the vdbench is stop ，This phenomenon will disappear

**Comment by wuhongsong** [comment]
need repetition
