### ISSUE TITLE
The space uploaded by s3 is more than 2 times the actual space used in the logging scene

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1348]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/165012629-82ed06ae-e04e-4db6-bb94-513f6106ed9d.png)
![image](https://user-images.githubusercontent.com/67582932/165012651-e7310531-4cd2-4aa1-bc34-8035ab9e2511.png)

**To Reproduce (复现方法)**
1、mount fuse to  curvefs log dir

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
使用场景是使用curvefs的fs，挂载之后，用来打印日志。
写入的日志文件总大小，小于后端写入S3的数据的总大小。打了551G的日志，后端s3却看到有929G。
具体到每个日志文件，发现有部分日志文件的大小和写入s3的文件大小不一致，相差可以达到10倍以上。
stat查看的文件大小
![image](https://user-images.githubusercontent.com/4277834/165231529-04596294-4070-42a0-b4a1-71c1d01efd82.png)
s3统计出来的文件大小
![image](https://user-images.githubusercontent.com/4277834/165231573-dfe53021-0ddb-4458-b717-739a23628738.png)

**Comment by cw123** [comment]
s3的文件分片
![image](https://user-images.githubusercontent.com/4277834/165231712-d5abd076-8e25-44cc-a932-bd0ea9a2f89e.png)

**Comment by cw123** [comment]
client端收到的请求，请求为顺序写
![image](https://user-images.githubusercontent.com/4277834/165231774-38986c02-d143-4f85-9f98-388bbb01e46b.png)

**Comment by cw123** [comment]
inode中记录的元数据
![image](https://user-images.githubusercontent.com/4277834/165231817-9ecc0d52-e1e6-4f4b-94af-90deb31468ee.png)
