### ISSUE TITLE
It seems the same architechure with GFS?

### ISSUE THREAD

**Issue by zhanglistar** [opencurve/curve#135]
## General Question
rt.

**Comment by ilixiaocui** [comment]
Yes, we refer to the GFS architecture and metadata design

**Comment by zhanglistar** [comment]
> Yes, we refer to the GFS architecture and metadata design

So will you do replace HDFS with curve?

**Comment by ilixiaocui** [comment]
HDFS is mainly for the storage requirements of big data scenarios, the main focus of its design is throughput performance. But it is impossible to output high-performance block device requirements based on this. However, the design of HDFS, such as the design of metadata, can be referred to.

**Comment by zhanglistar** [comment]
> HDFS is mainly for the storage requirements of big data scenarios, the main focus of its design is throughput performance. But it is impossible to output high-performance block device requirements based on this. However, the design of HDFS, such as the design of metadata, can be referred to.

I want to replace hdfs with higher performance storage like ceph or qfs or else, maybe curve is another option.

**Comment by aspirer** [comment]
> > HDFS is mainly for the storage requirements of big data scenarios, the main focus of its design is throughput performance. But it is impossible to output high-performance block device requirements based on this. However, the design of HDFS, such as the design of metadata, can be referred to.
> 
> I want to replace hdfs with higher performance storage like ceph or qfs or else, maybe curve is another option.

Thanks for your attention, welcome to join our wechat group, you can add the "opencurve" wechat account, and he will invite you join the group.
