### ISSUE TITLE
The performance of read-write mixed scenarios is unstable

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1353]
**Describe the bug (描述bug)**

The performance of read-write mixed scenarios is unstable
**To Reproduce (复现方法)**
1、fio -directory=/home/nbs/failover/test1 -ioengine=psync -rw=readwrite -bs=512k -direct=1 -group_reporting=1 -fallocate=none -time_based=1 -name=1.txt -numjobs=1 -nrfiles=1 -size=100G
2、￼

**Expected behavior (期望[行为]()**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
root@pubbeta2-curve13:/mnt/whs006# sudo fio -directory=./test -ioengine=psync -rw=readwrite -bs=512k -direct=1 -group_reporting=1 -fallocate=none -time_based=1 -name=1.txt -numjobs=1 -nrfiles=1 -size=100G
fio: time_based requires a runtime/timeout setting
1.txt: (g=0): rw=rw, bs=(R) 512KiB-512KiB, (W) 512KiB-512KiB, (T) 512KiB-512KiB, ioengine=psync, iodepth=1
fio-3.12
Starting 1 process
1.txt: Laying out IO file (1 file / 102400MiB)
Jobs: 1 (f=1): [f(1)][100.0%][eta 00m:00s]
1.txt: (groupid=0, jobs=1): err= 0: pid=1139262: Thu May  5 14:36:34 2022
  read: IOPS=420, BW=210MiB/s (220MB/s)(50.0GiB/243875msec)
    clat (usec): min=87, max=228185, avg=1548.57, stdev=4036.11
     lat (usec): min=87, max=228185, avg=1548.68, stdev=4036.11
    clat percentiles (usec):
     |  1.00th=[   100],  5.00th=[   116], 10.00th=[   128], 20.00th=[   151],
     | 30.00th=[   408], 40.00th=[   469], 50.00th=[  1631], 60.00th=[  1745],
     | 70.00th=[  1844], 80.00th=[  1991], 90.00th=[  2245], 95.00th=[  2900],
     | 99.00th=[ 14615], 99.50th=[ 17433], 99.90th=[ 22414], 99.95th=[ 31327],
     | 99.99th=[208667]
   bw (  KiB/s): min=23552, max=943104, per=100.00%, avg=215272.02, stdev=107641.93, samples=487
   iops        : min=   46, max= 1842, avg=420.44, stdev=210.24, samples=487
  write: IOPS=419, BW=210MiB/s (220MB/s)(49.0GiB/243875msec); 0 zone resets
    clat (usec): min=134, max=627528, avg=813.76, stdev=12537.48
     lat (usec): min=140, max=627554, avg=830.74, stdev=12537.49
    clat percentiles (usec):
     |  1.00th=[   159],  5.00th=[   178], 10.00th=[   190], 20.00th=[   204],
     | 30.00th=[   217], 40.00th=[   227], 50.00th=[   235], 60.00th=[   247],
     | 70.00th=[   265], 80.00th=[   289], 90.00th=[   351], 95.00th=[   412],
     | 99.00th=[   498], 99.50th=[   766], 99.90th=[242222], 99.95th=[316670],
     | 99.99th=[455082]
   bw (  KiB/s): min=23552, max=956416, per=100.00%, avg=214887.21, stdev=109584.28, samples=487
   iops        : min=   46, max= 1868, avg=419.68, stdev=214.03, samples=487
  lat (usec)   : 100=0.53%, 250=42.32%, 500=27.66%, 750=1.65%, 1000=0.15%
  lat (msec)   : 2=18.04%, 4=8.01%, 10=0.60%, 20=0.77%, 50=0.11%
  lat (msec)   : 100=0.02%, 250=0.08%, 500=0.04%, 750=0.01%
  cpu          : usr=0.95%, sys=2.04%, ctx=409676, majf=0, minf=413
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=102481,102319,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=210MiB/s (220MB/s), 210MiB/s-210MiB/s (220MB/s-220MB/s), io=50.0GiB (53.7GB), run=243875-243875msec
  WRITE: bw=210MiB/s (220MB/s), 210MiB/s-210MiB/s (220MB/s-220MB/s), io=49.0GiB (53.6GB), run=243875-243875msec


as you can see, 99.50 of the io is less than 1ms
