### ISSUE TITLE
CI：Inconsistent data in vdbench test

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1361]
**Describe the bug (描述bug)**

http://59.111.91.248:8080/job/curve_fs_failover_test/560/robot/report/log.html
![image](https://user-images.githubusercontent.com/67582932/165431683-2c084d9e-293d-4cbb-a421-7d3894c3bf0c.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
the s3 object(2_19_43752_2_0， 2_19_60166_10_0， 2_19_63253_4_0) has copyed to public account in the machine of mino

**Comment by wuhongsong** [comment]
as you can see, the s3 object md5 is equal to the write md5。 so the error may  occur when datacahe read

**Comment by baijiaruo** [comment]
The log has been cleaned up, to be reproduced

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/173173562-f9ca1592-5532-4196-990c-432c98dcc945.png)
From the log, we can see that the chunkid of the s3info currently being flushed by the flush has reached 42744, but the chunkid of the inode information at the bottom is still 42704, and all the following ones are lost.

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/173173601-fb0c8de4-2811-4a1a-bf30-91b51e1e6cd8.png)
vdbench ran out of inconsistent errors with all 0s

**Comment by baijiaruo** [comment]
After analysis, in the cto scenario, icache is directly removed in the getinode function, so the inode is overwritten if it is brushed.

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/173178217-ce7d5211-97ea-4d9e-94fa-174256e6c987.png)
In the getInode function, the inode is eliminated through lru, and the dirty data of the inode is asynchronously flushed to the metaserver. There is a problem here. The cache is eliminated first, and before the flush is successful, another thread will get an old inode from the metaserver and make a read request, which will cause inconsistency.
