### ISSUE TITLE
brpc can not be compiled on high version glibc

### ISSUE THREAD

**Issue by skypexu** [opencurve/curve#1370]
**Describe the bug (描述bug)**
brpc redefined gcc atttribute `__const__ `to empty string, this does not work on high version glibc, for example on version 2.35-0ubuntu3. the problem is glibc defined a macro glibc_has_attribute which is a redefinition of `__has_attribute`, `__has_attribute` needs a non-empty argument, for example `__has_attribute(__const__)`, if `__const__` is empty string, compiler will fail.

**To Reproduce (复现方法)**
compile curve on ubuntu jammy 

**Expected behavior (期望行为)**
can be compiled

**Versions (各种版本)**
OS: ubuntu jammy 
Compiler: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by fansehep** [comment]
The problem has been solved. https://github.com/apache/incubator-brpc/pull/1783
