### ISSUE TITLE
rocksdb version metaserver takes up a lot of memory

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1381]
**Describe the bug (描述bug)**
rocksdb version metaserver takes up a lot of memory

**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/165905495-e6aba65d-2f13-4f2c-8996-3f75fc1ddb5d.png)
![image](https://user-images.githubusercontent.com/67582932/165905542-2937d146-48a0-488b-9678-ab12b7f4e7cd.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
The bug fixed, for test, i deploy a cluster and run `mdtest` to create many files for monitor metaserver's memory. the cluster 
running about 17 hours and creates `7633225` files,  and the metaserver cost about 5GB memory, it's what we expected. 
the below images will explain it.

* mdtest:
```
$ mdtest -C -F -L -z 4 -b 10 -I 10000 -d /path/to/mount -w 1024
```

* number of files:
![image](https://user-images.githubusercontent.com/9267583/167057098-f6ec6246-5dc2-44dd-9c5f-6760035c41b8.png)

* cluster status:
![image](https://user-images.githubusercontent.com/9267583/167056990-35a9d908-5533-440b-8ce4-d858bac18633.png)

* metaserver memory usage:
![image](https://user-images.githubusercontent.com/9267583/167056954-bf7f176c-1fb4-4972-aa20-811b27aa5e32.png)

* jeprof:
