### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by renatozhang** [opencurve/curve#14]
## General Question
安装过程中总是提示创建文件被拒绝

**Comment by bai-charisu** [comment]
你好，可以进一步描你的问题吗？安装是指部署集群吗？操作系统，ansible版本，截图补充一下呢

**Comment by renatozhang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opencurve/curve"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 下午5:34
收件人:&nbsp;"opencurve/curve"<curve@noreply.github.com&gt;;
抄送:&nbsp;"Z"<865548937@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [opencurve/curve] 安装失败 (#14)





 
你好，可以进一步描你的问题吗？安装是指部署集群吗？操作系统，ansible版本，截图补充一下呢

**Comment by renatozhang** [comment]
单机部署

**Comment by aspirer** [comment]
你好 @renatozhang ，麻烦提供下详细的安装环境信息，如操作系统发行版、ansible版本等。

**Comment by aspirer** [comment]
https://github.com/opencurve/opencurve.github.io/blob/master/image/curve-wechat.jpeg
方便的话可以加上我们的沟通群，那边回复你的问题会比较及时。

**Comment by renatozhang** [comment]
VM workstation 操作系统：centos8.2&nbsp; &nbsp;ansible: 2.9.10&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opencurve/curve"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 晚上8:54
收件人:&nbsp;"opencurve/curve"<curve@noreply.github.com&gt;;
抄送:&nbsp;"Z"<865548937@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [opencurve/curve] 安装失败 (#14)





 
https://github.com/opencurve/opencurve.github.io/blob/master/image/curve-wechat.jpeg
 方便的话可以加上我们的沟通群，那边回复你的问题会比较及时。

**Comment by renatozhang** [comment]
![image](https://user-images.githubusercontent.com/50505086/88000837-41714600-cb31-11ea-99a9-4a3d5ebc0ae6.png)

**Comment by bai-charisu** [comment]
ansible版本是多少？我们目前只支持ansible 2.5.9下的安装

**Comment by renatozhang** [comment]
ansible改为2.5.9后曲折的通过&nbsp; &nbsp;目前集群状态为提示不健康&nbsp;&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "charisu"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午4:51
收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 
抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [opencurve/curve] 安装失败 (#14)





 
ansible版本是多少？我们目前只支持ansible 2.5.9下的安装
 
&mdash;

**Comment by aspirer** [comment]
能否把集群状态详情贴一下过来？

**Comment by renatozhang** [comment]
硬盘怎么添加到curve中去



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wangpan"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上6:39
收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 
抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [opencurve/curve] 安装失败 (#14)





 
能否把集群状态详情贴一下过来？
 
&mdash;

**Comment by renatozhang** [comment]
[curve@curve curve-ansible]$ curve_ops_tool status
curve_ops_tool: /lib64/libcurl.so.4: no version information available (required by /lib64/libaws-cpp-sdk-core.so)
Cluster status:
Get status metric from 127.0.0.1:8081 fail
No snapshot-clone-server is active
snapshot-clone-server 127.0.0.1:5556 is offline
cluster is not healthy
total copysets: 100, unhealthy copysets: 0, unhealthy_ratio: 0%
physical pool number: 1, logical pool number: 1
total space = 0GB, logical used = 0GB(0.00%, can be recycled = 0GB(0.00%)), physical used = 0GB(0.00%)


Client status:&nbsp;


MDS status:
version: 0.1.1
current MDS: 127.0.0.1:6666
online mds list: 127.0.0.1:6666
offline mds list:&nbsp;


Etcd status:
version: 3.4.0
current etcd: 127.0.0.1:2379
online etcd list: 127.0.0.1:2379
offline etcd list:&nbsp;


SnapshotCloneServer status:
no version found!
GetAndCheckSnapshotCloneVersion fail
Get status metric from 127.0.0.1:8081 fail
current snapshot-clone-server:&nbsp;
online snapshot-clone-server list:&nbsp;
offline snapshot-clone-server list: 127.0.0.1:5556


ChunkServer status:
version: 0.1.1
chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: [])
left size: min = 0GB, max = 0GB, average = 0.00GB, range = 0GB, variance = 0.00





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wangpan"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上6:39
收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 
抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [opencurve/curve] 安装失败 (#14)





 
能否把集群状态详情贴一下过来？
 
&mdash;

**Comment by renatozhang** [comment]
硬盘怎么添加到curve中去$ curve_ops_tool status
curve_ops_tool: /lib64/libcurl.so.4: no version information available (required by /lib64/libaws-cpp-sdk-core.so)
Cluster status:
Get status metric from 127.0.0.1:8081 fail
No snapshot-clone-server is active
snapshot-clone-server 127.0.0.1:5556 is offline
cluster is not healthy
total copysets: 100, unhealthy copysets: 0, unhealthy_ratio: 0%
physical pool number: 1, logical pool number: 1
total space = 0GB, logical used = 0GB(0.00%, can be recycled = 0GB(0.00%)), physical used = 0GB(0.00%)


Client status:&nbsp;


MDS status:
version: 0.1.1
current MDS: 127.0.0.1:6666
online mds list: 127.0.0.1:6666
offline mds list:&nbsp;


Etcd status:
version: 3.4.0
current etcd: 127.0.0.1:2379
online etcd list: 127.0.0.1:2379
offline etcd list:&nbsp;


SnapshotCloneServer status:
no version found!
GetAndCheckSnapshotCloneVersion fail
Get status metric from 127.0.0.1:8081 fail
current snapshot-clone-server:&nbsp;
online snapshot-clone-server list:&nbsp;
offline snapshot-clone-server list: 127.0.0.1:5556


ChunkServer status:
version: 0.1.1
chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: [])
left size: min = 0GB, max = 0GB, average = 0.00GB, range = 0GB, variance = 0.00



------------------ 原始邮件 ------------------
发件人: "Wangpan"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 晚上6:39
收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 
抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [opencurve/curve] 安装失败 (#14)





 
能否把集群状态详情贴一下过来？

**Comment by bai-charisu** [comment]
> 硬盘怎么添加到curve中去$ curve_ops_tool status curve_ops_tool: /lib64/libcurl.so.4: no version information available (required by /lib64/libaws-cpp-sdk-core.so) Cluster status: Get status metric from 127.0.0.1:8081 fail No snapshot-clone-server is active snapshot-clone-server 127.0.0.1:5556 is offline cluster is not healthy total copysets: 100, unhealthy copysets: 0, unhealthy_ratio: 0% physical pool number: 1, logical pool number: 1 total space = 0GB, logical used = 0GB(0.00%, can be recycled = 0GB(0.00%)), physical used = 0GB(0.00%) Client status:&nbsp; MDS status: version: 0.1.1 current MDS: 127.0.0.1:6666 online mds list: 127.0.0.1:6666 offline mds list:&nbsp; Etcd status: version: 3.4.0 current etcd: 127.0.0.1:2379 online etcd list: 127.0.0.1:2379 offline etcd list:&nbsp; SnapshotCloneServer status: no version found! GetAndCheckSnapshotCloneVersion fail Get status metric from 127.0.0.1:8081 fail current snapshot-clone-server:&nbsp; online snapshot-clone-server list:&nbsp; offline snapshot-clone-server list: 127.0.0.1:5556 ChunkServer status: version: 0.1.1 chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: []) left size: min = 0GB, max = 0GB, average = 0.00GB, range = 0GB, variance = 0.00
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Wangpan"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 晚上6:39 收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [opencurve/curve] 安装失败 (#14) 能否把集群状态详情贴一下过来？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，从工具的显示来看是正常的，集群不健康是因为快照克隆服务没有部署，如果不需要快照功能，可以忽略这个错误。
你说的添加磁盘到curve是指添加物理磁盘给chunkserver用吗？还是创建一个curve的云硬盘？

**Comment by renatozhang** [comment]
添加物理磁盘给chunkserver用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: charisu <notifications@github.com&gt;
发送时间: 2020年7月21日 21:55
收件人: opencurve/curve <curve@noreply.github.com&gt;
抄送: renatozhang <865548937@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[opencurve/curve] 安装失败 (#14)






硬盘怎么添加到curve中去$ curve_ops_tool status curve_ops_tool: /lib64/libcurl.so.4: no version information available (required by /lib64/libaws-cpp-sdk-core.so) Cluster status: Get status metric from 127.0.0.1:8081 fail No snapshot-clone-server is active snapshot-clone-server 127.0.0.1:5556 is offline cluster is not healthy total copysets: 100, unhealthy copysets: 0, unhealthy_ratio: 0% physical pool number: 1, logical pool number: 1 total space = 0GB, logical used = 0GB(0.00%, can be recycled = 0GB(0.00%)), physical used = 0GB(0.00%) Client status:&nbsp; MDS status: version: 0.1.1 current MDS: 127.0.0.1:6666 online mds list: 127.0.0.1:6666 offline mds list:&nbsp; Etcd status: version: 3.4.0 current etcd: 127.0.0.1:2379 online etcd list: 127.0.0.1:2379 offline etcd list:&nbsp; SnapshotCloneServer status: no version found! GetAndCheckSnapshotCloneVersion fail Get status metric from 127.0.0.1:8081 fail current snapshot-clone-server:&nbsp; online snapshot-clone-server list:&nbsp; offline snapshot-clone-server list: 127.0.0.1:5556 ChunkServer status: version: 0.1.1 chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: []) left size: min = 0GB, max = 0GB, average = 0.00GB, range = 0GB, variance = 0.00
…
------------------ 原始邮件 ------------------ 发件人: "Wangpan"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 晚上6:39 收件人: "opencurve/curve"<curve@noreply.github.com&gt;; 抄送: "Z"<865548937@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [opencurve/curve] 安装失败 (#14) 能否把集群状态详情贴一下过来？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，从工具的显示来看是正常的，集群不健康是因为快照克隆服务没有部署，如果不需要快照功能，可以忽略这个错误。
你说的添加磁盘到curve是指添加物理磁盘给chunkserver用吗？还是创建一个curve的云硬盘？

**Comment by bai-charisu** [comment]
chunkserver和磁盘对应是在部署的时候就指定的，部署结束以后只能通过扩容的方式增加磁盘以及对应的chunkserver。
我们的curve-ansible目前提供了两种部署方式，单机部署和多机部署。单机部署默认是不挂盘的，只是创建一个data目录，多机部署默认是预格式化所有磁盘，有几个磁盘就部署几个chunkserver。
请问你是单机部署还是多机部署，是只想挂载一部分磁盘还是全部数据盘？

**Comment by renatozhang** [comment]
部署结束以后只能通过扩容的方式增加磁盘以及对应的chunkserver 是不是重新执行playbook 还是怎么操作

**Comment by bai-charisu** [comment]
单机部署只是个demo，不支持扩容。多机部署的情况扩容比较复杂，文档和自动化都还在整理中。

**Comment by renatozhang** [comment]
单机部署后容量为零&nbsp; 可用容量不应该是data目录所在分区的容量大小么？&nbsp; 挂载全部数据盘该怎么操作，另外是否支持nvme盘？


-----------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opencurve/curve"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上10:57
收件人:&nbsp;"opencurve/curve"<curve@noreply.github.com&gt;;
抄送:&nbsp;"Z"<865548937@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [opencurve/curve] 安装失败 (#14)





 
chunkserver和磁盘对应是在部署的时候就指定的，部署结束以后只能通过扩容的方式增加磁盘以及对应的chunkserver。
 我们的curve-ansible目前提供了两种部署方式，单机部署和多机部署。单机部署默认是不挂盘的，只是创建一个data目录，多机部署默认是预格式化所有磁盘，有几个磁盘就部署几个chunkserver。
 请问你是单机部署还是多机部署，是只想挂载一部分磁盘还是全部数据盘？

**Comment by bai-charisu** [comment]
在实际的生产环境中，chunkserver需要将盘的部分空间（我们一般是80%）格式化成chunkFilePool，剩余的空间用于存放braft的WAL等数据。因此chunkserver能够用到的容量不是分区的容量大小而是chunkFilePool的容量。curve_ops_tool中统计的容量是chunkFilePool的容量，单机部署的情况下没有chunkFilePool，所以显示为0。

如果想要挂载全部数据盘的话，参考[部署文档](https://github.com/opencurve/curve/blob/master/docs/cn/deploy.md) 中的多机部署步骤，格式化chunkFilePool，挂盘都可以自动化完成的。

我们是通过文件系统读写的，所以nvme也是支持的

**Comment by renatozhang** [comment]
[curve@curve curve-ansible]$ sudo curve create --filename /test --length 10 --user curve
Traceback (most recent call last):
  File "curvefs_tool.py", line 20, in <module>
    import curvefs
  File "/usr/curvefs/curvefs.py", line 37, in <module>
    _curvefs = swig_import_helper()
  File "/usr/curvefs/curvefs.py", line 36, in swig_import_helper
    return importlib.import_module('_curvefs')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libunwind.so.8: cannot open shared object file: No such file or directory

**Comment by wu-hanqing** [comment]
> [curve@curve curve-ansible]$ sudo curve create --filename /test --length 10 --user curve
> Traceback (most recent call last):
> File "curvefs_tool.py", line 20, in
> import curvefs
> File "/usr/curvefs/curvefs.py", line 37, in
> _curvefs = swig_import_helper()
> File "/usr/curvefs/curvefs.py", line 36, in swig_import_helper
> return importlib.import_module('_curvefs')
> File "/usr/lib64/python2.7/importlib/**init**.py", line 37, in import_module
> **import**(name)
> ImportError: libunwind.so.8: cannot open shared object file: No such file or directory

查看一下libunwind软件包有没有安装，如果没有尝试从软件源或者编译安装。
如果已经安装，看一下libunwind.so.8的目录，把目录加到`LD_LIBRARY_PATH`中
