### ISSUE TITLE
单机部署-nbd读写挂起

### ISSUE THREAD

**Issue by qiuyi21** [opencurve/curve#140]
**Describe the bug (描述bug)**
单机部署-nbd读写挂起

**To Reproduce (复现方法)**
CentOS 8.2下单机部署，map nbd后读写/dev/nbd0

**Expected behavior (期望行为)**
正常读写

**Versions (各种版本)**
OS: CentOS 8.2 x86_64
Compiler:
curve-mds: 1.1.0-beta+5d648c9ec
curve-chunkserver: 1.1.0-beta+5d648c9ec
curve-snapshotcloneserver:
curve-sdk: 1.1.0-beta+5d648c9ec
nebd: 1.1.0-beta+5d648c9ec
curve-nbd: 1.1.0-beta+5d648c9ec

**Additional context/screenshots (更多上下文/截图)**
W 2020-10-26T16:46:02.317500+0800  2468 replicator.cpp:299] Group 4294967317 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317519+0800  2468 replicator.cpp:299] Group 4294967354 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317534+0800  2468 replicator.cpp:299] Group 4294967319 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317579+0800  2479 replicator.cpp:299] Group 4294967394 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317595+0800  2479 replicator.cpp:299] Group 4294967303 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317729+0800  2476 replicator.cpp:299] Group 4294967352 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317749+0800  2476 replicator.cpp:299] Group 4294967332 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317764+0800  2476 replicator.cpp:299] Group 4294967305 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.317780+0800  2476 replicator.cpp:299] Group 4294967302 fail to issue RPC to 10.202.91.10:8202:0 _consecutive_error_times=1, [E1008]Reached timeout=500ms @10.202.91.10:8202
W 2020-10-26T16:46:02.348995+0800  2475 node.cpp:1244] node 4294967358:10.202.91.10:8200:0 received invalid RequestVoteResponse from 10.202.91.10:8201:0 state not in CANDIDATE but LEADER
W 2020-10-26T16:46:02.349308+0800  2464 node.cpp:1316] node 4294967344:10.202.91.10:8200:0 received invalid PreVoteResponse from 10.202.91.10:8202:0 state not in STATE_FOLLOWER but CANDIDATE
W 2020-10-26T16:46:02.563308+0800  2468 node.cpp:1292] node 4294967381:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.563849+0800  2479 node.cpp:1292] node 4294967373:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.564920+0800  2466 node.cpp:1292] node 4294967348:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.628770+0800  2469 node.cpp:1222] node 4294967316:10.202.91.10:8200:0 term 362 steps down when reaching vote timeout: fail to get quorum vote-granted
W 2020-10-26T16:46:02.670714+0800  2469 node.cpp:1316] node 4294967306:10.202.91.10:8200:0 received invalid PreVoteResponse from 10.202.91.10:8202:0 state not in STATE_FOLLOWER but CANDIDATE
W 2020-10-26T16:46:02.702837+0800  2465 node.cpp:2065] node 4294967351:10.202.91.10:8200:0 ignore stale AppendEntries from 10.202.91.10:8201:0 in term 353 current_term 354
W 2020-10-26T16:46:02.703104+0800  2471 node.cpp:1316] node 4294967321:10.202.91.10:8200:0 received invalid PreVoteResponse from 10.202.91.10:8202:0 state not in STATE_FOLLOWER but CANDIDATE
W 2020-10-26T16:46:02.714792+0800  2479 node.cpp:1292] node 4294967338:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.714850+0800  2479 node.cpp:1292] node 4294967324:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.810375+0800  2473 node.cpp:1316] node 4294967316:10.202.91.10:8200:0 received invalid PreVoteResponse from 10.202.91.10:8202:0 state not in STATE_FOLLOWER but CANDIDATE
W 2020-10-26T16:46:02.811153+0800  2463 node.cpp:1244] node 4294967306:10.202.91.10:8200:0 received invalid RequestVoteResponse from 10.202.91.10:8202:0 state not in CANDIDATE but LEADER
W 2020-10-26T16:46:02.816112+0800  2479 node.cpp:1292] node 4294967344:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.816541+0800  2468 node.cpp:1292] node 4294967353:10.202.91.10:8200:0 received RequestVoteResponse from 10.202.91.10:8202:0 error: [E1008]Reached timeout=1000ms @10.202.91.10:8202
W 2020-10-26T16:46:02.844225+0800  2468 node.cpp:1222] node 4294967326:10.202.91.10:8200:0 term 360 steps down when reaching vote timeout: fail to get quorum vote-granted
W 2020-10-26T16:46:02.863354+0800  2468 node.cpp:1244] node 4294967321:10.202.91.10:8200:0 received invalid RequestVoteResponse from 10.202.91.10:8202:0 state not in CANDIDATE but LEADER
W 2020-10-26T16:46:03.010736+0800  2478 node.cpp:1244] node 4294967316:10.202.91.10:8200:0 received invalid RequestVoteResponse from 10.202.91.10:8202:0 state not in CANDIDATE but LEADER
W 2020-10-26T16:46:03.028254+0800  2473 node.cpp:1316] node 4294967326:10.202.91.10:8200:0 received invalid PreVoteResponse from 10.202.91.10:8202:0 state not in STATE_FOLLOWER but CANDIDATE
W 2020-10-26T16:46:03.127198+0800  2476 node.cpp:1244] node 4294967326:10.202.91.10:8200:0 received invalid RequestVoteResponse from 10.202.91.10:8201:0 state not in CANDIDATE but LEADER
W 2020-10-26T16:49:58.732772+0800  2469 baidu_rpc_protocol.cpp:255] Fail to write into Socket{id=85899347749 fd=191 addr=10.202.91.10:49188:8200} (0x7f02bfd83f40): Unknown error 1014 [1014]
W 2020-10-26T16:51:19.010679+0800  2462 baidu_rpc_protocol.cpp:255] Fail to write into Socket{id=51539609032 fd=191 addr=10.202.91.10:49506:8200} (0x7f02c07a58c0): Unknown error 1014 [1014]
W 2020-10-26T16:51:39.987674+0800  2465 baidu_rpc_protocol.cpp:255] Fail to write into Socket{id=60129543972 fd=191 addr=10.202.91.10:49610:8200} (0x7f02bfd83d00): Unknown error 1014 [1014]

*** Aborted at 1603702159 (unix time) try "date -d @1603702159" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x559f3295db4e) received by PID 3261 (TID 0x7ff2d1c95700) from PID 848681806; stack trace: ***
    @     0x7ff2df048dd0 (unknown)
    @     0x559f3295db4e curve::client::RequestSender::ReadChunk()
    @     0x559f329573dd _ZNSt17_Function_handlerIFvPN6google8protobuf7ClosureESt10shared_ptrIN5curve6client13RequestSenderEEEZNS6_13CopysetClient9ReadChunkERKNS6_11ChunkIDInfoEmlmmRKNS6_17RequestSourceIn
foES3_EUlS3_S8_E_E9_M_invokeERKSt9_Any_dataOS3_OS8_
    @     0x559f32957faa curve::client::CopysetClient::DoRPCTask()
    @     0x559f329583b0 curve::client::CopysetClient::ReadChunk()
    @     0x559f32955a34 curve::client::RequestScheduler::ProcessOne()
    @     0x559f32955db2 curve::client::RequestScheduler::Process()
    @     0x7ff2ddc46b73 (unknown)
    @     0x7ff2df03e2de start_thread
    @     0x7ff2dd6a5e83 __GI___clone
    @                0x0 (unknown)
*** Aborted at 1603702162 (unix time) try "date -d @1603702162" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x558257b1cb4e) received by PID 3369 (TID 0x7f353cd42700) from PID 1471269710; stack trace: ***
    @     0x7f3549d63dd0 (unknown)
    @     0x558257b1cb4e curve::client::RequestSender::ReadChunk()
    @     0x558257b163dd _ZNSt17_Function_handlerIFvPN6google8protobuf7ClosureESt10shared_ptrIN5curve6client13RequestSenderEEEZNS6_13CopysetClient9ReadChunkERKNS6_11ChunkIDInfoEmlmmRKNS6_17RequestSourceIn
foES3_EUlS3_S8_E_E9_M_invokeERKSt9_Any_dataOS3_OS8_
    @     0x558257b16faa curve::client::CopysetClient::DoRPCTask()
    @     0x558257b173b0 curve::client::CopysetClient::ReadChunk()
    @     0x558257b14a34 curve::client::RequestScheduler::ProcessOne()
    @     0x558257b14db2 curve::client::RequestScheduler::Process()
    @     0x7f3548961b73 (unknown)
    @     0x7f3549d592de start_thread
    @     0x7f35483c0e83 __GI___clone
    @                0x0 (unknown)
*** Aborted at 1603702163 (unix time) try "date -d @1603702163" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGILL (@0x5615cb349b4e) received by PID 3395 (TID 0x7fa7e6df5700) from PID 18446744072823806798; stack trace: ***
    @     0x7fa7f35a0dd0 (unknown)
    @     0x5615cb349b4e curve::client::RequestSender::ReadChunk()
    @     0x5615cb3433dd _ZNSt17_Function_handlerIFvPN6google8protobuf7ClosureESt10shared_ptrIN5curve6client13RequestSenderEEEZNS6_13CopysetClient9ReadChunkERKNS6_11ChunkIDInfoEmlmmRKNS6_17RequestSourceIn
foES3_EUlS3_S8_E_E9_M_invokeERKSt9_Any_dataOS3_OS8_
    @     0x5615cb343faa curve::client::CopysetClient::DoRPCTask()
    @     0x5615cb3443b0 curve::client::CopysetClient::ReadChunk()
    @     0x5615cb341a34 curve::client::RequestScheduler::ProcessOne()
    @     0x5615cb341db2 curve::client::RequestScheduler::Process()
    @     0x7fa7f219eb73 (unknown)
    @     0x7fa7f35962de start_thread
    @     0x7fa7f1bfde83 __GI___clone
    @                0x0 (unknown)

完整日志请见附件：
[nbd-hung-logs.tar.gz](https://github.com/opencurve/curve/files/5437855/nbd-hung-logs.tar.gz)

**Comment by wu-hanqing** [comment]
现在能稳定复现吗，看着是nebd-server异常退出了。
如果可以稳定复现，麻烦打开一下core，然后把nebd-server的core文件也提供一下。

顺便提供一下机器的环境：
内核版本，是否为虚拟机，内存大小等信息。

**Comment by qiuyi21** [comment]
> 现在能稳定复现吗，看着是nebd-server异常退出了。
> 如果可以稳定复现，麻烦打开一下core，然后把nebd-server的core文件也提供一下。
> 
> 顺便提供一下机器的环境：
> 内核版本，是否为虚拟机，内存大小等信息。

@wu-hanqing 
4.18.0-193.6.3.el8_2.x86_64，KVM虚拟机，2CPU核2GB内存。系统产生了大量coredump，我上传最近10个，请见附件。
[coredump.zip](https://github.com/opencurve/curve/files/5443742/coredump.zip)

**Comment by wu-hanqing** [comment]
从core里面看，大概是在设置rpc的ChunkRequest里面触发了SIGILL，导致nebd-server进程退出。
具体如何触发的还不能确定，有能跟机器内存小有关系。
1. 部署集群后，观察一下机器的内存情况。
2. 下载debug版本的nebd-server，你可以替换一下/usr/bin/nebd-server，然后再看一下具体的现象。如果还是有问题，麻烦把相关日志和core文件再提供一次。(链接: https://pan.baidu.com/s/1KFcBwiKViE5bIstKG6EJIw 提取码: 94mi)

**Comment by qiuyi21** [comment]
> 从core里面看，大概是在设置rpc的ChunkRequest里面触发了SIGILL，导致nebd-server进程退出。
> 具体如何触发的还不能确定，有能跟机器内存小有关系。
> 
> 1. 部署集群后，观察一下机器的内存情况。
> 2. 下载debug版本的nebd-server，你可以替换一下/usr/bin/nebd-server，然后再看一下具体的现象。如果还是有问题，麻烦把相关日志和core文件再提供一次。(链接: https://pan.baidu.com/s/1KFcBwiKViE5bIstKG6EJIw 提取码: 94mi)

用了debug版本后I/O正常了，没有修改代码但是表现不同了，有点奇怪。

**Comment by aspirer** [comment]
welcome to reopen this issue if anyone can reproduce.

**Comment by DemoLiang** [comment]
目前测试发现有出现同类问题
client 挂载 nbd 卷，出现ls 卡死现象，查看client日志如下：
![3e912d41dd76c80d6275e72b9591c62](https://user-images.githubusercontent.com/23476007/225561743-ebec0f45-6492-484b-bbcf-33a92d7c8614.png)


检查响应的server端出现如下日志：

**Comment by wuhongsong** [comment]
@wu-hanqing

**Comment by caoxianfei1** [comment]
@DemoLiang Has this issue been resolved and is this issue a repeat?

**Comment by caoxianfei1** [comment]
Close this issue because there is no response for a long time. Anyone can reopen it if occur again.
