### ISSUE TITLE
curvefs+bs:The client segment has a performance bottleneck， striped or three-copy volume, the fs-side performance is 60-70MB/s

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1426]
**Describe the bug (描述bug)**

The underlying striped or three-copy volume, the fs-side performance is 60-70MB/s
**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/168034202-357de390-a97c-46ef-bd2f-704e94bd7aa1.png)
![image](https://user-images.githubusercontent.com/67582932/168034245-354d6ac6-51b7-4225-ba9c-b63caa9aa9e7.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
i have a small cluster just have 3 disks. and the bandwith is 50MB/s，follow ` write: IOPS=103, BW=51.7MiB/s (54.2MB/s)(19.0GiB/395868msec);`

and after opt,we can get double bandwith，follow `write: IOPS=192, BW=96.1MiB/s (101MB/s)(20.0GiB/213048msec); 0 zone resets`  , and the disks util is nearly 100%
