### ISSUE TITLE
After the whole chunkserver is stopped, the copiesets are migrated for a period of time

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1441]
**Describe the bug (描述bug)**
After the whole chunkserver is stopped, the copiesets are migrated for a period of time
![image](https://user-images.githubusercontent.com/67582932/168249329-2bb16d94-5095-47c9-a707-7744cafdf223.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
The bug fixed, please wait for CurveAdm v0.0.23 released.

**Comment by Wine93** [comment]
you can use below command to show cluster pool information:
```
curveadm config show --pool
```
it works well.
