### ISSUE TITLE
 Metaserver occupies unbalanced memory resources

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1453]
**Describe the bug (描述bug)**
During the test of the release2.1 branch, it was found that the memory usage of the metaserver was unbalanced. It is necessary to confirm whether there are similar problems on the master.
![image](https://user-images.githubusercontent.com/15689619/168713361-feed72fb-c059-40d8-ab00-da5826ab47c1.png)
![image](https://user-images.githubusercontent.com/15689619/168713375-e56fa015-661d-474f-8d02-02162aefe75b.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/170038849-17e64e8a-0ae2-4274-ad07-92bc0fca84a5.png)

**Comment by cw123** [comment]
copyset个数比较均衡，但是partition选择copyset是随机选择的，就会导致不同的metaserver上的partition不均衡，从而导致metaserver的内存使用量不均衡。
