### ISSUE TITLE
curvefs+bs: Fuse appears coredump when you start running Vdbench

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1457]
**Describe the bug (描述bug)**
Fuse appears coredump when you start running Vdbench

**To Reproduce (复现方法)**
1、sudo .curveadm/bin/curveadm mount /curvebs-new7 /home/nbs/failover/curvebs4 -c client-bs4.yaml --fstype volume
2、start vdbench
3、
![image](https://user-images.githubusercontent.com/67582932/168777881-dd5250cb-20c6-4dae-a3e1-1647a1d8e9c7.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
might be introduced by https://github.com/opencurve/curve/pull/1390, and when reloading from a partial usable block group, BitmapAllocator::MarkUsedForBitmap do the wrong thing and causes an assert triggered.
