### ISSUE TITLE
curvefs+bs:Fuse Coredump during vDbench running

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1461]
**Describe the bug (描述bug)**
Fuse Coredump during vDbench running

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/168946623-935ac8fa-5416-4012-ab6b-256f407083bf.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
caused by dereferencing an invalid iterator.
