### ISSUE TITLE
Multiple Mount If the CTO function is inconsistent, the mount point data of the CTO function will be overwritten

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1463]
**Describe the bug (描述bug)**
Multiple Mount If the CTO function is inconsistent, the mount point data of the CTO function will be overwritten

1、curvebs2 close cto
volumeSize: 107374182400
volumeName: /test3
volumeUser: test
#VolumePassword: 123
container_image: harbor.cloud.netease.com/curve/curvefs:release2.2
log_dir: /data/logs/curvefs
client.loglevel: 8
core_dir: /corefile
container_pid: host
fuseClient.cto: false
2、curvebs3 open cto
![image](https://user-images.githubusercontent.com/67582932/168973621-7f84b9ea-4392-44b0-8baf-f71dda7b8c1c.png)

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/168973441-c8729bc2-2dc9-4073-a397-9d800732aad6.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
All mount points on the same file system are either enableCto, or they do not guarantee consistency. fix by pr: https://github.com/opencurve/curve/pull/1771

**Comment by YunhuiChen** [comment]
![image](https://user-images.githubusercontent.com/67582932/185567195-64727bb4-0c49-4976-a7bd-a7f1e66181ff.png)
