### ISSUE TITLE
Failed to delete directory

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#1490]
**Describe the bug (描述bug)**

It fails when the directory is deleted for the first time.
![image](https://user-images.githubusercontent.com/15775037/169777176-fb6f9ce9-7c1a-4d93-bc25-55f44d8ed8df.png)
But next time it worked

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:harbor.cloud.netease.com/curve/curvefs:release2.1-b6d2d306
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
grep ^E curve-fuse.log.INFO.20220526-021616.25
E 2022-05-30T16:04:03.986676+0800    86 inode_wrapper.cpp:310] DecreaseNLink find nlink <= 0, nlink = 0
E 2022-05-30T16:04:03.986709+0800    86 fuse_client.cpp:510] inodeManager DecreaseNLink fail, ret = -1[internal error], inodeid = 142500

**Comment by xu-chaojie** [comment]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/5245004/170980200-efbb515f-4b7f-4100-8b27-345e5a8a6a18.png">
rmdir [142500,b9] failed by DecreaseNlink inodeid 142500

**Comment by xu-chaojie** [comment]
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/5245004/171182397-15b23c2c-22a7-4b9f-934a-b392be30ce62.png">
cat curvefs-metaserver.log.INFO.20220526-022027.7 | grep -A 3 "Receive DeleteDentry request, dentry = (fsId: 1 parentInodeId: 142500"   found nlink from 11 to 9, missing 10

**Comment by xu-chaojie** [comment]
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/5245004/171183759-d323cd2c-01b8-40bd-b0e2-e4920201d14a.png">
between nlink from 11 to 9, there are UpdateInode call which update nlink to 10

**Comment by xu-chaojie** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5245004/172127179-f118331e-27b5-4d27-a78b-2ff955d5dc26.png">
after add a log, show that

**Comment by xu-chaojie** [comment]
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/5245004/172132010-4460323c-0ea0-46b0-9fb1-e8506582ed64.png">
between client DecreaseNLink and DeleteDentry,  client get inode from metaserver that inode have already decrease nlink

**Comment by wu-hanqing** [comment]
@[Cyber-SiKu](https://github.com/Cyber-SiKu)

**Comment by xu-chaojie** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5245004/173485540-e6b353bc-521e-4db3-8174-db219e487796.png">

**Comment by xu-chaojie** [comment]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/5245004/173485910-df94c596-435f-418a-ad22-ab8cc725de1c.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/5245004/173485993-d7c3cbeb-07ef-4775-a9fc-c045b35a9f55.png">

When rename, getdentry does not get type, which will result in more nlink reduction when rename
