### ISSUE TITLE
能详细介绍下chunkfilepool吗？

### ISSUE THREAD

**Issue by cannium** [opencurve/curve#15]
在简介里看到这么一句，好奇具体是怎么做的

> 在状态机的实现上采用 chunkfilepool 的方式 ( 初始化集群的时候格式化出指定比例的空间用作 chunk ) 使得底层的写入放大为 0

**Comment by qinyihust** [comment]
非常感谢对curve的关注。

**Comment by aspirer** [comment]
后续会有专门的在线分享给大家详细介绍curve的架构细节，我们排期出来后会在user group群里通知大家，敬请期待~

**Comment by DengJin88** [comment]
@aspirer fallocate不是就做了预分配空间并对空间置0(尽管不一定做物理的写)的操作吗？为何还要自己抹一遍呢？我看到你们的文档里说如果不这么做的话：
> 但是即便fallocate以后，在写文件未写过的块时仍需要更改元数据，存在一定的IO放大。

为何还需要更改元数据，更改些什么内容呢？
