### ISSUE TITLE
Metaserver has high memory usage

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1528]
**Describe the bug (描述bug)**
In the 7*24 hour stability test, it was observed that the memory occupied by metaserver is very high, far exceeding the limit of rocksdb
![image](https://user-images.githubusercontent.com/15689619/171128216-3c8331c2-3ba8-46d6-9efe-a87525b65da9.png)
![image](https://user-images.githubusercontent.com/15689619/171128234-377cc1d2-da9b-4f50-aefe-d6313e1328d4.png)
![image](https://user-images.githubusercontent.com/15689619/171128247-973e8307-1616-49aa-8328-5d3c40251c76.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch: master
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
```
VmSize(KB): 13080      VmRSS(KB): 1540
VmSize(KB): 778284     VmRSS(KB): 768332
Insert 10000000 keys, except memory usage = 120000 KB, actual memory usage = 766792 KB
```


```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <unordered_set>

#define KEYS_COUNT 10000000


uint64_t
get_meminfo()
{
    char           buffer[1024];
    unsigned long  vm_size, vm_rss;

    FILE *f = fopen("/proc/self/status", "r");
    if (f == NULL) {
        printf ("fopen() error\n");
        exit(1);
    }

    while (fscanf(f, "%s", buffer) == 1) {

        if (strcmp(buffer, "VmSize:") == 0) {
            fscanf(f, "%ld", &vm_size);

        } else if (strcmp(buffer, "VmRSS:") == 0) {
            fscanf(f, "%ld", &vm_rss);
        }
    }

    printf ("VmSize(KB): %-10ld VmRSS(KB): %-10ld\n", vm_size, vm_rss);
    return vm_rss;
}

int
main() {
    uint64_t start = get_meminfo();

    std::unordered_set<std::string> keys;
    for(uint32_t i = 0; i < KEYS_COUNT; i++) {
      std::stringstream ss;
      ss << std::setw(12) << std::setfill('0') << i;
      keys.insert(ss.str());
    }

    uint64_t end = get_meminfo();

    std::cout << "Insert " << KEYS_COUNT << " keys"
              << ", except memory usage = " << 12 * KEYS_COUNT / 1000 << " KB"
              << ", actual memory usage = " << end - start << " KB" << std::endl;

    return 0;
}
```

**Comment by Wine93** [comment]
There are 3 resident memory container in metaserver:

1. for store all inode id
```
std::unordered_set<std::string> keySet_;
```

2. for store every file's size
```
std::unordered_map<std::string, uint64_t> inodeS3MetaSize_;
```

3. for store every table size in KV storage
```
using ContainerType = absl::btree_set<size_t>;
std::unordered_map<std::string,
                   std::shared_ptr<ContainerType>> containerDict_;
```

we can remove the first one container and replace the second one to btree container which can reduce memory cost, ~~and for  the third container we can use proto serialization to reduce memory usage further,~~ in the next i will show various containers memory usage:

| container | memory usage (KB) |
| :---           | :---                            |
|         `<none>`      |      195312                             |
| std::unordered_map<std::string, uint64_t> | 783990 | 
| absl::brtee_map<std::string, uint64_t> | 465014 |

**Comment by Wine93** [comment]
for test, i replace all C++  deploy a cluster for insert 1E files, and the memory is grow to about `16GB`:

![image](https://user-images.githubusercontent.com/9267583/172091729-ebf8dd51-e6ef-4025-90c6-e42179f923ea.png)

![image](https://user-images.githubusercontent.com/9267583/172091693-0e8e7b1f-4e26-49b7-afec-4afa68f7ac44.png)

**Comment by Wine93** [comment]
After remove all memory container, the memory usage of metaserver is become stable:

* cluster running 18 hours:
![image](https://user-images.githubusercontent.com/9267583/172276910-d18e86a2-ac50-41f7-80c0-54616ff02af0.png)

* create `69619048` files:

![image](https://user-images.githubusercontent.com/9267583/172277098-583ec320-29b2-431b-8b12-b862d689da1e.png)

* memory usage of metaserver:
![image](https://user-images.githubusercontent.com/9267583/172276983-12211c2b-8157-4c48-bf9a-4ae483df3eaa.png)

so we can remove all memory conatiners, we can also remove the container for stat the number of inodes/dentry, it will make tools inaccurate in displaying the number of inode/dentry in the partition.

**Comment by Wine93** [comment]
now i add vdbench for running 10 hours, and mdtest create about `1.2E` files, the memory usage of metaserver also stable:

* cluster status
![image](https://user-images.githubusercontent.com/9267583/172518437-1894434e-a9b4-4884-b84e-975fc3f99cb0.png)

* create `120050048` files
![image](https://user-images.githubusercontent.com/9267583/172518385-e2a15083-f18d-4ddc-bbe0-1c5e378c1c23.png)

* memory usage of metaserver
![image](https://user-images.githubusercontent.com/9267583/172518470-a1a84ce2-9832-4202-9082-7b6d86dca3b0.png)
