### ISSUE TITLE
Unbalanced usage of disk space by metaserver

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1529]
**Describe the bug (描述bug)**
In the 7*24-hour test, it was found that the disk space occupied by the metaserver on different nodes is quite different：
root@prit2-curve-chunk-node15:/data/curvefs# du -sh metaserver*
140G	metaserver0
116G	metaserver1
92G	metaserver2

root@prit2-curve-chunk-node16:/data/curvefs# du -sh metaserver*
70G	metaserver0
76G	metaserver1
75G	metaserver2

root@prit2-curve-chunk-node17:/data/curvefs# du -sh metaserver*
55G	metaserver0
105G	metaserver1
73G	metaserver2

metaserver对磁盘的占用很不均衡

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/171174335-5aeb73ed-00c5-4ca2-af38-b0aaaec138d6.png)

**Comment by cw123** [comment]
当前fs为partition选择copyset是随机选择的，当fs个数不多，或者fs间使用不均衡的时候，会出现使用率不均衡。
schedule的资源调度有个范围，当资源的使用率相差30%的时候，才会触发调度。当前这个集群，配置文件磁盘配置了2TB，内存配置了30GB。当磁盘使用量相差超过600GB或者内存使用量相差超过9GB的时候，会触发调度。
图中，在下午4点的时候，内存使用量相差超过了9GB，确实触发了调度。
所以当前这个这个环境的资源使用情况是正常的，符合设计预期的。
![image](https://user-images.githubusercontent.com/4277834/171174997-3ba5d7ba-8988-46c0-9d00-6855e9aa2d6c.png)

**Comment by cw123** [comment]
<html>
<body>


  | 3 partition | 12 partition
-- | -- | --

配置 | mds.conf# id number in each partition 2^24 [0, 2^24-1]mds.topology.IdNumberInPartition=16777216# initial copyset number in clustermds.topology.InitialCopysetNumber=10# min avaiable copyset num in clustermds.topology.MinAvailableCopysetNum=10# default create partition number 3mds.topology.CreatePartitionNumber=3 | 修改配置项：mds.conf# id number in each partition 2^20 [0, 2^20-1]mds.topology.IdNumberInPartition=1048576# initial copyset number in clustermds.topology.InitialCopysetNumber=12# min avaiable copyset num in clustermds.topology.MinAvailableCopysetNum=12# default create partition number 3mds.topology.CreatePartitionNumber=12
partition 分布 | topology_metric_metaserver_id_1_partition_num 1topology_metric_metaserver_id_2_partition_num 0topology_metric_metaserver_id_3_partition_num 1topology_metric_metaserver_id_4_partition_num 2topology_metric_metaserver_id_5_partition_num 1topology_metric_metaserver_id_6_partition_num 0topology_metric_metaserver_id_7_partition_num 2topology_metric_metaserver_id_8_partition_num 2topology_metric_metaserver_id_9_partition_num 0 | topology_metric_metaserver_id_1_partition_num 4topology_metric_metaserver_id_2_partition_num 6topology_metric_metaserver_id_3_partition_num 4topology_metric_metaserver_id_4_partition_num 3topology_metric_metaserver_id_5_partition_num 2topology_metric_metaserver_id_6_partition_num 5topology_metric_metaserver_id_7_partition_num 5topology_metric_metaserver_id_8_partition_num 4topology_metric_metaserver_id_9_partition_num 3
copyset分布 | topology_metric_metaserver_id_1_copyset_num 4topology_metric_metaserver_id_2_copyset_num 3topology_metric_metaserver_id_3_copyset_num 4topology_metric_metaserver_id_4_copyset_num 3topology_metric_metaserver_id_5_copyset_num 3topology_metric_metaserver_id_6_copyset_num 3topology_metric_metaserver_id_7_copyset_num 4topology_metric_metaserver_id_8_copyset_num 3topology_metric_metaserver_id_9_copyset_num 3 | topology_metric_metaserver_id_1_copyset_num 4topology_metric_metaserver_id_2_copyset_num 4topology_metric_metaserver_id_3_copyset_num 4topology_metric_metaserver_id_4_copyset_num 4topology_metric_metaserver_id_5_copyset_num 4topology_metric_metaserver_id_6_copyset_num 4topology_metric_metaserver_id_7_copyset_num 4topology_metric_metaserver_id_8_copyset_num 4topology_metric_metaserver_id_9_copyset_num 4
memory分布单位字节 | topology_metric_metaserver_id_1_memory_used 1353793536topology_metric_metaserver_id_2_memory_used 748261376topology_metric_metaserver_id_3_memory_used 1392041984topology_metric_metaserver_id_4_memory_used 2071752704topology_metric_metaserver_id_5_memory_used 1559408640topology_metric_metaserver_id_6_memory_used 761909248topology_metric_metaserver_id_7_memory_used 1890193408topology_metric_metaserver_id_8_memory_used 2044469248topology_metric_metaserver_id_9_memory_used 745009152 | topology_metric_metaserver_id_1_memory_used 1504665600topology_metric_metaserver_id_2_memory_used 1960161280topology_metric_metaserver_id_3_memory_used 1392226304topology_metric_metaserver_id_4_memory_used 1169031168topology_metric_metaserver_id_5_memory_used 1197850624topology_metric_metaserver_id_6_memory_used 2001297408topology_metric_metaserver_id_7_memory_used 1713807360topology_metric_metaserver_id_8_memory_used 1525477376topology_metric_metaserver_id_9_memory_used 1276440576
File creation性能单位qps | Operation Max Min Mean Std DevFile creation : 126.517 126.517 126.517 0.000File creation : 126.518 126.518 126.518 0.000File creation : 126.423 126.423 126.423 0.000File creation : 123.251 123.251 123.251 0.000File creation : 123.269 123.269 123.269 0.000File creation : 126.475 126.475 126.475 0.000File creation : 126.521 126.521 126.521 0.000File creation : 123.280 123.280 123.280 0.000File creation : 127.787 127.787 127.787 0.000File creation : 126.428 126.428 126.428 0.000File creation : 123.331 123.331 123.331 0.000File creation : 123.287 123.287 123.287 0.000File creation : 127.797 127.797 127.797 0.000File creation : 123.208 123.208 123.208 0.000File creation : 123.224 123.224 123.224 0.000File creation : 123.263 123.263 123.263 0.000File creation : 126.440 126.440 126.440 0.000File creation : 127.777 127.777 127.777 0.000File creation : 123.320 123.320 123.320 0.000File creation : 127.799 127.799 127.799 0.000 | Operation Max Min Mean Std DevFile creation : 142.720 142.720 142.720 0.000File creation : 142.822 142.822 142.822 0.000File creation : 142.670 142.670 142.670 0.000File creation : 142.543 142.543 142.543 0.000File creation : 142.812 142.812 142.812 0.000File creation : 142.679 142.679 142.679 0.000File creation : 148.009 148.009 148.009 0.000File creation : 146.583 146.583 146.583 0.000File creation : 142.592 142.592 142.592 0.000File creation : 142.547 142.547 142.547 0.000File creation : 144.601 144.601 144.601 0.000File creation : 147.259 147.259 147.259 0.000File creation : 143.022 143.022 143.022 0.000File creation : 142.504 142.504 142.504 0.000File creation : 150.255 150.255 150.255 0.000File creation : 143.153 143.153 143.153 0.000File creation : 146.642 146.642 146.642 0.000File creation : 146.522 146.522 146.522 0.000File creation : 142.400 142.400 142.400 0.000File creation : 147.890 147.890 147.890 0.000
Tree creation性能单位qps | Operation Max Min Mean Std DevTree creation : 200.728 200.728 200.728 0.000Tree creation : 262.463 262.463 262.463 0.000Tree creation : 86.217 86.217 86.217 0.000Tree creation : 104.200 104.200 104.200 0.000Tree creation : 325.360 325.360 325.360 0.000Tree creation : 82.006 82.006 82.006 0.000Tree creation : 88.867 88.867 88.867 0.000Tree creation : 97.957 97.957 97.957 0.000Tree creation : 76.490 76.490 76.490 0.000Tree creation : 80.771 80.771 80.771 0.000Tree creation : 339.509 339.509 339.509 0.000Tree creation : 71.225 71.225 71.225 0.000Tree creation : 274.031 274.031 274.031 0.000Tree creation : 303.453 303.453 303.453 0.000Tree creation : 230.554 230.554 230.554 0.000Tree creation : 265.825 265.825 265.825 0.000Tree creation : 231.786 231.786 231.786 0.000Tree creation : 257.418 257.418 257.418 0.000Tree creation : 198.932 198.932 198.932 0.000Tree creation : 95.036 95.036 95.036 0.000 | Operation Max Min Mean Std DevTree creation : 247.052 247.052 247.052 0.000Tree creation : 281.997 281.997 281.997 0.000Tree creation : 242.985 242.985 242.985 0.000Tree creation : 272.633 272.633 272.633 0.000Tree creation : 245.098 245.098 245.098 0.000Tree creation : 239.550 239.550 239.550 0.000Tree creation : 299.530 299.530 299.530 0.000Tree creation : 255.873 255.873 255.873 0.000Tree creation : 164.323 164.323 164.323 0.000Tree creation : 218.888 218.888 218.888 0.000Tree creation : 353.569 353.569 353.569 0.000Tree creation : 207.350 207.350 207.350 0.000Tree creation : 282.973 282.973 282.973 0.000Tree creation : 327.548 327.548 327.548 0.000Tree creation : 349.623 349.623 349.623 0.000Tree creation : 311.094 311.094 311.094 0.000Tree creation : 336.201 336.201 336.201 0.000Tree creation : 302.792 302.792 302.792 0.000Tree creation : 263.215 263.215 263.215 0.000Tree creation : 271.872 271.872 271.872 0.000


</body>
</html>

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/173292325-7c6cd384-3891-4e2c-90a6-c29419bc15bc.png)
![image](https://user-images.githubusercontent.com/4277834/173292358-9642084a-e2c1-411b-b7de-d6949b08c101.png)
![image](https://user-images.githubusercontent.com/4277834/173292400-729dfdff-36f6-4a05-8fe4-7a7e69f9b685.png)
![image](https://user-images.githubusercontent.com/4277834/173292439-a29be936-9a08-430e-9907-bbdc6d58d53b.png)
