### ISSUE TITLE
【CI】curvefs_tool cluster is unhealthy

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1540]
**Describe the bug (描述bug)**
http://59.111.91.248:8080/job/curve_fs_failover_test/711/robot/report/log.html

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
we found that use `curvefs_tool` to query cluster status, it's return error for missing required fields in response, it cause cluster unhealthy:

![image](https://user-images.githubusercontent.com/9267583/172091094-846ea807-999a-4aee-9896-5a4783c4b640.png)
