### ISSUE TITLE
curvefs_tool list-copysetInfo fail

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#1541]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/4277834/172091467-df6cb927-fa54-4663-8105-a90362a478ac.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch: master
commit id: ee40af525a1959d484b07da5da4cbf6a97be070b

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
![image](https://user-images.githubusercontent.com/15775037/172154525-e66eb507-d636-4165-be7a-f92c0da87bf1.png)
查日志可知此时确实没有partitionId
