### ISSUE TITLE
curvebs : seems iops of 4k random reads do not grow with the number of jobs

### ISSUE THREAD

**Issue by xu-chaojie** [opencurve/curve#1546]
![image](https://user-images.githubusercontent.com/5245004/172328310-c0249269-0f08-44f0-bf0e-4d053e5ef428.png)

**Comment by skypexu** [comment]
网卡到瓶颈了，万兆网络是10Gbits，双网卡是20Gbits.
1B = 8b
20Gb/8b = 2.5G= 2500MB
实际机器的效率包括cpu，和网卡均衡，還有软件栈效率。
估计要全链路挤出性能，要精雕细啄
