### ISSUE TITLE
Common: Optimize the memory footprint of the LRU in the common library

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1573]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
https://github.com/opencurve/curve/issues/1532
https://github.com/opencurve/curve/issues/1528

https://github.com/opencurve/curve/blob/b55e815681eedb86ce8c18ae2ba9354b39c8fa67/src/common/lru_cache.h#L255
https://github.com/opencurve/curve/blob/b55e815681eedb86ce8c18ae2ba9354b39c8fa67/src/common/lru_cache.h#L257

The stl used by lrucache in the common library `std::list` and `std::unordered_map` occupy much more memory than the actual data

**Describe the solution you'd like (描述你期望的解决方法)**
Optimize the memory footprint of `std::list `and` std::unordered_map`

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by SGZW** [comment]
By Analyzing the heap profiler, I found redundancy of memory, follows

1.  when key is std::string,  the Item and unordered_map key construct std::string twice
2. when insert element to std::list and std::unordered_map, construct node twice

To Made It Simple，We can use  https://stackoverflow.com/questions/3361145/intrusive-lists like this

1. It's better on memory (not many small allocations for things to point at other things)
2. It allows you to have an object that exist in multiple containers at once.
3. It allows you to find an element with one search mode (hash) but then find the next element in lexographic order

For specific implementation, we can refer to leveldb lru cache.cc

PTAL

**Comment by ilixiaocui** [comment]
> By Analyzing the heap profiler, I found redundancy of memory, follows
> 
> 1. when key is std::string,  the Item and unordered_map key construct std::string twice
> 2. when insert element to std::list and std::unordered_map, construct node twice
> 
> To Made It Simple，We can use https://stackoverflow.com/questions/3361145/intrusive-lists like this
> 
> 1. It's better on memory (not many small allocations for things to point at other things)
> 2. It allows you to have an object that exist in multiple containers at once.
> 3. It allows you to find an element with one search mode (hash) but then find the next element in lexographic order
> 
> For specific implementation, we can refer to leveldb lru cache.cc
> 
> PTAL

Thanks for your analysis. We have considered referring to the lru implementation of leveldb before，and plan to do a comparison test. However, there is currently no time to develop it. If you are interested in planning, please complete this issue, we will be very grateful.

**Comment by SGZW** [comment]
ok, I will try it

**Comment by fansehep** [comment]
@SGZW hi, Do you finish it ? I am also interesting in this. If you have no time to rewrite it, I think it is a good way to assign to me.

**Comment by fansehep** [comment]
I think we can close it. @ilixiaocui

**Comment by ilixiaocui** [comment]
We also need a test result, how much the optimized memory saves compared to the case of 100w records.

**Comment by ilixiaocui** [comment]
> We also need a test result, how much the optimized memory saves compared to the case of 100w records.


We also need a test result, how much the optimized memory saves compared to the case of 100w records.

**Comment by ilixiaocui** [comment]
> I think we can close it. @ilixiaocui


We also need a test result, how much the optimized memory saves compared to the case of 100w records.

**Comment by fansehep** [comment]
> > I think we can close it. @ilixiaocui
> 
> We also need a test result, how much the optimized memory saves compared to the case of 100w records.

Do we need test it in curve ? Or just give you a benchmark?

**Comment by ilixiaocui** [comment]
> > > I think we can close it. @ilixiaocui
> > 
> > 
> > We also need a test result, how much the optimized memory saves compared to the case of 100w records.
> 
> Do we need test it in curve ? Or just give you a benchmark?

A benchmark is ok. 
key-value all string(The recommended average length is around 64Byte)

**Comment by fansehep** [comment]
> > > > I think we can close it. @ilixiaocui
> > > 
> > > 
> > > We also need a test result, how much the optimized memory saves compared to the case of 100w records.
> > 
> > 
> > Do we need test it in curve ? Or just give you a benchmark?
> 
> A benchmark is ok. key-value all string(The recommended average length is around 64Byte)

Here is a simple benchmark meets your need. https://github.com/fansehep/flog/commit/a9daa880020282f5233970f2e2633ad935f480dd.

**Comment by ilixiaocui** [comment]
> > > > > I think we can close it. @ilixiaocui
> > > > 
> > > > 
> > > > We also need a test result, how much the optimized memory saves compared to the case of 100w records.
> > > 
> > > 
> > > Do we need test it in curve ? Or just give you a benchmark?
> > 
> > 
> > A benchmark is ok. key-value all string(The recommended average length is around 64Byte)
> 
> Here is a simple benchmark meets your need. [fansehep/flog@a9daa88](https://github.com/fansehep/flog/commit/a9daa880020282f5233970f2e2633ad935f480dd).

Great! Thanks for your contribution.
