### ISSUE TITLE
curvebs-chunkserver 无法启动

### ISSUE THREAD

**Issue by tianser** [opencurve/curve#1585]
**Describe the bug (描述bug)**
使用curveadm 部署all in one，直到curveadm deploy都ok，curvebs-chunkserver 容器启动后过一会退出；
docker logs 如下
WARNING: Logging before InitGoogleLogging() is written to STDERR
I 2022-06-16T16:53:45.245608+0800     7 chunkserver_main.cpp:28] ChunkServer starting.
I 2022-06-16T16:53:45.245983+0800     7 chunkserver.cpp:88] Loading Configuration.
E 2022-06-16T16:53:45.251543+0800     7 file_pool.cpp:108] meta file open failed, /curvebs/chunkserver/data/chunkfilepool.meta
E 2022-06-16T16:53:45.251567+0800     7 file_pool.cpp:237] Decode meta info from meta file failed!
E 2022-06-16T16:53:45.251586+0800     7 file_pool.cpp:209] check valid failed!
F 2022-06-16T16:53:45.251610+0800     7 chunkserver.cpp:143] Failed to init chunk file pool
*** Check failure stack trace: ***
*** Aborted at 1655369625 (unix time) try "date -d @1655369625" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7) received by PID 7 (TID 0x7fea3462a240) from PID 7; stack trace: ***
    @     0x7fea3300e0e0 (unknown)
    @     0x7fea31f6cfff gsignal
    @     0x7fea31f6e42a abort
    @     0x560168945bae google::FlushAndAbort()
    @     0x560168943c6a google::LogMessage::Fail()
    @     0x560168945727 google::LogMessage::SendToLog()
    @     0x560168943900 google::LogMessage::Flush()
    @     0x560168945799 google::LogMessageFatal::~LogMessageFatal()
    @     0x5601682c84a8 curve::chunkserver::ChunkServer::Run()
    @     0x56016829e0a0 main
    @     0x7fea31f5a2e1 __libc_start_main
    @     0x5601682bdaea _start
    @                0x0 (unknown

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos8
Compiler: 官方版本
branch: opencurvedocker/curvebs:v1.2 
commit id: 

**Additional context/screenshots (更多上下文/截图)**

# df -h |grep chunk 
/dev/sdf        5.5T  145G  5.1T   3% /data/chunkserver1
/dev/sdg        5.5T  145G  5.1T   3% /data/chunkserver2
/dev/sde        5.5T  145G  5.0T   3% /data/chunkserver0
![image](https://user-images.githubusercontent.com/15101927/174035559-4fccec25-5458-4173-8817-41920366dcbf.png)

**Comment by aspirer** [comment]
did you run `curveadm format` command to make the chunkfilepool?

**Comment by tianser** [comment]
@tianser  确认运行了curveadm format -f format.yaml

**Comment by tianser** [comment]
@aspirer 确认运行过curveadm format -f format.yaml

**Comment by tianser** [comment]
![image](https://user-images.githubusercontent.com/15101927/174048987-4691f07e-7da0-4f40-b488-2b17712a0e90.png)

**Comment by aspirer** [comment]
```
/dev/sdf 5.5T 145G 5.1T 3% /data/chunkserver1
/dev/sdg 5.5T 145G 5.1T 3% /data/chunkserver2
/dev/sde 5.5T 145G 5.0T 3% /data/chunkserver0
```
我看到你这个df命令输出，空间使用率是3%，你format.yaml里面写的是90%，是不是没有格式化完就开始deploy了？
format之后要很长时间才能格式化完（创建并写入一遍chunkfile），格式化完毕之后，空间利用率应该超过90%才对。

可以看下这部分文档，用`curveadm format --status`检查一下格式化进度：https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment#2-%E5%BC%80%E5%A7%8B%E6%A0%BC%E5%BC%8F%E5%8C%96

如果格式化已经Done状态，可以尝试再次执行deploy命令看下是否可以成功，这个命令是可以多次重复运行的。
