### ISSUE TITLE
How to use client or interface to upload file?

### ISSUE THREAD

**Issue by joeevon** [opencurve/curve#1592]
## General Question
Sorry for disturbing, i have read doc several times, but i still do not know how to upload file both CurveBS and CurveFS.
Hope to get your help.

**Comment by ilixiaocui** [comment]
What does `upload file` mean? Did you mean that you want to contribute code to Curve?

**Comment by joeevon** [comment]
I'm sorry, i did not express clearly.
I mean how to upload file to CurveFS cluster or CurveBS cluster?

**Comment by ilixiaocui** [comment]
首先我们推荐使用 [curveadm](https://github.com/opencurve/curveadm/wiki)搭建一个单机的curvefs或者curvebs集群。
curvebs提供块存储，可以使用nbd的方式挂载。
curvefs提供文件存储，挂载到目录类似文件系统一样使用。

First of all, we recommend using [curveadm](https://github.com/opencurve/curveadm/wiki) to build a curvefs or curvebs 
https://github.com/opencurve/curveadm/wiki.
curvebs provides block storage, which can be mounted using nbd.
curvefs provides file storage, mounted to a directory and used like a file system.
