### ISSUE TITLE
Unknown client connection, mds will always report an error

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curve#1605]
**Describe the bug (描述bug)**
When there is an unknown client (low version) connection, mds will always report an error
![image](https://user-images.githubusercontent.com/7495307/174933400-aabd48ff-1699-4125-a5a2-5916c2c8ff07.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:release2.3
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
The question is the residual old client of old cluster send request to new cluster with new version. Have clean the residual old client and everything is ok.

TODO:
Need some measures to prevent clients that do not belong to the cluster try to connect the cluster.
