### ISSUE TITLE
copy not migrated after stopping metaserver

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1631]
**Describe the bug (描述bug)**

copy not migrated after stopping metaserver

**To Reproduce (复现方法)**
1、run vdbench and mdtest
2、stop metaserver1 copyset migrated
3、start metaserver1 
4、 stop metaserver2 copyset migrated

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
<img width="2299" alt="image" src="https://user-images.githubusercontent.com/10327590/175485660-3b3f96e5-d7e9-4efd-8b74-833d348d1078.png">

it seems when we delete a copyset the corresponding rocksdb instance is not closed, so when create the same copyset again, open rocksdb failed.
