### ISSUE TITLE
diskcache_count far exceeds the limit

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1633]
**Describe the bug (描述bug)**

diskcache_count far exceeds the limit

nbs@prit2-curve-chunk-node12:~$ curl -i 10.166.24.57:9002/vars |grep cache_count
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64169  100 64169    0dcache_cache_count : 10170:01 --:--:--  0:00:01 39410
 diskcache_cache_count : 3936811
    0   151k      0 --:--:-- --:--:-- --:--:--  151k
icache_cache_count : 1021
**To Reproduce (复现方法)**

1 、use fio \vdbench \mdtest test
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
environment：
prit2-curve-chunk-node12.jd.163.org

root     1669378 1669346 50 Jun22 ?        2-13:09:01 /curvefs/client/sbin/curve-fuse -f -o default_permissions -o allow_other -o fsname=test1 -o fstype=s3 -o user=curvefs -o conf=/curvefs/client/conf/client.conf /curvefs/client/mnt/home/nbs/failover/test3


Now the 'diskcache_cache_count' is normal:
<img width="717" alt="截屏2022-06-27 16 39 27" src="https://user-images.githubusercontent.com/13496900/175897772-9a16c24b-32e3-4b0e-96ce-0f901a98e316.png">

There is another problem: seams an object upload failed and can not remove from the cache, but it is not the time cache execeeds the limit.
<img width="1168" alt="截屏2022-06-27 15 59 52" src="https://user-images.githubusercontent.com/13496900/175898639-bd9a36e7-3d5e-4952-a971-0664dcd1d831.png">

<img width="1168" alt="截屏2022-06-27 16 00 23" src="https://user-images.githubusercontent.com/13496900/175898655-6c5bf4ba-1f9c-4402-9109-f164d706e7c2.png">

TODO:
1. Deploy the monitor and to reproduce.
2. Why the object always in write cache dir.
