### ISSUE TITLE
client fuse takes a lot of memory

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1641]
**Describe the bug (描述bug)**
client fuse takes a lot of memory

**To Reproduce (复现方法)**
1、mdtest -C -F -L -z 4 -b 10 -I 10000 -d /home/nbs/failover/test1 -w 1024
2、fio -directory=/home/nbs/failover/test2 -ioengine=psync -rw=write -bs=1024k -direct=1 -group_reporting=1 -fallocate=none -time_based=1 -name=1.txt -numjobs=1 -nrfiles=1 -size=100G
3、vdbench test
![image](https://user-images.githubusercontent.com/67582932/175886848-639b15d5-246d-474c-9394-fb77b57502ee.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/176834831-66e51da7-86cb-449b-a570-9c9ad7071ba9.png)

**Comment by ilixiaocui** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/15689619/177177558-553b38bc-dad1-40ae-8182-9a3ebca2e17e.png">

Memory is occupied by s3Info generated by fio 4k random write and vdbench.
