### ISSUE TITLE
The metaserver process consumes a lot of memory

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1643]
**Describe the bug (描述bug)**
The metaserver process consumes a lot of memory

**To Reproduce (复现方法)**
[zone]
zoneId:1, zoneName:zone1, poolId:1 serverList:{ 1 4 }
zoneId:2, zoneName:zone2, poolId:1 serverList:{ 5 2 }
zoneId:3, zoneName:zone3, poolId:1 serverList:{ 6 3 }
[server]
serverId:1, hostname:10.166.24.58_0_0, internalIp:10.166.24.58, internalPort:6710, externalIp:10.166.16.58, externalPort:7800, zoneId:1, poolId:1 metaserverList:{ 3 }
serverId:2, hostname:10.166.24.59_1_0, internalIp:10.166.24.59, internalPort:6711, externalIp:10.166.16.59, externalPort:7801, zoneId:2, poolId:1 metaserverList:{ 5 }
serverId:3, hostname:10.166.24.35_2_0, internalIp:10.166.24.35, internalPort:6712, externalIp:10.166.16.35, externalPort:7802, zoneId:3, poolId:1 metaserverList:{ 2 }
serverId:4, hostname:10.166.24.58_3_0, internalIp:10.166.24.58, internalPort:6713, externalIp:10.166.16.58, externalPort:7803, zoneId:1, poolId:1 metaserverList:{ 4 }
serverId:5, hostname:10.166.24.59_4_0, internalIp:10.166.24.59, internalPort:6714, externalIp:10.166.16.59, externalPort:7804, zoneId:2, poolId:1 metaserverList:{ 6 }
serverId:6, hostname:10.166.24.35_5_0, internalIp:10.166.24.35, internalPort:6715, externalIp:10.166.16.35, externalPort:7805, zoneId:3, poolId:1 metaserverList:{ 1 }

1、test vdbench and mdtest
2、stop one metaserver metaserverId:3
3、
![image](https://user-images.githubusercontent.com/67582932/175887691-8ffceddc-baec-4340-908c-a8627e4d808e.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
After we enable `allow_stall` for `WriteBufferManager`, the memory usage is stable, and the LOG shows that there are no stall write, so i double maybe that the snapshot recover cause memtables's memory usage exceed the limit:

* jeprof
![memory](https://user-images.githubusercontent.com/9267583/176335008-afa4fb1a-db6f-4c83-8963-74714c81f372.png)

* cluster memory usage:
![image](https://user-images.githubusercontent.com/9267583/176334835-c967ec81-c938-4d4a-8284-a3babae3a89f.png)

* stall request:
![image](https://user-images.githubusercontent.com/9267583/176334879-f8db51a2-28b3-4dc7-b7ce-6cc951dbc19c.png)

**Comment by Wine93** [comment]
The bug fixed, for test, i deploy a cluster and write by mdtest, now the cluster running abount `22` hours, and creates about `1.2E` filter, all metaserver's memory size is stable.

* configure
  * `2GB` write buffer
  * `2GB` cache 

* mdtest
![image](https://user-images.githubusercontent.com/9267583/176575719-12361b67-586d-4a45-add7-13e33961372d.png)

* metaserver's memory
![image](https://user-images.githubusercontent.com/9267583/176575830-63049a0f-d2e8-45ee-80a9-7ad28ce61cbb.png)

* cluster status
![image](https://user-images.githubusercontent.com/9267583/176575855-2c56b944-a416-46dd-9f3f-7f840d5253aa.png)
