### ISSUE TITLE
docker环境中编译不通过，缺少rocksdb/perf_context.h

### ISSUE THREAD

**Issue by sirizhou** [opencurve/curve#1651]
**Describe the bug (描述bug)**
使用docker进行编译，编译过程中显示缺少文件
```shell
Use --sandbox_debug to see verbose messages from the sandbox
[2,314 / 2,364] .../src/metaserver:curvefs_metaserver; 0s proces
In file included from curvefs/src/metaserver/storage/rocksdb_perf.cpp:30:0:
./curvefs/src/metaserver/storage/rocksdb_perf.h:30:34: fatal error: rocksdb/perf_context.h: No such file or directory
 #include "rocksdb/perf_context.h"
                                  ^
compilation terminated.
[2,314 / 2,364] .../src/metaserver:curvefs_metaserver; 0s proces
INFO: Elapsed time: 2992.531s, Critical Path: 57.56s
INFO: 2315 processes: 308 internal, 2007 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
build phase1 failed
```

**To Reproduce (复现方法)**
```shell
docker pull opencurvedocker/curve-base:build-debian9
docker run -it opencurvedocker/curve-base:build-debian9 /bin/bash
cd ~
git clone https://github.com/opencurve/curve.git 或者 git clone https://gitee.com/mirrors/curve.git
bash mk-tar.sh
```
出现编译错误
**Expected behavior (期望行为)**
编译通过

**Versions (各种版本)**
docker version： Docker version 20.10.8, build 3967b7d
 image commit id: opencurvedocker/curve-base   build-debian9   f1633d5137d1 

**Additional context/screenshots (更多上下文/截图)**

**Comment by sirizhou** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/29918459/176226492-1d71861f-9788-4421-9d30-eec0d1501da2.png">

**Comment by SeanHai** [comment]
The mk-tar.sh is no longer maintained after curve v2.0. If you want build the curve, you can refer to: https://github.com/opencurve/curve/blob/6d23a761ceb0b0340a6f6f4e3932d2a0e187f6f8/docs/cn/build_and_run.md

**Comment by sirizhou** [comment]
Is “build.sh” still under normal maintenance? and how can I make debian package or tar package
