### ISSUE TITLE
get inode fail

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1653]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/176341634-b9983536-062f-4836-b30d-9b492dbf871d.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
The root question is one of the partition's compaction is still valid after copyset/metastore had been shut down.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/10327590/176373498-62e11649-aa7e-41cf-8556-ebab1d6d2af9.png">

The first two s3 compactions reference two partitions under the same metastore, but the second one is expired, and the first one isn't.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/10327590/176374962-9d8d9376-87cc-4bb1-be50-151886f37d77.png">


So when the first s3 compaction gets executed, it will fetch inode(attributes and s3 chunkinfos) from backend storage, whereas, the backend storage had been closed, so it prints `get inode fail` into the log file.

![image](https://user-images.githubusercontent.com/10327590/176374354-1df83b8d-2c75-4e57-8853-e967dd6bedab.png)

We can see this from gdb, some members of storage have been set to false or nullptr.

**Comment by h0hmj** [comment]
the ref count of inodeManager_ (shared_ptr<InodeManager>) is 2, which means one for Partition object itself, the other for s3compact_ object
It seems the Partition object is still alive. It is strange.

**Comment by h0hmj** [comment]
avoid usage of invalid inodemanager object
https://gist.github.com/h0hmj/d684e55e19ab26a565e4a17b948924d2
