### ISSUE TITLE
【CI】create fs failed sometimes

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#1655]
**Describe the bug (描述bug)**
The space of metaserver is upload at first heartbeat and this metaserver is unavailable when create fs even it have registered. 

<img width="1436" alt="截屏2022-06-29 10 48 15" src="https://user-images.githubusercontent.com/13496900/176360921-4248a7d3-f89f-4af7-a508-15965d6b331a.png">
<img width="769" alt="截屏2022-06-29 10 49 35" src="https://user-images.githubusercontent.com/13496900/176360930-0f6df5fc-11b1-4d07-9dd2-9017576a664c.png">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
Increase the waiting time before creating fs after the system is created. Now create fs is OK.
