### ISSUE TITLE
Files deleted by other mount points during multiple mounts cannot be created on the original mount point with the same name

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1657]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/176368287-78bcd009-394d-441b-911c-14b022ebf46f.png)
1、touch test1/a
2、rm test2/a
3、touch test1/a

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
it's expected when turning off `cto`, because metadata of `a` in mount point test1 is still valid after removing it in mount point test2.

here is an example

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/10327590/176577200-ae74253f-50a9-4315-9fb0-21d055190a7a.png">

**Comment by ilixiaocui** [comment]
This result is expected and does not guarantee consistency across the same resource operation
