### ISSUE TITLE
curvefs/client: optimize DiskCacheManager::UmountDiskCache()

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1669]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
<img width="462" alt="image" src="https://user-images.githubusercontent.com/15689619/176585035-29d19ae4-3676-477a-85fd-a31c3ce69239.png">

When umount, we do not need UploadAllCacheWriteFile() again, just wait backgroud uploadthread finish upload.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Ziy1-Tan** [comment]
Can I take it? I will try to replace it with `std::promise<int>` to save the return value of uploadthread first, and we just need to check the `std::promise<int>::get_future()::get()` in the img.

**Comment by wuhongsong** [comment]
> I will try to replac

welcome, just do it. @Ziy1-Tan
