### ISSUE TITLE
please update tools.conf after migrate services.

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1674]
**Describe the bug (描述bug)**

please update tools.conf after migrate services.
**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/176626737-612dacfb-1ab9-4cfe-aeef-062708388ad9.png)

![image](https://user-images.githubusercontent.com/67582932/176626816-a0e31a5b-a5c8-4d14-921b-9e38c5999220.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
it will fix in new tool
