### ISSUE TITLE
The listDentry to an empty dir cost too much

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#1679]
**Describe the bug (描述bug)**
Run mdtest "mdtest -z 2 -b 3 -I 10000 -d /mountpoint"
When rmdir need to check dir empty use listDentry:
![截屏2022-07-01 10 44 39](https://user-images.githubusercontent.com/13496900/176813540-83fe0521-74ae-4751-8803-1ec651038565.png)

perf:
W 2022-06-30T20:43:27.583509+0800   311 rocksdb_perf.cpp:154] [RockDBPerf] slow operation
 opType(ITERATOR_SEEK_TO_FIRST)
 latencyUs(2354)
 slowUs(1000)
 perf context(user_key_comparison_count = 60032
 block_cache_hit_count = 30
 block_read_count = 0
 block_read_byte = 0
 block_read_time = 0
 block_cache_index_hit_count = 0
 index_block_read_count = 0
 block_cache_filter_hit_count = 0
 filter_block_read_count = 0
 compression_dict_block_read_count = 0
 secondary_cache_hit_count = 0
 block_checksum_time = 0
 block_decompress_time = 0
 get_read_bytes = 0
 multiget_read_bytes = 0
 iter_read_bytes = 88
 internal_key_skipped_count = 0
 internal_delete_skipped_count = 30000
 internal_recent_skipped_count = 0
 internal_merge_count = 0
 write_wal_time = 0
 get_snapshot_time = 0
 get_from_memtable_time = 0
 get_from_memtable_count = 0
 get_post_process_time = 0
 get_from_output_files_time = 0
 seek_on_memtable_time = 185
 seek_on_memtable_count = 1
 next_on_memtable_count = 0
 prev_on_memtable_count = 0
 seek_child_seek_time = 7509
 seek_child_seek_count = 3
 seek_min_heap_time = 559
 seek_internal_seek_time = 8859
 find_next_user_entry_time = 2343028
 write_pre_and_post_process_time = 0
 write_memtable_time = 0
 write_thread_wait_nanos = 0
 write_scheduling_flushes_compactions_time = 0
 db_mutex_lock_nanos = 0
 db_condition_wait_nanos = 0
 merge_operator_time_nanos = 0
 write_delay_time = 0
 read_index_block_nanos = 0
 read_filter_block_nanos = 0
 new_table_block_iter_nanos = 13513
 new_table_iterator_nanos = 0
 block_seek_nanos = 3388
 find_table_nanos = 0
 bloom_memtable_hit_count = 0
 bloom_memtable_miss_count = 1
 bloom_sst_hit_count = 2
 bloom_sst_miss_count = 0
 key_lock_wait_time = 0
 key_lock_wait_count = 0
 env_new_sequential_file_nanos = 0
 env_new_random_access_file_nanos = 0
 env_new_writable_file_nanos = 0
 env_reuse_writable_file_nanos = 0
 env_new_random_rw_file_nanos = 0
 env_new_directory_nanos = 0
 env_file_exists_nanos = 0
 env_get_children_nanos = 0
 env_get_children_file_attributes_nanos = 0
 env_delete_file_nanos = 0
 env_create_dir_nanos = 0
 env_create_dir_if_missing_nanos = 0
 env_delete_dir_nanos = 0
 env_get_file_size_nanos = 0
 env_get_file_modification_time_nanos = 0
 env_rename_file_nanos = 0
 env_link_file_nanos = 0
 env_lock_file_nanos = 0
 env_unlock_file_nanos = 0
 env_new_logger_nanos = 0
 get_cpu_nanos = 0
 iter_next_cpu_nanos = 0
 iter_prev_cpu_nanos = 0
 iter_seek_cpu_nanos = 2353482)
 iostat context(thread_pool_id = 4
 bytes_read = 120
 bytes_written = 0
 open_nanos = 0
 allocate_nanos = 0
 write_nanos = 0
 read_nanos = 2823
 range_sync_nanos = 0
 fsync_nanos = 0
 prepare_write_nanos = 0
 logger_nanos = 0
 cpu_write_nanos = 0
 cpu_read_nanos = 2194
 file_io_stats_by_temperature.hot_file_bytes_read = 0
 file_io_stats_by_temperature.warm_file_bytes_read = 0
 file_io_stats_by_temperature.cold_file_bytes_read = 0
 file_io_stats_by_temperature.hot_file_read_count = 0
 file_io_stats_by_temperature.warm_file_read_count = 0
 file_io_stats_by_temperature.cold_file_read_count = 0)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
It's a defect of rocksdb, because rocksdb only append an entry with delete type for delete operation, it leads there are many deleted keys in memtables even if all keys deleted, so it costs a lot of time for prefix scan.
We need some optimizations for this cases, but for rocksdb, there is no good way to optimize it (from author).

**Comment by Wine93** [comment]
We had tunning rocksdb to trigger compaction for deleted entrys (point tombstones) as soom as possible, it can reduce range scan performance skews in SST file, but the technologys are all for SST, and there are no good measures for memtables with many point tombstones which not flushed to level-0, except reducing the size of the memtable.
BTW: I don't thinks that's easy to arise in production environment, because there are a lots of writes.
