### ISSUE TITLE
ubuntu上无法编译成功

### ISSUE THREAD

**Issue by RuixiangMa** [opencurve/curve#168]
## General Question
test/failpoint/failpoint_test.cpp:24:25: fatal error: fiu-control.h: No such file or directory
在源代码里面，找不到该文件
需要自己编译下libfiu 嘛？在构建文件里面没发现

**Comment by wu-hanqing** [comment]
这个需要手动用apt安装一下libfiu-dev

**Comment by RuixiangMa** [comment]
> 这个需要手动用apt安装一下libfiu-dev
感谢！
