### ISSUE TITLE
Tool check needs to be unhealthy in case of copyset log behind

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1686]
**Describe the bug (描述bug)**
Tool check needs to be unhealthy in case of copyset log behind

**To Reproduce (复现方法)**

1、stop zone1 all metaserver and use \vdbench\mdtest
2、wait 1 hours
3、start metaserver, use curvefs_tool status 
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
leader 0.0.0.0

**Comment by Cyber-SiKu** [comment]
it will fix in new tool
