### ISSUE TITLE
failed to start curve-chunkserver

### ISSUE THREAD

**Issue by legionxiong** [opencurve/curve#1688]
**Describe the bug (描述bug)**
failed to start curve-chunkserver

**To Reproduce (复现方法)**
sudo curve-chunkserver -bthread_concurrency=18 -raft_max_segment_size=8388608 -raft_max_install_snapshot_tasks_num=1 -raft_sync=true -conf=/etc/curve/chunkserver.conf -chunkFilePoolDir=/home/curve/data/chunkserver0 -chunkFilePoolMetaPath=/home/curve/data/chunkserver0/chunkfilepool.meta -walFilePoolDir=/home/curve/data/chunkserver0 -walFilePoolMetaPath=/home/curve/data/chunkserver0/walfilepool.meta -chunkServerIp=172.24.202.237 -enableExternalServer=false -chunkServerExternalIp=172.24.202.237 -chunkServerPort=8200 -chunkServerMetaUri=local:///home/curve/data/chunkserver0/chunkserver.dat -chunkServerStoreUri=local:///home/curve/data/chunkserver0/ -copySetUri=local:///home/curve/data/chunkserver0/copysets -raftSnapshotUri=curve:///home/curve/data/chunkserver0/copysets -raftLogUri=curve:///home/curve/data/chunkserver0/copysets -recycleUri=local:///home/curve/data/chunkserver0/recycler -raft_sync_segments=true -graceful_quit_on_sigterm=true -raft_use_fsync_rather_than_fdatasync=false -log_dir=/home/curve/data/log/chunkserver0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I 2022-07-03T17:13:46.132970+0800 54270 chunkserver_main.cpp:28] ChunkServer starting.
I 2022-07-03T17:13:46.133183+0800 54270 chunkserver.cpp:89] Loading Configuration.
F 2022-07-03T17:13:46.142313+0800 54270 chunkserver.cpp:585] 
*** Check failure stack trace: ***
*** Aborted at 1656839626 (unix time) try "date -d @1656839626" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0xd3fe) received by PID 54270 (TID 0x7f6661387b40) from PID 54270; stack trace: ***
    @           0xce23d6 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f6660c75630 (unknown)
    @     0x7f665f131387 __GI_raise
    @     0x7f665f132a78 __GI_abort
    @           0xcd8e4e google::FlushAndAbort()
    @           0xcd831d google::LogMessage::Fail()
    @           0xcdd14d google::LogMessage::SendToLog()
    @           0xcd7fbd google::LogMessage::Flush()
    @           0xcd8a09 google::LogMessageFatal::~LogMessageFatal()
    @           0x4e91ce curve::chunkserver::ChunkServer::InitCopysetNodeOptions()
    @           0x4ed124 curve::chunkserver::ChunkServer::Run()
    @           0x4c8e92 main
    @     0x7f665f11d555 __libc_start_main
    @           0x4e78de _start
    @                0x0 (unknown)
Aborted

**Expected behavior (期望行为)**
 start curve-chunkserver successfully

**Versions (各种版本)**
OS: CentOS 7.6
Compiler:
branch: v2.1.0-beta
commit id:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/19409549/177033293-f5bbb0c4-c838-4116-b98a-04ac8bd1d357.png)

**Comment by ilixiaocui** [comment]
F 2022-07-03T17:13:46.142313+0800 54270 chunkserver.cpp:585]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/15689619/177068882-9a190bb2-337c-4a97-a232-8dfa0fade8e6.png">

Missing configuration item in configuration file: copyset.enable_odsync_when_open_chunkfile.

**Comment by legionxiong** [comment]
Only find “copyset.copyset_enable_odsync_when_open_chunkfile” config in chunkserver.conf template，it seems a template configuration issue?
![image](https://user-images.githubusercontent.com/19409549/177079035-9d761e10-02c7-44f8-907f-35acce23076c.png)
![image](https://user-images.githubusercontent.com/19409549/177079558-3f60eede-863e-445c-ab4a-b342bf97af7c.png)

**Comment by wu-hanqing** [comment]
> Only find “copyset.copyset_enable_odsync_when_open_chunkfile” config in chunkserver.conf template，is this the problem? The template configuration file and the code does not match! ![image](https://user-images.githubusercontent.com/19409549/177079035-9d761e10-02c7-44f8-907f-35acce23076c.png) ![image](https://user-images.githubusercontent.com/19409549/177079558-3f60eede-863e-445c-ab4a-b342bf97af7c.png)

You're right, it's a typo, you can remove `copyset_` after the dot or apply this patch https://github.com/opencurve/curve/pull/1690.

And we're deprecating ansible, you can try [curveadm](https://github.com/opencurve/curveadm) to deploy curvebs.
