### ISSUE TITLE
curvefs/client: most of the read data do not cached in diskcache 

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1743]
**Describe the bug (描述bug)**
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/15689619/178919382-762f59ab-bf6e-4a51-bd9a-972f284aab41.png">

diskcachesize is 20GB, cache_miss 360w，but cache_count is just 2.3w，that means the amount of data cached is less than 1GB

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
this is a bug that all the  objects is 4MB after prefetch， fix : https://github.com/opencurve/curve/pull/1711
