### ISSUE TITLE
How to run curveBS after build?

### ISSUE THREAD

**Issue by sirizhou** [opencurve/curve#1777]
## General Question
Hello, curve developers, I have build curve.
```shell
siri@ubuntu:~/curve/bazel-bin/src/chunkserver$ ls
chunkserver                    concurrent_apply               libchunkserver-lib.so               libchunkserver-test-lib.so           raftsnapshot
chunkserver-2.params           datastore                      libchunkserver-lib.so-2.params      libchunkserver-test-lib.so-2.params
chunkserver.runfiles           libchunkserver-lib.a           libchunkserver-test-lib.a           _objs
chunkserver.runfiles_manifest  libchunkserver-lib.a-2.params  libchunkserver-test-lib.a-2.params  raftlog
```
follow the doc "build_and_run_en.md", After building, I run 
```shell
$ ./bazel-bin/test/common/common-test
```
what does this program do? check the environment? I noticed that I have not run  curve before this command.
And the comman output is 
```shell
[  PASSED  ] 68 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] TestDLock.test_LockNoCmp
[  FAILED  ] TestDLock.test_LockCmpSuccess
[  FAILED  ] TestDLock.test_LockCmpSuccessAfterRetry
[  FAILED  ] TestDLock.test_LockCmpTimeout
````
may I ask which doc or .sh tell the procedure to  run curve? I'd like to know how to start curve so that I can debug it.
maybe start chunkserver is 
```shell
chunkserver -bthread_concurrency=18 -raft_max_segment_size=8388608 -raft_sync=true -minloglevel=1 -conf=${conf}/chunkserver.conf.docker3 > ${log}/chunkserver.log.2 2>&1 
```
thank you very much!

**Comment by Wine93** [comment]
>  I'd like to know how to start curve so that I can debug it?

Hi @sirizhou, you can use [curveadm](https://github.com/opencurve/curveadm) to deploy a curve cluster and try to use it. If you want to build curve by your own release you can build the project and make an image of your own tag, like:

```
cd curve
make build release=1
make image tag=TAG  // e.g: make image tag=opencurvedocker/curvebs:my-release
docker push TAG. // e.g: docker push opencurvedocker/curvebs:my-release
```

Then you can specify the [container_image](https://github.com/opencurve/curveadm/wiki/topology#curvebs-%E9%87%8D%E8%A6%81%E9%85%8D%E7%BD%AE%E9%A1%B9) in topology as your image tag and deploy the cluster.

**Comment by sirizhou** [comment]
Thank you very much， I will try it.
