### ISSUE TITLE
curvefs/client: User io and s3 upload will affect each other

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1817]
**Describe the bug (描述bug)**
1. new sdk (io + s3 upload)
![image](https://user-images.githubusercontent.com/15689619/184591406-369d0b28-3e65-4c25-861c-ea395ea2080f.png)
![image](https://user-images.githubusercontent.com/15689619/184782177-32bc125e-cd67-49a1-9942-8c61e452b844.png)

2. new sdk(s3 upload)
![image](https://user-images.githubusercontent.com/15689619/184782140-81b7e5b6-2910-4dad-9c22-a14683c1f099.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
need reproduce
