### ISSUE TITLE
新手：按照编译步骤执行编译报错

### ISSUE THREAD

**Issue by guzhongyan** [opencurve/curve#1819]
按照build_and_run文档，一步一步执行docker编译，报如下错：
![image](https://user-images.githubusercontent.com/12065952/184632192-eb3899d0-1cbf-4e79-a92c-5a7223f409f7.png)

能看看如何解决吗

**Comment by ilixiaocui** [comment]
make build dep=1 试一下

**Comment by guzhongyan** [comment]
@ilixiaocui 按照建议，还是报同样的错。步骤：
1 先拉镜像
docker pull opencurvedocker/curve-base:build-debian9
2 docker内执行：
![image](https://user-images.githubusercontent.com/12065952/184794372-54c0943b-1442-44a2-a3ff-b310d3b79a13.png)

3 编译报错：
![image](https://user-images.githubusercontent.com/12065952/184794417-83aa66f6-c42c-47bd-bb6a-29f4fa7ca8c0.png)

帮忙看看哪儿出问题了？

**Comment by fansehep** [comment]
试试
```
$ cd curve/thirdparties/etcdclient
$ make all
```

**Comment by guzhongyan** [comment]
谢谢。
继续遇到如下错误：
![image](https://user-images.githubusercontent.com/12065952/184873363-7088c295-c4f2-43cc-859d-93c5e6328c61.png)
and this:
![image](https://user-images.githubusercontent.com/12065952/184873489-6214b82a-c359-4d8f-aa26-3ea0e0ca35c1.png)

**Comment by fansehep** [comment]
> 谢谢。 继续遇到如下错误： ![image](https://user-images.githubusercontent.com/12065952/184873363-7088c295-c4f2-43cc-859d-93c5e6328c61.png) and this: ![image](https://user-images.githubusercontent.com/12065952/184873489-6214b82a-c359-4d8f-aa26-3ea0e0ca35c1.png)

here
```bash
$ cd curve/curvebs
$ make dep=1
```

**Comment by guzhongyan** [comment]
Thanks a lot.
I just tried curveadm following the manual, but some cmds do not work:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/12065952/184877499-7d4bd8c5-4e8d-4269-8129-cab75a6646ec.png">
I will try the left, hope it will work.

**Comment by wu-hanqing** [comment]
might be a version mismatch between `curveadm` and the wiki.

@Wine93, could you help @guzhongyan figure out this problem?

**Comment by Wine93** [comment]
@guzhongyan 你下载的应该是老版本，但是由于我们今天有段时间在调试文档，你看到的应该是最新的文档，所以导致不匹配了。你可以尝试重新安装 curveadm，并按照文档指引进行部署。

**Comment by h0hmj** [comment]
> 谢谢。 继续遇到如下错误： ![image](https://user-images.githubusercontent.com/12065952/184873363-7088c295-c4f2-43cc-859d-93c5e6328c61.png) and this: ![image](https://user-images.githubusercontent.com/12065952/184873489-6214b82a-c359-4d8f-aa26-3ea0e0ca35c1.png)

aws-sdk-cpp is a thirdparty module. cmake is needed to build it. 

it seems cmake is missing in the image.

run `apt install cmake` and try again.

**Comment by 201341** [comment]
hi, could you curvefs guys provide  docker-compose file that we can use `docker-compose up` to run  curvefs immediately?

**Comment by Wine93** [comment]
> 

Maybe curveadm `playground` can help you, try it: 

```
$ curveadm playground run --kind curvefs --mountpoint /path/to/mount
```

**Comment by Wine93** [comment]
> hi, could you curvefs guys provide docker-compose file that we can use `docker-compose up` to run curvefs immediately? @Wine93 @wu-hanqing

@201341 Maybe curveadm `playground` can help you, try it: 

```
$ curveadm playground run --kind curvefs --mountpoint /path/to/mount
```

**Comment by ilixiaocui** [comment]
@201341 If there are new questions, please submit the new issue.
