### ISSUE TITLE
deploy文档的all-in-one的docker镜像部署跑不起来

### ISSUE THREAD

**Issue by guzhongyan** [opencurve/curve#1824]
按照文档执行：
docker run --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules --privileged -it opencurve/curveintegration:centos8 /bin/bash
不想编译，想直接部署体验，于是找现成的编译好的tar包，进到docker 下载并执行
wget https://github.com/opencurve/curve/releases/download/v1.3.0-beta2/curve_1.3.0-beta2+1e621162.tar.gz
tar zxvf curve_1.3.0-beta2+1e621162.tar.gz
 cd curve
 cd curve-ansible/
 ansible-playbook -i server.ini deploy_curve.yml
结果：
![image](https://user-images.githubusercontent.com/12065952/184799905-d540bae1-f82c-4ce4-847c-1792659ce3a9.png)
运行工具报错：
![image](https://user-images.githubusercontent.com/12065952/184799987-e852d6c0-8d85-4465-a14f-fcb8b1b57e2e.png)

curve的工程师大牛们，能给个正确的姿势，一键编译搞不成功，一键单机部署咋也这么残？至少ceph的all in one box部署那是相当流畅没问题。
社区贡献了这么多代码，还出了详细的文档，B站精致的技术视频。 但编译和部署跟ceph比，体验也太差了吧。这要推广curve,跟ceph PK， 任重道远啊。

**Comment by fansehep** [comment]
hey, here https://github.com/opencurve/curveadm/wiki

**Comment by cw123** [comment]
按照最新的部署文档，部署是否能够成功？
