### ISSUE TITLE
CI test is unstable.

### ISSUE THREAD

**Issue by fansehep** [opencurve/curve#1827]
**Describe the bug (描述bug)**
Some tests will inexplicable failure. Many pull requests we should recheck repeatedly.
I think we should check and upgrade our CI and some tests. 

It's really Necessary to fix CI test as fast as we can.
This problem hinders our efficiency and **caused huge damage to our body and mind**. 💔 

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
1. Check out tests in CI. Find the reasons of failure and fix them.
2. Upgrade our CI version (maybe)

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by YunhuiChen** [comment]
The current master version incorporates some unstable code, to be resolved
 https://github.com/opencurve/curve/issues/1830

**Comment by fansehep** [comment]
> The current master version incorporates some unstable code, to be resolved #1830

Thanks for your reply. 😊 
And i meet the snapshot server tests fail many times. I hope we can fix it as soon as possible. 😢 
To prevent this case reproduce, we can check some pull requests with a lot of code **many times** after now.
The check times add to 4 times is good for some big pull requests.
