### ISSUE TITLE
fuse stuck after pre-reading the path of mdtest test

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1835]
**Describe the bug (描述bug)**
fuse stuck after pre-reading the path of mdtest test

**To Reproduce (复现方法)**
1、root      407473  407440 59 14:47 ?        01:20:54 /curvefs/client/sbin/curve-fuse -f -o default_permissions -o allow_other -o fsname=test2 -o fstype=s3 -o user=curvefs -o conf=/curvefs/client/conf/client.conf /curvefs/client/mnt/home/nbs/failover/test4
root      408373  408340 15 14:48 ?        00:20:48 /curvefs/client/sbin/curve-fuse -f -o default_permissions -o allow_other -o fsname=test2 -o fstype=s3 -o user=curvefs -o conf=/curvefs/client/conf/client.conf /curvefs/client/mnt/home/nbs/failover/test5

2、mdtest -C -F -L -z 4 -b 10 -I 10000 -d /home/nbs/failover/test4 -w 1024
3、
![image](https://user-images.githubusercontent.com/67582932/185079926-3139142f-6a6f-4f14-941c-0bef3b31ed8f.png)

![image](https://user-images.githubusercontent.com/67582932/185079977-841f70ed-e999-405b-98f0-e14b7d6ed11b.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
not use the new aws sdk
