### ISSUE TITLE
After curveadm clean metaserver, the interface needs to be set to offline

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1838]
**Describe the bug (描述bug)**
After curveadm clean metaserver, the interface needs to be set to offline
1、stop 
2、clean
3、修改stop的metaserver的数据路径,提交修改
4、deploy

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
@SeanHai will modify the pr later

**Comment by wuhongsong** [comment]
@SeanHai
