### ISSUE TITLE
Failed to umount warmup mount point

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1841]
**Describe the bug (描述bug)**
Failed to umount warmup mount point

**To Reproduce (复现方法)**

sudo curve fs warmup add /home/nbs/failover/test6

nbs@prit2-curve-chunk-node12:~$ curveadm umount /home/nbs/failover/test6  --host node12
Umount FileSystem: [ERROR]  
  + host=node12  mountPoint=/home/nbs/failover/test6 [0/1] [ERROR]  
---
Error-Code: 600000
Error-Description: execute command timed out
Error-Clue: wait container stop failed (docker stop CONTAINER)
How to Solve:
  * Website: https://github.com/opencurve/curveadm/wiki/errno#600000
  * Log: /home/nbs/.curveadm/logs/curveadm-2022-08-18_17-17-15.log
  * WeChat: opencurve_bot
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
The bug fixed for curveadm `v0.1.4`, maybe you can retry it again.
