### ISSUE TITLE
tag error in  “prepare_chunkserver_with_disk_format.yml”

### ISSUE THREAD

**Issue by sirizhou** [opencurve/curve#1846]
**Describe the bug (描述bug)**
./chunkserver_ctl.sh: command not found
```shell
TASK [format_chunkserver : format chunkfilepool] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "sudo ./chunkserver_ctl.sh deploy all --noConfirm", "delta": "0:00:00.005727", "end": "2022-08-19 12:09:53.160597", "msg": "non-zero return code", "rc": 1, "start": "2022-08-19 12:09:53.154870", "stderr": "sudo: ./chunkserver_ctl.sh: command not found", "stderr_lines": ["sudo: ./chunkserver_ctl.sh: command not found"], "stdout": "", "stdout_lines": []}
```
I think here should set **_chdir_** 
```yml
- name: format chunkfilepool
  shell: sudo ./chunkserver_ctl.sh deploy all --noConfirm
```

**To Reproduce (复现方法)**

```shell
ansible-playbook deploy_curve.yml -i server.ini --tags chunkserver
```

**Expected behavior (期望行为)**
run with no fatal
 **I think the shell tag should be**
```yml
 shell: chdir={{ deploy_dir }} sudo ./chunkserver_ctl.sh deploy all --noConfirm
```

**Versions (各种版本)**
OS:
Compiler:
branch: master
commit id: [7c70577](https://github.com/opencurve/curve/commit/7c705774a842a6a6af8c504ad879607ea218f232)

**Additional context/screenshots (更多上下文/截图)**

<img width="767" alt="image" src="https://user-images.githubusercontent.com/29918459/185543319-cf5ef88b-2b75-4375-bbff-5784db1e0376.png">
<img width="610" alt="image" src="https://user-images.githubusercontent.com/29918459/185543371-2a6bd8be-44a2-4eca-91ff-bb9c9ed0d4d6.png">

**Comment by ilixiaocui** [comment]
Ansible is the old deployment tool, please use the new deployment tool [adm](https://github.com/opencurve/curveadm/wiki)

**Comment by sirizhou** [comment]
thank you. I have deployed it by using curveadm
