### ISSUE TITLE
update `atime` correctly

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1849]
By default, curve-fuse is mounted with `relatime` flag, and `relatime` means we should only update access time in fewer cases, however, we update it each time in read.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/10327590/185641569-78dee54e-967c-40d3-a530-74586d294a8f.png">

And also, we don't handle file opened with `O_NOATIME` and mount fuse with `noatime`. 

#### relatime - relative time
> With relative atime, only update atime if the previous atime is
earlier than either the ctime or mtime or if at least a day has
passed since the last atime update.

https://github.com/torvalds/linux/blob/4c2d0b039c5cc0112206a5b22431b577cb1c57ad/fs/inode.c#L1805

**Comment by fansehep** [comment]
The atime/noatime/relatime mount options are ignored by fuse, so
that's not an indication whether the filesystem updates atime or not.

To enable full atime support, the filesystem needs to disable data
caching (set fi->direct_io = 1 in open) and update atime in each read.

**Comment by wuhongsong** [comment]
@wu-hanqing

**Comment by caoxianfei1** [comment]
@wu-hanqing
