### ISSUE TITLE
inode's timestamp is not fixed when encountered metaserver failover/restart

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1850]
Inode's timestamp(atime/ctime/mtime) is initialized in metaserver when creating an inode, but this has two problems:
1. The create inode request is executed in three replicas separately, which means the inode in three replicas may have a different timestamp, so if raft group's leader transferred, we will see timestamp changed automatically.
2. If a create inode request is not included in raft snapshot, the request will execute again, which also results in the inode's timestamp changed automatically.

And this should not meet the POSIX standard.

https://github.com/opencurve/curve/blob/6b7d5dd2d94ce487be81af7015f6a6ab623d1b7e/curvefs/src/metaserver/inode_manager.cpp#L101

**Comment by fansehep** [comment]
@wu-hanqing Close it. 😄
