### ISSUE TITLE
Warmup 50G files written sequentially, the cache capacity exceeds 70G 

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1851]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
mount fs1 to test1 and test3
1、fio --name=big-file-multi-write --directory=/home/nbs/failover/test1 --rw=write --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
2、sudo curve fs warmup add /home/nbs/failover/test3/big-file-multi-write.0.0
![image](https://user-images.githubusercontent.com/67582932/185888126-4f2d4799-d454-40f2-b885-8f816de9aff6.png)
![image](https://user-images.githubusercontent.com/67582932/185888195-e5dd3c1e-9359-42df-b4bf-7be469d47157.png)

17918 * 4m/1024 = 70G 
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
cc @wuhongsong 
Please continue to follow up and fix this problem.

**Comment by wuhongsong** [comment]
> cc @wuhongsong Please continue to follow up and fix this problem.

There is no good solution to this possible data redundancy problem.

**Comment by Cyber-SiKu** [comment]
![image](https://user-images.githubusercontent.com/15775037/211981967-779895f0-8174-4723-9c42-a62407c21760.png)

![image](https://user-images.githubusercontent.com/15775037/211982034-ec5bf868-7a8e-4d39-80b9-3d91e3ca9432.png)
