### ISSUE TITLE
The performance of reading files after warmup is relatively low

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1855]
**Describe the bug (描述bug)**
The performance of reading files after warmup is relatively low

**To Reproduce (复现方法)**
1、mount fs1 to test1 and test3
2、 fio --name=warmup-write-4 --directory=/home/nbs/failover/test1 --rw=write --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
3、sudo curve fs warmup add /home/nbs/failover/test3/warmup-write-3.0.0
4、fio --name=warmup-write-4 --directory=/home/nbs/failover/test3 --rw=read --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
![image](https://user-images.githubusercontent.com/67582932/186126889-9125edd4-31c2-49a3-b245-da04d8e82817.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
![image](https://user-images.githubusercontent.com/13897133/186588700-355878b5-53f3-458c-830d-3c9eeac5ba7d.png)

The funcition of GetInode has added lock(inodeWrapper->GetUniqueLock) for resolve cto bug

**Comment by wuhongsong** [comment]
so it will lead lock contention

**Comment by SeanHai** [comment]
To Reproduce:
code: branch release2.4-f2c6115d

1. mount fs curve to mut and warmup

2. fio --name=warmup-write-4 --directory=/home/wanghai01/curvefs/mut --rw=write --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
warmup-write-4: (g=0): rw=write, bs=1M-1M/1M-1M/1M-1M, ioengine=psync, iodepth=1
fio-2.16
Starting 1 process
warmup-write-4: Laying out IO file(s) (1 file(s) / 51200MB)
Jobs: 1 (f=1): [F(1)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00s]
warmup-write-4: (groupid=0, jobs=1): err= 0: pid=298640: Tue Aug 30 14:18:19 2022
  write: io=51200MB, bw=365931KB/s, iops=357, runt=143275msec
    clat (msec): min=1, max=245, avg= 2.55, stdev=10.11
     lat (msec): min=1, max=245, avg= 2.55, stdev=10.11
    clat percentiles (usec):
     |  1.00th=[ 1208],  5.00th=[ 1240], 10.00th=[ 1256], 20.00th=[ 1288],
     | 30.00th=[ 1304], 40.00th=[ 1336], 50.00th=[ 1368], 60.00th=[ 1416],
     | 70.00th=[ 1464], 80.00th=[ 1576], 90.00th=[ 1720], 95.00th=[ 1832],
     | 99.00th=[59648], 99.50th=[67072], 99.90th=[156672], 99.95th=[166912],
     | 99.99th=[179200]
    lat (msec) : 2=97.31%, 4=1.12%, 10=0.04%, 20=0.02%, 50=0.27%
    lat (msec) : 100=0.87%, 250=0.37%
  cpu          : usr=7.91%, sys=15.96%, ctx=460892, majf=0, minf=10
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=51200/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: io=51200MB, aggrb=365931KB/s, minb=365931KB/s, maxb=365931KB/s, mint=143275msec, maxt=143275msec

4. wait 5min and curve fs warmup add /home/wanghai01/curvefs/warmup/warmup-write-4.0.0

5. wait warmup finished : 
root@pubbeta2-curve9:/wanghai/diskcache1/cache/cacheread# ls | wc -l
12800

6. root@pubbeta2-curve9:/wanghai/diskcache1/cache# fio --name=warmup-write-4 --directory=/home/wanghai01/curvefs/warmup --rw=read --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
warmup-write-4: (g=0): rw=read, bs=1M-1M/1M-1M/1M-1M, ioengine=psync, iodepth=1
fio-2.16
Starting 1 process
Jobs: 1 (f=1): [R(1)] [97.6% done] [1367MB/0KB/0KB /s] [1367/0/0 iops] [eta 00m:02s]
warmup-write-4: (groupid=0, jobs=1): err= 0: pid=332689: Tue Aug 30 15:07:04 2022
  read : io=51200MB, bw=633573KB/s, iops=618, runt= 82751msec
    clat (usec): min=578, max=26637, avg=1614.55, stdev=1265.79
     lat (usec): min=578, max=26637, avg=1614.70, stdev=1265.81
    clat percentiles (usec):
     |  1.00th=[  628],  5.00th=[  652], 10.00th=[  668], 20.00th=[  692],
     | 30.00th=[  708], 40.00th=[  732], 50.00th=[  756], 60.00th=[  796],
     | 70.00th=[ 3152], 80.00th=[ 3344], 90.00th=[ 3472], 95.00th=[ 3568],
     | 99.00th=[ 3792], 99.50th=[ 3920], 99.90th=[ 4576], 99.95th=[ 5024],
     | 99.99th=[ 7840]
    lat (usec) : 750=48.23%, 1000=17.57%
    lat (msec) : 2=0.76%, 4=33.12%, 10=0.32%, 20=0.01%, 50=0.01%
  cpu          : usr=0.21%, sys=22.94%, ctx=399602, majf=0, minf=262
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=51200/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=51200MB, aggrb=633573KB/s, minb=633573KB/s, maxb=633573KB/s, mint=82751msec, maxt=82751msec

**Comment by SeanHai** [comment]
> so it will lead lock contention. and other issue is if the cacheread directory has a large number of files in it,then read may slow, especially in hdd

There is no lock contention, and the cost of get lock is just about 5us：
<img width="549" alt="截屏2022-08-30 15 13 51" src="https://user-images.githubusercontent.com/13496900/187373594-7ae5ca2e-50ab-448e-8735-cb39ce0ca9a8.png">


I 2022-08-30T15:05:41.956357+0800    87 inode_cache_manager.cpp:111] <<< GetInode hit
I 2022-08-30T15:05:41.956362+0800    87 inode_cache_manager.cpp:116] <<< after get lock
I 2022-08-30T15:05:41.956365+0800    87 inode_cache_manager.cpp:119] <<< after refresh need = 0
I 2022-08-30T15:05:41.956374+0800    81 inode_cache_manager.cpp:111] <<< GetInode hit
I 2022-08-30T15:05:41.956382+0800    81 inode_cache_manager.cpp:116] <<< after get lock
I 2022-08-30T15:05:41.956385+0800    81 inode_cache_manager.cpp:119] <<< after refresh need = 0
I 2022-08-30T15:05:41.956401+0800    87 inode_cache_manager.cpp:111] <<< GetInode hit
I 2022-08-30T15:05:41.956405+0800    87 inode_cache_manager.cpp:116] <<< after get lock
I 2022-08-30T15:05:41.956408+0800    87 inode_cache_manager.cpp:119] <<< after refresh need = 0
I 2022-08-30T15:05:41.956418+0800    81 inode_cache_manager.cpp:111] <<< GetInode hit
I 2022-08-30T15:05:41.956423+0800    81 inode_cache_manager.cpp:116] <<< after get lock
I 2022-08-30T15:05:41.956434+0800    81 inode_cache_manager.cpp:119] <<< after refresh need = 0

**Comment by SeanHai** [comment]
Test after turn on cto:
root@pubbeta2-curve9:/home/wanghai01/curvefs# fio --name=warmup-write-4 --directory=/home/wanghai01/curvefs/mut --rw=write --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
warmup-write-4: (g=0): rw=write, bs=1M-1M/1M-1M/1M-1M, ioengine=psync, iodepth=1
fio-2.16
Starting 1 process
warmup-write-4: Laying out IO file(s) (1 file(s) / 51200MB)
Jobs: 1 (f=1): [F(1)] [100.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 00m:00s]
warmup-write-4: (groupid=0, jobs=1): err= 0: pid=411467: Tue Aug 30 16:55:51 2022
  write: io=51200MB, bw=290212KB/s, iops=283, runt=180657msec
    clat (usec): min=896, max=345044, avg=2522.14, stdev=11576.69
     lat (usec): min=896, max=345044, avg=2522.36, stdev=11576.69
    clat percentiles (usec):
     |  1.00th=[  972],  5.00th=[ 1004], 10.00th=[ 1032], 20.00th=[ 1048],
     | 30.00th=[ 1080], 40.00th=[ 1112], 50.00th=[ 1160], 60.00th=[ 1208],
     | 70.00th=[ 1288], 80.00th=[ 1384], 90.00th=[ 1512], 95.00th=[ 1608],
     | 99.00th=[71168], 99.50th=[77312], 99.90th=[173056], 99.95th=[179200],
     | 99.99th=[232448]
    lat (usec) : 1000=3.99%
    lat (msec) : 2=93.80%, 4=0.61%, 10=0.05%, 20=0.02%, 50=0.16%
    lat (msec) : 100=0.97%, 250=0.38%, 500=0.01%
  cpu          : usr=6.09%, sys=12.29%, ctx=460889, majf=0, minf=10
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=51200/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: io=51200MB, aggrb=290211KB/s, minb=290211KB/s, maxb=290211KB/s, mint=180657msec, maxt=180657msec



root@pubbeta2-curve9:/home/wanghai01/curvefs# fio --name=warmup-write-4 --directory=/home/wanghai01/curvefs/warmup --rw=read --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
warmup-write-4: (g=0): rw=read, bs=1M-1M/1M-1M/1M-1M, ioengine=psync, iodepth=1
fio-2.16
Starting 1 process
^Cbs: 1 (f=1): [R(1)] [67.5% done] [75776KB/0KB/0KB /s] [74/0/0 iops] [eta 03m:39s]
fio: terminating on signal 2

warmup-write-4: (groupid=0, jobs=1): err= 0: pid=489567: Tue Aug 30 18:52:15 2022
  read : io=34520MB, bw=78013KB/s, iops=76, runt=453112msec
    clat (msec): min=8, max=194, avg=13.12, stdev= 3.24
     lat (msec): min=8, max=194, avg=13.12, stdev= 3.24
    clat percentiles (usec):
     |  1.00th=[ 9536],  5.00th=[10048], 10.00th=[10432], 20.00th=[11328],
     | 30.00th=[12096], 40.00th=[12608], 50.00th=[12864], 60.00th=[13248],
     | 70.00th=[13632], 80.00th=[14144], 90.00th=[14912], 95.00th=[15808],
     | 99.00th=[23936], 99.50th=[32384], 99.90th=[47360], 99.95th=[51456],
     | 99.99th=[63744]
    lat (msec) : 10=4.51%, 20=93.13%, 50=2.29%, 100=0.07%, 250=0.01%
  cpu          : usr=0.05%, sys=2.96%, ctx=191432, majf=0, minf=264
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=34520/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=34520MB, aggrb=78012KB/s, minb=78012KB/s, maxb=78012KB/s, mint=453112msec, maxt=453112msec

**Comment by SeanHai** [comment]
The reason is: refresh inode which have huge s3Info when getAttr in read operation

<img width="601" alt="截屏2022-08-30 18 53 08" src="https://user-images.githubusercontent.com/13496900/187418970-33d28fad-f983-4ef6-9af7-5ec98b61168e.png">

![截屏2022-08-30 18 52 22](https://user-images.githubusercontent.com/13496900/187418987-1fc8c413-c093-4c31-b4f5-9bf6b305c674.png)

**Comment by SeanHai** [comment]
after fix:
root@pubbeta2-curve9:/home/wanghai01/curvefs# fio --name=warmup-write-4 --directory=/home/wanghai01/curvefs/warmup --rw=read --refill_buffers --bs=1M --size=50G --numjobs=1 --end_fsync=1 -fallocate=none
warmup-write-4: (g=0): rw=read, bs=1M-1M/1M-1M/1M-1M, ioengine=psync, iodepth=1
fio-2.16
Starting 1 process
^Cbs: 1 (f=1): [R(1)] [64.6% done] [295.0MB/0KB/0KB /s] [295/0/0 iops] [eta 01m:02s]
fio: terminating on signal 2

warmup-write-4: (groupid=0, jobs=1): err= 0: pid=571221: Tue Aug 30 20:39:37 2022
  read : io=32974MB, bw=301622KB/s, iops=294, runt=111946msec
    clat (usec): min=2296, max=14275, avg=3392.71, stdev=296.33
     lat (usec): min=2296, max=14275, avg=3392.89, stdev=296.32
    clat percentiles (usec):
     |  1.00th=[ 2704],  5.00th=[ 2896], 10.00th=[ 3024], 20.00th=[ 3184],
     | 30.00th=[ 3280], 40.00th=[ 3344], 50.00th=[ 3408], 60.00th=[ 3472],
     | 70.00th=[ 3536], 80.00th=[ 3568], 90.00th=[ 3696], 95.00th=[ 3824],
     | 99.00th=[ 4080], 99.50th=[ 4256], 99.90th=[ 5280], 99.95th=[ 5792],
     | 99.99th=[ 8512]
    lat (msec) : 4=98.44%, 10=1.55%, 20=0.01%
  cpu          : usr=0.13%, sys=10.22%, ctx=210081, majf=0, minf=262
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=32974/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=32974MB, aggrb=301621KB/s, minb=301621KB/s, maxb=301621KB/s, mint=111946msec, maxt=111946msec
