### ISSUE TITLE
pjdtest truncate file larger result in high memory usage

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1861]
commit id: bcafdaf6d6b580a479b6ab59b1ab1285f5396025

one of the truncate cases in [pjdtest](https://github.com/pjd/pjdfstest) will truncate a file to very large `999999999999999`
https://github.com/pjd/pjdfstest/blob/e26d67b977ee5cdb4c83a2909c72e1e5dc12c4f1/tests/ftruncate/12.t#L15

and in our implementation, we will add enough zero s3chunkinfo to fulfill this, which means it will create lots of `S3ChunkInfo` objects in memory.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/10327590/186599475-f0b287f7-b51e-4cd4-97b5-43746703c64a.png">

https://github.com/opencurve/curve/blob/de5102a04ba7581b76c93f404d583e269698f535/curvefs/src/client/s3/client_s3_adaptor.cpp#L179

**Comment by wuhongsong** [comment]
@wu-hanqing
