### ISSUE TITLE
The copy data is damaged after the node is dropped ，Or need a repair tool

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1882]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/187883953-12af452b-ec5b-4ebf-86d4-9740ed8edc78.png)

![image](https://user-images.githubusercontent.com/67582932/187883990-d29a1046-1e63-45ef-a934-63665eb46cf1.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@YunhuiChen  assign ?
