### ISSUE TITLE
The recover of copysets seem abnormal

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#1914]
**Describe the bug (描述bug)**
1. code from master （harbor.cloud.netease.com/curve/curvefs:wanghai-offline_metaserver）
2. 3 server and 6 metaserver
3. there are 6 copysets on each metaserver after deploy
Here are the two metaserver's copysets of zone1:
<img width="813" alt="截屏2022-09-13 11 28 13" src="https://user-images.githubusercontent.com/13496900/189834086-e2a51095-d359-483c-914f-1753b72aa140.png">

4. stop metaserver id = 4 and clean (curveadm stop -id ; curveadm clean --id )
<img width="1041" alt="截屏2022-09-13 11 29 46" src="https://user-images.githubusercontent.com/13496900/189834280-ca2f87bc-32cd-4706-b338-999ad7fa1024.png">

5. set to offline
<img width="1168" alt="截屏2022-09-13 11 30 59" src="https://user-images.githubusercontent.com/13496900/189834915-1fbf2c21-3624-4ec3-acb5-fe0fc0ee356d.png">

6 find some copysets change peer form 4 to 3
<img width="856" alt="截屏2022-09-13 11 34 25" src="https://user-images.githubusercontent.com/13496900/189835186-0de3b98e-af13-4d05-a937-74de7e7dd663.png">

7. deploy agagin and add the metaserver (old id is 4) in cluster and new id is 7
<img width="1147" alt="截屏2022-09-13 15 22 51" src="https://user-images.githubusercontent.com/13496900/189836981-21025c90-2b84-430f-ad25-3c2e01fad88e.png">

<img width="752" alt="截屏2022-09-13 11 39 32" src="https://user-images.githubusercontent.com/13496900/189835358-c767423f-69f8-435c-8eeb-9c3953576f88.png">

8. but the distribution of copysets is not balance all the way
<img width="798" alt="截屏2022-09-13 11 39 51" src="https://user-images.githubusercontent.com/13496900/189835541-1bc01c91-522b-4f9c-802b-3ec88ff8de35.png">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
Metaserver 7 use more disk than metaserver 3, so copyset can't transfer from metaserve 3 to metaesrver 7.

After sudo tune2fs -m 0 /dev/disk_of_metaserver7 and the reserved space is free, the copyset transfer from metaserver 3 to metaserver 7. The copyset num of metaserver 3 and metaserver 7 are both 6.
