### ISSUE TITLE
Some data is lost after echo data and vdbench

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1926]
**Describe the bug (描述bug)**
Some data is lost after echo data and vdbench

![image](https://user-images.githubusercontent.com/67582932/190979467-54a5cba2-1d1d-4bda-bb55-e344c3edfde6.png)

**To Reproduce (复现方法)**
1、nbs@pubbeta2-nova48:~$ cat test2.sh 
#/bin/bash
for i in `seq 1 1000`;do
echo "test $i" >> /home/nbs/failover/test1/cyh5
echo "test $i" >> /home/nbs/failover/test1/cyh5
echo "test $i" >> /home/nbs/failover/test1/cyh5
done
2、use vdbench test
 

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
![image](https://user-images.githubusercontent.com/15775037/211991448-3bfd914f-6756-4a5f-bce1-ed1535db74ed.png)
