### ISSUE TITLE
curvefs: disk_used is too large

### ISSUE THREAD

**Issue by 201341** [opencurve/curve#1953]
**Describe the bug (描述bug)**
deploy the curvefs to one docker container, the disk_used value is too large.
<img width="679" alt="截屏2022-10-10 16 54 17" src="https://user-images.githubusercontent.com/13047679/195121863-f78a77aa-723f-43cf-9bc5-9a7b396921ed.png">

<img width="451" alt="截屏2022-10-10 16 09 41" src="https://user-images.githubusercontent.com/13047679/195121882-5951725f-eda2-48bf-b6e0-f69df74919a2.png">

**To Reproduce (复现方法)**
```
mkdir -p /share
cd share
git clone https://github.com/201341/projects.git 
mv projects /share/
docker run -it --privileged -v /share:/code opencurvedocker/curve-base:build-debian9  /bin/bash
cd projects/scripts 
bash start-etcd.sh
bash start-mds.sh
bash start-metaserver.sh
bash create-topology.sh
```

**Expected behavior (期望行为)**
disk_used is the acutal value of metaserver data

**Versions (各种版本)**
OS: debian9
Compiler: gcc7
branch: master
commit id: 00bf32f4

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
@cw123

**Comment by wuhongsong** [comment]
@cw123  Can you confirm it?
