### ISSUE TITLE
umountfs failed: mountpoint not exist but can list out

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#1981]
**Describe the bug (描述bug)**
v2.3

umountfs failed after client crash:

<img width="1437" alt="截屏2022-10-14 17 23 02" src="https://user-images.githubusercontent.com/13496900/195812357-517f3a11-672a-4cf1-b82c-cf61be327525.png">

<img width="606" alt="截屏2022-10-14 17 21 45" src="https://user-images.githubusercontent.com/13496900/195812323-bf0e4630-6914-45bf-b720-0a815ba3c83e.png">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
@Cyber-SiKu @jolly-sy How is it going on？
