### ISSUE TITLE
When the cluster is abnormal, the tool hangs up when viewing the cluster information

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1994]
**Describe the bug (描述bug)**

When the cluster is abnormal, the tool hangs up when viewing the cluster information

**To Reproduce (复现方法)**
1、stop metaserver 、mds \ etcd 
2、curve fs status cluster

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@Cyber-SiKu
