### ISSUE TITLE
Plan to support helm deploy?

### ISSUE THREAD

**Issue by fly3366** [opencurve/curve#2016]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Autoscale with k8s and local PV.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
yes， here is the discussion, community partners have already started.

**Comment by zhanghuidinah** [comment]
ref：https://github.com/opencurve/curve/issues/2052
