### ISSUE TITLE
[curve tool]: implement `reset-peer` commnad

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#2018]
**Describe the feature you'd like:**

we'd like to support `reset-peer` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

`reset-peer` is one of the commands to make configuration changes to a raft replication group. 

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/5e49aed29c6cbf75f046373ecfd17ec0d3fbe0c5/src/tools/curve_cli.cpp#L189
- The old command input and out put:
  ```
  reset-peer : reset the configuration of copyset, only reset to one peer is supported
  
  curve_ops_tool reset-peer --example
  Example
  curve_ops_tool reset-peer -logicalPoolId=1 -copysetId=10001 -peer=127.0.0.1:8080:0 -new_conf=127.0.0.1:8080:0 -max_retry=3 -timeout_ms=100
  
  output:
  reset peer ok
  ```
  

**Teachability, Documentation, Adoption, Migration Strategy:**

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

**Comment by ilixiaocui** [comment]
Please note that the code submission deadline for this developer activity is December 3rd :) 
@whalecold

**Comment by wuhongsong** [comment]
@whalecold   If you are free, you are welcome to continue the work

**Comment by whalecold** [comment]
> 

ok

**Comment by whalecold** [comment]
> @whalecold If you are free, you are welcome to continue the work

my pleasure

**Comment by ilixiaocui** [comment]
cc @whalecold Is this issue still being followed up?
