### ISSUE TITLE
[compile] Merge the two scripts `mk-tar.sh` and `mk-deb.sh`

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#2024]
**Describe the feature you'd like:**

Currently we have two scripts, one for [generating tar packages](https://github.com/opencurve/curve/blob/master/mk-tar.sh) and one for [generating deb packages](https://github.com/opencurve/curve/blob/master/mk-deb.sh). There are a lot of duplicated parts in these two scripts, like compilation.

We hope to combine these two scripts，compile different types of packages through parameters, such as `sh mk-package.sh tar `and `sh mk-package.sh deb`.

**Teachability, Documentation, Adoption, Migration Strategy:**

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md.

**Comment by Nageshbansal** [comment]
@ilixiaocui, can I work on this issue, and if so then please assign this issue to me.

**Comment by ilixiaocui** [comment]
> @ilixiaocui, can I work on this issue, and if so then please assign this issue to me.

It's okay!

**Comment by cw123** [comment]
@Nageshbansal  你好, 这个任务现在进展如何啦？Developer Activities 将于本周结束。  Hello, how is this task going? Developer Activities will end this week.

**Comment by Nageshbansal** [comment]
Hey. I'm working on it, actually, till Saturday I was busy with my university semester exams.

**Comment by Nageshbansal** [comment]
I'm working on it now, and by end of this week i.e 3 Dec, I will make a PR.

**Comment by Nageshbansal** [comment]
While building the package, in `thirdparties/etcdclient` : on [L25](https://github.com/opencurve/curve/blob/137b54ea402a5bb999c0274dabafee24331f07f5/thirdparties/etcdclient/Makefile#L25), curve is just downloading the `go1.12.8` right? if yes then can I do it manually as from downloading the given URL , it's taking much time.

**Comment by ilixiaocui** [comment]
> While building the package, in `thirdparties/etcdclient` : on [L25](https://github.com/opencurve/curve/blob/137b54ea402a5bb999c0274dabafee24331f07f5/thirdparties/etcdclient/Makefile#L25), curve is just downloading the `go1.12.8` right? if yes then can I do it manually as from downloading the given URL , it's taking much time.

Doing it manually is no problem.

**Comment by Nageshbansal** [comment]
Hey, While building the `tar` package using `mk-tar. sh` I'm facing the following issues:
 * in the `thirdparties/etcdclient/Makefile`, on the [L30](https://github.com/opencurve/curve/blob/137b54ea402a5bb999c0274dabafee24331f07f5/thirdparties/etcdclient/Makefile#L30) , curve is using [gitee.com/mirrors/etcd](https://gitee.com/mirrors/etcd), which takes a much time for downloading ( around 20.1 Kb/s) so i replaced it with [etcd-io/etcd](https://github.com/etcd-io/etcd).
 * the build fails and throws the error : 
 ```
 external/aws/aws-cpp-sdk-core/include/aws/core/Core_EXPORTS.h:8:32: fatal error: aws/core/SDKConfig.h: No such file or directory
 #include <aws/core/SDKConfig.h>
```

**Comment by ilixiaocui** [comment]
> Hey, While building the `tar` package using `mk-tar. sh` I'm facing the following issues:
> 
> * in the `thirdparties/etcdclient/Makefile`, on the [L30](https://github.com/opencurve/curve/blob/137b54ea402a5bb999c0274dabafee24331f07f5/thirdparties/etcdclient/Makefile#L30) , curve is using [gitee.com/mirrors/etcd](https://gitee.com/mirrors/etcd), which takes a much time for downloading ( around 20.1 Kb/s) so i replaced it with [etcd-io/etcd](https://github.com/etcd-io/etcd).
> * the build fails and throws the error :
> 
> ```
> external/aws/aws-cpp-sdk-core/include/aws/core/Core_EXPORTS.h:8:32: fatal error: aws/core/SDKConfig.h: No such file or directory
> #include <aws/core/SDKConfig.h>
> ```

1.[etcd-io/etcd]( https://github.com/etcd-io/etcd) is not as fast as [gitee/etcd](https://gitee.com/mirrors/etcd) in most cases. One suggestion is to keep both and try the other when one times out

2. The compilation of `aws `requires` cd thirdparties/aws && make build`, this part can be added to the compilation script

**Comment by ilixiaocui** [comment]
cc @Nageshbansal Is there any question at that time?

**Comment by wuhongsong** [comment]
@Nageshbansal  keep on? and need any help？

**Comment by ilixiaocui** [comment]
@Nageshbansal Since you haven't responded for a long time, cancel assgin and leave the opportunity to others.

**Comment by ilixiaocui** [comment]
关于如何着手这个issue：
1. 现在是可以直接看这个issue, 这个issue不需要专业的分布式存储的知识

2. 对这个issue的解读：
- mk-tar.sh 和 mk-deb.sh 这个脚本都可以看到，前一部分是项目的编译指令，后一部分是打包为tar包和deb包的指令
- 对于编译部分两个脚本是相同的，所以一旦有编译命令的改动，就要同时改动两个脚本，容易遗漏
- 期望完成后的脚本比如mk-package.sh 可以通过指定参数打包：mk-package.sh deb     mk-package.sh tar

3. 建议
- 可以先搭建curve的编译环境，可以参考：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md
- 在curve编译环境中执行一下mk-tar.sh 和 mk-deb.sh两个脚本，看是否能够执行成功
- 如果可以正常执行，就可以合并两个脚本了，新脚本同样也是两部分：先是编译（大部分应该直接拷贝原有脚本）；然后是根据输入参数区分是打哪个包（同样也是把deb和tar中对应的部分拷贝）
- 如果有一些问题可以在微信群交流，也可以自己尝试解决。比如先确定脚本挂在了哪一步，假设是bazel挂了，假设是打包步骤挂了，可以根据问题去了解相应的知识点

**Comment by charlie0129** [comment]
Since the script contains a lot of `if` and `exit` that checks the exit status of the previous command, and `make` can automatically do this for us, I think we can convert the script into `make` script to reduce these bolilerplates.

https://github.com/opencurve/curve/blob/88b4b0b9998cc28eff04fd889471ba08562d6c1f/mk-deb.sh#L197-L202

**Comment by ilixiaocui** [comment]
> Since the script contains a lot of `if` and `exit` that checks the exit status of the previous command, and `make` can automatically do this for us, I think we can convert the script into `make` script to reduce these bolilerplates.
> 
> https://github.com/opencurve/curve/blob/88b4b0b9998cc28eff04fd889471ba08562d6c1f/mk-deb.sh#L197-L202

Good idea.
