### ISSUE TITLE
[curve tool]: implement seginfo command

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2029]
**Describe the feature you'd like:**

we'd like to support seginfo command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

seginfo is one of the commands to list the segments info of the volume.

- The implementation of the old tool is here：

https://github.com/opencurve/curve/blob/master/src/tools/namespace_tool.cpp#L277

- The old command input and out put:

```
seginfo : list the segments info of the file

$ curve_ops_tool seginfo list --example
Example:
curve_ops_tool seginfo -mdsAddr=127.0.0.1:6666 -fileName=/test

$ curve_ops_tool seginfo -fileName=/test
logicalPoolID: 3
startOffset: 0
segmentSize: 1073741824
chunkSize: 16777216
chunks:
chunkID: 21227073, copysetID: 969
chunkID: 21227074, copysetID: 970
chunkID: 21227075, copysetID: 971
chunkID: 21227076, copysetID: 972
chunkID: 21227077, copysetID: 973
chunkID: 21227078, copysetID: 974
.......

logicalPoolID: 2
startOffset: 1073741824
segmentSize: 1073741824
chunkSize: 16777216
chunks:
chunkID: 21227201, copysetID: 5518
chunkID: 21227202, copysetID: 5519
chunkID: 21227203, copysetID: 5520
chunkID: 21227204, copysetID: 5521
chunkID: 21227205, copysetID: 5522
.......
```

- The new command we want:

```
curve bs seginfo /curvebs-file-name
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Comment by cw123** [comment]
The old output format is inconvenient to read. Need to improve the presentation of results

**Comment by wuhongsong** [comment]
you are welcome to continue the work if you are free @wudong5

**Comment by ilixiaocui** [comment]
cc @wudong5 Since you haven't responded for a long time, this issue is reopened to others who is interested.

**Comment by caoxianfei1** [comment]
@Cyber-SiKu take it?
