### ISSUE TITLE
[curve tool]: implement delete volume command 

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2030]
**Describe the feature you'd like:**

we'd like to support delete volume command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

delete is one of the commands to delete one volume.

- The implementation of the old tool is here：

https://github.com/opencurve/curve/blob/master/src/tools/namespace_tool_core.cpp#L58

- The old command:

```
delete : delete the file, to force delete, should specify the --forcedelete=true

$ curve_ops_tool delete --example
Example:
curve_ops_tool delete -mdsAddr=127.0.0.1:6666 -fileName=/test -userName=test -password=123 -forcedelete=true

```

- The new command we want:

```
curve bs delete --filename /curvebs-file-name --username username [--password password] [--forcedelete true]

If command sucess, print success.
If command failed, print failed, and the fail reason.
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Comment by shentupenghui** [comment]
i would like solve this
