### ISSUE TITLE
[curve tool]: implement create volume command

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2031]
**Describe the feature you'd like:**

we'd like to support create command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

create is one of the commands to create one volume.

- The implementation of the old tool is here：

https://github.com/opencurve/curve/blob/master/src/tools/namespace_tool_core.cpp#L63

- The old command input and out put:

```
create : create file, file length unit is GB

$ curve_ops_tool create --example
Example:
curve_ops_tool create -mdsAddr=127.0.0.1:6666 -fileName=/test -userName=test -password=123 -fileLength=20‬

```

- The new command we want:

```
curve bs create --filename /curvebs-file-name --username username --filelength the_length_num_of_volume [--password password] 

If command sucess, print success.
If command failed, print failed, and the fail reason.
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Comment by ilixiaocui** [comment]
Please note that the code submission deadline for this developer activity is December 3rd :)
 @wangyanghack

**Comment by wangyanghack** [comment]
ok. I'm very sorry. I'm developing.

**Comment by wuhongsong** [comment]
@wangyanghack    Are you having some trouble? If so, please let us know so that we can communicate together

**Comment by wangyanghack** [comment]
![image](https://user-images.githubusercontent.com/18416672/208300928-cb68c139-ec16-4781-8ee0-3e1bf7242255.png)
yes, I am having some trouble. I don't know how to get more error information from the output.

**Comment by wuhongsong** [comment]
> `[root@node2 ~]# docker exec -it 40c bash root@40c63b12304a:/# ./curve2 bs create -h Usage: curve bs create [flags]
> 
> create certain file in curvebs
> 
> Flags: -c, --conf string config file (default is $HOME/.curve/curve.yaml or /etc/curve/curve.yaml) --filelength int curve bs file length (default 20) --filename string the full path of file[required] --filetype string directory,pagefile,appendfile,appendecfile,snapshot_pagefile -f, --format string output format (json|plain) (default "plain") -h, --help print help --mdsaddr string mds address, should be like 127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702 --password string user password --rpcretrytimes int32 rpc retry times (default 1) --rpctimeout duration rpc timeout (default 10s) --showerror display all errors in command --user string username[required] --verbose show some log
> 
> Examples: curve bs create --filename /curvebs-file-name --user username --filelength the_length_num_of_volume [--password password] root@40c63b12304a:/# ./curve1 bs create --filename /curvebs-file-name --user root --password root_password --filetype pagefile --verbose --showerror 2022/12/18 21:26:05.808029 base.go:296: 127.0.0.1:6702: start to dial 2022/12/18 21:26:05.808167 base.go:296: 127.0.0.1:6700: start to dial 2022/12/18 21:26:05.808821 base.go:296: 127.0.0.1:6701: start to dial 2022/12/18 21:26:05.810073 base.go:311: 127.0.0.1:6700: start to rpc [CreateFile] 2022/12/18 21:26:05.811767 base.go:328: 127.0.0.1:6700: get rpc[CreateFile] request successfully {Code:90040 Message:create file fail. the error is %s} root@40c63b12304a:/#`
> 
> yes, I am having some trouble. I don't know how to get more error information from the output.

@Cyber-SiKu Can you take a look at this？

**Comment by Cyber-SiKu** [comment]
Please submit your code and let me have a look.

**Comment by wuhongsong** [comment]
@wangyanghack keep on? Can you tell  more about your troubles?

**Comment by wangyanghack** [comment]
> @wangyanghack keep on? Can you tell more about your troubles?

I have submitted my code. But I don't know how to get more details from log.

**Comment by Cyber-SiKu** [comment]
@wangyanghack

**Comment by wangyanghack** [comment]
> 

thanks a lot! I will try it tonight.

**Comment by Cyber-SiKu** [comment]
@wangyanghack Please update the code

**Comment by Cyber-SiKu** [comment]
@wangyanghack Are you still going on?

**Comment by Cyber-SiKu** [comment]
@wangyanghack If you have any questions, you can contact us in time.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Cyber-SiKu** [comment]
https://github.com/opencurve/curve/pull/2404

**Comment by Cyber-SiKu** [comment]
https://github.com/opencurve/curve/pull/2404
