### ISSUE TITLE
[curve tool]: implement clean-recyle command 

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2032]
**Describe the feature you'd like:**

we'd like to support clean-recycle command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

clean-recycle is one of the commands to delete all volume under recycle of curveBS.

The curveBS has a recycle, every volume deleted will mv to the recycle. The clean-recycle command will delete all the volume under the recycle.

The path of the recycle in the curveBS is /RecycleBin.

- The implementation of the old tool is here：

https://github.com/opencurve/curve/blob/master/src/tools/namespace_tool_core.cpp#L134

- The old command:

```
clean-recycle : clean the RecycleBin

$ curve_ops_tool clean-recycle --example
Example:
curve_ops_tool clean-recycle -mdsAddr=127.0.0.1:6666 [-fileName=/cinder]
If -fileName is specified, delete the files in recyclebin that the original directory is fileName

```

- The new command we want:

```
curve bs clean-recycle

If command sucess, print success.
If command failed, print failed, and the fail reason.
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Comment by ilixiaocui** [comment]
Please note that the code submission deadline for this developer activity is December 3rd :)
@Joey777210

**Comment by wuhongsong** [comment]
you are welcome to continue the work if you are free   @Joey777210

**Comment by ilixiaocui** [comment]
cc@Joey777210 Since you haven't responded for a long time, this issue is reopened to others who is interested.

**Comment by wuhongsong** [comment]
@cw123

**Comment by lng2020** [comment]
I would like to contribute to this issue, please assign it to me. @ilixiaocui

**Comment by ilixiaocui** [comment]
> I would like to contribute to this issue, please assign it to me. @ilixiaocui

Welcome!

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by lng2020** [comment]
complete a pr[https://github.com/opencurve/curve/pull/2401] for it.
