### ISSUE TITLE
[compile] update the brpc vesion

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2034]
**Describe the feature you'd like:**

curve uses brpc as the data transmission component, the version of brpc we are currently using is too old. Hope to be able to upgrade brpc to a relatively new stable version.

The external dependencies used by curve are documented in https://github.com/opencurve/curve/blob/master/WORKSPACE. The currently used version of brpc is:

curve使用brpc作为数据传输组件，我们当前使用的brpc版本太老了。希望能够把brpc的升级到一个比较新的稳定版本。

curve使用的外部依赖库记录在 https://github.com/opencurve/curve/blob/master/WORKSPACE 这个文件中。其中brpc的当前使用的版本为：

```
git_repository(
    name = "com_github_apache_brpc",
    remote = "https://github.com/apache/incubator-brpc",
    commit = "1b9e00641cbec1c8803da6a1f7f555398c954cb0",
    patches = ["//:thirdparties/brpc/brpc.patch"],
    patch_args = ["-p1"],
)
```

Replace the old commit with the new version of the commit, and then `make build` compiles the entire curve project, some compilation errors may occur. You need to find a way to solve these compilation problems and complete the version replacement of braft.

We also made some modifications to brpc, and the patch is placed at this address: thirdparties/brpc/brpc.patch. It is also necessary to confirm whether the new version of brpc solves these problems, and whether this patch needs to be marked in the new brpc.

使用新版本的commit替换这个旧的commit，然后`make build`编译整个curve工程。可能会出现一些编译错误，你需要想办法解决这些编译问题，完成brpc的版本替换。

我们对brpc还做了一些修改，patch放在这个地址 ：thirdparties/brpc/brpc.patch。还需要确认新版本的brpc是否解决这些问题，是否需要在新的brpc中打上这个patch。

**Teachability, Documentation, Adoption, Migration Strategy:**

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md.

**Comment by fansehep** [comment]
i will work on this.

**Comment by wuhongsong** [comment]
@fansehep  take it?

**Comment by fansehep** [comment]
> @fansehep take it?

Sorry, I am currently interviewing. Maybe wait a long time.

**Comment by caoxianfei1** [comment]
@fansehep How is the recent progress？

**Comment by fansehep** [comment]
> @fansehep How is the recent progress？

I'm so bad for this. Interviewing is not going well. I will fix it as soon as possible after my interview.

**Comment by legionxiong** [comment]
> > @fansehep How is the recent progress？
> 
> I'm so bad for this. Interviewing is not going well. I will fix it as soon as possible after my interview.

bRPC 1.4.0 has been released, maybe we could update brpc to the latest version 1.4.0 with bazel third-party supported.

**Comment by fansehep** [comment]
> bRPC 1.4.0 has been released, maybe we could update brpc to the latest version 1.4.0 with bazel third-party supported.

I tried to migrate the old patch to the new bRPC. But there are some problems, which I can't troubleshoot at the moment, and I need someone to help me.

**Comment by legionxiong** [comment]
> > bRPC 1.4.0 has been released, maybe we could update brpc to the latest version 1.4.0 with bazel third-party supported.
> 
> I tried to migrate the old patch to the new bRPC. But there are some problems, which I can't troubleshoot at the moment, and I need someone to help me.

Will you start again with brpc v1.4.0?

**Comment by fansehep** [comment]
> Will you start again with brpc v1.4.0?

Maybe. If someone can help me to solve the patch. I'am happy to retrty it.

**Comment by Cyber-SiKu** [comment]
@fansehep Are you still going on?

**Comment by caoxianfei1** [comment]
> > Will you start again with brpc v1.4.0?
> 
> Maybe. If someone can help me to solve the curve_brpc.patch, I'am happy to retry it.

so what's the problem with the path? you can present it here and we can exchange
