### ISSUE TITLE
[curve/tools-v2]: add list chunkserver

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2036]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `list chunkserver` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/5e49aed29c6cbf75f046373ecfd17ec0d3fbe0c5/src/tools/status_tool.cpp#L228-L333
- The old command input and out put:
```
  curve_ops_tool chunkserver-list 
  output:
curve chunkserver list: 
chunkServerID = 54, diskType = nvme, hostIP = ***.***.***.***, port = 8217, rwStatus = READWRITE, diskState = DISKNORMAL, onlineState = ONLINE, copysetNum = 100, mountPoint = local:///curvebs/chunkserver/data, diskCapacity = 732 GB, diskUsed = 623 GB, unhealthyCopysetRatio = 0%, externalIP = ***.***.***.***
...
chunkServerID = 5, diskType = nvme, hostIP = ***.***.***.***, port = 8209, rwStatus = READWRITE, diskState = DISKNORMAL, onlineState = ONLINE, copysetNum = 100, mountPoint = local:///curvebs/chunkserver/data, diskCapacity = 732 GB, diskUsed = 623 GB, unhealthyCopysetRatio = 0%, externalIP = ***.***.***.***
total: 54, online: 54, unstable: 0, offline: 0
pendding: 0, penddingCopyset: 0, retired:0
```

Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand chunkserver to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Please note that the code submission deadline for this developer activity is December 3rd :)
 @leonatone

**Comment by wuhongsong** [comment]
@leonatone  you are welcome to continue the work  if you are free,

**Comment by ilixiaocui** [comment]
cc @leonatone Since you haven't responded for a long time, this issue is reopened to others who is interested.

**Comment by wuhongsong** [comment]
@Cyber-SiKu

**Comment by Sindweller** [comment]
please assign this to me😄

**Comment by Cyber-SiKu** [comment]
@Sindweller Are you still going on?

**Comment by Sindweller** [comment]
> @Sindweller Are you still going on?

Sorry for the delay, I would done it this week.
