### ISSUE TITLE
[curve/client]: the warm-up task manager

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2039]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Create a warmp task manager, through which the manager can support querying the warmup progress and canceling the warmp task in the future.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
# curve 预热进度查询
要获取curve的预热流程，需要完成对预热流程的分析，通过预热的流程完成对预热进度查询的设计。
## curve warmup 流程分析
单个文件的预热与解析预热列表文件后预热列表文件中的单文件流程一样，因此在这里仅分析预热列表文件的预热流程
### 列表文件预热流程
1. 工具将预热的方式和预热的目录以设置xattr的形式提供给client，client调用PutWarmTask 来预热预热列表文件；
```c++
switch (curvefs::client::common::GetWarmupType(type)) {
    case curvefs::client::common::WarmupType::kWarmupTypeList:
        g_ClientInstance->PutWarmTask(path);
        break;
    ...
}
```
2. PutWarmTask 将预热列表文件加入预热任务队列，并唤醒扫描队列（warmUpRun）；
```c++
std::unique_lock<std::mutex> lck(warmUpTaskMtx_);
warmUpTasks_.push_back(warmUpTask);
WarmUpRun();
```
3. FuseClient::WarmUpTask() 会扫描warmupTask队列，当存在warmUpTask时，会从中取出一个warmUpTask，并获取warmUpTask的inodeid、len，并保存到warmUpFile队列中；
```c++
while (hasWarmTask()) {
    std::string warmUpTask;
    GetwarmTask(&warmUpTask);
    ...
    Dentry dentry;
    CURVEFS_ERROR ret = dentryManager_->GetDentry(
      fsInfo_->rootinodeid(), pToken, &dentry);
   ...
    fuse_ino_t  ino = dentry.inodeid();
    std::shared_ptr<InodeWrapper> inodeWrapper;
    ret = inodeManager_->GetInode(ino, inodeWrapper);
   ...
    uint64_t len = inodeWrapper->GetLength();
    WarmUpFileContext_t warmUpFile{ino, len, true};
    SetWarmUpFile(warmUpFile);
}
```
4. FuseS3Client::BackGroundFetch() 后台扫描warmUpFile队列。如果存在预热文件任务，则取出预热列表文件并根据文件内容解析出预热文件列表warmUpFilelist。然后按照预热文件列表依次添加获取文件dentry（FetchDentryEnqueue）队列；
```c++
void FuseS3Client::BackGroundFetch() {
    while (!bgFetchStop_.load(std::memory_order_acquire)) {
        if (hasWarmUpTask()) {  // new warmup task
            WarmUpFileContext_t warmUpFile;
            GetWarmUpFile(&warmUpFile);

            std::vector<std::string> warmUpFilelist;
            GetWarmUpFileList(warmUpFile, warmUpFilelist);
            for (auto filePath : warmUpFilelist) {
                FetchDentryEnqueue(filePath);
            }
        }
        {   // file need warmup
            std::list<fuse_ino_t> readAheadFiles;
            readAheadFiles.swap(GetReadAheadFiles());
            for (auto iter : readAheadFiles) {
                fetchDataEnqueue(iter);
            }
        }
        usleep(WARMUP_CHECKINTERVAL_US);
    }
    return;
}
```
5. FetchDentryEnqueue 在线程池中添加LookPath线程（根据文件路径解析出inodeid）；
6. LookPath 根据文件路径按照文件的类型以以下的方式获取文件的dentry；
    1. 根（/）：FetchChildDentryEnqueue
    2. 根目录的子目录 FetchDentry
    3. 其他 FetchDentry
```c++
if (splitPath.size() == 1 && isRoot) {
    FetchChildDentryEnqueue(fsInfo_->rootinodeid());
    return;
} else if (splitPath.size() == 1) {
    this->FetchDentry(fsInfo_->rootinodeid(), splitPath[0]);
    return;
} else if (splitPath.size() > 1) {  // travel path
    splitPath.pop_back();
    fuse_ino_t ino = fsInfo_->rootinodeid();
    for (auto iter : splitPath) {
        Dentry dentry;
        std::string pathName = iter;
        CURVEFS_ERROR ret = dentryManager_->GetDentry(
          ino, pathName, &dentry);
        if (ret != CURVEFS_ERROR::OK) {
            ...
            return;
        }
        ino = dentry.inodeid();
    }
    this->FetchDentry(ino, lastName);
    return;
}
```
7. FetchDentry 根据上一级路径的inodeid 和 文件名 获取文件的dentry，然后根据文件的文件的类型执行以下操作：
    1. 目录 执行FetchChildDentryEnqueue
    2. s3文件 将inodeid 添加到 readAheadFiles_
```c++
CURVEFS_ERROR ret = dentryManager_->GetDentry(ino, file, &dentry);
...
if (FsFileType::TYPE_S3 == dentry.type()) {
    std::unique_lock<std::mutex> lck(fetchMtx_);
    readAheadFiles_.push_front(dentry.inodeid());
    return;
} else if (FsFileType::TYPE_DIRECTORY == dentry.type()) {
    FetchChildDentryEnqueue(dentry.inodeid());
    return;

}
```
8. FetchChildDentryEnqueue 添加扫描目录下dentry的子任务（FetchChildDentry）；
9. FetchChildDentry 获取当前dentry下的所有dentry，然后根据类型：
    1. 目录 执行FetchChildDentryEnqueue
    2. s3 将inodeid 添加到 readAheadFiles_
```c++
CURVEFS_ERROR ret = dentryManager_->ListDentry(
      ino, &dentryList, limit);
...
for (auto iter : dentryList) {
    if (FsFileType::TYPE_S3 == iter.type()) {
        std::unique_lock<std::mutex> lck(fetchMtx_);
        readAheadFiles_.push_front(iter.inodeid());
    } else if (FsFileType::TYPE_DIRECTORY == iter.type()) {
        FetchChildDentryEnqueue(iter.inodeid());
    } 
    ...
}
```

10. 根据上述流程可以看到：整个预热的流程就是将要预热文件的inode加入 readAheadFiles_  中，而 readAheadFiles_ 会在step 4.中的下述代码中将inode转化为数据预热队列（fetchDataEnqueue）。
 ```c++
std::list<fuse_ino_t> readAheadFiles;
readAheadFiles.swap(GetReadAheadFiles());
for (auto iter : readAheadFiles) {
        fetchDataEnqueue(iter);
}    
 ```
11. fetchDataEnqueue 创建遍历文件inode所有s3InfoMap (travelChunks) 的task并加入线程池；
```c++
auto task = [this, ino]() {
        std::shared_ptr<InodeWrapper> inodeWrapper;
        CURVEFS_ERROR ret = inodeManager_->GetInode(ino, inodeWrapper);
        ...
        google::protobuf::Map<uint64_t, S3ChunkInfoList> *s3ChunkInfoMap
          = nullptr;
        {
            ::curve::common::UniqueLock lgGuard = inodeWrapper->GetUniqueLock();
            s3ChunkInfoMap = inodeWrapper->GetChunkInfoMap();
        }
        if (nullptr == s3ChunkInfoMap ||
          s3ChunkInfoMap->empty()) {
            return;
        }
        travelChunks(ino, s3ChunkInfoMap);
    };
GetTaskFetchPool().Enqueue(task);
```
12. travelChunks使用travelChunk遍历s3ChunkInfoMap获取要预热的s3对象列表(prefetchObjs)，然后使用WarmUpAllObjs预热这些对象。
```c++
for (auto &iter : *s3ChunkInfoMap) {
    travelChunk(ino, iter.second, &prefetchObjs);
}
WarmUpAllObjs(prefetchObjs);
```

13. travelChunk 解析 chunkInfo 获取所有的s3对象名称及其长度。
14. WarmUpAllObjs添加下载任务，并过滤掉已经下载的s3对象。
```c++
GetObjectAsyncCallBack cb =
    [&](const S3Adapter *adapter,
        const std::shared_ptr<GetObjectAsyncContext> &context) {
        if (context->retCode == 0) {
            int ret = s3Adaptor_->GetDiskCacheManager()->WriteReadDirect(
              context->key, context->buf, context->len);
           ...
            if (pendingReq.fetch_sub(1, std::memory_order_seq_cst) == 1) {
                cond.Signal();
            }
            delete []context->buf;
            return;
        }
        s3Adaptor_->GetS3Client()->DownloadAsync(context);
};
    
for (auto iter : prefetchObjs) {
    std::string name = iter.first;
    uint64_t readLen = iter.second;
    if (s3Adaptor_->GetDiskCacheManager()->IsCached(name)) {
        pendingReq.fetch_sub(1);
        continue;
    }
    char *cacheS3 = new char[readLen];
    memset(cacheS3, 0, readLen);
    auto context = std::make_shared<GetObjectAsyncContext>();
...
    s3Adaptor_->GetS3Client()->DownloadAsync(context);
}
```

**Comment by Cyber-SiKu** [comment]
CurveFS warmup 方案
流程
增加
获取指定预热路径列表文件（或指定单文件/目录），该文件必须在 curvefs 中。
工具对路径文件中的内容进行处理：将需要预热用户路径转化为curvefs路径。
首先获取挂载的所有 FilesystemType:fuse 的目录（后续优化：设置FilesystemType为fuse.curvefs，通过该属性判断挂载点fs类型是否）
{
    MountID:3179
    ParentID:3158
    StDev:0:172
    Root:/
    MountPoint:/cfs
    MountOptions:rw,nosuid,nodev,relatime
    OptionalFields:[]
    FilesystemType:fuse
    MountSource:/dev/fuse
    SuperOptions:rw,user_id=0,group_id=0,default_permissions,allow_other
}
根据第一个预热文件的路径确定挂载的路径和curvefs的路径，进行替换并更新列表文件。
设置预热列表文件的属性 curvefs.warmup.op 为 add\n(single/list)\n{path}，在 FuseOpSetAttr(curvefs/src/client/curve_fuse_op.cpp) 中激活预热，其中single/list是由单目录/文件还是列表文件决定，path为列表文件在curvefs中的路径。
删除
主要流程与增加相同，在设置列表文件属性时设置curvefs.warmup.op 为 del ，然后client端将通知预热线程，取消列表文件中路径的预热，已经预热的不处理。
查询
主要流程与增加相同，在设置列表文件属性时设置curvefs.warmup.op 为 search，然后 client 端将当前预热的进度设置为文件的属性（如curvefs.warmup.total curvefs.warmup.left curvefs.warmup.time等）。
优点
不会限制用户对特殊文件的使用。
预热路径转化更为合理，后续的工作优化可以免除错误的预热其他fs。
支持子目录挂载
缺点
预热列表文件必须保存在curvefs中。
会修改列表文件导致列表文件不可复用。
使用示例
对预热的操作考虑支持增加、删除和查询：
# 预热列表
curve fs warmup add --filelist /warmup/0809.list
curve fs warmup del --filelist /warmup/0809.list
curve fs warmup query --filelist /warmup/0809.list
# 预热单目录/文件
curve fs warmup add /warmup
curve fs warmup del /warmup
curve fs warmup query /warmup
预热列表文件
物理机挂载
用户将curvefs的”/“目录挂载到本机的 “/mnt/curvefs/”下，如果用户需要预热curvefs的“/”下的“/B /C /A/D”，用户需要将列表文件保存为“/mnt/curvefs/warmup/0809.list”，文件的内容为：
/mnt/curvefs/B
/mnt/curvefs/C
/mnt/curvefs/A/D
预热命令为：
curve fs warmup add --filelist /mnt/curvefs/warmup/0809.list 
工具会将文件内容转换为：
/B
/C
/A/D
Docker bind mountpoint
用户将curvefs的”/“目录挂载到本机的 “/mnt/curvefs/”下，然后在curvefs下拥有目录“/A/D /A/E”，使用bind mounpoint的方式将目录“/A” 挂载到docker镜像中的”/share“下：
docker run -v /mnt/curvefs/A:/share debian
docker镜像中的用户想要预热目录“/share/D /share/E”，需要将预热的列表文件保存为：“/share/warmup/0809.list”，文件内容为：
/share/D
/share/E
预热命令为：
curve fs warmup add --filelist /share/warmup/0809.list
工具会将文件内容转化为：
/A/D
/A/E

**Comment by Ziy1-Tan** [comment]
look like a great features and excellent plan. I'm interested in it but I'll take some time for it. I have some features on juicefs but not so much.

**Comment by CodeFarmerPK** [comment]
Maybe this issue is a little challenging for me and I want to try it

**Comment by Ziy1-Tan** [comment]
> any one want do it?

I wanna do it

**Comment by ilixiaocui** [comment]
cc @CodeFarmerPK Is this issue still being followed up? Did you encounter any difficulties?

**Comment by CodeFarmerPK** [comment]
Before,I have a little trouble in life and work because of covid, until this week I have time in this issue.
I'm so sorry about it.

**Comment by ilixiaocui** [comment]
> Before,I have a little trouble in life and work because of covid, until this week I have time in this issue. I'm so sorry about it.

Welcome to continue to follow up on this issue！

**Comment by CodeFarmerPK** [comment]
> > Before,I have a little trouble in life and work because of covid, until this week I have time in this issue. I'm so sorry about it.
> 
> Welcome to continue to follow up on this issue！

I'll try my best to deal with it.
