### ISSUE TITLE
[curvefs] Clean up resources after failing to create fs

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2043]
curve文件系统在CreateFs时，会创建一些资源，包括创建一个fsinfo，创建partition，创建root inode等。当后面的步骤失败了，需要清理掉前面步骤创建的资源。当前的代码实现中，有一些资源在执行失败的时候没有删除，希望这些资源能够被清理。

When the curve file system creates Fs, it will create some resources, including creating a fsinfo, creating a partition, creating a root inode, etc. When the later steps fail, the resources created in the previous steps need to be cleaned up. In the current code implementation, some resources are not deleted when the execution fails, and it is hoped that these resources can be cleaned up.

CreateFs的代码在：

the code is here:

https://github.com/opencurve/curve/blob/master/curvefs/src/mds/fs_manager.cpp

```
FSStatusCode FsManager::CreateFs(const ::curvefs::mds::CreateFsRequest* request,
                                 FsInfo* fsInfo) {
    ......
```

**Comment by wpy-321** [comment]
Hello, I want to participate

**Comment by wuhongsong** [comment]
@wpy-321

**Comment by Ziy1-Tan** [comment]
Some rough ideas:
- **Clean the partition:**
	- Define the `TopologyManager::DeletePartition` by passing the `partitionId` to wrap `TopologyManager::DeletePartition`  in `CreateFs`
- **Clean the fs**
	- Calling the `FsStorage::Delete` by passing the `fsName`
- **Clean the root inode**
	- I cound not find function to delete root inode in `MetaserverClient`, what should I do next?
	- `MetaserverClient::DeleteInode` need `uint64_t inodeId`, Is the root inode id 1?

**Comment by ilixiaocui** [comment]
> Hello, I want to participate

cc @wpy-321 Due to no reply for a long time, cancel the assignment first. Welcome to continue to join if you have time！

**Comment by cw123** [comment]
> Some rough ideas:
> 
> * **Clean the partition:**
>   
>   * Define the `TopologyManager::DeletePartition` by passing the `partitionId` to wrap `TopologyManager::DeletePartition`  in `CreateFs`
> * **Clean the fs**
>   
>   * Calling the `FsStorage::Delete` by passing the `fsName`
> * **Clean the root inode**
>   
>   * I cound not find function to delete root inode in `MetaserverClient`, what should I do next?
>   * `MetaserverClient::DeleteInode` need `uint64_t inodeId`, Is the root inode id 1?

you can use MetaserverClient::DeleteInode to delete root inode.

root inode is 1, but you should not use 1 directly. You can use  `uint64_t FsManager::GetRootId();`  to get root inode id

**Comment by Ziy1-Tan** [comment]
> > Some rough ideas:
> > 
> > * **Clean the partition:**
> >   
> >   * Define the `TopologyManager::DeletePartition` by passing the `partitionId` to wrap `TopologyManager::DeletePartition`  in `CreateFs`
> > * **Clean the fs**
> >   
> >   * Calling the `FsStorage::Delete` by passing the `fsName`
> > * **Clean the root inode**
> >   
> >   * I cound not find function to delete root inode in `MetaserverClient`, what should I do next?
> >   * `MetaserverClient::DeleteInode` need `uint64_t inodeId`, Is the root inode id 1?
> 
> you can use MetaserverClient::DeleteInode to delete root inode.
> 
> root inode is 1, but you should not use 1 directly. You can use `uint64_t FsManager::GetRootId();` to get root inode id

thx a lot! I will continue to it, assign me plz :).

**Comment by wuhongsong** [comment]
@Ziy1-Tan  just do it
