### ISSUE TITLE
curvefs/client: add qos for curve-fuse

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2048]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

add qos for curve-fuse, then  we can limits the bandwidth and  iops

**Describe the solution you'd like (描述你期望的解决方法)**

what are we going to do with this task ?

The qos module already exists in the curve project, and we need to apply it to curve-fuse

**Comment by YLShiJustFly** [comment]
OK, i'd like to try it.

**Comment by wuhongsong** [comment]
> OK, i'd like to try it.

enjoy it

**Comment by wuhongsong** [comment]
@YLShiJustFly
