### ISSUE TITLE
Quickmount volumes fail

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2050]
**Describe the bug (描述bug)**

Quickmount volumes fail

**To Reproduce (复现方法)**
nbs@pubbeta2-curve3:~$ sudo docker logs c732780cec72
create fs success.
E 2022-11-09T11:04:17.342435+0800 424360 fuse_client.cpp:177] MountFs failed, FSStatusCode = 32, FSStatusCode_Name = MOUNT_POINT_CONFLICT, fsName = test2, mountPoint = hostname: "pubbeta2-curve3.dg.163.org" port: 9000 path: "/curvefs/client/mnt/home/nbs/failover/test2" cto: false
F 2022-11-09T11:04:17.506296+0800 424360 curve_fuse_op.cpp:203] FuseOpInit failed, ret = -14[mount failed]
*** Check failure stack trace: ***
Begin to mount fs test2 to /curvefs/client/mnt/home/nbs/failover/test2
fuse start loop, singlethread = 0, max_idle_threads = 10
*** Aborted at 1667963057 (unix time) try "date -d @1667963057" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x67946) received by PID 424262 (TID 0x7f4a3f9ff700) from PID 424262; stack trace: ***
    @     0x7f4a7b2330e0 (unknown)
    @     0x7f4a798eafff gsignal
    @     0x7f4a798ec42a abort
    @     0x55c2c0df5bda google::FlushAndAbort()
    @     0x55c2c0df2e2c google::LogMessage::Fail()
    @     0x55c2c0df2d75 google::LogMessage::SendToLog()
    @     0x55c2c0df259e google::LogMessage::Flush()
    @     0x55c2c0df556e google::LogMessageFatal::~LogMessageFatal()
    @     0x55c2c01b4f24 FuseOpInit
    @     0x7f4a7b8dcf2d do_init
    @     0x7f4a7b8de5d1 fuse_session_process_buf_int
    @     0x7f4a7b8da061 fuse_do_work
    @     0x7f4a7b2294a4 start_thread
    @     0x7f4a799a0d0f clone
    @                0x0 (unknown)
/client.sh: line 26: 424262 Aborted                 (core dumped) $g_entrypoint "$@"
nbs@pubbeta2-curve3:~$ 
nbs@pubbeta2-curve3:~$ /home/nbs/.curveadm/bin/curveadm umount /home/nbs/failover/test2 && /home/nbs/.curveadm/bin/curveadm mount test2 /home/nbs/failover/test2 -c client-test2.yaml

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@Cyber-SiKu
