### ISSUE TITLE
Support helm deploy for CurveFS

### ISSUE THREAD

**Issue by cmssliangxin** [opencurve/curve#2052]
**Describe the task you choose (描述你选择的任务)**
基于helm发送部署curve服务端应用程序
**Describe alternatives you've considered (optional) (描述你想到的方案(可选))**
参考openebs服务端应用程序部署，根据helm传参env环境变量，自动检测disk设备等，服务器pod管理方式通过k8s中的demoset来进行管理
**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Please note that the code submission deadline for this developer activity is December 3rd :)
@cmssliangxin

**Comment by wuhongsong** [comment]
@cmssliangxin   feel free to continue this

**Comment by caoxianfei1** [comment]
@cmssliangxin Work in progress? Feel free to contact us if you have any confusion.
