### ISSUE TITLE
build can be faster

### ISSUE THREAD

**Issue by Tangruilin** [opencurve/curve#2060]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Every time to do `make build dep=1`, it will download aws-core and go1.12, which is a waster of time.

**Describe the solution you'd like (描述你期望的解决方法)**
Before download these, we can check if the tar and directory already exist. If exist, this step can be skipped.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/23651891/201047489-de2ac072-1cce-4636-9d68-6831bbe46342.png">

**Comment by cw123** [comment]
的确是有这么一个问题，你是否愿意帮忙解决这个问题，如果你能试着帮我们解决，那就再好不过了

**Comment by Tangruilin** [comment]
@cw123 可以的，我最近把这个提上去

**Comment by Tangruilin** [comment]
assign to me

**Comment by linshiyx** [comment]
You can run `make build` without `dep=1`

**Comment by Tangruilin** [comment]
> You can run `make build` without `dep=1`

确实可以这样，我之前没找到，这个 issue 应该可以关闭了

**Comment by Tangruilin** [comment]
unassign
