### ISSUE TITLE
The back-end storage connection fails or is full. After the recovery, the fuse does not resume the service, and the upload is stuck.

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2061]
**Describe the bug (描述bug)**
The back-end storage connection fails or is full. After the recovery, the fuse does not resume the service, and the upload is stuck.

**To Reproduce (复现方法)**
1、vdbench write data
2、s3 disk full
3、restore s3 space
4、fuse  upload still fails
![image](https://user-images.githubusercontent.com/67582932/201049443-7f0694ef-6382-4e20-b032-20288a75cf35.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
just like https://github.com/opencurve/curve/issues/2062
