### ISSUE TITLE
Building from debian docker container failed

### ISSUE THREAD

**Issue by tsonglew** [opencurve/curve#2065]
**Describe the bug (描述bug)**

```
ERROR: /curve/src/kvstorageclient/BUILD:19:11: Compiling src/kvstorageclient/etcd_client.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g '-std=c++0x' -MD -MF ... (remaining 95 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from src/kvstorageclient/etcd_client.cpp:26:0:
./src/kvstorageclient/etcd_client.h:26:27: fatal error: libetcdclient.h: No such file or directory
 #include <libetcdclient.h>
```

**To Reproduce (复现方法)**

Follow this doc : https://github.com/opencurve/curve/blob/v2.3.0-rc0/docs/cn/build_and_run.md

```
$ docker run -it opencurvedocker/curve-base:build-debian9 /bin/bash
$ git clone https://github.com/opencurve/curve.git
$ cd curve 
$ git checkout v2.3.0-rc0
$ make build dep=1
```

**Expected behavior (期望行为)**

Build success

**Versions (各种版本)**
No LSB modules are available.

OS: Ubuntu 22.04.1 LTS
Compiler:
branch:v2.3.0-rc0
commit id: 5df72f5e1e2813e4bfa5d73672ea0f6a25630e74

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
`make build dep=1 `does not compile etcd related libraries, you can `cd thirdparties/etcdclient, make clean && make all`

**Comment by tsonglew** [comment]
thanks, but could it be added into the document?

**Comment by ilixiaocui** [comment]
> thanks, but could it be added into the document?

What version did you compile against？

**Comment by tsonglew** [comment]
> > thanks, but could it be added into the document?
> 
> What version did you compile against？

v2.3.0-rc0

**Comment by ilixiaocui** [comment]
`make build dep=1` on the `master` branch already supports compiling etcd by default.

**Comment by ilixiaocui** [comment]
you can `cd thirdparties/rocksdb, make`.

`rocksdb/db.h` is dependent on curvefs, and `dep=1` on the master will automatically install this dependency.
https://github.com/opencurve/curve/blob/ac6e3a3400b17b68eb14244f05a3231d6249379c/curvefs/util/build.sh#L193

**Comment by tsonglew** [comment]
> you can `cd thirdparties/rocksdb, make`.
> 
> `rocksdb/db.h` is dependent on curvefs, and `dep=1` on the master will automatically install this dependency.
> 
> https://github.com/opencurve/curve/blob/ac6e3a3400b17b68eb14244f05a3231d6249379c/curvefs/util/build.sh#L193

Im trying to build curvebs, should I make rocksdb before running `make build dep=1` in curve root directory?

**Comment by ilixiaocui** [comment]
> > you can `cd thirdparties/rocksdb, make`.
> > `rocksdb/db.h` is dependent on curvefs, and `dep=1` on the master will automatically install this dependency.
> > https://github.com/opencurve/curve/blob/ac6e3a3400b17b68eb14244f05a3231d6249379c/curvefs/util/build.sh#L193
> 
> Im trying to build curvebs, should I make rocksdb before running `make build dep=1` in curve root directory?

curvebs does not depend on rocksdb, no need to compile.
