### ISSUE TITLE
Async read need

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2070]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

in function of ReadFromS3, the default is sync read

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by YLShiJustFly** [comment]
Dear Song, Let me have a try.

**Comment by wuhongsong** [comment]
@YLShiJustFly

**Comment by Ziy1-Tan** [comment]
It seem that `ReadFromS3` is not existed, do you mind to update desc?

**Comment by wuhongsong** [comment]
> It seem that `ReadFromS3` is not existed, do you mind to update desc?

yep，`FileCacheManager::ReadKVRequest` has replaced， so maybe we can use asynchronies io in it
