### ISSUE TITLE
update to latest braft version and add io_metric for append_entry.

### ISSUE THREAD

**Issue by tangwz** [opencurve/curve#2071]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

In the lastest version of braft, function `append_entries` add a parameter `io_metric`.We must change class `CurveSegmentLogStorage` too before we update the braft.

**Describe the solution you'd like (描述你期望的解决方法)**

1. update to braft v1.1.2;
2. add `io_metric` to class `CurveSegmentLogStorage`;
3. modify all the function which called `append_entries`;
4. `make build` and pass all the test case.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

reference: https://github.com/opencurve/curve/pull/2063

cc @wu-hanqing @ilixiaocui

**Comment by ilixiaocui** [comment]
👍
