### ISSUE TITLE
[curvefs] add new "getfattr -n curve.dir.recursive_rfbytes" command

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2093]
当curvefs mount的时候，会指定 enableSumInDir，来决定是否需要开启在inode的xattr属性中更新目录下的文件长度的统计信息。这个记录目录下的文件每次更新length的时候更新，可以在统计目录的下所有文件的长度时进行加速。

现在的代码实现中，在多挂载的时候，这个统计值可能不准，希望新增一个getxattr命令，每次查询目录下所有文件的长度统计信息时，不要从属性中读取，而是递归遍历目录下的所有文件。

When the curvefs is mounted, enableSumInDir will be specified to determine whether to enable the statistical information of the file length in the update directory in the xattr attribute of the inode. The files in this record directory are updated every time the length is updated, which can speed up the length of all files in the directory.

In the current code implementation, this statistical value may be inaccurate when there are multiple mounts. I hope to add a getxattr command. When querying the length statistics of all files in the directory, do not read from the attribute, but recursively Traverse all files in the directory.

相关的代码在：

The relevant code is at:

```
curvefs/src/client/xattr_manager.cpp

CURVEFS_ERROR XattrManager::GetXattr(const char* name, std::string *value,
    InodeAttr *attr, bool enableSumInDir) 
```

原来的用法：

The original usage:

getfattr -n curve.dir.rfbytes -d dirname

希望新增一个：

Hope to add one:

getfattr -n curve.dir.recursive_rfbytes -d dirname

**Comment by CodeFarmerPK** [comment]
By reading the codes, i found that the total bytes is added by InodeWrapper. 
Does this issue mean that the total bytes is added by existed files directly?

**Comment by CodeFarmerPK** [comment]
@cw123 
Can you give me some suggestions？

**Comment by ilixiaocui** [comment]
@CodeFarmerPK  Are you still following up on this issue? If yes, you can add storage sig for more convenient contact？Please note the issueid when entering the group.

![image](https://user-images.githubusercontent.com/15689619/224596436-23c329b9-c85d-4a60-a768-993aa00a063f.png)

In addition, this problem is the same as #2094，So this issue is closed first, we can continue the discussion under #2094
