### ISSUE TITLE
 Remove the dependence of curve-nbd, fio, and tgt on nebd

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#2097]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

和性能相关。当前[curve-nbd](https://github.com/opencurve/curve-nbd)、[tgt](https://github.com/opencurve/curve-tgt)都依赖于
[nebd](https://github.com/opencurve/curve/blob/master/docs/cn/nebd.md)。之前是为了客户端可以做热升级，当前curve块存储的客户端已经是稳定版本，为了提升性能，希望将nebd模块去掉，上层应用直接对接curve-client sdk。

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/15689619/206615686-841c1999-569a-4ec9-9b37-f2acb73da124.png">

The issue related to performance. At that time [curve-nbd](https://github.com/opencurve/curve-nbd), [tgt](https://github.com/opencurve/curve-tgt) all depended on
[nebd](https://github.com/opencurve/curve/blob/master/docs/cn/nebd.md). Previously, it was for the hot upgrade of the client. At that time, the client of the curve block storage was already a stable version. In order to improve the performance, it was hoped that the nebd module would be removed.The upper application directly use curve-client sdk.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
now curve-nbd，fio，tgt all support curve-sdk directly.

**Comment by legionxiong** [comment]
> now curve-nbd，fio，tgt all support curve-sdk directly.

Are there any code/pr links?
