### ISSUE TITLE
create logical pool failed

### ISSUE THREAD

**Issue by DemoLiang** [opencurve/curve#2100]
**Describe the bug (描述bug)**
1.当出现多chunkserver的时候，偶发性出现 create logical pool failed
![image](https://user-images.githubusercontent.com/23476007/203748761-33d1e636-9e1a-4060-be7b-3d925f80391c.png)
Error-Code: 410019                                                                                                                                                                    
Error-Description: create logical pool failed                                                                                                                                         
Error-Clue: E 2022-11-24T16:47:20.309028+0800   350 curvefsTool.cpp:193] CreateLogicalPool Rpc response fail. Message is :statusCode: -12                                             
            E 2022-11-24T16:47:20.309067+0800   350 curvefsTool.cpp:1109] exec fail, ret = -12                                                                                        
How to Solve:                                                                                                                                                                         
  * Website: https://github.com/opencurve/curveadm/wiki/errno4#410019                                                                                                                 
  * Log: /home/curve/.curveadm/logs/curveadm-2022-11-24_08-45-14.log                                                                                                                  
  * WeChat: opencurve_bot 
2.当再次执行`curveadm deploy -k` 后执行部署成功
 可能的远因是chunkserver上线和逻辑池初始化是并行的，chunkserver没上线完，就创建逻辑池失败了

**To Reproduce (复现方法)**
1.创建一个集群，然后chunkserver部署4*10，执行curveadm deploy
2.偶发性出现create logical pool failed

**Expected behavior (期望行为)**
1.执行部署成功

**Versions (各种版本)**
OS:  ubuntu 20.04
Compiler:curvebs1.2
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
What is the version of curveadm?

**Comment by ilixiaocui** [comment]
This is indeed a bug in the code. 

It is judged in the code that only the status of the registered chunkservers is judged, and the unregistered chunkservers cannot be queried through the following interfaces.
https://github1s.com/opencurve/curveadm/blob/HEAD/internal/task/scripts/wait_chunkservers.go

@Wine93 will fix it.

Thanks for your proposal!

**Comment by Wine93** [comment]
@DemoLiang @ilixiaocui We have fixed it, it will be released with the `v0.1.12-rc4`.
