### ISSUE TITLE
[opencurvedocker] opencurvedocker bs do not support 1.2.6

### ISSUE THREAD

**Issue by linuxgood1230** [opencurve/curve#2101]
## General Question
opencurvedocker bs do not support 1.2.6

**Comment by Cyber-SiKu** [comment]
update @linuxgood1230

**Comment by linuxgood1230** [comment]
666 
curveadm do not update to support curve_ops_tool stripe unit/count args

**Comment by Cyber-SiKu** [comment]
> 666 curveadm do not update to support curve_ops_tool stripe unit/count args

enter some container to create.

**Comment by Cyber-SiKu** [comment]
> 666 curveadm do not update to support curve_ops_tool stripe unit/count args

Curveadm is only responsible for deployment, and the creation is executed by curve_ops_tool. This command can be executed by entering the container (curvadm enter).

**Comment by linuxgood1230** [comment]
v1.2.6+cb7c2dd6+release
root@curvebs-chunkserver-e75c006d6156:/curvebs/chunkserver# curve_ops_tool create  -fileName=/ntmdb  -fileLength=100  -userName=usera --stripeUnit=32768  --stripeCount=32
ERROR: unknown command line flag 'stripeCount'
ERROR: unknown command line flag 'stripeUnit'

**Comment by Cyber-SiKu** [comment]
> docker image version do not match the release version commit ?
> 
> root@curvebs-chunkserver-e75c006d6156:/curvebs/chunkserver# curve_ops_tool version v1.2.6+cb7c2dd6+release root@curvebs-chunkserver-e75c006d6156:/curvebs/chunkserver# curve_ops_tool create -fileName=/ntmdb -fileLength=100 -userName=usera --stripeUnit=32768 --stripeCount=32 ERROR: unknown command line flag 'stripeCount' ERROR: unknown command line flag 'stripeUnit' @Cyber-SiKu

Sorry, curve_ops_tool supports creating volumes at `72cb758`, the packaged version is one commit behind, the image has been updated, please redeploy.

**Comment by Cyber-SiKu** [comment]
@linuxgood1230 Has the problem been solved?

**Comment by wuhongsong** [comment]
ping @linuxgood1230

**Comment by linuxgood1230** [comment]
yes ,thks
