### ISSUE TITLE
执行mk-tar.sh失败

### ISSUE THREAD

**Issue by wangxiyuan** [opencurve/curve#215]
**Describe the bug (描述bug)**

执行`bash mk-tar.sh`进行编译打包，进行到第七步`打包python whell`的打包py2时，报错。我的环境上同时安装了python2和python3。

**To Reproduce (复现方法)**

在同时有py2、py3的机器上执行`bash mk-tar.sh`

**Expected behavior (期望行为)**

期望py2和py3的包都打出来，但实际上只打出了py3的，py2的报错。

**Versions (各种版本)**
OS: Ubuntu 18.04
Compiler: gcc 7.4.0 bazel 0.17.2
curve-mds: master
curve-chunkserver: master
curve-snapshotcloneserver: master
curve-sdk: master
nebd: master
curve-nbd: master

**Additional context/screenshots (更多上下文/截图)**

在python包build过程中，会重建tmplib目录：https://github.com/opencurve/curve/blob/master/curvefs_python/configure.sh#L62-L73，
会从bazel-bin目录中拷贝so文件到tmplib。

然后在第一遍打包py3时没问题：
https://github.com/opencurve/curve/blob/master/mk-tar.sh#L90

但当打完py3的包后，bazel-bin目录已经发生了改变，导致再打包py2时，bazel-bin目录已经没有了需要的so文件，从而py2打包失败。

**建议**：
1. 需要在打包前，备份一下bazel-bin中生成的各个so文件。Patch: https://github.com/opencurve/curve/pull/216

2. 或者，由于py2已经官方废弃，不如curve这里只支持py3？

**Comment by aspirer** [comment]
Thanks very much, we are checking this issue now, we will review the pr if the issue is confirmed.

**Comment by wu-hanqing** [comment]
本地复现的过程，发现是 bazel build curvefs_python这里，自动清理了其他目录下已编译生成的so文件。
备份的方式也是可行的。
