### ISSUE TITLE
the latest master branch compile error

### ISSUE THREAD

**Issue by fansehep** [opencurve/curve#2159]
**Describe the bug (描述bug)**

build error in offical docker.

![2022-12-13_12-12-1670906452](https://user-images.githubusercontent.com/75058860/207228638-a603ae47-7ede-4956-93d9-2da7db4c92b3.jpg)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Arch Linux (6.0.11)
Compiler: gcc 6.3
branch: master
commit id: e00097b00048b954f3051004b5f049c8b38ea657

**Additional context/screenshots (更多上下文/截图)**

**Comment by h0hmj** [comment]
what does "offical docker" refer to?

**Comment by fansehep** [comment]
> what does "offical docker" refer to?
> 
> Arch Linux is your host os? or docker image?
> 
> what is your docker image tag?

from this 
```bash
docker pull opencurvedocker/curve-base:build-debian9
```
yep, the docker image is run in Arch Linux.

**Comment by h0hmj** [comment]
it seems that recently added thirdparty under https://github.com/opencurve/curve/tree/master/thirdparties/memcache
need cmake >= 3.9 but cmake version in debian9 is 3.7.2 (stretch-backport cmake is broken)

make dep should failed but it seems no check of return code $?

you can install high version cmake from cmake official website and try again maybe (cd thirdparties/memcache && make)

maybe lack of som build deps also, like bison, flex...emm @ilixiaocui

**Comment by fansehep** [comment]
> it seems that recently added thirdparty under https://github.com/opencurve/curve/tree/master/thirdparties/memcache need cmake >= 3.9 but cmake version in debian9 is 3.7.2 (stretch-backport cmake is broken)
> 
> make dep should failed but it seems no check of return code $?
> 
> you can install high version cmake from cmake official website and try again maybe (cd thirdparties/memcache && make)
> 
> maybe lack of some build deps also, like bison, flex...emm @ilixiaocui should make them all work

Thanks a lot, install high version cmake and install the bison and flex can solve this problem.
