### ISSUE TITLE
raft snapshot 是不是存在不一致？

### ISSUE THREAD

**Issue by zexuan** [opencurve/curve#217]
## General Question
chunkserver raftsnapshot 模块，copyset_node.cpp 中 on_snapshot_save 方法只是列举了所有CHUNKFILE 类型的文件，并将文件名保存在 BRAFT_SNAPSHOT_META_FILE 文件中。后续 install_snapshot 的时候，follower会从leader下载这个meta文件、data目录下的chunkfile文件、data目录下的snapshotfile文件。snapshotfile可以理解为只读的，而chunkfile非只读的，那么安装快照的过程中，chunkfile有可能发生变化，会造成follower和leader数据的不一致。

不知道我理解的是不是有问题，还是有其他机制保证此处的一致性，敬请解答～

**Comment by zexuan** [comment]
@ilixiaocui 请帮忙看一下

**Comment by bai-charisu** [comment]
你好，非常感谢你的提问。你说的这个问题确实存在，但是follower在把chunkfile下载过去之后，会继续复制日志并apply，这个过程中会把打快照的时刻之后的写操作都同步过来，最终leader和follower数据就一致了。我们这样设计是利用了覆盖写的幂等性，写过的数据再写一遍不会影响结果。

**Comment by zexuan** [comment]
> 你好，非常感谢你的提问。你说的这个问题确实存在，但是follower在把chunkfile下载过去之后，会继续复制日志并apply，这个过程中会把打快照的时刻之后的写操作都同步过来，最终leader和follower数据就一致了。我们这样设计是利用了覆盖写的幂等性，写过的数据再写一遍不会影响结果。

1. braft安装快照的时候会拒绝appendEntries请求，安装完快照之后，即on_snapshot_load_done之后，将_downloading_snapshot置为NULL，此时才允许appendEntries请求。
2. 此时继续从leader复制日志并apply，会把leader上的增量数据同步过来。这个阶段能够最终保证leader和follower的数据完全一致，原因是leader写入chunkfile的数据，其日志必然是committed过的。数据不会多不会少。
3. curvefs具有覆盖写的幂等性，保证重写没有影响。
非常感谢，我理解的没有问题吧？

**Comment by bai-charisu** [comment]
没问题，是这样的~

**Comment by zexuan** [comment]
感谢～
