### ISSUE TITLE
Failed to register to MDS.

### ISSUE THREAD

**Issue by zhujintao** [opencurve/curve#2172]
I 2022-12-26T21:01:47.472833+0800     1 register.cpp:73]  Registering to MDS 10.4.0.233:6666. internal ip: 10.4.0.234, port: 8200, enable external server: 1, external ip: 10.4.0.234
E 2022-12-26T21:01:47.479765+0800     1 register.cpp:100] 10.4.0.234:8200 Fail to register to MDS 10.4.0.233:6666, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2022-12-26T21:01:48.480907+0800     1 register.cpp:100] 10.4.0.234:8200 Fail to register to MDS 10.4.0.233:6666, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.

**Comment by Cyber-SiKu** [comment]
@zhujintao Are you using curvefs or curvebs? Is this a chunkserver or metaserver log? Please give more details.

**Comment by SeanHai** [comment]
1. The error seems cluster topology didn't create successfully in mds.
2. statusCode: -7 is 'kTopoErrCodeServerNotFound', means the server which chunkserver run doesn't record in mds before chunkserver start.

Which version of Curve you deployed?
First: you can find error log of mds leader

**Comment by zhujintao** [comment]
> 1. The error seems cluster topology didn't create successfully in mds.
> 2. statusCode: -7 is 'kTopoErrCodeServerNotFound', means the server which chunkserver run doesn't record in mds before topology start.
> 
> Which version of Curve you deployed? First: you can find error log of mds leader


谢谢！curve-tool -op create_logicalpool -cluster_map topo.json 创建后正常了。

chunkserver 可以自动注册吗？如果通过k8s的deploy来分发chunkserver，如何自动注册、伸缩呢？
现有的拓扑信息从那里可以获取的到？

**Comment by SeanHai** [comment]
The detail of CurveBS cluster topology: https://github.com/opencurve/curve/blob/master/docs/cn/mds.md#topoloy

The chunkserver of Curve cluster is relatively fixed, it belongs to one specific server which belongs to a zone of a pool.
Now the capacity is expanded by pool, and you can use tool 'curve_ops_tool' to get topo of the cluster.

**Comment by SeanHai** [comment]
> > 1. The error seems cluster topology didn't create successfully in mds.
> > 2. statusCode: -7 is 'kTopoErrCodeServerNotFound', means the server which chunkserver run doesn't record in mds before topology start.
> > 
> > Which version of Curve you deployed? First: you can find error log of mds leader
> 
> 谢谢！curve-tool -op create_logicalpool -cluster_map topo.json 创建后正常了。
> 
> chunkserver 可以自动注册吗？如果通过k8s的deploy来分发chunkserver，如何自动注册、伸缩呢？ 现有的拓扑信息从那里可以获取的到？

The detail of CurveBS cluster topology: https://github.com/opencurve/curve/blob/master/docs/cn/mds.md#topoloy

The chunkserver of Curve cluster is relatively fixed, it belongs to one specific server which belongs to a zone of a pool.
Now the capacity is expanded by pool, and you can use tool 'curve_ops_tool' to get topo of the cluster.
