### ISSUE TITLE
curve/tools-v2: More than two mds did not report an error

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2175]
**Describe the bug (描述bug)**

More than two mds did not report an error

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:543f95dc

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/15775037/209786292-812a665f-9892-4c35-b63c-db5d97c74745.png)

**Comment by wuhongsong** [comment]
@Cyber-SiKu
