### ISSUE TITLE
[curvefs] Add a command to quickly delete a directory

### ISSUE THREAD

**Issue by cw123** [opencurve/curve#2231]
Description：

为Curvefs 增加一个快速删除目录的命令。
因为curvefs使用fuse的方式使用，rm -r 删除一个目录的时候，为文件下的每个目录或者文件删除的时候，fuse都会调用一次FuseClient的删除接口。
希望增加一个命令，只需要向curvefs传入删除的目录，curvefs自己会递归调用目录下的子目录和文件的删除。减少了fuse和curvefs之间的请求个数。

Add a command to quickly delete directories for Curvefs.
Because curvefs uses fuse, when rm -r deletes a directory, when deleting each directory or file under the file, fuse will call the delete interface of FuseClient once.
I hope to add a command, just pass the deleted directory to curvefs, and curvefs will recursively call the deletion of subdirectories and files under the directory. Reduced the number of requests between fuse and curvefs.

Proposed solution：

增加一个单独的删除目录的命令，删除一个目录不走fuse接口，curvefs处理目录递归遍历删除逻辑。

Add a separate command to delete a directory, delete a directory without going through the fuse interface, curvefs handles the directory recursive traversal deletion logic.

**Comment by Laihuihang** [comment]
i want to try this issue.

**Comment by Kaushik-Nishant** [comment]
I want to work on this issue. i am not getting that  where do i add this command?

**Comment by SeanHai** [comment]
> 

This command is to avoid multiple system calls brought by ‘rm -r‘, so a way can send this command to curve-fuse is needed.
For example, you can use interface 'setxattr' like warmup function: https://github.com/opencurve/curve/blob/e03e921012f94e07bb6e85e962bf7e073333ce24/curvefs/src/client/curve_fuse_op.cpp#L353
Or some other suitable interface.

**Comment by caoxianfei1** [comment]
> > > i want to try this issue.
> > 
> > 
> > @Laihuihang any progress ? you can contact us if you have any difficulty.
> 
> how to contact you? email?

You would join our WeChat group

![POPO20230306-105315](https://user-images.githubusercontent.com/54139479/223008747-ae539cbd-2b61-46ff-956f-8280f1847e37.jpg)

**Comment by SeanHai** [comment]
> 
The above is just a way of thinking. If you want to use it, you can pass the quick delete command (maybe name is curvefs.rm) through it, and curve-fuse will process it after receiving it.

**Comment by Cyber-SiKu** [comment]
@Kaushik-Nishant Are you still going on?
