### ISSUE TITLE
After the memcache service hangs up, it starts and does not join the cluster.

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2246]
**Describe the bug (描述bug)**

After the memcache service hangs up, it starts and does not join the cluster.

**To Reproduce (复现方法)**
1、kill memcache server
2、sleep time
3、start memcache server docker

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
@ilixiaocui Is this still going on?

**Comment by ilixiaocui** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/15689619/222076223-56ed1fc5-388f-42df-bb31-1068ee522389.png">
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/15689619/222076334-2a585469-f786-4d24-993d-0f0312faabdf.png">
