### ISSUE TITLE
When testing with fsthrash and vdbench, the mount point oom

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2247]
**Describe the bug (描述bug)**
When testing with fsthrash and vdbench, the mount point oom

**To Reproduce (复现方法)**
1、./virtualenv/bin/fsthrash-suite  --suite_path /home/nbs/fsthrash/suites/posix --testdir /home/nbs/failover/test2 --numjobs 1 --filter-out iozone
2、start vdbench test
![image](https://user-images.githubusercontent.com/67582932/218990089-930cad5c-76cc-4e8a-8a21-05d22ccb18c3.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
@ilixiaocui Is this still going on?

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/222075258-a48814c8-6cb0-4ea5-9260-162075037aa6.png)

I use the `jeprof` tool to collect memory allocation information for a period of time，you can see the memory leak point as follows: 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/15689619/222075676-ab78d925-6441-4135-8301-46ae9192d9d0.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/15689619/222075779-faa891f6-0620-4cbf-af29-df4c527ef49c.png">

When `Get` does not use the thread pool to operate, each io uses a new thread to process, and a new `memcache_client` will be cloned, causing the memory to grow all the time.
