### ISSUE TITLE
After the memcache exits abnormally and is pulled up, the data is inconsistent

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2248]
**Describe the bug (描述bug)**
After the memcache exits abnormally and is pulled up, the data is inconsistent

**To Reproduce (复现方法)**
1、start vdbench test
2、kill memcache
3、start memcache
4、vdbench error
After the memcache exits abnormally and is pulled up, the data is inconsistent

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/15689619/219301757-bc81799a-e176-49a3-8dec-65b8b48188ad.png">

**Comment by Cyber-SiKu** [comment]
@ilixiaocui Is this still going on?
