### ISSUE TITLE
Inconsistent data appears during the use of memcache. 

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2251]
**Describe the bug (描述bug)**

Inconsistent data appears during the use of memcache. 
**To Reproduce (复现方法)**
data_errors=1
fsd=fsd1,anchor=/home/nbs/failover/test6/t1,depth=1,width=10,files=50,sizes=(200m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test7/t2,depth=1,width=10,files=50,sizes=(200m,0),shared=yes,openflags=o_direct
#fsd=fsd3,anchor=/home/nbs/failover/test3/t3,depth=1,width=10,files=50,sizes=(300m,0),shared=yes,openflags=o_direct
#fsd=fsd4,anchor=/home/nbs/failover/test4/t4,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=70
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=2000000,interval=1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
@ilixiaocui Is this still going on?

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/222074096-2a078c2f-ee18-4d3e-9545-28a954754ed2.png)
![image](https://user-images.githubusercontent.com/15689619/222074125-947d0c60-844f-4c1e-9474-69fe07432f5a.png)

As can be seen from the log, inconsistent fragments are read from memcache.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/15689619/222074422-a2e8d503-4db5-426c-80a4-e94005f1dfd5.png">
`Get` in memcache does not judge whether the return value is ok.
