### ISSUE TITLE
format chunkfilepool in backgroud

### ISSUE THREAD

**Issue by xu-chaojie** [opencurve/curve#2261]
目前curve的部署前置步骤中，需要格式化chunkfilepool以提升性能，这一步骤通常需要很长时间，尤其是对于HDD等场景耗时就更加长。我们期望实现在后台进行格式化chunkfilepool的功能，在首次部署时，先格式化部分chunkfilepool或者不格式化chunkfilepool，当chunkserver启动后，在后台格式化chunkfilepool，并需要再工具中提示当前格式化chunkfilepool的进度，以告知用户当前格式化完成，可测试最佳性能。
你可能需要修改chunkserver的格式化chunkfilepool部分代码，以及chunkserver增加后台线程格式化chunkfilepool，这部分需要你熟悉c++。
此外，你还可能需要修改curve部署工具curveadm，这部分需要go开发。

本项目难度为进阶，参与项目需要熟悉c++开发，go开发，熟悉gtest等单元测试框架，以及linux上的编译，调试等，此外需要了解curve部署工具curveadm。

**Comment by caoxianfei1** [comment]
@Cyber-SiKu

**Comment by ashutosh887** [comment]
@xu-chaojie @caoxianfei1 Let me work on this

**Comment by Xinlong-Chen** [comment]
I am interested in this task. Can I apply for this task for OSPP2023？

**Comment by ilixiaocui** [comment]
> I am interested in this task. Can I apply for this task for OSPP2023？

you can sign up in the [OSPP2023](https://summer-ospp.ac.cn/), and give the design document.

**Comment by wuhongsong** [comment]
> @xu-chaojie @caoxianfei1 Let me work on this

for free  to try it
