### ISSUE TITLE
There are two s3clients 

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2262]
**Describe the bug (描述bug)**

<img width="706" alt="POPO-20230224-165910" src="https://user-images.githubusercontent.com/15775037/221136341-b2b78757-8863-496a-b2af-00f73470c3c8.png">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

One S3Adaptor should be used instead of creating a separate one.

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
https://github.com/opencurve/curve/pull/1706  seprate the s3 for diskcache and datacache
