### ISSUE TITLE
【C-Plan】编译及部署初体验

### ISSUE THREAD

**Issue by taohansi** [opencurve/curve#227]
# 编译及部署初体验
本issue为C-Plan的必选任务，包含部署及编译。
本文先介绍遇到的问题，然后为成功的截图。

## 问题
1 
执行`ansible-playbook -i client.ini deploy_nbd.yml`遇到权限问题
![{760D6D75-14BA-488C-936C-F59744BBB6A6}](https://user-images.githubusercontent.com/29743804/104924428-5c395000-59d8-11eb-845e-25935781a52b.png)
后加上`sudo`成功
```shell
sudo ansible-playbook -i client.ini deploy_nbd.yml
```
## 成功的流程
注意curve提供了两个docker镜像，分别用于开发和部署，需要分别拉取
```shell
docker pull opencurve/curvebuild:centos8
docker pull opencurve/curveintegration:centos8
```
根据文档，创建对应的container，执行对应步骤即可

**编译及打包成功**
![{AAB4C34B-06EB-4A70-BF85-423728BF69B0}](https://user-images.githubusercontent.com/29743804/104926269-e682b380-59da-11eb-8ec9-f60f100afa12.png)

![{3F27D22F-2A90-4481-A415-4C7F0D287461}](https://user-images.githubusercontent.com/29743804/104926329-f7332980-59da-11eb-9766-651484a3600e.png)

**部署成功**
集群状态满足文档要求
![{B517BC78-277F-41D9-B2C7-52567A5E324A}](https://user-images.githubusercontent.com/29743804/104926542-42e5d300-59db-11eb-86c9-4de30dc29f0a.png)

查看`/test`的创建信息
![截图 ](https://user-images.githubusercontent.com/29743804/104927683-ae7c7000-59dc-11eb-9485-f431ff197ad8.png)

观察到一个类型为nbd0类型的卷被添加
![{32AFEC1F-62CF-4DD0-9F81-4519AB8DB86A}](https://user-images.githubusercontent.com/29743804/104926948-c69fbf80-59db-11eb-844a-7b36d41c57c8.png)

**Comment by cw123** [comment]
恭喜taohansi同学成功部署了curve！从结果上来看，已经部署成功。
整个编译部署的过程，总共花费了多少时间呢？除了sudo权限问题，还有碰到了什么其他问题吗？有没有发现哪些可以改进的地方？这些也可以和我们分享一下。
接下来可以尝试下用fio在nbd0上跑跑测试感受一下，或者挂载成一个文件系统使用一下。然后看看还有什么感兴趣的任务的，继续加油吧。

**Comment by wu-hanqing** [comment]
感谢 @taohansi 的反馈。sudo问题，应该是内核没有nbd模块，第一次添加nbd模块时，需要root权限导致的。
解决思路应该是在 `curve-ansible/common_tasks/check_if_nbd_exists_in_kernel.yml` 里面，在`/sbin/modprobe nbd`命令前面加上sudo即可。
你可以尝试解决一下，并在本地进行测试，如果没有其他问题，可以将修复发起Pull Request。
