### ISSUE TITLE
【C-Plan】编译与部署

### ISSUE THREAD

**Issue by YechenGu** [opencurve/curve#229]
#### 1、基本步骤

编译的过程还是比较顺利的，按部就班操作即可，总共用时一个多小时

体验非常的丝滑顺畅

可以看到编译成功的提示：

<img width="465" alt="屏幕快照 2021-01-18 上午4 53 17" src="https://user-images.githubusercontent.com/43727142/105282747-f6bcad80-5be9-11eb-877a-d6eea0ae0295.png">

打包成功：

<img width="725" alt="屏幕快照 2021-01-18 上午4 57 07" src="https://user-images.githubusercontent.com/43727142/105282767-076d2380-5bea-11eb-8f55-8982c96cd170.png">

#### 1、基本步骤

一路部署下来还是遇到不少坑的，先po出结果吧：

集群部署成功：

<img width="1017" alt="屏幕快照 2021-01-20 下午10 32 32" src="https://user-images.githubusercontent.com/43727142/105282776-0b00aa80-5bea-11eb-90eb-f1dfbe47b311.png">

集群状态检查：

<img width="981" alt="屏幕快照 2021-01-20 下午10 33 50" src="https://user-images.githubusercontent.com/43727142/105282785-0dfb9b00-5bea-11eb-9a95-5843ea8dd7af.png">

Nbd0卷检查：

<img width="956" alt="屏幕快照 2021-01-20 下午10 44 11" src="https://user-images.githubusercontent.com/43727142/105283770-18b72f80-5bec-11eb-97c8-75076a53ee28.png">

#### 2、踩坑&填坑

- 镜像要选择正确

最开始，我直接在curvebuild镜像下，对着编译打好的tar包解压并部署了。配环境真的需要很多时间～

还是使用curveintegration这个镜像最省事了

- 切换到curve用户时，会报出下列警告：

```bash
-bash: /dev/null: Permission denied
```

这是出了权限问题

设置一下，就可以了：

```bash
chmod 777 /dev/null
```

- wget速度过慢，经常中断的问题

换用axel多线程下载工具，可以大大加快速度

带上-c参数，启用断点续传，就不用担心经常速度变成0了

- 部署集群时报错：Curl error (28): Timeout was reached 

连接超时了，经常还和6号错误一同出现，这是源的问题

换一个能用的源可以解决问题

- 部署集群时报错：/usr/bin/python: No such file or directory

在bin下确实不存在python目录，但是存在具体版本的目录

使用软连接，把python连接到python2,7上：

```bash
ln -s /usr/bin/python2.7 /usr/bin/python
```

- 部署集群时报错：Errors during downloading metadata for repository 'base'

这也是源出问题了

换一个能用的源可以解决问题

- 部署集群时报错：dev/urandom not found

好像是权限出了问题，dev下是存在urandom的

在执行命令的时候加上sudo就可以了

**Comment by bai-charisu** [comment]
同学你好，本次任务完成的很好，文档写的也很详细，给你点赞~
另外，请问一下你最后列出来的部署过程中遇到的坑全部都是使用curveintegration镜像时遇到的吗？

**Comment by ilixiaocui** [comment]
感谢你的关注与参与！部署和编译完成的很棒，文档简洁明了，good job ！

看到 ## 体验非常的丝滑顺畅 ## 甚至欣慰，哈哈。

**Comment by YechenGu** [comment]
> 同学你好，本次任务完成的很好，文档写的也很详细，给你点赞~
> 另外，请问一下你最后列出来的部署过程中遇到的坑全部都是使用curveintegration镜像时遇到的吗？

嗯嗯，都是在使用curveintegration镜像的时候遇到的
