### ISSUE TITLE
[feature] add libfmt to WORKSPACE

### ISSUE THREAD

**Issue by fansehep** [opencurve/curve#2291]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

We currently use glog as out log output. a log like :
``` c++
 LOG(INFO) << "XXXX" << "xxx" << "xxxx" << xxx.xxx ...;
```
libfmt is a fast simple for format lib. 
If we use libfmt we can do:

``` c++
 LOG(INFO) << fmt::format("{} {} {} {}", xxx, xxx, xxx, xxx):
```
libfmt is support C++11.

From the libfmt benchmark. we can see it is more faster than any style.

Not only fast. libfmt is elegant to use. Seems most cppers hate chain logs. like glog ```<<``` ugly grammar.

This is the benchmark of libfmt:

![2023-03-04_22-03-1677939269](https://user-images.githubusercontent.com/75058860/222907278-fa204270-e370-4c11-9108-b12ca66ba220.jpg)

**Describe the solution you'd like (描述你期望的解决方法)**

Just add fmt to our WORKSPACE, libfmt provide https://github.com/fmtlib/fmt/tree/master/support/bazel for us.
use a stable release version.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Ziy1-Tan** [comment]
Great introduction.

**Comment by ashutosh887** [comment]
@fansehep Let me work on this Issue

**Comment by Cyber-SiKu** [comment]
@Tangruilin Are you still working on this issue?

**Comment by Cyber-SiKu** [comment]
@ashutosh887 Someone is already working on this, you can look at other issues or wait until this person stops doing it.

**Comment by caoxianfei1** [comment]
@Tangruilin the issue is going on?

**Comment by Tangruilin** [comment]
@caoxianfei1 @Cyber-SiKu I will finish the issue these days.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Tangruilin** [comment]
I come to Beijing for work these days and my computer is not here.

This weekend it will be sent to Beijing

**Comment by caoxianfei1** [comment]
@Tangruilin free to do it.

**Comment by ilixiaocui** [comment]
@Tangruilin Are you going to follow up on this issue?

**Comment by ashutosh887** [comment]
@Cyber-SiKu Is this resolved now?

**Comment by Tangruilin** [comment]
> @Tangruilin Are you going to follow up on this issue?

Maybe this issue should assign to others. I have no time util Aug, I am so sorry

**Comment by ashutosh887** [comment]
@ilixiaocui @fansehep 
I would like to work on this

**Comment by ilixiaocui** [comment]
> @ilixiaocui @fansehep I would like to work on this

welcome!

**Comment by ilixiaocui** [comment]
> > @Tangruilin Are you going to follow up on this issue?
> 
> Maybe this issue should assign to others. I have no time util Aug, I am so sorry



> Maybe this issue should assign to others. I have no time util Aug, I am so sorry

Never mind!

**Comment by caoxianfei1** [comment]
@Tangruilin How is going on? Do you have time for it ?

**Comment by caoxianfei1** [comment]
@ashutosh887 How is going on? Do you have time for it ?

**Comment by fansehep** [comment]
solved with https://github.com/opencurve/curve/commit/4ae45e5dd0970147d36ca2d74f21722647edd5a6.
