### ISSUE TITLE
UmountFs will cause deadlock

### ISSUE THREAD

**Issue by surpassly** [opencurve/curve#2308]
**Describe the bug (描述bug)**
UmountFs will cause deadlock

**To Reproduce (复现方法)**
Deadlock happens in this circumstances.
A and B are different mount points of same Fs.
1. A acquires NameLockGuard in UmountFs
2. B acquires WriteLockGuard in UpdateClientAliveTime
3. B acquires NameLockGuard in AddMountPoint
4. A acquires WriteLockGuard in DeleteClientAliveTime

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@surpassly   thanks for you contribution.  @SeanHai  have a look？

**Comment by surpassly** [comment]
这是来自QQ邮箱的自动回复邮件。

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by liuxy028** [comment]
Hello, I want to solve this porblem!

**Comment by liuxy028** [comment]
ok
&nbsp;


刘习永
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hui ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opencurve/curve] UmountFs will cause deadlock (Issue #2308)






***@***.***

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by caoxianfei1** [comment]
@liuxy028 how ois going on?

**Comment by liuxy028** [comment]
Sorry, it's too difficult. I'm still studying and I'm afraid I can't solve it. I am about to start my final exam recently, and I want to give up. I'm really sorry&nbsp;


刘习永
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opencurve/curve] UmountFs will cause deadlock (Issue #2308)





 
@liuxy028 how is going on?

**Comment by Xinlong-Chen** [comment]
I don't  find the code about add NameLockGuard  in AddMountPoint.
https://github.com/opencurve/curve/blob/a71355156add0d38f306cb8451f508b0e0823ee6/curvefs/src/mds/fs_manager.cpp#L1060-L1085
**Has the bug been fixed?**
