### ISSUE TITLE
Data duplication

### ISSUE THREAD

**Issue by mykgspace** [opencurve/curve#2309]
Hello! I'm testing your CurveBS system. In the course of work, a question arose about the distribution of data. I give my example:
There are 3 servers, on everyone a disk in the size of 20 Gb. After deploying the CurveBS cluster, I mount a 10GB volume on the client with the command:

`curveadm map curvebsuser1:/test --host client-node  -c clientbs.yaml`

After mounting the disk on the client in the /mnt directory, I loaded a 1.1 GB VM image, but the number of chunks decrease by a size comparable to 2.2 GB. Moreover, they evenly decreased on all 3 servers and it turned out that the total occupied memory from one image of 1.1.GB is 6.6GB (1.1 * 2 (data duplication) * 3 (number of servers))
Please tell me why is this happening? Thank you in advance!

**Comment by ilixiaocui** [comment]
https://github.com/opencurve/curve/blob/master/docs/cn/mds.md
<img width="917" alt="image" src="https://user-images.githubusercontent.com/15689619/224989323-ca97194d-9968-48f0-afa9-0efd63501565.png">

1.1 GB VM image load may be randomly written, so more chunk allocation will be involved.

**Comment by mykgspace** [comment]
Thanks for the answer! But why then is it possible to use the number of chunks more than potentially allocated by the volume?
If a 10GB volume is approximately 640 chunks, but if upload several VM images, then the chunks run out and the containers on the server hosts fall.
Thanks in advance for your reply!

**Comment by wuhongsong** [comment]
> And another question. Can I change the data duplication policy?
yes, but now the replicas should greater than 3 because of curve use raft.( we are currently retrofitting raft to support replicas less than 3), and ec is not in this year's roadmap.

thanks for your attention curve.

**Comment by mykgspace** [comment]
Thanks for answer!
