### ISSUE TITLE
【C-Plan】Ubuntu 18.04 下编译及部署

### ISSUE THREAD

**Issue by An-DJ** [opencurve/curve#231]
**Describe the task you choose (描述你选择的任务)**
> 完成 Ubuntu 18.04 环境下 curve 编译及部署

## curve 编译
编译环境：4核8G Ubuntu 18.04

首先需要安装各种所需库依赖。 Dockerfile 中从 centos 基础镜像开始构建，依次 install 了许多安装包，对应 ubuntu 环境下需要安装如下预编译包（apt-get install）：
> libssl-dev  uuid-dev  libfiu-dev  libcurl4-openssl-dev  zlib  zlib1g.dev  libnl-3-dev  libboost-dev  libunwind8-dev  libnl-genl-3-dev  python-pip

接着安装 bazel，执行
> wget https://curve-build.nos-eastchina1.126.net/bazel-0.17.2-installer-linux-x86_64.sh
> bash bazel-0.17.2-installer-linux-x86_64.sh

安装上述依赖和 bazel 均需 sudo 或 root 用户下执行。接下来编译及打包即可。

![image](https://user-images.githubusercontent.com/24536972/105478569-4bd9eb80-5cde-11eb-8cc0-2fd30063b7b0.png)

![image](https://user-images.githubusercontent.com/24536972/105478583-51373600-5cde-11eb-8254-0a7f612041c2.png)

**建议1**：请勿打开 go mod，最好环境中不安装 golang。编译过程中下载了 1.12.8 版本的 golang 且对所有 etcd v3.4.0 的 go 依赖统一源代码形式下载至本地，编译时默认从源代码编译。由于 etcd 出现过替换 go.etcd.io/etcd 替换为 github.com/coreos/etcd ，以及 grpc 的版本问题，使用 go mod 下载的依赖会造成编译无法通过。

**建议2**：2次编译时可以将 https://github.com/opencurve/curve/blob/master/build.sh#L94 的 make clean 和 make all 注释掉，这部分 libetcdclient.so 已经编译完成后无需重新编译。

执行 bash build.sh 开始编译。由于未指定版本信息，打包完成生成如下4个文件
> curve_9.9.9+5f9b5f68.tar.gz 
> curve-monitor_9.9.9+5f9b5f68.tar.gz 
> nbd_9.9.9+5f9b5f68.tar.gz 
> nebd_9.9.9+5f9b5f68.tar.gz

## curve 部署
单机环境下按照部署文档中描述进行部署。

![image](https://user-images.githubusercontent.com/24536972/105478685-74fa7c00-5cde-11eb-91a0-56f2351959eb.png)

**建议1**：curve 使用了 perf，而 ubuntu 源中没有约定的 linux-perf 包，ubuntu 18.04 既定内核版本下安装：
> sudo apt-get install linux-tools-common

安装完成后执行 perf 有对应提示，表明生效。
之后，将 https://github.com/opencurve/curve/blob/master/curve-ansible/roles/prepare_software_env/tasks/main.yml#L48 注释 install perf 相关。

**建议2**：部署权限问题。目前暂使用 root 用户直接部署，创建 curve 用户后包括 /etc/curve 等配置文件夹、nbd 执行等都存在权限问题，猜测 ansible 执行既定 playbooks 时仍需要 root 权限。

**建议3**：python 包网络下载慢建议添加 pip 国内源，etcd 也可手动下载至 /tmp/etcd-v3.4.0.tar.gz，并修改对应 ansible 配置文件。

**Comment by qinyihust** [comment]
感谢你对C计划的关注与参与！
文档写得不错，特别是几点建议，都比较实用~
希望你继续加油！
