### ISSUE TITLE
[optimze] optimize some metric style

### ISSUE THREAD

**Issue by fansehep** [opencurve/curve#2319]
In ```/curvefs/src/client/metric/client_metric.h```:

``` c++
struct FSMetric {
    const std::string prefix = "curvefs_client";

...

struct S3Metric {
    const std::string prefix = "curvefs_s3";

...
struct DiskCacheMetric {
    const std::string prefix = "curvefs_disk_cache";

struct KVClientMetric {
    const std::string prefix = "curvefs_kvclient";

...

struct KVClientMetric {
    const std::string prefix = "curvefs_kvclient";

...
```

Use ```const std::string xxx``` in a ```struct``` type is strange. ```static``` is right.

Optimize them in all *.h and *.cpp;

**Comment by Veeshavanachu** [comment]
i will take this

**Comment by ashutosh887** [comment]
@fansehep Let me work on this

**Comment by caoxianfei1** [comment]
@ashutosh887 the work going on?

**Comment by wu-hanqing** [comment]
```cpp
struct FSMetric {
    static constexpr const char* prefix = "curvefs_client";
};
```

maybe this's better, if you use `static const std::string`, you have to define the string in cpp file.

[godbolt](https://godbolt.org/z/6vvh69hqo)

**Comment by fansehep** [comment]
```const char*``` if we have a function like ``` void xxx(const std::string& str_name)```, we input a ```const char*``` here, that will construct a string.

But in fact, static variables are initialized at runtime, and char* can be compile-time constants. It may depend on the scenario.

I think here ```std::string``` is better than ```const char*```.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Xinlong-Chen** [comment]
The issue seems more simple than other issues, can I get this task?
I agree with the `const static std::string` plan because it is more high-efficiency.
I will add a cpp file to initialize all the string variables.

**Comment by Xinlong-Chen** [comment]
Why does following variables not define const? (such as `const std::string prefix;`，other class in this file do it)
In `/curvefs/src/client/metric/client_metric.h`：
```cpp
struct MDSClientMetric {
    std::string prefix;
}

struct MetaServerClientMetric {
    std::string prefix;
}

struct ClientOpMetric {
    std::string prefix;
}
```

**Comment by wu-hanqing** [comment]
> 

it should be, you can fix this.

**Comment by czzmiku** [comment]
can I do it? #2319
