### ISSUE TITLE
【C-Plan】编译与部署

### ISSUE THREAD

**Issue by yangqings** [opencurve/curve#232]
## 一、编译

基于`curvebuild`镜像，拉取docker镜像并启动

```bash
docker pull opencurve/curvebuild:centos8
docker run -it opencurve/curvebuild:centos8 /bin/bash
```

遇到无法联网问题，加上--net=host

```bash
docker run --net=host -it opencurve/curvebuild:centos8 /bin/bash
```

编译和打包顺利，没有遇到问题：

![0 curve build](https://user-images.githubusercontent.com/20638528/105630297-4e297a80-5e83-11eb-8b3c-ae79f9190521.png)
![0 curve build1](https://user-images.githubusercontent.com/20638528/105630298-4ec21100-5e83-11eb-8456-4ddafb1b5879.png)
使用的是个人PC的虚拟机，编译打包耗时约一个小时

可以看到，tar文件打包成功
![0 打包成功](https://user-images.githubusercontent.com/20638528/105630300-51246b00-5e83-11eb-82bc-29b5f3566d43.png)

## 二、单机部署

基于`curveintegration`镜像

#### 拉取并启动镜像

```bash
docker run --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules --privileged -it opencurve/curveintegration:centos8 /bin/bash
```

容器内无法联网，加上`--net=host`，重新 `docker run`

```bash
docker run --net=host --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules --privileged -it opencurve/curveintegration:centos8 /bin/bash
```

#### 获取tar并解压

按步骤进行

#### 执行单机部署

部署集群并启动服务

```bash
ansible-playbook -i server.ini deploy_curve.yml
```

执行命令查看当前集群状态

```bash
curve_ops_tool status
```

![1 Chunkserver status](https://user-images.githubusercontent.com/20638528/105630291-44a01280-5e83-11eb-9e90-a98702ee2d3c.png)

```bash
ansible-playbook -i client.ini deploy_nebd.yml
ansible-playbook -i client.ini deploy_nbd.yml
ansible-playbook -i client.ini deploy_curve_sdk.yml
```

前几次部署尝试安装NBD包一直遇到报错，原因是第一次添加nbd模块时权限不足，感谢前面的@taohansi同学提供的解决办法。

#### 单机部署验证

![2 创建curve卷](https://user-images.githubusercontent.com/20638528/105630289-42d64f00-5e83-11eb-80f7-798028f00289.png)

可以看到nbd0卷

**Comment by qinyihust** [comment]
祝贺你顺利迈出C计划的第一步！
希望你再接再厉，继续攻克后续关卡~
