### ISSUE TITLE
Chunk reservation

### ISSUE THREAD

**Issue by mykgspace** [opencurve/curve#2323]
Hello! Can you please tell me how the time is determined after which the reserved chunks return to normal and are available again for reservation?
In my case, the chunks started coming back after about 30 minutes:
![image](https://user-images.githubusercontent.com/86982151/226548777-b05fcd3d-ce65-4f44-b59e-c91b5b61f5da.png)
Thanks in advance for your reply!

**Comment by ilixiaocui** [comment]
What commands were executed during this time？

**Comment by mykgspace** [comment]
After the file download was completed (16:53 according to the schedule presented above), no further actions were taken with the disk

**Comment by Cyber-SiKu** [comment]
@mykgspace You can add our WeChat group to communicate with us further.

**Comment by mykgspace** [comment]
Thank you for the answer!
