### ISSUE TITLE
bazel 4.2.2 is not compatible with Apple M1 on docker

### ISSUE THREAD

**Issue by zzzz-vincent** [opencurve/curve#2330]
**Describe the bug (描述bug)**
it seems that bazel	4.2.2 is not compatible with Apple M1 chip on docker. See log of running `cd curve && make build stor=bs dep=1` below:

cd /curve/thirdparties/etcdclient/tmp/gosrc/src/go.etcd.io/etcd && cp /curve/thirdparties/etcdclient/expose-session-for-election.patch . && patch -p1 < expose-session-for-election.patch
patching file clientv3/concurrency/election.go
cp etcdclient.go /curve/thirdparties/etcdclient/tmp/gosrc/src && cp objectManager.go /curve/thirdparties/etcdclient/tmp/gosrc/src
mv /curve/thirdparties/etcdclient/tmp/gosrc/src/go.etcd.io/etcd/vendor/google.golang.org /curve/thirdparties/etcdclient/tmp/gosrc/src/
mv /curve/thirdparties/etcdclient/tmp/gosrc/src/go.etcd.io/etcd/vendor/golang.org /curve/thirdparties/etcdclient/tmp/gosrc/src/
mv /curve/thirdparties/etcdclient/tmp/gosrc/src/go.etcd.io/etcd/vendor/github.com /curve/thirdparties/etcdclient/tmp/gosrc/src/
/curve/thirdparties/etcdclient/tmp/go/bin/go build -buildmode=c-shared -o libetcdclient.so /curve/thirdparties/etcdclient/tmp/gosrc/src/etcdclient.go /curve/thirdparties/etcdclient/tmp/gosrc/src/objectManager.go
make[1]: Leaving directory '/curve/thirdparties/etcdclient'
Opening zip "/proc/self/exe": lseek(): Bad file descriptor
FATAL: Failed to open '/proc/self/exe' as a zip file: (error: 9): Bad file descriptor

The issue may related to bazel on docker https://github.com/bazelbuild/bazel/pull/14391

**To Reproduce (复现方法)**
`cd curve && make build stor=bs dep=1` on Apple M1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: 13.0 (22A380)

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
We have no experience compiling on M1 chip, but why must compile on M1?

**Comment by zzzz-vincent** [comment]
not necessary. i was just trying to build dev env on my laptop per: https://github.com/opencurve/curve/blob/master/docs/en/build_and_run_en.md. If M1 is not compatible, it can be good to mention it there and redirect individual developers to other approaches, eg. aws and gcp.

**Comment by Cyber-SiKu** [comment]
Sorry, there is no support for the arm environment mentioned in the documentation/. Have you tried using buildx to emulate an x86 environment?

**Comment by zzzz-vincent** [comment]
No I didn't :( 
I then just used AWS EC2 instead.
