### ISSUE TITLE
[2023 Q2 Developer Activities]: Call For Participation！

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#2334]
### Contributions are welcomed! 

Since Curve's open source, it has received extensive attention from the industry. Contributions are welcomed! 

BTW, it's better to file a PR for every single function.

**For more details, please refer to our dev guideline.**

- https://ask.opencurve.io/t/topic/142

***

#### 1、Cloud native deployment (Languages: Go), mentor: @caoxianfei1 

| Func                    |   Issue   | Assigne         |    PR   | Progress|      
|-----------------|--------|--------------|-----|:----------|
|  Feature optimization | https://github.com/opencurve/curve-operator/issues/24 |  @anurnomeru| https://github.com/opencurve/curve-operator/pull/49 | Done |
|  Stand-alone deployment  | https://github.com/opencurve/curve-operator/issues/25 | @caoxianfei1  | https://github.com/opencurve/curve-operator/pull/52 | Done
|  Monitor deployment  | https://github.com/opencurve/curve-operator/issues/26 | @caoxianfei1  | https://github.com/opencurve/curve-operator/pull/64 | Done
|  $\color{#FF0000} Hard$ Disk discovery  | https://github.com/opencurve/curve-operator/issues/27  | @xzt1590  |  |
|  Code clean  | https://github.com/opencurve/curve-operator/issues/28  | @hezhizhen  | https://github.com/opencurve/curve-operator/pull/38 | Done |
|  $\color{#FF0000} Hard$ Update cluster  | https://github.com/opencurve/curve-operator/issues/29  |  |  |
|  Formating progress show  | https://github.com/opencurve/curve-operator/issues/30  |   |  |

#### 2、New tool support (Languages: Go), mentor: @Cyber-SiKu 

| Func                                      | Issue                | Assigne        | PR                                                     | Progress |
| ----------------------------------------- | -------------------- | -------------- | ------------------------------------------------------ | :------- |
| transfer-leader                           | opencurve/curve#2022 | @Xinlong-Chen  |  [2452](https://github.com/opencurve/curve/pull/2452)                                                      |     Done     |
| do-snapshot                               | opencurve/curve#2023 | @Xinlong-Chen  |  [2454](https://github.com/opencurve/curve/pull/2454)                                                      |    Done      |
| clean-recycle                             | opencurve/curve#2032 | @lng2020       | [2351]( https://github.com/opencurve/curve/pull/2351)  | Done     |
| chunkserver-list                          | opencurve/curve#2036 | @sindweller    | [2386]( https://github.com/opencurve/curve/pull/2386 ) |     Done     |
| $\color{#FF0000} Hard$ chunkserver-status | opencurve/curve#2344 | @TheR1sing3un  |                                                        |   Done       |
| client-status                             | opencurve/curve#2345 | @Xinlong-Chen  | [2446](https://github.com/opencurve/curve/pull/2446)   |   Done       |
| snapshot-clone-status                     | opencurve/curve#2346 | @Xinlong-Chen  | [2442](https://github.com/opencurve/curve/pull/2442)   |  Done       |
| $\color{#FF0000} Hard$ copysets-status    | opencurve/curve#2347 | @tobehardest   |                                                        |  Done        |
| do-snapshot-all                           | opencurve/curve#2352 | @iiiuwioajdks  |                                                        |          |
| $\color{#FF0000} Hard$ check-chunkserver  | opencurve/curve#2353 | @lng2020       |                                                        |          |
| $\color{#FF0000} Hard$ check-copyset      | opencurve/curve#2354 | @baytan0720    | [2435](https://github.com/opencurve/curve/pull/2434)   |   Done       |
| check-server                              | opencurve/curve#2355 | @pengpengSir   |    [2463](https://github.com/opencurve/curve/pull/2463)                                                    |          |
| list-may-broken-vol                       | opencurve/curve#2356 |      @baytan0720         | [2518](https://github.com/opencurve/curve/pull/2518) |     Done     |
| set-copyset-availflag                     | opencurve/curve#2357 | @baytan0720    | [2455](https://github.com/opencurve/curve/pull/2455)                                                      |    Done      |
| rapid-leader-schedule                     | opencurve/curve#2359 | @montaguelhz |      [](https://github.com/opencurve/curve/pull/2551)                                                   | Done          |
| set-scan-state                            | opencurve/curve#2360 |  @montaguelhz              |   [2465](https://github.com/opencurve/curve/pull/2465)                                                    |   Done       |
| scan-state                                | opencurve/curve#2361 |     @lianzhanbiao            |       [2481](https://github.com/opencurve/curve/pull/2481)                                                |     Done     |
| clean up code about peer/configs                                | opencurve/curve#2451 |                |                                                        |          |

#### 3、Modification of code logic (Languages: C++), mentor: @ilixiaocui @wuhongsong 

| Func                    |   Issue   | Assigne         |    PR   | Progress|      
|-----------------|--------|--------------|-----|:----------|
| [curve] optimize some metric style | opencurve/curve#2319 |  @Xinlong-Chen  | #2417 | Done |
| [build] Upgrade Image | opencurve/curve#2305| @DuckdanB |  |  |
| [curve] add libfmt to WORKSPACE |  opencurve/curve#2291 | @Tangruilin | #2367  |  |
| [monitor] Use tdengine as the data engine for promethues | opencurve/curve#2027 | @KeeProMise  | | | 
| [curvefs] Can metaserver's raft snapshot implementation be asynchronous|  opencurve/curve#1617 | @Ziy1-Tan  | | |
| [compile] Clean up warnings in code compilation | opencurve/curve#1264| @MizukiCry  | #2383 | Done |
| [curvefs] When the fs mount is mounted multiple times with different enableSumInDir switches, the xattr information recorded in the metadata will be inaccurate | #2094 | @bit-dance | #2491 | Done |
| [curvefs] cancel the warm-up task in the warm-up queue | #2019 | @Tom-CaoZH  | ||
| [curvefs] change the data organization format | #2380  | @201341 | #2420 | Done | 
| [curvefs] add qos for curve-fuse| #2225  |  @UniverseParticle | #2424 | Done| 
| [curvefs] make background curve-fuse metric correct | #2391 | | | |
| [curvebs] optimize curvebs rapid leader schedule | #2388 | @JadeFlute0127 | | |
| [curvebs] Add Tracing Feature for Curve | #2229 | @UniverseParticle | | |
| [ut]ut.sh run in build-debian9 | #2181 |  | | |
| [curvefs] UmountFs will cause deadlock | #2308  | @Xinlong-Chen | | |
| [curvefs] Async read need | #2070  |  @Ziy1-Tan  | #2421| Done |

#### 4、Perfection of Curveadm (Languages: Go), memtor: @Wine93 

| Func                    |   Issue   | Assigne         |    PR   | Progress|      
|-----------------|--------|--------------|-----|:----------|
| smarter core_pattern | opencurve/curveadm#178 | | | |
| incremental formatting | opencurve/curveadm#189 | | | |
| sharing database | opencurve/curveadm#206 | | | |
| service log | opencurve/curveadm#197 | @fengshunli | https://github.com/opencurve/curveadm/pull/230 | |
| map prompt | opencurve/curveadm#177 | @mfordjody  | https://github.com/opencurve/curveadm/pull/222 | |
| `replica` | opencurve/curveadm#146 | | | |
| support deploy minio-s3-gateway | opencurve/curveadm#218 | | | |

see also: [curveadm develop activities issue](https://github.com/opencurve/curveadm/issues?q=is%3Aissue+is%3Aopen+label%3A%22developer+activities%22)

**Comment by zhanghuidinah** [comment]
**Developer Activities Registration Steps:**

- Step 1: Select the issue you want to participate in and comment (up to three contestants may choose the same issue, but only one will be merged; the first merged PR wins)

- Step 2: Note [Issue ID + GitHub ID] and add the community assistant
![image](https://user-images.githubusercontent.com/31201589/231367673-d08a53fe-5b09-497f-9735-7ad777b96b71.png)


- Step 3: The community assistant will invite you to the Developer Activities Group, where online meetings will be held occasionally (as needed) to answer questions and provide assistance.

- Step 4: Submit the PR for the corresponding issue before June 3rd.


**开发者活动参赛流程**

- 第一步：选中想参与 issue 并 comment (同一个issue最多允许有三个参赛者选择，但最终只有一个合入；公平竞争，PR 先合入者先得～)

- 第二步：备注【Issue ID + GitHub ID】添加社区小助手
![image](https://user-images.githubusercontent.com/31201589/231367673-d08a53fe-5b09-497f-9735-7ad777b96b71.png)

- 第三步：社区小助手邀请至开发者活动群，群中会不定期(按需)线上会议，为大家答疑解惑。

- 第四步：在6月3日之前提交对应 issue 的 PR；

**Comment by mfordjody** [comment]
I would like to try https://github.com/opencurve/curveadm/issues/177

**Comment by caoxianfei1** [comment]
Close it because Q2 developer activitiy finished.
