### ISSUE TITLE
[curve/toos-v2]: add chunkserver-status

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2344]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs status chunkserver` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/status_tool.cpp#L919-L982
- The old command input and out put:
```bash
curve_ops_tool chunkserver-status
  
----------
output:
version: 45bcea49+release
chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: [])
```

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand dir to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by TheR1sing3un** [comment]
I would like to contribute to this issue, please assign it to me~

**Comment by ilixiaocui** [comment]
> I would like to contribute to this issue, please assign it to me~

Welcome!

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Cyber-SiKu** [comment]
@TheR1sing3un Are you still going on? Still have any difficulties?

**Comment by TheR1sing3un** [comment]
> @TheR1sing3un Are you still going on? Still have any difficulties?

Sorry, I've been a little busy these past few weeks, I will restart this issue next few days~

**Comment by Cyber-SiKu** [comment]
> > @TheR1sing3un Are you still going on? Still have any difficulties?
> 
> Sorry, I've been a little busy these past few weeks, I will restart this issue next few days~

ok

**Comment by Cyber-SiKu** [comment]
@TheR1sing3un Are you still going on? Still have any difficulties?

**Comment by caoxianfei1** [comment]
@TheR1sing3un This issue will be temporarily unassigned because you have no response, reassign to you if you want to continue.
