### ISSUE TITLE
[curve/toos-v2]: add copysets-status

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2347]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs status copyset` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/copyset_check.cpp#L170-L182
- The old command input and out put:
```bash
curve_ops_tool copysets-status

-------
output:
Copysets are healthy!
total copysets: ***, unhealthy copysets: ***, unhealthy_ratio: ***%
```
Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand clinet to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by tobehardest** [comment]
I'm a newbie, can I try this?

**Comment by Cyber-SiKu** [comment]
> I'm a newbie, can I try this?

yep

**Comment by Cyber-SiKu** [comment]
@tobehardest If you have any difficulties, you can contact me.

**Comment by tobehardest** [comment]
I don't see your contact information on your homepage. How should I ask you questions?

**Comment by Cyber-SiKu** [comment]
> I don't see your contact information on your homepage. How should I ask you questions?

email Cyber-SiKu@outlook.com

**Comment by Cyber-SiKu** [comment]
> I don't see your contact information on your homepage. How should I ask you questions?

or wechat bot:
![image](https://user-images.githubusercontent.com/15775037/230380515-d270296c-5907-4303-807c-f2609c9c4108.png)
We will create a group to connect with you

**Comment by Cyber-SiKu** [comment]
@tobehardest this should rely on [check-copyset](https://github.com/opencurve/curve/issues/2354), you can do this first.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**
