### ISSUE TITLE
[curve/toos-v2]: add chunk-location

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2350]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs query chunk` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/namespace_tool.cpp#L329-L362
- The old command input and out put:
```bash
curve_ops_tool chunk-location -fileName=/test

-------
output:
chunkId: ***, logicalPoolId: ***, copysetId: ***, groupId: ***
location: {***, ***, ***}
```
Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand clinet to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Cyber-SiKu** [comment]
https://github.com/opencurve/curve/pull/2397
