### ISSUE TITLE
[curve/toos-v2]: add rapid-leader-schedule

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2359]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs repair leader-schedule` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/schedule_tool.cpp#L99-L109
- The old command input and out put:
```bash
curve_ops_tool rapid-leader-schedule

-------
output:
RapidLeaderSchedule success
```
Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand clinet to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by JadeFlute0127** [comment]
This issue looks relatively simple, I want to try to complete it.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Cyber-SiKu** [comment]
@JadeFlute0127 Have you encountered any difficulties?

**Comment by DuckdanB** [comment]
I'd like to try this project

**Comment by wuhongsong** [comment]
> I'd like to try this project

for free to try it

**Comment by montaguelhz** [comment]
let me try it

**Comment by ilixiaocui** [comment]
> let me try it
Welcome!
