### ISSUE TITLE
curvebs安装完成后，服务器重启，chunkserver无法向mds注册成功

### ISSUE THREAD

**Issue by jiachengdong** [opencurve/curve#2364]
## General Question
1、环境
       一台ubuntu20.04机器，物理机和虚拟机都容易复现
2、部署步骤
      https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment
      部署单节点
3、复现方法
      部署完单节点后重启服务器，再curveadm start --role chunkserver 启动chunkserver，log显示向mds注册失败
4、log
chunkserver log
I 2023-03-31T16:24:32.652125+0800     6 chunkserver_metrics.cpp:288] Init chunkserver metric success.
I 2023-03-31T16:24:32.654438+0800     6 concurrent_apply.cpp:55] Init concurrent module's threads success
I 2023-03-31T16:24:32.654479+0800     6 ext4_filesystem_impl.cpp:79] Kernel version: 5.15.0-69-generic
I 2023-03-31T16:24:32.654491+0800     6 ext4_filesystem_impl.cpp:80] System version: #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023
I 2023-03-31T16:24:32.654497+0800     6 ext4_filesystem_impl.cpp:81] Machine: x86_64
I 2023-03-31T16:24:32.654539+0800     6 ext4_filesystem_impl.cpp:103] major: 5, minor: 15, revision: 0
I 2023-03-31T16:24:32.654773+0800     6 file_pool.cpp:458] scan dir/curvebs/chunkserver/data/chunkfilepool
I 2023-03-31T16:24:32.655380+0800     6 file_pool.cpp:464] list file pool dir done, size = 524
I 2023-03-31T16:24:32.663626+0800     6 file_pool.cpp:513] scan done, pool size = 524
I 2023-03-31T16:24:32.663707+0800     6 chunkserver.cpp:166] initialize to use chunkfilePool as walpool success.
W 2023-03-31T16:24:32.664378+0800     6 client_config.cpp:233] config no global.turnOffHealthCheck info, using default value 0
W 2023-03-31T16:24:32.664428+0800     6 client_config.cpp:240] config no closefd.timeout info, using default value 300
W 2023-03-31T16:24:32.664440+0800     6 client_config.cpp:247] config no closefd.timeInterval info, using default value 600
I 2023-03-31T16:24:32.666620+0800     6 mds_client.cpp:86] MDSClient init success, addresses: 192.168.27.129:6700 192.168.27.129:6701 192.168.27.129:6702
I 2023-03-31T16:24:32.666649+0800     6 libcurve_file.cpp:638] No need register to MDS
I 2023-03-31T16:24:32.666658+0800     6 s3_adapter.cpp:32] Loading s3 configurations
W 2023-03-31T16:24:32.673012+0800     6 ext4_filesystem_impl.cpp:286] pread returns zero.offset: 61, length: 4035
I 2023-03-31T16:24:32.673221+0800     6 chunkserver.cpp:829] Found persisted chunkserver data, skipping registration, chunkserver id: 3, token: xmbearkl
I 2023-03-31T16:24:32.673247+0800     6 register.cpp:73]  Registering to MDS 192.168.27.129:6700. internal ip: 192.168.27.129, port: 8200, enable external server: 0, external ip: 192.168.27.129
E 2023-03-31T16:25:57.855170+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:25:58.858054+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:25:59.860136+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:00.861909+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:01.865170+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:02.868075+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:03.871467+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:04.876408+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:05.879032+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:06.882054+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:07.885632+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:08.888353+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:09.890412+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:10.895574+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:11.899778+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:12.903024+0800     6 register.cpp:100] 192.168.27.129:8200 Fail to register to MDS 192.168.27.129:6700, cntl errorCode: 0, cntl error: , statusCode: -7, going to sleep and try again.
E 2023-03-31T16:26:13.904472+0800     6 register.cpp:118] 192.168.27.129:8200 Fail to register to MDS for 100 times.
F 2023-03-31T16:26:13.904711+0800     6 chunkserver.cpp:208] Failed to register to MDS.

mds log
E 2023-03-31T16:26:11.247807+0800    30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53878. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:11.898562+0800    30 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53882 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8200
chunkServerID: 3
token: "xmbearkl"
E 2023-03-31T16:26:11.898849+0800    30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53882. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:12.199347+0800    23 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53888 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8201
chunkServerID: 2
token: "syjzgfvr"
E 2023-03-31T16:26:12.199597+0800    23 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53888. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:12.252380+0800    30 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53892 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8202
chunkServerID: 1
token: "gtsnzylb"
E 2023-03-31T16:26:12.252625+0800    30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53892. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:12.901772+0800    24 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53894 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8200
chunkServerID: 3
token: "xmbearkl"
E 2023-03-31T16:26:12.902081+0800    24 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53894. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:13.203889+0800    30 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53900 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8201
chunkServerID: 2
token: "syjzgfvr"
E 2023-03-31T16:26:13.204133+0800    30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53900. [ChunkServerRegistResponse] statusCode: -7
I 2023-03-31T16:26:13.256189+0800    30 topology_service.cpp:41] Received request[log_id=0] from 192.168.27.129:53916 to 192.168.27.129:6700. [ChunkServerRegistRequest] diskType: "nvme"
diskPath: "local:///curvebs/chunkserver/data"
hostIp: "192.168.27.129"
port: 8202
chunkServerID: 1
token: "gtsnzylb"
E 2023-03-31T16:26:13.256340+0800    30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53916. [ChunkServerRegistResponse] statusCode: -7

5、yml配置
hosts.yaml
global:
  user: root
  ssh_port: 22
  private_key_file: /root/.ssh/id_rsa

hosts:
  - host: host129
    hostname: 192.168.27.129

format.yaml
     host:
  - host129
disk:
  - /dev/sdb:/data/chunkserver0:50
  - /dev/sdc:/data/chunkserver1:50
  - /dev/sdd:/data/chunkserver2:50
 topology.yaml 
kind: curvebs
global:
  container_image: opencurvedocker/curvebs:v1.2
  log_dir: ${home}/logs/${service_role}${service_host_sequence}
  data_dir: ${home}/data/${service_role}${service_host_sequence}
  variable:
    home: /tmp
    target: host129

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 2380${service_host_sequence}
    listen.client_port: 2379${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 670${service_host_sequence}
    listen.dummy_port: 770${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

chunkserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 820${service_host_sequence}  # 8200,8201,8202
    data_dir: /data/chunkserver${service_host_sequence}  # /data/chunkserver0, /data/chunksever1
    copysets: 100
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

snapshotclone_services:
  config:
    listen.ip: ${service_host}
    listen.port: 555${service_host_sequence}
    listen.dummy_port: 810${service_host_sequence}
    listen.proxy_port: 800${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

**Comment by wuhongsong** [comment]
mds failed to find peers` (E 2023-03-31T16:26:13.204133+0800 30 topology_service.cpp:50] Send response[log_id=0] from 192.168.27.129:6700 to 192.168.27.129:53900. [ChunkServerRegistResponse] statusCode: -7)`

**Comment by wuhongsong** [comment]
`curveadm status -v` output?

**Comment by Cyber-SiKu** [comment]
error code:

[const int kTopoErrCodeServerNotFound = -7;](https://github.com/opencurve/curve/blob/5e89a861764d68190d4a81f3746cc447cd014619/src/mds/common/mds_define.h#L83)

**Comment by jiachengdong** [comment]
> `curveadm status -v` output?

Get Service Status: [OK]  

cluster name      : curvebs
cluster kind      : curvebs
cluster mds addr  : 192.168.27.129:6700,192.168.27.129:6701,192.168.27.129:6702
cluster mds leader: 192.168.27.129:6702 / 16564627c3e9

Id            Role         Host     Replicas  Container Id  Status                           Ports        Log Dir                 Data Dir          
--            ----         ----     --------  ------------  ------                           -----        -------                 --------          
95eb3d71cee3  etcd         host129  1/1       40b7b8ecb413  Up 5 minutes                     23790,23800  /tmp/logs/etcd0         /tmp/data/etcd0   
a461b3306762  etcd         host129  1/1       87c26a84b2ba  Up 5 minutes                     23791,23801  /tmp/logs/etcd1         /tmp/data/etcd1   
834baa2cf89d  etcd         host129  1/1       e903771842a0  Up 5 minutes                     23792,23802  /tmp/logs/etcd2         /tmp/data/etcd2   
570fe2baf90f  mds          host129  1/1       3d5223ffe308  Up 5 minutes                     7700         /tmp/logs/mds0          /tmp/data/mds0    
347bf90e880b  mds          host129  1/1       9ab5352a2b61  Up 5 minutes                     7701         /tmp/logs/mds1          /tmp/data/mds1    
16564627c3e9  mds          host129  1/1       747e524f4020  Up 5 minutes                     6702,7702    /tmp/logs/mds2          /tmp/data/mds2    
84531f452c2a  chunkserver  host129  1/1       7a974a48b146  Exited (134) About a minute ago  -            /tmp/logs/chunkserver0  /data/chunkserver0
5469c02feabb  chunkserver  host129  1/1       149bd68f2ee1  Exited (134) About a minute ago  -            /tmp/logs/chunkserver1  /data/chunkserver1
25f0c31dd596  chunkserver  host129  1/1       0f643030b6b2  Exited (134) About a minute ago  -            /tmp/logs/chunkserver2  /data/chunkserver2

**Comment by jiachengdong** [comment]
> `curveadm status -v` output?

![image](https://user-images.githubusercontent.com/35023505/230916620-639eb712-51dc-4560-972d-dd862261d47e.png)

**Comment by caoxianfei1** [comment]
@wuhongsong 
![241680507284_ pic](https://user-images.githubusercontent.com/54139479/234743327-4859f56f-ea17-4ed0-9442-f0b9ffec9aa4.jpg)

![271680507485_ pic](https://user-images.githubusercontent.com/54139479/234743388-aea92fa8-07fe-4c8d-a73a-7635b58db931.jpg)

Should be the problem of improper operation, is still unable to locate.

**Comment by ilixiaocui** [comment]
@jiachengdong Is this problem solved?

**Comment by caoxianfei1** [comment]
close it because long time response

**Comment by caoxianfei1** [comment]
Close it because long time no response.
