### ISSUE TITLE
[curvefs/client] curvefs metric problem

### ISSUE THREAD

**Issue by h0hmj** [opencurve/curve#2391]
**Describe the bug (描述bug)**

if we run client curve-fuse background, then we cannot get correct read/write and other metric from bvar. metrics may be all zero.
if we run client foreground, then we can get correct read/write and other metric from bvar

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

background metrics should work correctly

**Versions (各种版本)**
all version

**Additional context/screenshots (更多上下文/截图)**

## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by lihuibng** [comment]
it seems wired

**Comment by PerseidMeteor** [comment]
is it worked out?

**Comment by h0hmj** [comment]
> is it worked out?

no, still unresolved

**Comment by h0hmj** [comment]
maybe we can backport brpc patches to fix this problem, @wuhongsong pls help attach the related patches

**Comment by h0hmj** [comment]
https://github.com/apache/brpc/pull/1863

**Comment by PerseidMeteor** [comment]
plz assign me, I want to take over this issue and fix it later

**Comment by caoxianfei1** [comment]
@PerseidMeteor how is going on?

**Comment by PerseidMeteor** [comment]
> @PerseidMeteor how is going on?

I'm sorry that I had some things in July and the progress was a little slow. I had applied it in curve summer coding camp and I will complete this task in August.

**Comment by PerseidMeteor** [comment]
At present, I am still solving this problem and it will take some time

**Comment by h0hmj** [comment]
@PerseidMeteor any progress?

**Comment by ysjyx7** [comment]
hello, I am very interested in cloud-native and storage systems. Can i try this?

**Comment by xzt1590** [comment]
hello, I am a graduate student of the University of Electronic Science and Technology of China. I have learned the course MIT6.824 and completed all the labs. Now I am working as an intern in the file storage team of Didi Chuxing. Can I try this issue?

**Comment by caoxianfei1** [comment]
@ysjyx7 any progress?

**Comment by h0hmj** [comment]
fixed by #2960
