### ISSUE TITLE
【C-Plan】基于Docker的编译与部署

### ISSUE THREAD

**Issue by liuyishi** [opencurve/curve#241]
## 一、编译

* 基于VM虚拟机的ubuntu系统在docker中进编译

* 1、从仓库中下载curvebuild、curveintegration两个镜像，分别对应与编译与部署

  ```
  docker pull opencurve/curvebuild:centos8
  docker pull opencurve/curveintegration:centos8
  ```

![image-20210128153536505](https://user-images.githubusercontent.com/17061194/106136960-01a4ae80-61a5-11eb-99e1-93304cba194b.png)

* 2、运行Curvebuild镜像，进入curve目录

  ```
  docker run -it opencurve/curvebuild:centos8 /bin/bash
  ```

* 3、[执行编译命令](https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md)

* 4、大概等待一个小时，结果如下

![image-20210128154226944](https://user-images.githubusercontent.com/17061194/106137101-34e73d80-61a5-11eb-9b63-82098618e68c.png)

##   二、部署

* 运行curveintegration镜像，加上--net=host命令使其能够访问互联网

  ```
  docker run --net=host --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules --privileged -it opencurve/curveintegration:centos8 /bin/bash
  ```

* [获取tar包并解压](https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md)

  ```
  wget https://github.com/opencurve/curve/releases/download/v{version}/curve_{version}.tar.gz
  wget https://github.com/opencurve/curve/releases/download/v{version}/nbd_{version}.tar.gz
  wget https://github.com/opencurve/curve/releases/download/v{version}/nebd_{version}.tar.gz
  tar zxvf curve_{version}.tar.gz
  tar zxvf nbd_{version}.tar.gz
  tar zxvf nebd_{version}.tar.gz
  ```

  (**部署过程很顺利，只是上面的v{version}开始使用的是最新v1.0.2-beta会出现unhealthy_copysets不为0, 后参考其它同学的部署经验改成v1.0.1-rc0之后问题解决**）

  
![image-20210128185217449](https://user-images.githubusercontent.com/17061194/106137135-43355980-61a5-11eb-84ff-46bd2ebd29e4.png)

* 集群启动结果

![image-20210128180819147](https://user-images.githubusercontent.com/17061194/106137184-534d3900-61a5-11eb-8d99-3dd02378196a.png)

* 安装Nebd服务和NBD包

  ```
  ansible-playbook -i client.ini deploy_nebd.yml
  ansible-playbook -i client.ini deploy_nbd.yml
  ansible-playbook -i client.ini deploy_curve_sdk.yml
  ```

* 创建CRUVE卷，可以查看到NBD0

![image-20210128175659566](https://user-images.githubusercontent.com/17061194/106137207-5ba57400-61a5-11eb-8017-890af2b8e389.png)

**Comment by ilixiaocui** [comment]
恭喜@liuyishi同学成功部署了curve！从结果上来看，已经部署成功。也感谢你的关注和参与！

部署过程中提到的使用v1.0.2-beta会出现unhealthy_copysets不为0, 这个日志文件是否还保留着呢？如果有的话是否可以贴下mds和chunkserver的错误日志？

接下来可以尝试下用fio在nbd0上跑跑测试感受一下，或者挂载成一个文件系统使用一下。然后看看还有什么感兴趣的任务的，继续加油吧。
