### ISSUE TITLE
curvefs ApplyQueue多线程apply raft log 执行顺序问题

### ISSUE THREAD

**Issue by liuzr0558** [opencurve/curve#2467]
ApplyQueue的[默认线程数是3](https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/conf/metaserver.conf#L135)
那ApplyQueue::TaskWorker::Work(),从std::queue< Task >中[取任务后](https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/src/metaserver/copyset/apply_queue.cpp#L129),
是怎么保证多线程Apply Log时,所有节点执行Task的顺序一样的? [Log放入ApplyQueue](https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/src/metaserver/copyset/copyset_node.cpp#L274)
多线程执行操作不会打乱Log的顺序吗?这个是在哪里保证Task的执行顺序的?

**Comment by ilixiaocui** [comment]
It is recommended to read the diagram in [this document](https://github.com/opencurve/curve/blob/master/docs/cn/CurveBS%E5%86%99%E6%97%B6%E5%BB%B6%E4%BC%98%E5%8C%96.md), first understand the relationship between on_apply and raft log in the code

**Comment by Xinlong-Chen** [comment]
Summary: according to a hash code about `partitionid` in function `Push`:

---

`Push` implement:
https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/src/metaserver/copyset/apply_queue.h#L56-L61

`Push` use in here. It's ought to be known that the function `HashCode` is a virtual function:
https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/src/metaserver/copyset/copyset_node.cpp#L270-L274

`HashCode` define in here:
https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/src/metaserver/copyset/meta_operator.cpp#L406-L427

Auto generation by portobuf:
https://github.com/opencurve/curve/blob/8a2d5d086e8dfd572be924790b01187d4660f2d6/curvefs/proto/metaserver.proto#L54-L64

**Comment by liuzr0558** [comment]
不好意思,没有仔细看代码,我以为ApplyQueue的work_count是控制每个TaskQueue有三个worker线程.
实际上每个TaskQueue只有1个worker线程,同一个partition的操作都是串行的.
ApplyQueue的work_count实际上是[控制TaskQueue的个数的](https://github.com/opencurve/curve/blob/c67b7eacf5dcd1bb37bce1c85eb761ec746cf62d/curvefs/src/metaserver/copyset/apply_queue.h#L58).
