### ISSUE TITLE
出现410008错误代码，可能该版本curveadm有逻辑问题

### ISSUE THREAD

**Issue by DuckdanB** [opencurve/curve#2483]
我触发这个bug的情况是：
1：我新建了一个集群：curveadm cluster add my-cluster -f topology.yaml
2：切换集群：curveadm cluster checkout my-cluster
3：预检测：curveadm precheck，在check network Firewall的时候出现error
 
4：随即执行了curveadm status，连续几次都是该错误代码
 
5：执行了curveadm deploy -k后，在Start Service处出现了error（很奇怪的是第一个error了后两个没有error，我之前也是第一次curveadm deploy -k的时候有两个没有error，再之后执行curveadm deploy -k后，在Start Service处三个都是error），再此之后执行curveadm status指令能够获取正常的数据
[](url)
[触发bug流程.pdf](https://github.com/opencurve/curve/files/11494345/bug.pdf)

**Comment by caoxianfei1** [comment]
If the firewall detection fails during the pre-check, there should be a problem with the configuration of the Alibaba Cloud server. You can open the corresponding security group and use tools such as `ufw` to check.

**Comment by caoxianfei1** [comment]
close it because long time no response.
