### ISSUE TITLE
[CurveFS] Need to clean up resources when partition persistence fails 

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#2484]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

When the partition is successfully created on the metaserver, but fails to persist in the topology, we should go to the metaserver to delete the partition

https://github.com/opencurve/curve/blob/b235bd5b4a00d8577ebc096f97b539be15c1e7a1/curvefs/src/mds/topology/topology_manager.cpp#L679

**Describe the solution you'd like (描述你期望的解决方法)**

It is recommended to call the following interface on the metaserver side to clean up, and add corresponding unit tests.
https://github.com/opencurve/curve/blob/b235bd5b4a00d8577ebc096f97b539be15c1e7a1/curvefs/proto/metaserver.proto#L506

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by yanchaomei** [comment]
I'm excited about this idea and eager to give it a try. Could you please guide me on where to begin?

**Comment by ilixiaocui** [comment]
> I'm excited about this idea and eager to give it a try. Could you please guide me on where to begin?

What kind of guidance do you need? How is the project compiled? Or how to run unit tests? or something else?

**Comment by ilixiaocui** [comment]
> I have a question: How can we determine that a partition has not been persisted in the topology?

In the above scenario, the partition on the metaserver is created, but the persistence in etcd fails, so the partition on the metaserver needs to be cleaned up.

Of course, if etcd is broken, it cannot provide query, addition, deletion, and modification operations, and it is really impossible to judge whether it has been persisted at present.At this time, if the partition on the mtaserver is cleared, but it is recorded in the database, data inconsistency will occur.

Perhaps this function can be done in heartbeat? The metaserver reports the partition list, if there is no record in etcd, it will be cleared. It seems more reasonable.

**Comment by yanchaomei** [comment]
> > I have a question: How can we determine that a partition has not been persisted in the topology?
> 
> In the above scenario, the partition on the metaserver is created, but the persistence in etcd fails, so the partition on the metaserver needs to be cleaned up.
> 
> Of course, if etcd is broken, it cannot provide query, addition, deletion, and modification operations, and it is really impossible to judge whether it has been persisted at present.At this time, if the partition on the mtaserver is cleared, but it is recorded in the database, data inconsistency will occur.
> 
> Perhaps this function can be done in heartbeat? The metaserver reports the partition list, if there is no record in etcd, it will be cleared. It seems more reasonable.

I think do this fuction in heartbeat is reasonable, I really want to try to solve this issue. Could you assign this issue to me?

**Comment by ilixiaocui** [comment]
> > > I have a question: How can we determine that a partition has not been persisted in the topology?
> > 
> > 
> > In the above scenario, the partition on the metaserver is created, but the persistence in etcd fails, so the partition on the metaserver needs to be cleaned up.
> > Of course, if etcd is broken, it cannot provide query, addition, deletion, and modification operations, and it is really impossible to judge whether it has been persisted at present.At this time, if the partition on the mtaserver is cleared, but it is recorded in the database, data inconsistency will occur.
> > Perhaps this function can be done in heartbeat? The metaserver reports the partition list, if there is no record in etcd, it will be cleared. It seems more reasonable.
> 
> I think do this fuction in heartbeat is reasonable, I really want to try to solve this issue. Could you assign this issue to me?

Welcome!

**Comment by ilixiaocui** [comment]
This issue was selected for [GLCC](https://www.gitlink.org.cn/glcc/2023/subjects/detail/731), interested students can sign up. Please pay attention to the registration time [6.4-6.21](https://www.gitlink.org.cn/glcc/2023.)

**Comment by ilixiaocui** [comment]
@yanchaomei If you are still interested in this issue, welcome to register on [GLCC](https://www.gitlink.org.cn/glcc/2023.)

**Comment by ilixiaocui** [comment]
> > > I have a question: How can we determine that a partition has not been persisted in the topology?
> > 
> > 
> > In the above scenario, the partition on the metaserver is created, but the persistence in etcd fails, so the partition on the metaserver needs to be cleaned up.
> > Of course, if etcd is broken, it cannot provide query, addition, deletion, and modification operations, and it is really impossible to judge whether it has been persisted at present.At this time, if the partition on the mtaserver is cleared, but it is recorded in the database, data inconsistency will occur.
> > Perhaps this function can be done in heartbeat? The metaserver reports the partition list, if there is no record in etcd, it will be cleared. It seems more reasonable.
> 
> Hello, I would like to ask whether this Task needs to re-implement a heartbeat or use the original heartbeat of curve to judge the status of etcd

original heartbeat of curve is enough.

heartbeat of curve will report partition information of echo copyset. MDS just judge if these partition record in etcd, if not, isue a delete command.

**Comment by ilixiaocui** [comment]
> ![image](https://user-images.githubusercontent.com/58766816/243634343-85c29e17-673e-47d0-8264-728fcc115180.png) So just need to call `DeletePartition` to delete this partition?

When metaserver recieve hearbeat `delete command`, delete local.

**Comment by yanchaomei** [comment]
> @yanchaomei If you are still interested in this issue, welcome to register on [GLCC](https://www.gitlink.org.cn/glcc/2023.)

Okay, I have recently developed some ideas and developed some code for this issue. May I ask if it is convenient to send you my proposal via email?

**Comment by ilixiaocui** [comment]
> > @yanchaomei If you are still interested in this issue, welcome to register on [GLCC](https://www.gitlink.org.cn/glcc/2023.)
> 
> Okay, I have recently developed some ideas and developed some code for this issue. May I ask if it is convenient to send you my proposal via email?

Welcome to communicate！

**Comment by caoxianfei1** [comment]
Close the issue because the releated pr #2537 has fixed and merged.
