### ISSUE TITLE
[CurveBS] cannot show the version of curvebs-mds and curvebs-chunkserver

### ISSUE THREAD

**Issue by chengyu-l** [opencurve/curve#2494]
**Describe the bug (描述bug)**

在 opencurvedocker/curvebs:v1.2 Docker镜像运行的容器中，curvebs-mds curvebs-chunkserver 无法通过 -version 参数查看版本信息

**To Reproduce (复现方法)**
not sure

**Expected behavior (期望行为)**
输出二进制文件的版本信息

**Versions (各种版本)**
docker 镜像：opencurvedocker/curvebs:v1.2。

**Additional context/screenshots (更多上下文/截图)**

<img width="1014" alt="image" src="https://github.com/opencurve/curve/assets/21003538/cc7cf8c2-f693-45ee-a27c-4ac8ffa69484">

**Comment by caoxianfei1** [comment]
you can use curve tool to check version, for your image you can use `curve_ops_tool version`.

**Comment by caoxianfei1** [comment]
Close it temporary adn someone can reopen it later.
