### ISSUE TITLE
Set the UA of Aws::S3::S3Client as a configurable item 

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2499]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Some users restrict the useragent for security reasons, please set Aws::S3::S3Client as a configurable option.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

![image](https://github.com/opencurve/curve/assets/15775037/4af47455-44ef-4160-8862-e10c7d8544ee)

**Comment by Ziy1-Tan** [comment]
Hey, @Cyber-SiKu!  Just make item `userAgent` configurable?

**Comment by Cyber-SiKu** [comment]
> Hey, @Cyber-SiKu! Just make item `userAgent` configurable?

yep

**Comment by wuhongsong** [comment]
@Ziy1-Tan  will do it later, It's a bit busy these days.

**Comment by caoxianfei1** [comment]
Close the issue because the pr #2501  has been merged.
