### ISSUE TITLE
bug when check the progress of warmup

### ISSUE THREAD

**Issue by zjuzxy1995** [opencurve/curve#2504]
![image](https://github.com/opencurve/curve/assets/35260342/95498f51-7fde-4621-bb6f-4a2b3020d654)

**Comment by GOVINDBALAJI** [comment]
Verify that the file system you're using supports the operations you're attempting.Ensure that you have the necessary permissions to perform the operations.Double-check the syntax and arguments of the warmup query commands to make sure they are correct.Check if there are any updates or patches available for the "curvefs" file system or the warmup tool you are using. 


If you want the code please provide me some details

The name and version of the warmup tool you're using.

The type and version of the file system you're working with (e.g., curvefs).

The exact warmup query command you're trying to run, along with its arguments and options. 

Happy to assist you

**Comment by zjuzxy1995** [comment]
您好，您发的邮件我已经收到，我会尽快阅读。

**Comment by caoxianfei1** [comment]
Close it temporary and someone can reopen it later.

**Comment by zjuzxy1995** [comment]
您好，您发的邮件我已经收到，我会尽快阅读。
