### ISSUE TITLE
【C-Plan】编译与部署

### ISSUE THREAD

**Issue by IxaRyo** [opencurve/curve#251]
**编译及部署初体验**

本issue为C-Plan的必选任务，包含部署及编译。
本文先介绍遇到的问题，然后为成功的截图。

使用 opencurve/curveintegration:centos8 挂载与编译

**部署成功**

![image](https://user-images.githubusercontent.com/18397480/106602163-94738d80-6597-11eb-8899-bc7d3364c2fe.png)

![image](https://user-images.githubusercontent.com/18397480/106605984-896f2c00-659c-11eb-80ea-74f7965450f6.png)

遇到情况：

1）
 map的时候提示打不开镜像 nebd-server进程一直占用CPU高达25% (刚好4核之1核)，根据日志知道/data下面没有nebd目录，为什么会没有暂不清楚，用build目录下stop再start 没有办法解决，后来删除nebd日志并且执行 deploy_nebd.yml 可以启动。

I 2021-02-02T12:22:54.056986+0000 2000722 source_reader.cpp:59] SourceReader fdCloseThread run successfully
I 2021-02-02T12:22:54.056990+0000 2000722 nebd_server.cpp:60] NebdServer init curveRequestExecutor ok
W 2021-02-02T12:22:54.056999+0000 2000722 metafile_manager.cpp:142] File not exist: /data/nebd/nebdserver.meta
I 2021-02-02T12:22:54.057001+0000 2000722 metafile_manager.cpp:48] Init metafilemanager success.
I 2021-02-02T12:22:54.057020+0000 2000722 file_manager.cpp:84] Load file record finished.
I 2021-02-02T12:22:54.057021+0000 2000722 nebd_server.cpp:67] NebdServer init fileManager ok
I 2021-02-02T12:22:54.057047+0000 2000722 heartbeat_manager.cpp:42] Run heartbeat manager success.
I 2021-02-02T12:22:54.057049+0000 2000722 nebd_server.cpp:74] NebdServer init heartbeatManager ok
I 2021-02-02T12:22:54.057051+0000 2000722 nebd_server.cpp:76] NebdServer init ok
I 2021-02-02T12:22:54.057052+0000 2000722 nebd_server.cpp:78] nebd version: 9.9.9+984a60e7
E 2021-02-02T12:22:54.057240+0000 2000722 file_lock.cpp:38] open file failed, error = No such file or directory, filename = /data/nebd/nebd.sock.lock
E 2021-02-02T12:22:54.057245+0000 2000722 nebd_server.cpp:235] Address already in use
I 2021-02-02T12:22:54.057246+0000 2000722 file_manager.cpp:57] Stop file manager success.
I 2021-02-02T12:22:54.057404+0000 2000722 heartbeat_manager.cpp:48] Stopping heartbeat manager...
I 2021-02-02T12:22:54.057443+0000 2000722 heartbeat_manager.cpp:52] Stop heartbeat manager success.

2）curve_ops_tool delete -fileName=/test1 -userName=curve -forcedelete=true 无法删除卷 
       解决办法： -forcedelete=true 去掉，再进入recyclebin删除。为什么删除recyclebin下的文件userName为curve的时候失败，而改成root成功？

**Comment by aspirer** [comment]
部署过程完成的很好，遇到的相关问题我们已经记录，如果有兴趣也可以自己尝试修复。

**Comment by bai-charisu** [comment]
你好，遇到的问题2无法删除卷的原因我这边解释一下。第一个问题，Curve设计是不允许forcedelete recyclebin目录以外的目录下的文件的。第二个问题，recyclebin目录是属于root用户的，curve用户没有权限修改root用户的目录。你可以认为清空recyclebin是管理员操作，普通用户不会去执行的。

**Comment by wu-hanqing** [comment]
你还，第一个问题在没有复现出来，目前也没看到哪里有问题。能不能把你的本地环境清空，然后尝试复现一下。
如果复现出来，用`gcore ${nebd-server-pid}`生成一个core文件，同时把`/usr/bin/nebd-server`这两个文件通过附件上传一下。
