### ISSUE TITLE
after use curvebs for the backend of curvefs，a unified name needed 

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2514]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Regardless of whether the backend is s3, or bs, we now use a unified cache layer(https://github.com/opencurve/curve/tree/fs_curvebs_storage_support) ,so we need a  unified name, 

for example: S3ChunkInfo maybe replaced by ChunkInfo(or other name)

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by infdahai** [comment]
Let me have a try.

**Comment by wuhongsong** [comment]
> Let me have a try.

yeap, lets do it.

**Comment by Cyber-SiKu** [comment]
@infdahai Have you encountered any difficulties?

**Comment by infdahai** [comment]
@Cyber-SiKu I will propose a draft pr in these few days.

**Comment by caoxianfei1** [comment]
> @Cyber-SiKu I will propose a draft pr in these few days.

ok
