### ISSUE TITLE
CurveFS consider merging associated operations on dentry and parentInode

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#2548]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

The dentry and parenInode is on the same partition, The associated operations on dentry and parentInode maybe can merge. For example, when create dentry need update parentInode's time and other attrs. Now It is now implemented through multiple rpc. 

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
work for it now

**Comment by caoxianfei1** [comment]
Close it because the related pr https://github.com/opencurve/curve/pull/2744 has merged.
