### ISSUE TITLE
【C-Plan】编译和部署

### ISSUE THREAD

**Issue by sshpark** [opencurve/curve#256]
# 环境
* 云服务器：CPU: 1核 内存: 2GB
* OS：CentOS 8

使用非 **docker** 方式进行部署，**curve** 版本是 **1.0.2-rc0**

# 问题及解决方案
## 问题
1. 下载 **etcd-client** 时多次连接超时
2. 启动 `./chunkserver_ctl.sh start all` 失败
3. 权限问题
4. 执行 **ansible** 任务报错
    ```
    fatal: [localhost]: FAILED! => {
    "assertion": "ansible_kernel|version_compare('3.15', '>=')", 
    "changed": false, 
    "evaluated_to": false
    }
    ```
## 解决方案
* 其中问题 **1, 2** 参照 #245 的解决方案；
* 问题 **3** 加上 `sudo`；
* 问题 **4** 升级centos系统内核，然后重启系统，最后安装的系统内核为 **4.18.0-240.10.1.el8_3.x86_64**。

# 部署结果
集群状态
<img width="936" alt="截屏2021-02-04 下午12 36 29" src="https://user-images.githubusercontent.com/20206158/106845379-cabf2300-66e5-11eb-9ab2-17bb80bbc228.png">

创建 CURVE 卷，并通过 NBD 挂载到本地
<img width="629" alt="截屏2021-02-04 下午12 45 05" src="https://user-images.githubusercontent.com/20206158/106845882-d19a6580-66e6-11eb-9c7e-cbba40e3b03d.png">

**Comment by aspirer** [comment]
赞，没有用docker也顺利完成了部署任务。可以开始下一阶段的任务了。

**Comment by bai-charisu** [comment]
你好，问题3权限问题可以再具体说明一下吗？

**Comment by sshpark** [comment]
> 你好，问题3权限问题可以再具体说明一下吗？

您好，具体问题是：在 curve 用户下执行 ansible-playbook 去安装 Nebd 服务和 NBD 包时，错误信息显示部分目录 `Permission denied` 。

**Comment by bai-charisu** [comment]
是ansible-playbook这个命令报错吗？安装ansible的时候是使用什么方式的？

**Comment by sshpark** [comment]
> 是ansible-playbook这个命令报错吗？安装ansible的时候是使用什么方式的？

是的，`ansible-playbook -i client.ini deploy_nbd.yml` 的时候提示权限不足，安装 ansible 是按照文档步骤来的，安装的版本是推荐的 2.5.9 。
