### ISSUE TITLE
【CI】Use github action to do some static checks and code security tests on the code in the curve warehouse

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2570]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Use github action to do some static checks and code security tests on the code in the curve warehouse

**Describe the solution you'd like (描述你期望的解决方法)**
Add gitlab actions configuration and use ubuntu system to do some simple tests

1. Use the resources in github actions to check the overall code cpplint\cppcheck
2. Use acitons to compile a small amount of code and run tests
3. Some other lightweight tests
**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by czm23333** [comment]
I want to try this

**Comment by wuhongsong** [comment]
> I want to try this

welcome, and you can apply for the subject in: https://summercoding-curve.app.codewave.163.com/apply
