### ISSUE TITLE
[tools-v2]:add bs delete volume snapshot

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2578]
## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

- The implementation of the old tool is here：
https://github.com/opencurve/curve/blob/44949da50bacd046e2143448fb524ca1dece908b/tools/snaptool/snaptool.py#L20-L21

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
working for it now

**Comment by ZackSoul** [comment]
I want to assign this issue

**Comment by ZackSoul** [comment]
I'm from Beihang university, majoring in software engineering, commonly used languages are go and java, interested in the distributed field, I've been working on issues related to this before, so I'd like to apply this

**Comment by lng2020** [comment]
Sorry for not being able to finish it. Anyone interested in this issue is welcomed.

**Comment by reeered** [comment]
Interested in this issue.

**Comment by reeered** [comment]
I am a junior student at Wuhan University of Technology, majoring in Software Engineering. I have proficiency in languages such as Golang, C, Python, and have experience in cloud-native and backend development. At the same time, I am interested in distributed file system, too. And I wish I can work for this issue, please assign it to me.

**Comment by caoxianfei1** [comment]
Under review.

**Comment by caoxianfei1** [comment]
see https://github.com/opencurve/curve/pull/2889

**Comment by caoxianfei1** [comment]
Close this issue because someone has already submitted a PR and it has been completed.
