### ISSUE TITLE
[tools-v2]:add bs delete volume clone

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2581]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

https://github.com/opencurve/curve/blob/44949da50bacd046e2143448fb524ca1dece908b/tools/snaptool/snaptool.py#L26-L27

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by setcy** [comment]
Hello, I want to apply for this issue because it's very similiar with issue #2580
