### ISSUE TITLE
[tools-v2]:add bs query volume clone-recover

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2584]
## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

https://github.com/opencurve/curve/blob/44949da50bacd046e2143448fb524ca1dece908b/tools/snaptool/snaptool.py#L32-L33

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by 374954417** [comment]
assign me this issue please

**Comment by Subzeroo7** [comment]
> assign me this issue please

fighting!!!

**Comment by baytan0720** [comment]
@374954417 How is the progress?

**Comment by zzzzzfj** [comment]
Hello, I am a second-year master student at USTC. My major is Software Engineering. I have interned ByteDance as a backend developer.
I am familiar with programming languages such as Golang and C++, and interested in technology fields such as distributed systems and storage systems. 
As a experienced developers, I think I can solve it. Please assign it to me.

**Comment by youarefree123** [comment]
Hello, I am a postgraduate student at Nanjing University of Information Science and Technology，commonly used languages are C++ and Go.  I have learned the course MIT6.82.  Can I try this issue?

**Comment by baytan0720** [comment]
@youarefree123 sorry, this issue was done.
