### ISSUE TITLE
[tools-v2]:add bs update volume flatten

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2587]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs update volume flatten` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

**Describe the solution you'd like (描述你期望的解决方法)**

- The implementation of the old tool is here：
https://github.com/opencurve/curve/blob/44949da50bacd046e2143448fb524ca1dece908b/tools/snaptool/snaptool.py#L40-L41

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by baytan0720** [comment]
I applied for this topic in Summer Code Camp, and I will do it.
