### ISSUE TITLE
The curveadm template variable misspelling and not exist

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#2591]
**Describe the bug (描述bug)**
![截屏2023-06-29 15 05 12](https://github.com/opencurve/curve/assets/13496900/fe307a6c-597b-4828-bd2d-e2576e8550ce)

![截屏2023-06-29 15 08 36](https://github.com/opencurve/curve/assets/13496900/45a2b081-4fef-470b-bd49-cadaf410a5c9)

‘cluster_snapshot_addr‘ maybe 'cluster_snapshotclone_addr'?

'cluster_snapshotclone_addr' not exist in curvedm.

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
@SeanHai The problem because tools-v2 config yaml file.

**Comment by SeanHai** [comment]
> @SeanHai The problem because tools-v2 config yaml file.

Have this problem fixed?

**Comment by caoxianfei1** [comment]
> > @SeanHai The problem because tools-v2 config yaml file.
> 
> Have this problem fixed?

Fixed.
