### ISSUE TITLE
Change the confusing configuration name

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2597]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Change the confusing configuration name: s3.enableDeleteObjects

what enableDeleteObjects means in curve now? 
whether support batch delete objects or not. so if enableDeleteObjects is false, we can delete objs any way.

His literal meaning is can not be deleted, so it will mislead people.

`int S3ClientAdaptorImpl::Delete(const Inode &inode) {
    if (enableDeleteObjects_) {
        return DeleteInodeByDeleteBatchChunk(inode);
    } else {
        return DeleteInodeByDeleteSingleChunk(inode);
    }
}`

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Jason011125** [comment]
Could you please specify which file s3.enableDeleteObjects is located as I couldn't find it in the s3.conf file. Thanks a lot!

**Comment by wuhongsong** [comment]
> Could you please specify which file s3.enableDeleteObjects is located as I couldn't find it in the s3.conf file. Thanks a lot!
metaserver.cpp

**Comment by wuhongsong** [comment]
https://github.com/opencurve/curve/issues/2597
