### ISSUE TITLE
【C-Plan-选题二】代码翻译

### ISSUE THREAD

**Issue by YechenGu** [opencurve/curve#260]
对以下板块的注释进行中文到英文的翻译
- curve/src/chunkserver

**Comment by Wine93** [comment]
Hi, i think it's a valuable issue, you can reopen the PR, we will review it. @YechenGu

**Comment by YechenGu** [comment]
> Hi, i think it's a valuable issue, you can reopen the PR, we will review it. @YechenGu

fine
