### ISSUE TITLE
Stuck when unmounting a volume

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2601]
**Describe the bug (描述bug)**

Stuck when unmounting a volume
![b44b65b18b0188f41241a5a65bb04d0b](https://github.com/opencurve/curve/assets/67582932/30526725-3b1e-468c-85d5-859c72430f7d)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
Close it temporary. Everyone can reopen it if encounter the problem again.
