### ISSUE TITLE
 sometimes fails when mounting filesystems

### ISSUE THREAD

**Issue by chentaotao-mater** [opencurve/curve#2609]
## General Question
1.部署curvefs客户端的时候，mds正常，curvefs集群也正常，但是在做挂载的时候一直报连接mds超时的情况
fs服务端集群正常，mds正常
<img width="440" alt="a603a4ae1c3ab6af559d42baea9e248" src="https://github.com/opencurve/curve/assets/78401379/48e3911d-0094-4170-a2ca-88cedbec32cd">
但是一直报连接mds超时
<img width="831" alt="b7e258718a602b16c9a39dc338178a7" src="https://github.com/opencurve/curve/assets/78401379/2b381e00-9580-45a4-a0c3-7f8ce8ab1fc7">
试过很多次，一直报超时。
后面将client.yaml的s3服务的s3.endpoint配置改成去掉http
这时候容器报fs已经存在
<img width="505" alt="dc9e9174975437f9d9ed51fa7c03618" src="https://github.com/opencurve/curve/assets/78401379/2e5f0ed4-223c-43e5-a9b4-6a9e9024c4c3">
进到主mds查看fs卷创建情况，发现虽然报超时，但是test2和test3已经创建好了，test还没创建好
<img width="829" alt="e25e9e59d735f9e416b69d4650f5e58" src="https://github.com/opencurve/curve/assets/78401379/23e0e02a-9078-4d79-a605-b8579c16da7a">
所以我就用去掉http的创建test，发现test的fs一次性就创建好，这会就有点怀疑是不是http导致的超时问题
<img width="829" alt="42f1a60853f1e3aaa37b4c61d60d561" src="https://github.com/opencurve/curve/assets/78401379/5fdd4e6a-69a0-4435-a516-f430f79bedf5">
但是又将client.yaml增加了http://，创建了test-new的fs，发现一次性创建成功。
<img width="335" alt="beaf1dac2a20dae01cc714fb4c73038" src="https://github.com/opencurve/curve/assets/78401379/e531b64f-e629-4dba-95d3-c1b3b667f3fa">
服务和minio的之间网络排查也是一直正常。
<img width="598" alt="de33229895dbe077424bdf062a22622" src="https://github.com/opencurve/curve/assets/78401379/f3fd659c-a067-4acc-b489-9592ee134977">
所以s3的info配置http://加上以后，就出现了一会好一会不好的情况，有待深究。

最后所有客户端的/etc/hosts增加了127.0.0.1  主机名，重新挂载，卷挂在正常了
![image](https://github.com/opencurve/curve/assets/78401379/cf8f3ffb-da46-436f-9701-76e729cf5daf)

**Comment by caoxianfei1** [comment]
@chentaotao-mater the probelm is solved?

**Comment by caoxianfei1** [comment]
Close it first and reopen it if someone meet the problem.
