### ISSUE TITLE
Adaptor OpenEuler

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2612]
openEuler is a reliable open source OS that unleashes diversified computing power for a sustainable future.

mentor:
@wangxiyuan from openEuler 
@Cyber-SiKu from Curve

[pandoc adpator OpenEuler](https://summer-ospp.ac.cn/org/prodetail/23b970472?list=org&navpage=org)

**Comment by peter5232** [comment]
您好，我在迁移curve到openeuer上，目前遇到的一个bug是curve中使用的brpc的版本较低，导致报错，对应的brpc的报错为https://github.com/apache/brpc/issues/1693
问题：请问使用这个版本的brpc和patch是有原因的吗，还是因为我这边系统软件版本的问题呢？
环境：
```
[root@MiWiFi-R3-srv curve]# uname -a
Linux MiWiFi-R3-srv 5.10.0-153.12.0.92.oe2203sp2.x86_64 #1 SMP Wed Jun 28 23:04:48 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@MiWiFi-R3-srv curve]# gcc --version
gcc (GCC) 10.3.1
Copyright © 2020 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。
[root@MiWiFi-R3-srv curve]# g++ --version
g++ (GCC) 10.3.1
Copyright © 2020 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。
[root@MiWiFi-R3-srv curve]# bazel --version
bazel 4.2.2

系统：virtualBox 虚拟机 + https://mirrors.nju.edu.cn/openeuler/openEuler-22.03-LTS-SP2/ISO/x86_64/openEuler-22.03-LTS-SP2-x86_64-dvd.iso



```

**Comment by Cyber-SiKu** [comment]
> 您好，我在迁移curve到openeuer上，目前遇到的一个bug是curve中使用的brpc的版本较低，导致报错，对应的brpc的报错为[apache/brpc#1693](https://github.com/apache/brpc/issues/1693) ，对应的PR已经解决了这个bug [apache/brpc#1783](https://github.com/apache/brpc/pull/1783) 问题：请问使用这个版本的brpc和patch是有原因的吗，还是因为我这边系统软件版本的问题呢？ 环境：
> 
> ```
> [root@MiWiFi-R3-srv curve]# uname -a
> Linux MiWiFi-R3-srv 5.10.0-153.12.0.92.oe2203sp2.x86_64 #1 SMP Wed Jun 28 23:04:48 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
> [root@MiWiFi-R3-srv curve]# gcc --version
> gcc (GCC) 10.3.1
> Copyright © 2020 Free Software Foundation, Inc.
> 本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
> 包括没有适销性和某一专用目的下的适用性担保。
> [root@MiWiFi-R3-srv curve]# g++ --version
> g++ (GCC) 10.3.1
> Copyright © 2020 Free Software Foundation, Inc.
> 本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
> 包括没有适销性和某一专用目的下的适用性担保。
> [root@MiWiFi-R3-srv curve]# bazel --version
> bazel 4.2.2
> 
> 系统：virtualBox 虚拟机 + https://mirrors.nju.edu.cn/openeuler/openEuler-22.03-LTS-SP2/ISO/x86_64/openEuler-22.03-LTS-SP2-x86_64-dvd.iso
> ```

Hello, first of all thank you for your contribution to the curve community! This patch curve should already be marked:
https://github.com/opencurve/curve/blob/402f237bdbae091fbcb998cb7ef66eb1520be6e4/thirdparties/brpc/brpc.patch#L131

How did you compile it?

**Comment by peter5232** [comment]
执行make的命令不会编译他吗，是需要手动编译吗

**Comment by Cyber-SiKu** [comment]
@peter5232

**Comment by Cyber-SiKu** [comment]
> bazel不会执行patch操作吗

will done if add in build.
you can add wechat
https://github.com/opencurve/curve/blob/master/docs/images/curve-wechat.jpeg

**Comment by peter5232** [comment]
我并没有修改源代码，WORKSPACE中确实是有这个patch，但是仍然编译报这个错误

**Comment by peter5232** [comment]
你好，我想问下适配系统的评价标准是什么呢? 系统编译正常&test case全部通过吗？

**Comment by Cyber-SiKu** [comment]
> 我并没有修改源代码，WORKSPACE中确实是有这个patch，但是仍然编译报这个错误

I am [upgrading the base image to debian11](https://github.com/opencurve/curve/pull/2629), which is 10.2.1 and this problem has not been reported. So I'm wondering how you compiled it.

**Comment by wuhongsong** [comment]
> 我并没有修改源代码，WORKSPACE中确实是有这个patch，但是仍然编译报这个错误
您好，适配openEuler这个是curve社区和openEuler社区联合做的，最终的目的如下所示：期望能在aarch64，x86_64等架构下编译完成，并运行起来
![image](https://github.com/opencurve/curve/assets/13897133/36818ae1-5e36-4f19-8bc7-7befe83e5613)
