### ISSUE TITLE
The memory usage of fuse is too high, about 10G, and it will not drop

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2621]
**Describe the bug (描述bug)**
The memory usage of fuse is too high, about 10G, and it will not drop

**To Reproduce (复现方法)**
run mdtest and vdbench

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
@Wine93 related pull request https://github.com/opencurve/curve/pull/2678
