### ISSUE TITLE
need forward compatibility

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2671]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

https://github.com/opencurve/curve/pull/2647/files
**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by 201341** [comment]
> @201341 can you fix it later?

ok

**Comment by wuhongsong** [comment]
@201341  got it?
