### ISSUE TITLE
Error occurred during the cloud server standalone deployment of curvebs, seeking assistance for a solution

### ISSUE THREAD

**Issue by ZackSoul** [opencurve/curve#2690]
![部署bug](https://github.com/opencurve/curve/assets/91828262/d3b6e916-3860-4111-bfd5-f5bb94cb954f)

Deployed a cluster on Alibaba Cloud servers in standalone mode. After successful deployment of the cluster, when checking the cluster's health status, encountered the error shown in the image. The obscured part in the image is the private IP of the server. What should be done in this situation? Seeking assistance!!!

**Comment by Cyber-SiKu** [comment]
@ZackSoul you can use [new curve tool](https://github.com/opencurve/curve/tree/master/tools-v2#install)

**Comment by ZackSoul** [comment]
Can I use this tool for debugging? The purpose of my standalone deployment of the cluster is to debug a command related to snapshots in tools-v2 for future use.

**Comment by Cyber-SiKu** [comment]
> Can I use this tool for debugging? The purpose of my standalone deployment of the cluster is to debug a command related to snapshots in tools-v2 for future use.

可以

**Comment by Cyber-SiKu** [comment]
Does this seem to have not deployed Snapshot? If you are deployed to look at the log.

**Comment by ZackSoul** [comment]
So, do I still need to deploy the cluster snapshot before I can use this new tool to debug the new snapshot-related commands?

**Comment by Cyber-SiKu** [comment]
> So, do I still need to deploy the cluster snapshot before I can use this new tool to debug the new snapshot-related commands?

yep

**Comment by ZackSoul** [comment]
ok, I will try it, thanks
