### ISSUE TITLE
[curvefs]mds: create fs

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2779]
**Describe the bug (描述bug)**

When using v2.4 client to mount v2.6 mds, a creation fs error will be reported.

Reason for error:
mds will check whether s3info is consistent, but an attribute is added in the middle: objectPrefix. This attribute does not exist in the old proto, so an error will occur when checking the consistency.

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by 201341** [comment]
Assign it to me, I will fix it later. @Cyber-SiKu

**Comment by Cyber-SiKu** [comment]
> Assign it to me, I will fix it later. @Cyber-SiKu

done

**Comment by caoxianfei1** [comment]
@Cyber-SiKu
