### ISSUE TITLE
Error log print

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2811]
**Describe the bug (描述bug)**

Since the error log is printed on the standard output, the content running in the container will be saved in the docker directory, causing the log to occupy a large amount of disk. It is hoped that it will only be printed in the log file instead of the standard output.
This is [an entry](https://github.com/opencurve/curve/blob/570d6a69df088eaaf4b0e7d4b8523738789bbad0/curvefs/src/mds/main.cpp#L67).

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by NaturalSelect** [comment]
Hello @Cyber-SiKu , I'm interested in this issue.

**Comment by NaturalSelect** [comment]
Hello @Cyber-SiKu, glog still write log to stderr, even `FLAGS_logtostderr` is `false`.

Here is my scheme:
* If `FLAGS_logtostderr` is false, use `dup2` function to set fd2(`stderr`) to `/dev/null`.
