### ISSUE TITLE
ARC cache support

### ISSUE THREAD

**Issue by skypexu** [opencurve/curve#2819]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Current LRUCache is not scan-resistant and does not distinguish recently-used and frequently-used.

**Describe the solution you'd like (描述你期望的解决方法)**
Implement ARC cache, has compatible interface with current LRUCacheInterface.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by caoxianfei1** [comment]
Close it because related pull request closed.
