### ISSUE TITLE
[draft]  [ *******Coding Camp]: Call For Participation！

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2833]
We have provided some topics:

#### 1、Web page console for Curve(Languages: vue3 ts；go ), mentor: @SeanHai 
| Func                                                         | Issue                                                 | Difficulty level | Assigne | PR   | Progress |
| ------------------------------------------------------------ | ----------------------------------------------------- | ---------------- | ------- | ---- | :------- |
| remove the dependency of grpc from curve-manager                                | https://github.com/opencurve/curve-manager/issues/1   | medium           |      |      |          |
| Fix request for time series data exceeding limit                                | https://github.com/opencurve/curve-manager/issues/3   | easy           |      |      |          |
| Fix the disk type monitor info of nvme-ssd missed from node_exporter | https://github.com/opencurve/curve-manager/issues/2   | easy             |     |      |          |
| When zooming in on the page, the two pie charts on the homepage should be redrawn and centered | https://github.com/opencurve/curve-dashboard/issues/3 | easy             |         |      |          |
| The homepage cluster capacity pie chart is missing the legend for unallocated capacity | https://github.com/opencurve/curve-dashboard/issues/4 | easy             |        |      |          |
| Limit the display length of the text box content             | https://github.com/opencurve/curve-dashboard/issues/5 | easy             |        |      |          |

#### 2、Perfection of Curveadm (Languages: Go), memtor: @caoxianfei1 
| Func                                                         | Issue                                                 | Difficulty level | Assigne | PR   | Progress |
| ------------------------------------------------------------ | ----------------------------------------------------- | ---------------- | ------- | ---- | :------- |
| Manage service log                                         | https://github.com/opencurve/curveadm/issues/197 | easy | | | |
| Add cluster type to deploy cluster                 | https://github.com/opencurve/curveadm/issues/257 | easy | | | |
| Fix CurveAdm wiki document | https://github.com/opencurve/curveadm/issues/175 | easy | | | |
| host and hostname | https://github.com/opencurve/curveadm/issues/260 | easy | | | |
| Optimize the process of deploying memcache | https://github.com/opencurve/curveadm/issues/240 | easy | | | |
| docker and podman create container options init and pid host conflict | https://github.com/opencurve/curveadm/issues/320 | easy | | | |
| curveadm target start will timeout | https://github.com/opencurve/curveadm/issues/291 | easy | | | |
| support export the yaml that tools-v2 used | https://github.com/opencurve/curveadm/issues/315 | easy | | | |
| add cobra library document | https://github.com/opencurve/curveadm/issues/265 | easy | | | |
| replace old tool with new tool | https://github.com/opencurve/curveadm/issues/323 | easy | | | |
| curveadm enter command can directly enter the leader container | https://github.com/opencurve/curveadm/issues/324 | easy | | | |
| Support install new tool outside continer using curveadm | https://github.com/opencurve/curveadm/issues/325 | easy | | | |
| Support deploying minio-s3-gateway | https://github.com/opencurve/curveadm/issues/218 | medium | | | |
| More smart `core_pattern` | https://github.com/opencurve/curveadm/issues/178 | medium | | | |
|  Customized selection disk | https://github.com/opencurve/curve-operator/issues/27 |  medium | @liuminjian | https://github.com/opencurve/curve-operator/pull/79 |
| K8s/Deployment: Update cluster | https://github.com/opencurve/curve-operator/issues/29 |  medium | @peaceLT | |

<br class="Apple-interchange-newline">

#### 3、New tool support (Languages: Go), mentor: @Cyber-SiKu 
| Func                                                           | Issue                                                   | Difficulty level | Assigne | PR  | Progress |
| -------------------------------------------------------------- | ------------------------------------------------------- | ---------------- | ------- | --- | :------- |
| [tools-v2]: Add the command of statistical curvefs information | [#2532](https://github.com/opencurve/curve/issues/2532) | easy             |         |     |
| [tools-v2]:add bs delete volume snapshot                       | [#2578](https://github.com/opencurve/curve/issues/2578) | easy             |         |     |
| [tools-v2]:add bs query volume snapshot                        | [#2582](https://github.com/opencurve/curve/issues/2582) | easy             |         |     |
| [tools-v2]:add bs status volume snapshot                       | [#2583](https://github.com/opencurve/curve/issues/2583) | easy             |         |     |
| [tools-v2]:add bs query volume clone-recover                   | [#2584](https://github.com/opencurve/curve/issues/2584) | easy             |         |     |
| [tools-v2]:add bs create volume snapshot                       | [#2585](https://github.com/opencurve/curve/issues/2585) | easy             |         |     |
| [tools-v2]:add bs create volume clone/recover                  | [#2586](https://github.com/opencurve/curve/issues/2586) | easy             |         |     |
| [tools-v2]:add bs recover volume                               | [#2588](https://github.com/opencurve/curve/issues/2588) | easy             |         |     |
| [tools-v2]:support export monitor target                       | [#2564](https://github.com/opencurve/curve/issues/2564) | easy             |         |     |
| [tools-v2]:add bs stop volume snapshot                         | [#2579](https://github.com/opencurve/curve/issues/2579) | easy             |         |     |

#### 4、Modification of code logic (Languages: C++)
| Func                                                           | Issue                                                   | Difficulty level | Assigne | PR  | Progress |
| -------------------------------------------------------------- | ------------------------------------------------------- | ---------------- | ------- | --- | :------- |
|[curvefs/client] curvefs metric problem | #2391   | easy |     |  | | @h0hmj |
| When the cluster capacity is almost full, make the cluster readonly | #2561   |hard  ||  | | @xu-chaojie|
[#2576](https://github.com/opencurve/curve/issues/2576) | medium             |      |   |   |@Cyber-SiKu|
|add metric for memcached queue list | #2841   | easy |     |  | | @Cyber-SiKu  |
|curvefs support x-amz-storage-class | #2783   | easy |     |  | | @Cyber-SiKu  |

**Comment by caoxianfei1** [comment]
see https://github.com/opencurve/curve/issues/2847
