### ISSUE TITLE
add metric for memcached queue list

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#2841]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

curvefs  will use memecached，and we want to know the set and get counts in request queue

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

## Registration procedure
Step 1. Add a comment when you sign up.The purpose of comments is for us to understand you and determine whether you have the basic ability to complete this issue. 

- If you are a student, please introduce your school, major, programming language, technical fields of interest, what you are good at, and why you chose this issue. 
- If you are already working, please introduce your company, career, work content, technical fields of interest, and why you chose this issue.

Step 2. Use WeChat to add the Curve community assistant "Curve" as a WeChat friend, tell your GitHub ID, and send the Issue link of your choice. The assistant will invite you to communicate with the mentor  by WeChat.

Step 3. In order to better complete each development task, the mentor will select the developer who best matches the issue based on everyone's comment on GitHub and communication status by WeChat. If you are not selected, please select another issue.

## Tips
- Before developing, please read the dev guideline( https://ask.opencurve.io/t/topic/201) carefully and communicate with your mentor.
- Please submit a draft PR before 11.29, and the mentor will review it within 2-5 working days and may guide you to modify the PR based on the actual situation.
- If you successfully merge into PR before 12.27 and you will receive gifts carefully prepared by the Curve community.

**Comment by Songjf-ttk** [comment]
Hello, I am a student from Hunan University. My major is Software Engineering. I am familiar with C++ and Golang, and I am very interested in cloud-native and storage systems. My technical strengths include C++ server development and kernel virtualization techniques. I am confident in completing this topic, and I have previously submitted two PRs to the community：

1.[Add debug mode](https://github.com/opencurve/curveadm/pull/303)
2.[Fix variable position](https://github.com/opencurve/curveadm/pull/305)

**Comment by shuaihehe** [comment]
Hello, I am a student from Zhengzhou University, majoring in artificial intelligence. I am very interested in storage and am familiar with C++, Python, Linux, and shell scripts. I am particularly interested in applying for this issue and am confident in completing it.

**Comment by Subzeroo7** [comment]
> Hello, I am a student from Hunan University. My major is Software Engineering. I am familiar with C++ and Golang, and I am very interested in cloud-native and storage systems. My technical strengths include C++ server development and kernel virtualization techniques. I am confident in completing this topic, and I have previously submitted two PRs to the community：
> 
> 1.[Add debug mode](https://github.com/opencurve/curveadm/pull/303) 2.[Fix variable position](https://github.com/opencurve/curveadm/pull/305)

You have become a contributor to the curve community. It is recommended that you challenge more difficult issues.

**Comment by Subzeroo7** [comment]
> Hello, I am a student from Zhengzhou University, majoring in artificial intelligence. I am very interested in storage and am familiar with C++, Python, Linux, and shell scripts. I am particularly interested in applying for this issue and am confident in completing it.

Welcome！Just do it！
