### ISSUE TITLE
Modify fs.disableXattr on the fly is useless.

### ISSUE THREAD

**Issue by caoxianfei1** [opencurve/curve#2897]
**Describe the bug (描述bug)**
1. fs.disableXattr=false
<img width="1139" alt="image-20231112170100682" src="https://github.com/opencurve/curve/assets/54139479/ec1e4674-0791-4bbe-b4c1-2e6204251426">

2. fs.disableXattr=true
<img width="1046" alt="image-20231112170133140" src="https://github.com/opencurve/curve/assets/54139479/69083ecc-4c28-416b-ab3f-e12ca4de20df">

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
The special built-in xattrs not bound by switches.
