### ISSUE TITLE
curvefs/metaserver unit test IteratorTest.MergeIterator segmentation fault in release binary

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#2916]
**Describe the bug (描述bug)**
version: master
code: https://github.com/opencurve/curve/blob/1205fd64d0d993f74da2f97a5df3d4b22e93d166/curvefs/test/metaserver/storage/iterator_test.cpp#L167

build to release: make build stor=fs release=1 only=//curvefs/test/metaserver
run: ./bazel-bin/curvefs/test/metaserver/storage/storage_test --gtest_filter=IteratorTest.MergeIterator

```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from IteratorTest
[ RUN      ] IteratorTest.MergeIterator
Segmentation fault (core dumped)
```

![截屏2023-11-20 15 50 19](https://github.com/opencurve/curve/assets/13496900/72ddf239-0b2b-43ee-a54e-8739ffd25288)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Ziy1-Tan** [comment]
Let me try it.:) assign me plz.
