### ISSUE TITLE
[BUG](common): ARCCache's param `c` means cache capacity

### ISSUE THREAD

**Issue by zztaki** [opencurve/curve#2952]
**Describe the bug (描述bug)**
ARCCache's param `c` means cache capacity, but in the code, it is not. So this will cause ARCCache's real capacity will be maxCount/2.

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by zztaki** [comment]
If you think this makes sense, I am glad to submit a PR and add some tests for ARCCache :)

**Comment by zztaki** [comment]
![image](https://github.com/opencurve/curve/assets/50295684/a2f76dd8-7d68-4a5a-80a7-5a9e7d034ecf)

**Comment by wuhongsong** [comment]
https://github.com/opencurve/curve/pull/2852  @zztaki this pr will be ok.may reopen it later.

**Comment by skypexu** [comment]
#2962 
[https://github.com/opencurve/curve/issues/2962](url)
