### ISSUE TITLE
【C-Plan选题三】代码翻译&fix typo

### ISSUE THREAD

**Issue by zzl200012** [opencurve/curve#318]
**Describe the task you choose (描述你选择的任务)**
* translate comments in these files:
  * src/client/libcurve_file.h
  * src/client/libcurve_file.cpp
  * include/client/libcurve.h

**Describe alternatives you've considered (optional) (描述你想到的方案(可选))**

**Additional context/screenshots (更多上下文/截图)**
* fix a typo (SNAPSTHO_FROZEN => SNAPSHOT_FROZEN) in these files:
  * curvefs_python/curvefs_tool.py
  * src/client/mds_client.cpp
  * include/client/libcurve.h

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/118233716-de3c1000-b4c4-11eb-8e16-8cbb92b0c85d.png)
please fix the confict
