### ISSUE TITLE
【C-Plan选题一：清理代码中的TODO】parameters rename

### ISSUE THREAD

**Issue by zzl200012** [opencurve/curve#325]
**Describe the task you choose (描述你选择的任务)**
`// TODO(hzchenwei3): change oldFileName to sourceFileName and newFileName to destFileName` at [src/mds/nameserver2/curvefs.cpp](https://github.com/opencurve/curve/blob/master/src/mds/nameserver2/curvefs.cpp#L863)

**Describe alternatives you've considered (optional) (描述你想到的方案(可选))**

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
Thank you for your contribution. :smile:
