### ISSUE TITLE
【C-Plan选题一：清理代码中的TODO】add return value check

### ISSUE THREAD

**Issue by zzl200012** [opencurve/curve#327]
**Describe the task you choose (描述你选择的任务)**
`// TODO(wuhanqing): 判断返回值` at [src/client/libcbd_libcurve.cpp](https://github.com/opencurve/curve/blob/master/src/client/libcbd_libcurve.cpp#L93)

**Describe alternatives you've considered (optional) (描述你想到的方案(可选))**

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
thank u for submit！
