### ISSUE TITLE
Docker中执行 ./build.sh 编译错误

### ISSUE THREAD

**Issue by Super-long** [opencurve/curve#333]
## General Question
按照官方文档拉取 opencurve/curvebuild:centos8 镜像，随后拉取代码以后执行build.sh进行编译，出现如下错误：

[280 / 833] 8 actions, 7 running
    Compiling external/com_google_protobuf/src/google/protobuf/descriptor.cc; 2s processwrapper-sandbox
    @com_google_protobuf//:protobuf; 1s processwrapper-sandbox
    @com_google_protobuf//:protoc_lib; 1s processwrapper-sandbox
    @com_google_protobuf//:protoc_lib; 1s processwrapper-sandbox
    @com_google_protobuf//:protobuf; 0s processwrapper-sandbox
    Compiling external/com_google_protobuf/src/google/protobuf/descriptor.pb.cc; 0s processwrapper-sandbox
    Compiling external/com_google_protobuf/src/google/protobuf/descriptor_database.cc; 0s processwrapper-sandbox
    [-----] Compiling external/com_google_protobuf/src/google/protobuf/util/internal/object_writer.cc

Server terminated abruptly (error code: 14, error message: '', log file: '/root/.cache/bazel/_bazel_root/6f5f4033910d16741199bab868564698/server/jvm.out')

build phase1 failed
[root@0e79895da77d curve]# cat /root/.cache/bazel/_bazel_root/6f5f4033910d16741199bab868564698/server/jvm.out
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.cache/bazel/_bazel_root/install/792a28b07894763eaa2bd870f8776b23/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by zzl200012** [comment]
I met this problem on the physical machine as well, which seems to be an OOM, and I fixed it by allocating more (4G) swap space. So I guess you should allocate more memory or swap space for your docker container.
