### ISSUE TITLE
单机部署第三步失败

### ISSUE THREAD

**Issue by lwllvyb** [opencurve/curve#4]
## General Question
按照单机部署：https://github.com/opencurve/curve/blob/master/docs/cn/deploy.md

执行第三步：ansible-playbook -i server.ini deploy_curve.yml
报如下错误：
TASK [install_package : determine if etcd exists] **********************************************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 1046: Connection refused", "unreachable": true}

**Comment by bai-charisu** [comment]
非常感谢对curve的关注。
ansible需要ssh权限，所以单机部署的时候，执行ansible的用户需要能够ssh登录到本机。执行ansible的用户不一定是curve，但是要能够sudo -iu到curve用户。

ssh 到127.0.0.1失败参考步骤：
生成ssh秘钥
$ ssh-keygen -t rsa (连按两次回车，生成秘钥)
$ cat ~/.ssh/id_rsa >> ~/.ssh/authorized_keys
安装openssh-server（以ubuntu操作系统为例）
$ sudo apt install openssh-server
$ sudo /etc/init.d/ssh start
测试
$ ps -ef | grep ssh(查看sshd进程)
$ ssh localhot

**Comment by lwllvyb** [comment]
使用root权限运行：python3 $(which ansible-playbook) -i server.ini deploy_curve.yml
部署继续报错：
TASK [start_service : start by daemon] *****************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "[sudo] password for curve: \r\n\r\n{\"changed\": true, \"end\": \"2020-07-17 08:58:52.223388\", \"stdout\": \"\", \"cmd\": \"sudo ./etcd-daemon.sh start\", \"failed\": true, \"delta\": \"0:05:00.028365\", \"stderr\": \"sudo: timed out reading password\", \"rc\": 1, \"invocation\": {\"module_args\": {\"creates\": null, \"executable\": null, \"chdir\": \"/home/curve\", \"_raw_params\": \"sudo ./etcd-daemon.sh start\", \"removes\": null, \"warn\": true, \"_uses_shell\": true, \"stdin\": null}}, \"start\": \"2020-07-17 08:53:52.195023\", \"warnings\": [\"Consider using 'become', 'become_method', and 'become_user' rather than running sudo\"], \"msg\": \"non-zero return code\"}\r\n", "msg": "MODULE FAILURE", "rc": 1}

**Comment by xuefengchang** [comment]
> ~/.ssh/authorized_keys

还需要执行：ssh-copy-id curve@127.0.0.1

**Comment by BBJG001** [comment]
@lwllvyb 您好，我在部署过程中也遇到了这个问题，目前已有的回答在我这里是无效的，请问您最终是如何解决的

**Comment by bai-charisu** [comment]
> @lwllvyb 您好，我在部署过程中也遇到了这个问题，目前已有的回答在我这里是无效的，请问您最终是如何解决的

你好，部署过程中出现的问题可以提一个issue把具体的截图发出来。也可以加入Curve微信群，我们会根据具体情况帮你解答。
