### ISSUE TITLE
多机部署失败

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#434]
**Describe the bug (描述bug)**
使用的是Debian 9 操作系统部署。
安装过程中，会检查所依赖的 lib。其中会检查软件podlators-perl，但是该软件被perl-modules-5.24替代，因此检查和安装都会失败，需要手动修改配置文件 roles/prepare_software_env/tasks/main.yml。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Debian
Compiler: gcc-6.3.0 g++
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/15775037/125421511-2b93140c-e901-4d1c-8284-e231c38689ad.png)

**Comment by aspirer** [comment]
This issue has been resolved through wechat user group.
