### ISSUE TITLE
单机部署提示could not find or access ../curve-mds/bin/导致部署失败

### ISSUE THREAD

**Issue by xlyhw** [opencurve/curve#496]
## General Question
按照官方文档的指导，使用ansible-playbook命令部署单节点curve环境，在install mds bin阶段提示could not find or access ../curve-mds/bin/，导致部署失败。
![image](https://user-images.githubusercontent.com/88713992/128859583-ed44eb42-2505-42db-ae34-ddaf84d619c3.png)

查看脚本发现，在install mds bin阶段会将../curve-mds/bin/中的文件复制到/usr/bin中，但在../curve-mds目录下没有/bin目录，仅有DEBIAN和home两个文件夹。因此可以认为是curve-mds文件夹中没有mds组件，导致脚本无法找到源文件而报错。但整体阅读代码后并未找到下载或构建mds的命令，因此想请教一下如何解决这个问题。

OS：CentOS-8.2.2004
内核：4.18.0-193.el8.x86_64
openssl：1.1.1g FIPS 21 Apr 2020
gcc：8.4.1 20200928 （Red Hat 8.4.1-1）
curve：curve-1.0.4（1.2.1-rc0和1.3.0-beta2也有同样的问题）

**Comment by SeanHai** [comment]
> ## General Question
> 按照官方文档的指导，使用ansible-playbook命令部署单节点curve环境，在install mds bin阶段提示could not find or access ../curve-mds/bin/，导致部署失败。
> ![image](https://user-images.githubusercontent.com/88713992/128859583-ed44eb42-2505-42db-ae34-ddaf84d619c3.png)
> 
> 查看脚本发现，在install mds bin阶段会将../curve-mds/bin/中的文件复制到/usr/bin中，但在../curve-mds目录下没有/bin目录，仅有DEBIAN和home两个文件夹。因此可以认为是curve-mds文件夹中没有mds组件，导致脚本无法找到源文件而报错。但整体阅读代码后并未找到下载或构建mds的命令，因此想请教一下如何解决这个问题。
> 
> OS：CentOS-8.2.2004
> 内核：4.18.0-193.el8.x86_64
> openssl：1.1.1g FIPS 21 Apr 2020
> gcc：8.4.1 20200928 （Red Hat 8.4.1-1）
> curve：curve-1.0.4（1.2.1-rc0和1.3.0-beta2也有同样的问题）

这里ansible部署使用的是curve tar包，curve-mds/bin 目录是位于其中的，对应版本的tar包见https://github.com/opencurve/curve/releases；部署过程可参考：https://github.com/opencurve/curve/blob/master/docs/cn/deploy.md#%E5%AE%9E%E6%96%BD%E9%83%A8%E7%BD%B2

**Comment by aspirer** [comment]
有问题再reopen
