### ISSUE TITLE
单机部署成功，创建文件失败

### ISSUE THREAD

**Issue by xuefengchang** [opencurve/curve#50]
[root@057e65f0a884 curve-ansible]# curve_ops_tool status
Cluster status:
Copysets are not healthy!
Get status metric from 127.0.0.1:8081 fail
No snapshot-clone-server is active
snapshot-clone-server 127.0.0.1:5556 is offline
cluster is not healthy
total copysets: 100, unhealthy copysets: 13, unhealthy_ratio: 13%
physical pool number: 1, logical pool number: 1
total space = 0GB, logical used = 0GB(0.00%, can be recycled = 0GB(0.00%)), physical used = 0GB(0.00%)

Client status:

MDS status:
version: 9.9.9
current MDS: 127.0.0.1:6666
online mds list: 127.0.0.1:6666
offline mds list:

Etcd status:
version: 3.4.0
current etcd: 127.0.0.1:2379
online etcd list: 127.0.0.1:2379
offline etcd list:

SnapshotCloneServer status:
no version found!
GetAndCheckSnapshotCloneVersion fail
Get status metric from 127.0.0.1:8081 fail
current snapshot-clone-server:
online snapshot-clone-server list:
offline snapshot-clone-server list: 127.0.0.1:5556

ChunkServer status:
version: 9.9.9
chunkserver: total num = 3, online = 3, offline = 0(recoveringout = 0, chunkserverlist: [])
left size: min = 0GB, max = 0GB, average = 0.00GB, range = 0GB, variance = 0.00
[root@057e65f0a884 curve-ansible]# curve create --filename /test --length 10 --user root
E 2020-08-03T23:09:59.519749+0800 12349 server.cpp:994] Fail to listen 0.0.0.0:9000
E 2020-08-03T23:09:59.519836+0800 12349 server.cpp:1832] Fail to start dummy_server at port=9000
E 2020-08-03T23:09:59.529330+0800 12349 mds_client.cpp:314] CreateFile: filename = /test, owner = root, is nomalfile: 1, errocde = 4, error msg = kOwnerAuthFail, log id = 1
create fail, ret = -4
[root@057e65f0a884 curve-ansible]#

[root@057e65f0a884 curve-ansible]# ps -aux|grep chunkserver
root      6893 55.9  4.3 745128 88044 ?        Sl   22:56  11:06 curve-chunkserver -bthread_concurrency=18 -raft_max_segment_size=8388608 -raft_max_install_snapshot_tasks_num=1 -raft_sync=true -conf=/etc/curve/chunkserver.conf -enableChunkfilepool=false -chunkFilePoolDir=./data/chunkserver0 -chunkFilePoolMetaPath=./data/chunkserver0/chunkfilepool.meta -chunkServerIp=127.0.0.1 -chunkServerPort=8200 -chunkServerMetaUri=local://./data/chunkserver0/chunkserver.dat -chunkServerStoreUri=local://./data/chunkserver0/ -copySetUri=local://./data/chunkserver0/copysets -raftSnapshotUri=curve://./data/chunkserver0/copysets -recycleUri=local://./data/chunkserver0/recycler -graceful_quit_on_sigterm=true -raft_sync_meta=true -raft_sync_segments=true -graceful_quit_on_sigterm=true -log_dir=./data/log/chunkserver0
root      6899 35.2  4.1 728712 84560 ?        Sl   22:56   6:59 curve-chunkserver -bthread_concurrency=18 -raft_max_segment_size=8388608 -raft_max_install_snapshot_tasks_num=1 -raft_sync=true -conf=/etc/curve/chunkserver.conf -enableChunkfilepool=false -chunkFilePoolDir=./data/chunkserver1 -chunkFilePoolMetaPath=./data/chunkserver1/chunkfilepool.meta -chunkServerIp=127.0.0.1 -chunkServerPort=8201 -chunkServerMetaUri=local://./data/chunkserver1/chunkserver.dat -chunkServerStoreUri=local://./data/chunkserver1/ -copySetUri=local://./data/chunkserver1/copysets -raftSnapshotUri=curve://./data/chunkserver1/copysets -recycleUri=local://./data/chunkserver1/recycler -graceful_quit_on_sigterm=true -raft_sync_meta=true -raft_sync_segments=true -graceful_quit_on_sigterm=true -log_dir=./data/log/chunkserver1
root      6987 27.4  4.1 728696 85064 ?        Sl   22:56   5:26 curve-chunkserver -bthread_concurrency=18 -raft_max_segment_size=8388608 -raft_max_install_snapshot_tasks_num=1 -raft_sync=true -conf=/etc/curve/chunkserver.conf -enableChunkfilepool=false -chunkFilePoolDir=./data/chunkserver2 -chunkFilePoolMetaPath=./data/chunkserver2/chunkfilepool.meta -chunkServerIp=127.0.0.1 -chunkServerPort=8202 -chunkServerMetaUri=local://./data/chunkserver2/chunkserver.dat -chunkServerStoreUri=local://./data/chunkserver2/ -copySetUri=local://./data/chunkserver2/copysets -raftSnapshotUri=curve://./data/chunkserver2/copysets -recycleUri=local://./data/chunkserver2/recycler -graceful_quit_on_sigterm=true -raft_sync_meta=true -raft_sync_segments=true -graceful_quit_on_sigterm=true -log_dir=./data/log/chunkserver2
root     12363  0.0  0.0   9180  1036 pts/0    R+   23:16   0:00 grep --color=auto chunkserver

**Comment by bai-charisu** [comment]
你好，这个问题是由于你指定的user是root，root用户的话操作必须指定root_password，curve这个工具目前还不支持输入密码。你可以将user从root改成curve。

**Comment by xuefengchang** [comment]
> 你好，这个问题是由于你指定的user是root，root用户的话操作必须指定root_password，curve这个工具目前还不支持输入密码。你可以将user从root改成curve。

单机环境构建(非docker)报错，请问需要怎么解决？

ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:37:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:50:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:78:1: name 'http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:92:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:133:1: name 'new_git_repository' is not defined (did you mean 'git_repository'?)
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:151:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:162:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:173:1: name 'new_http_archive' is not defined
ERROR: /mnt/hgfs/curve_ws/curve/WORKSPACE:184:1: name 'new_http_archive' is not defined
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.455s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
build phase1 failed

**Comment by bai-charisu** [comment]
应该是bazel版本不匹配导致的，请查看[编译文档](https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md)里的详细说明

**Comment by xuefengchang** [comment]
遇到的问题总结(编译和部署均是在docker环境里)：
**安装SSH**
    安装ssh:  sudo yum install openssh-server
    安装service:  sudo yum install initscripts
    将配置修改持久化到docker镜像： docker commit $container_id opencurve/curvebuild:latest
 
**docker启动(支持启动SSH服务)**
docker run -tid --privileged=true -p 2222:22 -v /sys/fs/cgroup:/sys/fs/cgroup:ro -u root  opencurve/curvebuild:latest /sbin/init
docker exec -it -e TZ="Asia/Shanghai" $container_id /bin/bash
(注意：一定要使用上面这种方式启动docker容器，否则无法执行sudo service sshd start，无法启动ssh服务，会报"System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down" 的错误)

**编译阶段**
(1) 使用curve官方提供的镜像，不要使用其他镜像，否则会有各种环境问题需要解决；
(2) bazel只能使用0.17.2版本，其他版本会有语法错误；
(3) 将bazel软链接到/usr/bin/ 目录下，否则非root用户执行mk-tar.sh脚本时不识别bazel命令；
sudo ln -s /usr/local/bin/bazel /usr/bin/bazel

**部署阶段**
(1) 使用curve用户，不要使用root用户，并且需要curve用户能够免密sudo；
(2) ansible单机部署需要能够ssh免密登陆到本机，需要进行配置：
    生成密钥：ssh-keygen -t rsa (连按两次回车，生成秘钥)
    配置免密登陆：
    cat ~/.ssh/id_rsa >> ~/.ssh/authorized_keys
    ssh-copy-id curve@127.0.0.1
    验证： ssh curve@localhost

**Comment by xuefengchang** [comment]
> 应该是bazel版本不匹配导致的，请查看[编译文档](https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md)里的详细说明

版本换成0.17.2了，编译还报这个错误：

[2,301 / 2,306] 2 actions running
ERROR: /curve_ws/curve/test/mds/nameserver2/BUILD:17:1: C++ compilation of rule '//test/mds/nameserver2:curvefs_test' failed (Exit 1)
In file included from ./src/common/concurrent/concurrent.h:30,
                 from ./src/mds/nameserver2/file_lock.h:35,
                 from ./src/mds/nameserver2/namespace_service.h:30,
                 from test/mds/nameserver2/namespace_service_test.cpp:27:
./src/common/concurrent/count_down_event.h: In member function 'bool curve::common::CountDownEvent::WaitFor(int)':
./src/common/concurrent/count_down_event.h:98:22: warning: unused variable 'ret' [-Wunused-variable]
                 auto ret = cond_.wait_for(guard,
                      ^~~
In file included from ./src/mds/nameserver2/idgenerator/chunk_id_generator.h:30,
                 from ./src/mds/nameserver2/chunk_allocator.h:30,
                 from ./src/mds/nameserver2/curvefs.h:35,
                 from test/mds/nameserver2/namespace_service_test.cpp:28:
./src/mds/nameserver2/idgenerator/etcd_id_generator.h: In constructor 'curve::mds::EtcdIdGenerator::EtcdIdGenerator(const std::shared_ptr<curve::kvstorage::KVStorageClient>&, const string&, uint64_t, uint64_t)':
./src/mds/nameserver2/idgenerator/etcd_id_generator.h:64:38: warning: 'curve::mds::EtcdIdGenerator::client_' will be initialized after [-Wreorder]
     std::shared_ptr<KVStorageClient> client_;
                                      ^~~~~~~
./src/mds/nameserver2/idgenerator/etcd_id_generator.h:60:17: warning:   'std::__cxx11::string curve::mds::EtcdIdGenerator::storeKey_' [-Wreorder]
     std::string storeKey_;
                 ^~~~~~~~~
./src/mds/nameserver2/idgenerator/etcd_id_generator.h:39:5: warning:   when initialized here [-Wreorder]
     EtcdIdGenerator(
     ^~~~~~~~~~~~~~~
In file included from ./src/mds/topology/topology_chunk_allocator.h:35,
                 from ./src/mds/nameserver2/chunk_allocator.h:31,
                 from ./src/mds/nameserver2/curvefs.h:35,
                 from test/mds/nameserver2/namespace_service_test.cpp:28:
./src/mds/nameserver2/allocstatistic/alloc_statistic.h: In constructor 'curve::mds::AllocStatistic::AllocStatistic(uint64_t, uint64_t, std::shared_ptr<curve::kvstorage::EtcdClientImp>)':
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:208:18: warning: 'curve::mds::AllocStatistic::currentValueAvalible_' will be initialized after [-Wreorder]
     Atomic<bool> currentValueAvalible_;
                  ^~~~~~~~~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:198:18: warning:   'curve::common::Atomic<bool> curve::mds::AllocStatistic::segmentAllocFromEtcdOK_' [-Wreorder]
     Atomic<bool> segmentAllocFromEtcdOK_;
                  ^~~~~~~~~~~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:75:5: warning:   when initialized here [-Wreorder]
     AllocStatistic(uint64_t periodicPersistInterMs, uint64_t retryInterMs,
     ^~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:217:18: warning: 'curve::mds::AllocStatistic::stop_' will be initialized after [-Wreorder]
     Atomic<bool> stop_;
                  ^~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:214:14: warning:   'uint64_t curve::mds::AllocStatistic::periodicPersistInterMs_' [-Wreorder]
     uint64_t periodicPersistInterMs_;
              ^~~~~~~~~~~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:75:5: warning:   when initialized here [-Wreorder]
     AllocStatistic(uint64_t periodicPersistInterMs, uint64_t retryInterMs,
     ^~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:214:14: warning: 'curve::mds::AllocStatistic::periodicPersistInterMs_' will be initialized after [-Wreorder]
     uint64_t periodicPersistInterMs_;
              ^~~~~~~~~~~~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:211:14: warning:   'uint64_t curve::mds::AllocStatistic::retryInterMs_' [-Wreorder]
     uint64_t retryInterMs_;
              ^~~~~~~~~~~~~
./src/mds/nameserver2/allocstatistic/alloc_statistic.h:75:5: warning:   when initialized here [-Wreorder]
     AllocStatistic(uint64_t periodicPersistInterMs, uint64_t retryInterMs,
     ^~~~~~~~~~~~~~
In file included from ./src/mds/nameserver2/curvefs.h:40,
                 from test/mds/nameserver2/namespace_service_test.cpp:28:
./src/common/authenticator.h: At global scope:
./src/common/authenticator.h:33:13: warning: 'curve::common::b' defined but not used [-Wunused-variable]
 static char b[] =
             ^
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
INFO: Elapsed time: 2263.455s, Critical Path: 184.07s
INFO: 1871 processes: 1871 linux-sandbox.
FAILED: Build did NOT complete successfully
build phase1 failed

**Comment by xuefengchang** [comment]
@bai-charisu 在curve用户下单机部署报这些错误，请问需要怎么解决？
TASK [install_package : install etcd] *************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mv etcd /usr/bin && mv etcdctl /usr/bin", "delta": "0:00:00.558924", "end": "2020-08-06 00:37:52.495765", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 00:37:51.936841", "stderr": "mv: cannot move 'etcd' to '/usr/bin/etcd': Permission denied", "stderr_lines": ["mv: cannot move 'etcd' to '/usr/bin/etcd': Permission denied"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [generate_config : create dir] ***************************************************************************
 [WARNING]: Consider using the file module with state=directory rather than running mkdir.  If you need to use
command because file is insufficient you can add warn=False to this command task or set command_warnings=False
in ansible.cfg to get rid of this message.

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mkdir -p /etc/curve", "delta": "0:00:00.559528", "end": "2020-08-06 00:37:56.180493", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 00:37:55.620965", "stderr": "mkdir: cannot create directory '/etc/curve': Permission denied", "stderr_lines": ["mkdir: cannot create directory '/etc/curve': Permission denied"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [generate_config : generate configuration file directly] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "27c7b68395f392cdc4d364ba6afa06b577c925ff", "msg": "Destination /etc/curve not writable"}

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mkdir -p /etc/curve", "delta": "0:00:00.559528", "end": "2020-08-06 00:37:56.180493", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 00:37:55.620965", "stderr": "mkdir: cannot create directory '/etc/curve': Permission denied", "stderr_lines": ["mkdir: cannot create directory '/etc/curve': Permission denied"], "stdout": "", "stdout_lines": []}

TASK [start_service : start by daemon] ************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "sudo ./mds-daemon.sh start", "delta": "0:00:00.562987", "end": "2020-08-06 00:38:31.855684", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 00:38:31.292697", "stderr": "", "stderr_lines": [], "stdout": "No curve-mds installed", "stdout_lines": ["No curve-mds installed"]}

NO MORE HOSTS LEFT ********************************************************************************************
	to retry, use: --limit @/curve_ws/curve/curve-ansible/deploy_curve.retry

PLAY RECAP ****************************************************************************************************
localhost                  : ok=77   changed=35   unreachable=0    failed=1

**Comment by bai-charisu** [comment]
> @bai-charisu 在curve用户下单机部署报这些错误，请问需要怎么解决？
> 
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mkdir -p /etc/curve", "delta": "0:00:00.562881", "end": "2020-08-06 02:45:32.117816", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 02:45:31.554935", "stderr": "mkdir: cannot create directory '/etc/curve': Permission denied", "stderr_lines": ["mkdir: cannot create directory '/etc/curve': Permission denied"], "stdout": "", "stdout_lines": []}
> ...ignoring
> 
> TASK [generate_config : generate configuration file directly] ******************
> fatal: [localhost]: FAILED! => {"changed": false, "checksum": "c8d272f39f3311eaf74f72d3671ab78c772718ca", "msg": "Destination /etc/curve not writable"}
> ...ignoring
> 
> TASK [start_service : start chunkserver] ***************************************
> fatal: [localhost]: FAILED! => {"ansible_job_id": "719967831328.6878", "changed": true, "cmd": "sudo ./chunkserver_ctl.sh start all", "delta": "0:00:01.679262", "end": "2020-08-06 02:46:50.405626", "failed_when_result": true, "finished": 1, "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 02:46:48.726364", "stderr": "", "stderr_lines": [], "stdout": "subnet: 127.0.0.1/22\nbase port: 8200\nchunkserver0 is down\nchunkserver1 is down\nchunkserver2 is down", "stdout_lines": ["subnet: 127.0.0.1/22", "base port: 8200", "chunkserver0 is down", "chunkserver1 is down", "chunkserver2 is down"]}
> 
> NO MORE HOSTS LEFT *************************************************************
> to retry, use: --limit @/curve_ws/curve/curve-ansible/deploy_curve.retry
> 
> PLAY RECAP *********************************************************************
> localhost : ok=119 changed=46 unreachable=0 failed=1

chunkserver启动失败了，先输入curve-chunkserver看一下是不是缺少了什么库。同时可以看下/home/curve/data/chunkserver0下面有没有日志

**Comment by xuefengchang** [comment]
> > @bai-charisu 在curve用户下单机部署报这些错误，请问需要怎么解决？
> > fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mkdir -p /etc/curve", "delta": "0:00:00.562881", "end": "2020-08-06 02:45:32.117816", "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 02:45:31.554935", "stderr": "mkdir: cannot create directory '/etc/curve': Permission denied", "stderr_lines": ["mkdir: cannot create directory '/etc/curve': Permission denied"], "stdout": "", "stdout_lines": []}
> > ...ignoring
> > TASK [generate_config : generate configuration file directly] ******************
> > fatal: [localhost]: FAILED! => {"changed": false, "checksum": "c8d272f39f3311eaf74f72d3671ab78c772718ca", "msg": "Destination /etc/curve not writable"}
> > ...ignoring
> > TASK [start_service : start chunkserver] ***************************************
> > fatal: [localhost]: FAILED! => {"ansible_job_id": "719967831328.6878", "changed": true, "cmd": "sudo ./chunkserver_ctl.sh start all", "delta": "0:00:01.679262", "end": "2020-08-06 02:46:50.405626", "failed_when_result": true, "finished": 1, "msg": "non-zero return code", "rc": 1, "start": "2020-08-06 02:46:48.726364", "stderr": "", "stderr_lines": [], "stdout": "subnet: 127.0.0.1/22\nbase port: 8200\nchunkserver0 is down\nchunkserver1 is down\nchunkserver2 is down", "stdout_lines": ["subnet: 127.0.0.1/22", "base port: 8200", "chunkserver0 is down", "chunkserver1 is down", "chunkserver2 is down"]}
> > NO MORE HOSTS LEFT *************************************************************
> > to retry, use: --limit @/curve_ws/curve/curve-ansible/deploy_curve.retry
> > PLAY RECAP *********************************************************************
> > localhost : ok=119 changed=46 unreachable=0 failed=1
> 
> chunkserver启动失败了，先输入curve-chunkserver看一下是不是缺少了什么库。同时可以看下/home/curve/data/chunkserver0下面有没有日志

解决依赖库之后chunkserver启动了，但是还是创建文件失败


[curve@b48cef67eec4 curve_ws]$ sudo curve create --filename /test --length 10 --user curve
E 2020-08-06T10:19:58.059389+0800 17923 server.cpp:994] Fail to listen 0.0.0.0:9000
E 2020-08-06T10:19:58.061826+0800 17923 server.cpp:1832] Fail to start dummy_server at port=9000
E 2020-08-06T10:19:58.091537+0800 17923 mds_client.cpp:314] CreateFile: filename = /test, owner = curve, is nomalfile: 1, errocde = 1, error msg = kFileExists, log id = 1
create fail, ret = -1

**Comment by bai-charisu** [comment]
显示文件已存在，应该是/test这个文件之前创建成功过，可以直接进行下一步挂载。

**Comment by xuefengchang** [comment]
> 显示文件已存在，应该是/test这个文件之前创建成功过，可以直接进行下一步挂载。

可以了，编译和部署都成功了，使用fio压了一下IO也正常，thanks @bai-charisu
