### ISSUE TITLE
请告知一个部署自测的时候可以成功的CentOS版本吧

### ISSUE THREAD

**Issue by guihecheng** [opencurve/curve#56]
请问开发人员测试的时候是用的CentOS哪个小版本？比如CentOS7.8或者CentOS8.2？
毕竟C/C++编写的东西，依赖问题还是挺多的，先谢啦~

**Comment by wu-hanqing** [comment]
你好，单机部署在CentOS8.2上测试过
```bash
[root@centos8 sbin]# cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core) 
[root@centos8 sbin]# uname -r
4.18.0-193.el8.x86_64
```
具体的安装镜像版本是 `CentOS-8.2.2004-x86_64-dvd1-dvd1.iso` ，可以参考一下。

**Comment by guihecheng** [comment]
好的，谢谢这么及时的反馈，这下有底了。
