### ISSUE TITLE
关于chunkserver中CopysetNode的删除时机问题

### ISSUE THREAD

**Issue by lday0321** [opencurve/curve#588]
感谢curve团队的开源，代码很值得学习！

我在阅读chunkserve相关逻辑上，关于CopysetNode的清理时机，有个问题想请教一下：

CopysetNode清理逻辑：
chunkserver删除CopysetNode是在heartbeat的`PurgeCopyset`中，最终会调用[`CopysetNodeManager::PurgeCopysetNodeData`](https://github.com/opencurve/curve/blob/master/src/chunkserver/copyset_node_manager.cpp#L449-L486)，完成对应CopysetNode的清理工作
\1. CopysetNodeManager::PurgeCopysetNodeData执行清理时，首先加读锁调用CopysetNode::Fini，
\1.1 关闭该node的raft服务，同时等待所有在途的raft处理完成
\1.2 同时，通过corrent apply的flush，将在途的对应该node的chunk op request处理掉
\2. 接着，加写锁，执行相应的清理工作
\2.1 首先将对应node的问题回收(`copysetNodeOptions_.trash->RecycleCopySet`)
\2.2 将对应node从manager上移除`copysetNodeMap_.erase(it)`

主线IO处理逻辑：
另一方面，ChunkServer在处理Write/Read请求时，
\1. 在rpc service层，会通过CopysetNodeManager拿到对应的CopysetNode (`copysetNodeManager_->GetCopysetNode`)
\1.1 这个get过程，会拿读锁，从copysetNodeMap_中查找并返回对应的CopysetNode
\2. 接着，基于拿到的node信息，组装对应的ChunkRequest，执行`process`处理
\3. 在`Propose`中，构造raft task，并提交到raft group
\4. 在FSM的on_apply中，进一步将raft task封装成task项提交给current apply
\5. 由current apply底层线程，最终调用到对应Request的OnApply/OnApplyFromLog进行处理，此时会依赖于CopysetNode中的`datastore_`执行实际的对应操作。

我的问题是，在"CopysetNode清理逻辑"的**1.1.2**完成后，也就是CopysetNodeManager的读锁释放后，"主线IO处理逻辑"的**1.1**执行完成，此时，对应的raft task还没有生成,current apply中也没有在途的task，而接着，"CopysetNode清理逻辑"的**1.2**及后续逻辑继续执行，也就是对应CopysetNode的对应数据文件被清理掉。***而在此之后，主线IO处理逻辑没有意识到持有的CopysetNode已经不可用，进而后续依赖`datastore_`的处理逻辑会出问题***。

可能的解决解决方法：
在CopysetNode中，需要增加使用该CopysetNode的在途请求统计，在"主线IO处理逻辑"的**1.1**中，需要一并增加该在途请求数信息，同时在请求结束时，需递减在途请求信息；而对于“CopysetNode清理逻辑”，需要先将该CopysetNode，从`copysetNodeMap_`上移除，接着等待调用`CopysetNode::Fini`等待在途请求处理结束，最终，执行回收动作（ `RecycleCopySet` )。

ps. 目前的处理没有问题，是不是因为协议上做了保证，对于CopysetNode的清理，一定不会是该copyset node的leader，而不是leader，就不会有IO处理请求，因此两者不会有冲突？但从自身处理逻辑完毕来考虑，是不是需要考虑等待在途请求结束，再做清理。

**Comment by ilixiaocui** [comment]
> copyset的迁移（rebalance）是不是也会做对应清理

**Comment by lday0321** [comment]
我读代码的理解是，curve的处理和HDFS的行为类似，通过heartbeat，将指定CMD，转交到对应的chunkserver去做处理，当发现自己已不再该copyset的peer list中时，则会主动执行`PurgeCopyset`，将该copyset从本地删除；对于其他情况，则会根据heartbeat response携带的不同conf.type()执行相应的处理(transfer_leader/add_peer/remove_peer/change_peer)

**Comment by aspirer** [comment]
如有问题请reopen或新开issue。
