### ISSUE TITLE
curvefs: data inconsistent and io error occurs while runing vdbench

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#673]
**Describe the bug (描述bug)**
Vdbench reading and writing are inconsistent and io error
![image](https://user-images.githubusercontent.com/3424999/141718204-d56460b7-f298-4a08-b79b-bc60ad92ac1d.png)

**To Reproduce (复现方法)**
use vdbench test,profile is：
fsd=fsd1,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=1200,interval=1

**Expected behavior (期望行为)**
test success

**Versions (各种版本)**
OS: 4.9.65-netease
Compiler:
curve-mds: 
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Inodeid: 
![image](https://user-images.githubusercontent.com/15689619/141774049-0d03d219-0983-4c7a-b36f-053d13689f54.png)

Inode info from log:
I 2021-11-15T10:58:11.168519+0800 1554059 metaserver_client.cpp:465] UpdateInode success, request: poolId: 1
copysetId: 25
partitionId: 2
fsId: 2
inodeId: 930
length: 95420416
ctime: 1636945091
mtime: 1636945090
atime: 1636945091
uid: 0
gid: 0
mode: 33188
s3ChunkInfoMap {
  key: 2
  value {
    s3Chunks {
      chunkId: 126919
      compaction: 0
      offset: 8388608
      len: 4194304
      size: 4194304
      zero: false
    }
    s3Chunks {
      chunkId: 155025
      compaction: 0
      offset: 8818688
      len: 4096
      size: 4096
      zero: false
    }
    s3Chunks {
      chunkId: 155028
      compaction: 0
      offset: 9961472
      len: 1048576
      size: 1048576
      zero: false
    }
    s3Chunks {
      chunkId: 189063
      compaction: 0
      offset: 8523776
      len: 4096
      size: 4096
      zero: false
    }
    s3Chunks {
      chunkId: 189066
      compaction: 0
      offset: 8732672
      len: 512
      size: 512
      zero: false
    }
    s3Chunks {
      chunkId: 189067
      compaction: 0
      offset: 9184768
      len: 512
      size: 512
      zero: false
    }
    s3Chunks {
      chunkId: 189068
      compaction: 0
      offset: 9437184
      len: 1048576
      size: 1048576
      zero: false
    }
  }
}
 
Write scene：
![image](https://user-images.githubusercontent.com/15689619/141774229-946d5327-6bac-4445-9585-75fb0651a5aa.png)

Relative read log:
![image](https://user-images.githubusercontent.com/15689619/141774318-96d32a70-b409-4ec1-8a3e-b0b9f0259807.png)
We should read 2_930_189068_1_0, but actually read 2_930_126919_1_0. 

Conclusion：
There was an error in the s3Chunks merge. Need to be resolved by @baijiaruo
Relative code: 

https://github.com/opencurve/curve/blob/8af56e68afc99b4ab36ae2415cb6877f120db935/curvefs/src/client/s3/client_s3_cache_manager.cpp#L676
