### ISSUE TITLE
The default path of metaserver data should not be under tmp

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#688]
**Describe the bug (描述bug)**

The default path of metaserver data should not be under tmp
**To Reproduce (复现方法)**

deploy new cluster
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/142338222-9779096e-bea6-43a3-8bc3-9705939e44ab.png)

**Comment by aspirer** [comment]
this path is a config value, so we can change it when we deploy a new cluster, this may not be a bug.
