### ISSUE TITLE
reduce lock conflicts

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#704]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
after every datacache flush， there will update inode.

**Describe the solution you'd like (描述你期望的解决方法)**
update inode is heavy operation, it will apply for the lock.
we can update inode just in every chunk flush

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
https://github.com/opencurve/curve/pull/671

**Comment by ilixiaocui** [comment]
abondon
