### ISSUE TITLE
curve-fuse: segfault error is reported in syslog during umount

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#709]
**Describe the bug (描述bug)**

![image](https://user-images.githubusercontent.com/67582932/142601090-c3d7d9a6-c649-40f1-b082-7dbb9861cc4f.png)
umount fuse :
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
@ilixiaocui

**Comment by xu-chaojie** [comment]
![8772b14e2c1d4c0786a5e41f5719885e](https://user-images.githubusercontent.com/5245004/143861056-dc6110a4-36cd-4441-ab3b-9722eb746e3a.png
![0fc46eaea90c40b596604aac663d3b58](https://user-images.githubusercontent.com/5245004/143861068-e7562e03-4ead-46f0-9243-69e9a29d8de8.png)
)

**Comment by xu-chaojie** [comment]
As shown in the figure above, since Deinit is not called before s3Adaptor is destroyed, the asynchronous read and write request is returned to be executed, s3Adaptor has already been destructed, then resulting in core
