### ISSUE TITLE
curvefs: Cannot get directory capacity information using du command

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#711]
**Describe the bug (描述bug)**
Cannot get directory capacity information using du command, pls fix it.

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/142807663-f34aabc0-5a75-4284-befa-ab3eefe78bea.png)

**Comment by xu-chaojie** [comment]
directory capacity  is 0， it is right， we should not sum directory  capacity with file，because they are store in different place(file is in s3)
