### ISSUE TITLE
Inconsistent data after umount

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#727]
**Describe the bug (描述bug)**
Inconsistent data after umount

**To Reproduce (复现方法)**
1、use vdbench test ,profile is 
fsd=fsd1,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=no,elapsed=restart,interval=1
2、umount fuse and wait fuse  process exit

3、mount fuse

4、fsd=fsd1,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=no,elapsed=600,interval=1
use this profile test ，cmd is : 
sudo ./vdbench -f profile -jr

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/143212496-fdbebab7-575e-446c-a3c6-1fc102c984fb.png)

**Comment by aspirer** [comment]
This is not a problem of curvefs, this issue also occurs on local filesystem, if you find it's really a bug of curvefs, reopen this issue pls.
