### ISSUE TITLE
deploy: Change the default path of config and binary files

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#729]
**Describe the bug (描述bug)**

The deployment needs to make the tools available to a path, and the configuration file needs to be activated under /etc/curvefs

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
tools now is in :+1: nbs@pubbeta2-curve2:~/machine/pubbeta2-curve2-1/curvefs/tools/
Hope to be in /usr/bin or others

tools.conf in /etc/curvefs

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/143390634-2b1152a9-dc51-4fc2-848c-dc49969bf075.png)

**Comment by Cyber-SiKu** [comment]
test
