### ISSUE TITLE
config: rpcRetryTimes should be added to tools.conf

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#730]
**Describe the bug (描述bug)**
nbs@pubbeta2-curve2:/var/lib/jenkins/workspace/curve_failover/curvefs/conf did not have rpcRetryTimes conf 

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/143391376-feee4c66-f8be-4ec9-aa00-a83f29227145.png)

**Comment by Cyber-SiKu** [comment]
fix by pr https://github.com/opencurve/curve/pull/728
