### ISSUE TITLE
Mds failed to start after restarting mds after power failure

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#733]
**Describe the bug (描述bug)**
Mds failed to start after restarting mds after power failure

**To Reproduce (复现方法)**
1、run vdbench
2、power off one mds
3、mds status fail
4、nbs@pubbeta2-curve4:~/machine/pubbeta2-curve4/curvefs/mds/logs$ cat mds.pid 
40545
0

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
The ansible will be abandoned, and it works well in `curveadm`.
closing it.
