### ISSUE TITLE
etcd failed to start after restarting mds after power failure

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#734]
**Describe the bug (描述bug)**
etcd failed to start after restarting mds after power failure

**To Reproduce (复现方法)**
1、run vdbench
2、power off one etcd
3、etcd status fail
![image](https://user-images.githubusercontent.com/67582932/143400925-af6a527b-8a50-4271-b5f2-5d573ecd5129.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
This is an exist problem, see this issue: https://github.com/etcd-io/etcd/issues/2780.

**Comment by Wine93** [comment]
If we lost your data dir and datas are not too large, we can also exec the below operations:

* remove the old member via dynamic configuration API

* add the new member via dynamic configuration API

* remove all residuals datas : `rm -rf /var/lib/etcd2/*`

* start etcd with initial-cluster=existing

**Comment by aspirer** [comment]
> If we lost data, we can also exec the below operations:
> 
> * remove the old member via dynamic configuration API
> * add the new member via dynamic configuration API
> * remove all residuals datas : `rm -rf /path/to/etcd/data`
> * start etcd with initial-cluster=existing

If this process doesn't make sense, pls reopen this issue.
