### ISSUE TITLE
curvefs: The curve-fuse process uses more than 10GB of memory after creating a large number of files using MDtest

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#742]
**Describe the bug (描述bug)**
The FUSE process has more than 10GB of memory after creating a large number of files using MDtest

**To Reproduce (复现方法)**
mdtest -C -F -L -z 4 -b 10 -I 10000 -d /home/nbs/failover/test8 -w 1024 

![image](https://user-images.githubusercontent.com/67582932/144001083-c925ef7c-034d-4630-8d8f-2f310a764364.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by aspirer** [comment]
Waiting for reproduce.

**Comment by xu-chaojie** [comment]
![POPO20211206-185118](https://user-images.githubusercontent.com/5245004/144833555-5b258a6a-3ef5-4c47-97a1-ad4c1d893da5.jpg)

**Comment by xu-chaojie** [comment]
[1517344.7460.pdf](https://github.com/opencurve/curve/files/7660105/1517344.7460.pdf)

**Comment by xu-chaojie** [comment]
![image](https://user-images.githubusercontent.com/5245004/145741701-e023b2f5-1291-44bf-94e9-835465043fd6.png)

**Comment by xu-chaojie** [comment]
As shown in the figure above，comparing the “top” information of “free FsCacheManager” and "without free FsCacheManager",  when FsCacheManager is not free currently， the memory is leaking slowly.

**Comment by YunhuiChen** [comment]
After testing, the test will still use 5G memory for 2 days

**Comment by ilixiaocui** [comment]
Use the perftest branch to test
<img width="913" alt="image" src="https://user-images.githubusercontent.com/15689619/167059234-77a1dec3-1635-4dcf-a61d-6cc07b9b04b0.png">

**Comment by opencurveadmin** [comment]
**Question-1:** Why does physical memory go down, but virtual memory doesn't?

**Comment by opencurveadmin** [comment]
Question-1: Why does virtual memory keep growing? Is it consistent with the behavior of jemalloc?
This is consistent with the behavior of jemalloc. jemalloc will free physical memory but not virtual memory.

**Comment by opencurveadmin** [comment]
**Question-3:** Is there a maximum value for the growth of virtual memory? Will it exceed the set maximum value?

**Comment by ilixiaocui** [comment]
**Question-1:** Why does physical memory go down, but virtual memory doesn't?
The performance of jemalloc and ptmalloc was tested in the same scenario: 10 concurrent copies of large files of 130GB; 4 concurrent decompression of small files.

jemalloc:
![image](https://user-images.githubusercontent.com/15689619/167806841-96739980-596a-4b34-bbe2-5cb04c27d63f.png)

ptmalloc:
image

The change trend of virtual memory and physical memory of ptmalloc is the same.
The physical memory of jemalloc is released, but the virtual memory is not released.
[ptmalloc free](https://www.modb.pro/db/152449)
In a nutshell, the memory ptmalloc allocated by mmap can be directly returned to the system; the memory allocated by brk is used to see whether the released virtual memory plus nearby free virtual memory reaches the specified value (default 128k), and if it can be reached, return it to the system. So the memory allocator of ptmalloc, virtual memory and physical memory have the same trend of change.

[jemalloc free](http://mysql.taobao.org/monthly/2019/08/04/)
Jemalloc releases memory by GC. Internally, jemalloc will gradually GC the extents that are not used for allocation from time to time. GC uses the MADV_FREE parameter through madvise to tell the kernel that the currently managed memory may no longer be accessed, but does not release virtual memory.

**Comment by ilixiaocui** [comment]
**Question-2**: Why does virtual memory keep growing? Is it consistent with the behavior of jemalloc?
Virtual memory size will never decrease, since by default jemalloc retain unused virtual address space. See http://jemalloc.net/jemalloc.3.html#opt.retain for details

**Comment by ilixiaocui** [comment]
**Question-3:** Is there a maximum value for the growth of virtual memory? Will it exceed the set maximum value?
The kernel parameter vm.overcommit_memory accepts values：
**0（default）** – Heuristic overcommit handling. This is the default value, which allows overcommit, but overcommit that is too blatant will be rejected. For example, the memory size requested by malloc at one time exceeds the total system memory. Heuristic means "heuristic", the kernel uses an algorithm (see the end of the article for a detailed explanation of the algorithm) to guess whether your memory application is reasonable, and if it thinks it is unreasonable, it will reject overcommit.
1 – Always overcommit. Overcommit is allowed, and memory requests are not rejected.
2 – Don’t overcommit. Overcommit is prohibited.

So as long as the physical memory that needs to be allocated at one time is not outrageous, virtual memory can be allocated.

**Comment by ilixiaocui** [comment]
Use master branch to test （The curve-fuse uses jemalloc to manage memory）
mdtest -C -F -L -z 4 -b 10 -I 10000 -d /home/nbs/failover/test8 -w 1024

**Comment by wu-hanqing** [comment]
It seems this problem still exists or appears again, I ran 50 parallel mdtests on the same curve-fuse mount point, and the memory keeps growing, some metrics added by #1462 show the number of file managers and chunk managers is quite a lot.

```
curvefs_client_manager_chunk_manager_num : 18326566
curvefs_client_manager_file_manager_num : 18326566
curvefs_client_manager_read_data_cache_byte : 209715200
curvefs_client_manager_read_data_cache_num : 3200
curvefs_client_manager_write_data_cache_byte : 3276800
curvefs_client_manager_write_data_cache_num : 50
```

Apart from this, about 15% (3G/20G) of memory is consumed by AWS SDK,

![memory 8](https://user-images.githubusercontent.com/10327590/186654838-d44e2101-2735-4f61-864c-188535ea92dd.gif)

commit id: bcafdaf6d6b580a479b6ab59b1ab1285f5396025

**Comment by SeanHai** [comment]
use image: harbor.cloud.netease.com/curve/curvefs:v2.3_4175f0c7

mount one fs to mountpoint mnt, and run three mdtest process with command 'mdtest -C -F -L -z 4 -b 10 -I 10000 -w 1024 -d mnt'

The resident memory and virtual memory keep growing and slowly decreasing when stop all mdtest process when diskcache is released slowly.

**Comment by h0hmj** [comment]
update aws-c-s3 https://github.com/opencurve/curve/pull/1908

fix aws s3 sdk memory leak issue

some objects didn't destroy, `array_list`, `string`

**Comment by SeanHai** [comment]
v2.4
![截屏2022-09-26 16 42 56](https://user-images.githubusercontent.com/13496900/192232790-85fa2764-4707-40c0-810e-251d7ff2c3e0.png)
![截屏2022-09-26 16 43 11](https://user-images.githubusercontent.com/13496900/192232824-caa57c46-ded8-4079-8d71-682000015374.png)
