### ISSUE TITLE
Core dump occurs after curve-fuse -h  is used

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#745]
**Describe the bug (描述bug)**
Core dump occurs after curve-fuse -h  is used

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/144016341-123cd28a-249b-415a-8fca-5272fbe4f8d7.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by aspirer** [comment]
also need to push to fs branch.
