### ISSUE TITLE
curvefs_tool: beautify output

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#758]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

The member variables vector<string> output, vector<string> erroutput and output function should be added to CurvefsTool. All output in the execution path is converted into string and saved in the corresponding vector, and processed in the output function.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by aspirer** [comment]
It's better to give some examples of your old and new output format.
