### ISSUE TITLE
curvefs: After 20 seconds of VDBench testing, each FUSE took up less than 2 gigabytes of memory

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#790]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/144960369-719bd754-0f05-42f8-b7e7-afe537377a58.png)

**To Reproduce (复现方法)**

fsd=fsd1,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test3,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test6,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=30
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=144000,interval=1
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by YunhuiChen** [comment]
Fio tests are more likely to occur：
[global]
rw=write
direct=1
size=50G
numjobs=1
ioengine=libaio
bsrange=512k-512k

group_reporting

[disk01]
filename=/home/nbs/failover/test1/1.txt

**Comment by wu-hanqing** [comment]
it seems curve-fuse started within docker doesn't preload jemalloc, that's why I and @wuhongsong didn't reproduce this problem.

https://github.com/opencurve/curve/blob/01dfdb458551e96004700690231537bad3c94617/curvefs/docker/entrypoint.sh#L69-L117

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```

* use the latetd container image to mount
