### ISSUE TITLE
curveadm: Fuse Log names must be distinguished by PID process numbers when running several curve-fuse processes in docker on same host

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#797]
**Describe the bug (描述bug)**

Fuse Log names must be distinguished by PID process numbers when running several curve-fuse processes in docker, their pids    
are all 1 in docker.

**To Reproduce (复现方法)**

curve-fuse.log.INFO.20211207-025359.1  curve-fuse.log.INFO.20211207-032818.1  curve-fuse.log.INFO.20211207-063801.1  curve-fuse.log.INFO.20211207-081013.1
curve-fuse.log.INFO.20211207-025401.1  curve-fuse.log.INFO.20211207-032823.1  curve-fuse.log.INFO.20211207-070902.1  curve-fuse.log.INFO.20211207-081027.1
curve-fuse.log.INFO.20211207-025402.1  curve-fuse.log.INFO.20211207-033944.1  curve-fuse.log.INFO.20211207-070904.1  curve-fuse.log.INFO.20211207-081028.1
curve-fuse.log.INFO.20211207-02
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```

* add `container_pid` to client.yaml
```
container_pid: host
```

* try rmeount
