### ISSUE TITLE
无法在centos7上面编译

### ISSUE THREAD

**Issue by lkkey80** [opencurve/curve#8]
**Describe the bug (描述bug)**
无法在centos7上面编译

**To Reproduce (复现方法)**
bazel 1.2.1
bash ./mk-tar.sh

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:  centos7
Compiler: gcc (GCC) 7.3.1
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
name 'http_archive' is not defined
name 'new_git_repository' is not defined (did you mean 'git_repository'?)

**Comment by qinyihust** [comment]
非常感谢对curve的关注。
目前curve依赖0.17.2版本的bazel (参见docs/cn/build_and_run.md)，请更换该版本的bazel再尝试一下。

**Comment by luciferhs** [comment]
如何能加入进群呢？

**Comment by qinyihust** [comment]
目前交流群人数满200，需要添加个人微信，通过被邀请的方式进群。请查看最新的简介https://opencurve.github.io/，进行扫码。
