### ISSUE TITLE
curvefs: The performance of MDTest does not improve after concurrency is added

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#810]
**Describe the bug (描述bug)**
The performance of MDTest does not improve after concurrency is added

**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/145318065-1ad7cf9e-4fa5-4b0c-8799-ef15cd137afe.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by SeanHai** [comment]
pr: https://github.com/opencurve/curve/pull/1052
![截屏2022-01-24 上午10 58 08](https://user-images.githubusercontent.com/13496900/150715035-865dc421-3d3a-4de0-b116-ff4c688ebebb.png)
