### ISSUE TITLE
curveadm: Etcd log file is not output

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#820]
**Describe the bug (描述bug)**
Etcd log file is not output

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/145361163-ee09e86e-b384-4f63-9ded-4bbc8de730ee.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
The bug has fixed, now you can see etcd log files in the configured directory:
![image](https://user-images.githubusercontent.com/9267583/167078556-a412e959-192f-43e7-9a01-d7fdfd29eadc.png)
