### ISSUE TITLE
curveadm: Fuse Coredump files need to be mapped to the host machine

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#823]
**Describe the bug (描述bug)**

Fuse Coredump files need to be mapped to the host machine

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```

* add `core_dir` to `client.yaml` or `topoloyaml.yaml`
```
core_dir: /path/to/store/core_file
```

* setting core_pattern
```
echo /core/core.%t.%e.%p > /proc/sys/kernel/core_pattern
```
NOTE: you must set `/core` prefix for `core_pattern` path

* try to redeploy or remount
