### ISSUE TITLE
curveadm: Docker does not force exit by waiting for FUSE to finish brushing data and exit

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#824]
**Describe the bug (描述bug)**
Docker does not force exit by waiting for FUSE to finish brushing data and exit

**To Reproduce (复现方法)**

ec 10 14:13:36 pubbeta2-curve2 dockerd[1936]: time="2021-12-10T14:13:36.316814125+08:00" level=info msg="Container f5486c685ee32c795f4b433ef7cb872d3719c91f59930d494e9851d412719a96 failed to exit within 10 seconds of signal 15 - using the force"
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```

* try mount and umount by curveadm
