### ISSUE TITLE
curveadm: Make Image requires automatic updating of the base image

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#825]
**Describe the bug (描述bug)**
Make Image requires automatic updating of the base image

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should

* Fetch curvefs branch to latest
* try make image again
