### ISSUE TITLE
curveadm: The fuse Client node did not automatically update the image when it was mounted

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#826]
**Describe the bug (描述bug)**
The fuse Client node did not automatically update the image when it was mounted

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```

* remount use curveadm
```
curveadm mount NAME_OF_CURVEFS MOUNT_POINT [OPTION]
```
