### ISSUE TITLE
curvefs/client: Trash does not take effect after file deleted

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curve#827]
**Describe the bug (描述bug)**
file is deleted,and client update inode failed,The specific log is as follows：
dtime: 1639116477
openflag: false
, errcode = 3, errmsg = NOT_FOUND
E 2021-12-10T14:08:06.659878+0800 123218 inode_wrapper.cpp:54] metaClient_ UpdateInode failed, MetaStatusCode = 3, MetaStatusCode_Name = NOT_FOUND, inodeid = 1327

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by xu-chaojie** [comment]
I 2021-12-16T04:46:56.303767+0800    94 trash.cpp:49] Add Trash Item success, item.fsId = 2, item.inodeId = 16907140, item.dtime = 3218676527
