### ISSUE TITLE
curveadm: The first mount fuse fails with probability

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#828]
**Describe the bug (描述bug)**
The first mount fuse fails with probability

**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/145549162-99b8327a-fa4e-465c-90f9-b013a9c50718.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Bug fixed, you should:

* update curveadm to v0.0.7:
```
curveadm -u
```
