### ISSUE TITLE
建议优化一下部署方式

### ISSUE THREAD

**Issue by xishian** [opencurve/curve#854]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
否

**Describe the solution you'd like (描述你期望的解决方法)**
用docker部署竟然还要执行一堆命令，感觉上手难度有点高

**Describe alternatives you've considered (描述你想到的折衷方案)**
提供一个开箱即用的容器版本，配置和性能优化可以另外写个文档

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
@xishian 感谢您的建议，我们已经计划给 `curveadm` 增加 `playground` 命令来部署一个本地开箱即用的 `curvefs` 集群及客户端，让用户可以快速体验 `curvefs`，例如：
```
curveadm playground --mount-point /path/to/mnt
```

**Comment by aspirer** [comment]
https://github.com/opencurve/curveadm/issues/29
