### ISSUE TITLE
curvefs: elk file read  error

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curve#855]
**Describe the bug (描述bug)**
elk read file error，as follows：
org.apache.lucene.index.CorruptIndexException: Problem reading index. (resource=/srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index
/_b.kdm)
but stat file is exist
stat  /srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index/_b.kdm
  File: /srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index/_b.kdm
  Size: 363             Blocks: 1          IO Block: 65536  regular file
Device: 28h/40d Inode: 33574943    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 9767/elasticsearch)   Gid: ( 9767/elasticsearch)
Access: 2021-12-15 11:16:23.480512041 +0800
Modify: 2021-12-15 11:16:22.871698469 +0800
Change: 2021-12-15 11:16:23.480512041 +0800

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by xu-chaojie** [comment]
xuchaojie@xxx:/mnt/data/logs/metaserver1$ cat  curvefs-metaserver.log.INFO.20211216-032904.1 | grep dentry_manager.cpp | grep -A 1 "translog-19.ckp"
I 2021-12-16T03:59:16.705049+0800    92 dentry_manager.cpp:39] Receive DeleteDentry request, dentry = (fsId: 2 parentInodeId: 80725 name: "translog-19.ckp" txId: 22855)
I 2021-12-16T03:59:16.705072+0800    92 dentry_manager.cpp:52] DeleteDentry success, retCode = OK
--
I 2021-12-16T04:15:13.895968+0800    86 dentry_manager.cpp:39] Receive HandleRenameTx request, dentry = (fsId: 2 inodeId: 16907140 parentInodeId: 33675571 name: "translog-19.ckp" txId: 18845 flag: 5)
I 2021-12-16T04:15:13.895989+0800    86 dentry_manager.cpp:52] HandleRenameTx success, retCode = OK
--
I 2021-12-16T04:46:56.270371+0800    86 dentry_manager.cpp:39] Receive DeleteDentry request, dentry = (fsId: 2 parentInodeId: 33675571 name: "translog-19.ckp" txId: 19213)
E 2021-12-16T04:46:56.270391+0800    86 dentry_manager.cpp:54] DeleteDentry fail, retCode = NOT_FOUND

**Comment by xu-chaojie** [comment]
As seen in the log above,  dentry (33675571, translog-19.ckp), was create by HandleRenameTx at 2021-12-16T04:15:13, when we try to delete it at 2021-12-16T04:46:56,  it report an error "NOT_FOUND"
