### ISSUE TITLE
Coredump appears on FUSE after mdTest is run

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#863]
**Describe the bug (描述bug)**
Coredump appears on FUSE after mdTest is run

**To Reproduce (复现方法)**
1、mpirun --allow-run-as-root -np 4  mdtest -n 5000 -u -z 2 -i 3 -d /home/nbs/failover/test8
2、
![image](https://user-images.githubusercontent.com/67582932/146496764-60b69526-adb6-4a5d-9e2a-6b9d8f183cb6.png)

![image](https://user-images.githubusercontent.com/67582932/146496776-d5020887-133c-4dec-96a7-d621b4fe22c3.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by xu-chaojie** [comment]
this core is no longer exist since we remove the logical of clear cache in fuse client
