### ISSUE TITLE
Mdtest test metadata performance deteriorates greatly

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#864]
**Describe the bug (描述bug)**

Mdtest test metadata performance deteriorates greatly

**To Reproduce (复现方法)**

mpirun --allow-run-as-root -np 1  mdtest -n 5000 -u -z 2 -i 3 -d /home/nbs/failover/test7
**Expected behavior (期望行为)**

SUMMARY: (of 3 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   Directory creation:        334.702        328.612        331.299          2.537
   Directory stat    :      55528.671      30305.404      44286.668      10477.944
   Directory removal :        341.075        336.545        338.270          2.001
   File creation     :        225.117        222.069        223.377          1.282
   File stat         :      43878.412      37243.206      40023.264       2813.462
   File read         :       1165.567       1130.773       1147.084         14.287
   File removal      :        441.159        438.934        439.785          0.981
   Tree creation     :        309.209        300.631        304.821          3.505
   Tree removal      :        229.780        215.912        222.751          5.663
**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
@SeanHai 's test:

https://github.com/opencurve/curve/blob/df55c9aef8934b68e0cc0db95543e71fa3ed61c3/curvefs/src/client/fuse_client.cpp#L374

**Comment by SeanHai** [comment]
The fix pr is https://github.com/opencurve/curve/pull/952
After the fix and run the mdtest:
<img width="749" alt="截屏2022-01-18 下午1 59 47" src="https://user-images.githubusercontent.com/13496900/149880250-fdad6514-05cb-4dad-96e4-e4fb8d0d9b11.png">
