### ISSUE TITLE
挂载卷失败

### ISSUE THREAD

**Issue by tomqijianbo** [opencurve/curve#87]
问题描述：
        创建完卷后进行卷挂载时提示失败，返回如下：
        curve-nbd: kernel reported invalid size (85899345920, expected 10737418240)
        curve-ndb: failed to map, status: Invalid argument

**To Reproduce (复现方法)**
     单物理机进行单机部署. 步骤参照: [https://github.com/opencurve/curve/blob/master/docs/cn/deploy.md#单机部署](url)

**Versions (各种版本)**
OS: CentOS Linux release 7.3.1611 (Core)
gcc: 8.4.0
opsnssl: OpenSSL 1.1.1g  21 Apr 2020
git: 2.28.0
curve: v1.0.0-beta
nbd info
![image](https://user-images.githubusercontent.com/42462349/92343476-6f691480-f0f6-11ea-9bc5-b969375d04e9.png)
集群状态：
![image](https://user-images.githubusercontent.com/42462349/92344119-2619c480-f0f8-11ea-9cfb-d53722dc7b80.png)

创建卷、挂载卷：
![image](https://user-images.githubusercontent.com/42462349/92343547-9c1d2c00-f0f6-11ea-9b5c-ead0167af1a1.png)

[nebd.zip](https://github.com/opencurve/curve/files/5180841/nebd.zip)

**Comment by wu-hanqing** [comment]
从nebd-server的日志来看，打开卷是正常的。上述报错，应该是curve-nbd与内核nbd交互过程中出错。
内部测试过程中，没有在3.10版本内核测试过。
可以参考[部署文档](https://github.com/opencurve/curve/blob/master/docs/cn/deploy.md#%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E)，将内核升级到4.18，再进行部署。

**Comment by tomqijianbo** [comment]
好的
