### ISSUE TITLE
ls request is hang

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curve#872]
**Describe the bug (描述bug)**
I executed vdbench，so ls is hang。
vdbench conf:
fsd=fsd1,anchor=/home/nbs/failover/test1,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test3,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test6,depth=5,width=1,files=100,sizes=1m,shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test7,depth=1,width=1,files=10,sizes=5000m,shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=0
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=140000,interval=1

client log:
![image](https://user-images.githubusercontent.com/7495307/146708118-665e63e6-dff6-43ab-832b-e58a71f13ca1.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/146731186-4c7bb93c-a739-4a9a-971a-df0844a433dc.png)

**Comment by cw123** [comment]
![image](https://user-images.githubusercontent.com/4277834/146731661-3f392934-a1ee-41ea-a5df-8ab7f990c901.png)

**Comment by cw123** [comment]
W 2021-12-20T10:07:54.782948+0800    39 input_messenger.cpp:248] Close Socket{id=360777257855 fd=211 addr=10.182.26.25:55340:6701} (0x7fc51826e040): too big data
E 2021-12-20T10:07:55.536571+0800    77 baidu_rpc_protocol.cpp:115] body_size=67121164 from 10.182.26.25:55344 is too large
E 2021-12-20T10:07:55.536631+0800    77 input_messenger.cpp:113] A message from 10.182.26.25:55344(protocol=baidu_std) is bigger than 67108864 bytes, the connection will be closed. Set max_body_size to allow bigger messages

**Comment by cw123** [comment]
Copyset: (1, 5, 4294967301), peer id: 10.182.26.17:6701:0 stepped down, previous term is 456, reason: Majority of the group dies

**Comment by cw123** [comment]
client
![image](https://user-images.githubusercontent.com/4277834/146734181-43331c9e-a6e5-418a-92dc-45e6d38c3be6.png)

**Comment by cw123** [comment]
@wu-hanqing The related problems he is locating, after the problem locating is completed, continue to analyze.
