### ISSUE TITLE
Stability test vdbench io continues to be 0

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#874]
**Describe the bug (描述bug)**
Stability test vdbench io continues to be 0

**To Reproduce (复现方法)**

fsd=fsd1,anchor=/home/nbs/failover/test1,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test3,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test6,depth=5,width=1,files=100,sizes=1m,shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test7,depth=1,width=1,files=10,sizes=5000m,shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=0
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=140000,interval=1
![image](https://user-images.githubusercontent.com/67582932/146718080-6e0c8eff-b22f-42c2-9339-f3cb3769dc34.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
updateInode will keep retrying after the client timeout, resulting in the inode lock not being released
![image](https://user-images.githubusercontent.com/7495307/147048129-ed743317-999a-4d16-b83a-436562516f79.png)

**Comment by baijiaruo** [comment]
Other threads accessing the file are also blocked by the owner, as follows:
![image](https://user-images.githubusercontent.com/7495307/147048247-db878160-95eb-4aea-9c95-1b86aea615ca.png)

**Comment by baijiaruo** [comment]
However, other files of cat will also become the owner. The current reason is only located at the fuse layer.
If I go to cat another file, gdb finds that there will be one more thread, as follows
![image](https://user-images.githubusercontent.com/7495307/147048390-8c22fc01-f6fc-450b-84d2-81560a35bc42.png)
