### ISSUE TITLE
support NBD_CMD_WRITE_ZEROES and scsi WRITE SAME command

### ISSUE THREAD

**Issue by skypexu** [opencurve/curve#887]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Yes

**Describe the solution you'd like (描述你期望的解决方法)**
Linux filesystem ext4 always write 2M bytes zero block in background, the background thread issues WRITE SAME command to scsi target, in implementing iscsi target,  we want to reduce bandwidth usage when file system zeroing disk block, current I have to send full disk block data to chunk server despite data is zero, if chunk server can accept WRITE ZERO command, it would save lots of network bandwidth. 

**Describe alternatives you've considered (描述你想到的折衷方案)**

support WRITE ZERO in part1, part2 and chunk server.

**Additional context/screenshots (更多上下文/截图)**
![屏幕截图 2021-12-23 170400](https://user-images.githubusercontent.com/8241337/147216176-8022887a-0453-4287-82c9-571a10f5edba.png)

**Comment by wuhongsong** [comment]
@xu-chaojie  ping ，Is this pr still needed
