### ISSUE TITLE
failover daily:Coredump appeared in fuse during the test

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#906]
**Describe the bug (描述bug)**

core.1640683124.curve-fuse.109034
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
abandoned
