### ISSUE TITLE
unittest: ClientS3AdaptorTest.test_flush_write_more_chunk failed

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#928]
pull request #775 

unittest result: http://59.111.91.248:8080/job/curve_untest_job/3147/console

**Comment by wu-hanqing** [comment]
appear again

http://59.111.91.248:8080/job/curve_untest_job/3156/console

pull request #931

**Comment by baijiaruo** [comment]
Unit test failure never occurs again
