### ISSUE TITLE
CI failover: Fuse memory is increasing while running IO

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#935]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/148182653-d8eb006b-6807-4c9d-8204-81335242b2a4.png)

![image](https://user-images.githubusercontent.com/67582932/148182688-10d2a520-9b88-42f3-aa89-c982e346addc.png)

**To Reproduce (复现方法)**
[global]
rw=randwrite
direct=1
iodepth=128
ioengine=libaio
bsrange=4k-4k
group_reporting
size=1G
fallocate=none
verify=md5
runtime=600
write_iops_log=str

[disk01]
filename=/home/nbs/failover/test1/1.txt
[disk02]
filename=/home/nbs/failover/test1/2.txt

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by xu-chaojie** [comment]
![image](https://user-images.githubusercontent.com/5245004/148208935-826dfbe6-4d70-48fe-a993-74d75d78b401.png)

**Comment by xu-chaojie** [comment]
![image](https://user-images.githubusercontent.com/5245004/148213191-f873801d-d4c2-487a-8ad9-0b5c5bb90280.png)

**Comment by xu-chaojie** [comment]
![image](https://user-images.githubusercontent.com/5245004/148321768-f99158c2-2872-4765-8a92-dca011e9e572.png)

**Comment by xu-chaojie** [comment]
As the figure showing before, the cluster has many problem before write, thus will cause incremental S3ChunkInfo pile up, then cause AppendS3ChunkInfo request rpc timeout.  But the FuseOpWrite is not affected， it will continuously write to the cache and add  incremental S3ChunkInfo  map, which will cause memory increasing.
