### ISSUE TITLE
delete fs failed

### ISSUE THREAD

**Issue by wuhongsong** [opencurve/curve#955]
**Describe the bug (描述bug)**

if delete the fs,  then delete partition will ailed because its always in REDIRECTED.

**To Reproduce (复现方法)**
1.  mount fs
2. rand write(fio) at this fs 
3. delete fs
4. curvefs_tool  list-fs , then you will see the fs is always in deleting

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/13897133/148519715-a45ae1d7-3be0-4b9c-acb8-3ff0206e83be.png)

**Comment by cw123** [comment]
fixed in pr https://github.com/opencurve/curve/pull/947
