### ISSUE TITLE
fio segfault

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#970]
**Describe the bug (描述bug)**

![image](https://user-images.githubusercontent.com/67582932/148869111-e38e5f6f-11f3-4ac8-a51f-24ab1c347e17.png)

**To Reproduce (复现方法)**
http://59.111.91.248:8080/job/curve_fs_failover_test/297/robot/report/log.html

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149052916-032124fc-6d77-4360-8231-6b10100cd7e9.png)
![image](https://user-images.githubusercontent.com/15689619/149052925-b7743410-0a55-404a-8fd0-374dfbe04692.png)
![image](https://user-images.githubusercontent.com/15689619/149052944-d352dc92-4502-45bb-a7ae-3db3549dd26e.png)

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149053005-ff9ec8a8-2060-4f84-a469-5f0ae475bb2a.png)
![image](https://user-images.githubusercontent.com/15689619/149053013-ae784507-0f79-4d77-99b7-2188b6b6af52.png)

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149053061-005e457f-02a7-4f50-857e-14048d1e727f.png)
![image](https://user-images.githubusercontent.com/15689619/149053068-86f60b7d-e153-434f-93e5-dd3489db4212.png)

**Comment by ilixiaocui** [comment]
We can find that fiO Segfaults occur when md5 is read，so we construct this scenario to try to reproduce, hoping to get the Coredump file.

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149053314-8237e7dd-8eea-4ebd-a35f-519851a71f33.png)
![image](https://user-images.githubusercontent.com/15689619/149053330-e4c0d0c2-c8a3-4276-9ab4-b2c105b85a1d.png)
![image](https://user-images.githubusercontent.com/15689619/149053397-311fe58b-0133-4968-93eb-9df0c00e64e9.png)

**Comment by ilixiaocui** [comment]
https://github.com/opencurve/curve/blob/76dba54e5752317122ab68a39eff74154aa40c40/curvefs/src/client/s3/client_s3_adaptor.cpp#L112

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149054603-c5f0307d-efff-45eb-9e5f-f898ab6696ae.png)

From the log we found a request for fsCacheManager_->WaitFlush() that took four minutes.

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/149055196-a5d77c32-b144-4764-9492-d929c6513af9.png)

According to the log, it took 5 minutes to asynchronously upload data to S3.

**Comment by ilixiaocui** [comment]
It seems when sync upload tasksI wrote a unit test to test that when there are many asynchronous upload tasks in S3, the upload time is very long in the current configuration.

`#include "curvefs/src/client/s3/client_s3_adaptor.h"
#include "src/common/s3_adapter.h"
#include "src/common/configuration.h"
#include <gtest/gtest.h>

namespace curvefs {
namespace client {

using ::curve::common::Configuration;
using ::curve::common::PutObjectAsyncContext;
using ::curve::common::S3Adapter;
using ::curve::common::S3AdapterOption;

std::atomic<int> under1s(0);
std::atomic<int> under2s(0);
std::atomic<int> under3s(0);
std::atomic<int> under4s(0);
std::atomic<int> under5s(0);
std::atomic<int> uper5s(0);

const int second = 1000 * 1000;
const int threadmum = 10;

std::map<int64_t, std::atomic<int>> sendNum;

void PutObject(S3Adapter *adapter, int64_t init, int count, char *buffer) {
    std::vector<std::shared_ptr<PutObjectAsyncContext>> contexts;
    for (int i = 0; i < count; i++) {
        PutObjectAsyncCallBack cb =
            [&](const std::shared_ptr<PutObjectAsyncContext> &context) {
                auto endTime = butil::cpuwide_time_us();
                auto duringtime = endTime - context->startTime;
                if (duringtime < second) {
                    under1s.fetch_add(1);
                } else if (duringtime < 2 * second) {
                    under2s.fetch_add(1);
                } else if (duringtime < 3 * second) {
                    under3s.fetch_add(1);
                } else if (duringtime < 4 * second) {
                    under4s.fetch_add(1);
                } else if (duringtime < 5 * second) {
                    under5s.fetch_add(1);
                } else {
                    uper5s.fetch_add(1);
                }

                sendNum[init]++;
            };
        std::string key =
            std::string("wangyidashaerqi_") + std::to_string(init + i);
        auto context = std::make_shared<PutObjectAsyncContext>();
        context->key = key;
        context->buffer = buffer;
        context->bufferSize = 4 * 1024;
        context->cb = cb;
        context->startTime = butil::cpuwide_time_us();
        contexts.push_back(context);
    }

    for (int i = 0; i < contexts.size(); i++) {
        adapter->PutObjectAsync(contexts[i]);
    }

    while (sendNum[init] < count) {
        sleep(1);
    }
}

TEST(Tests3concurrent, test1) {
    // init s3 adapter
    S3Adapter adapter;
    adapter.Init("/home/lixiaocui1/Project/c++/lixiaocuicoding-curve/"
                 "curve/curvefs/conf/client.conf");

    // test putObjectAsync
    int bufflen = 4 * 1024;
    char *buffer = new char[bufflen];
    memset(buffer, '1', bufflen);

    // 10 thread send rpcs
    std::vector<std::thread> threads;
    for (int i = 0; i < threadmum; i++) {
        int init = 10000 * threadmum;
        sendNum[init] = 0;
        threads.emplace_back(
            std::thread(PutObject, &adapter, init, 10000, buffer));
    }

    for (int i = 0; i < threadmum; i++) {
        threads[i].join();
    }

    LOG(INFO) << "under1s: " << under1s << ", under2s: " << under2s
              << ", under3s: " << under3s << ", under4s: " << under4s
              << ", uper5s: " << uper5s;
}

}  // namespace client
}  // namespace curvefs
`
