### ISSUE TITLE
CI failover: s3compact cannot be triggered when diskcache is enabled

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#971]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/67582932/148870753-dc7a097b-5fde-463c-92ff-d4dfa4c97932.png)

![image](https://user-images.githubusercontent.com/67582932/148870796-30deffa9-6330-41cc-b33e-dcd8aec6e51f.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by h0hmj** [comment]
when diskcache write cache is enabled, metadata maybe newer than data in s3, read will fail

pr #1006
