### ISSUE TITLE
curvefs_tool should better get metaserver address from mds

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#972]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
If a metaserver changed the deployed server when the server crashed, the addr will change but the addr in the conf is outdated.

**Describe the solution you'd like (描述你期望的解决方法)**
It is better get metaserver address from mds like curvebs.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
The new tool metaserver address has been obtained from mds
