### ISSUE TITLE
curveamd should support metaserver external IP and port.

### ISSUE THREAD

**Issue by SeanHai** [opencurve/curve#980]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

Now the curveamd doesn't support config metaserver external IP and port.
This contains metaserver.conf and topology.json.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Wine93** [comment]
Feature provided, you should:

* upgrade curveadm to v0.0.13
```
$ curveadm -u
```
> NOTE: if the curveadm version lower than v0.0.12, you should upgrade twice

* try to redeploy your cluster with enable external server feature
