### ISSUE TITLE
Configuration queries for client profiles and tools

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#988]
**Describe the bug (描述bug)**
Configuration queries for client profiles and tools

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
fs info fetch in mds and metaserver should be fetched from mds, not from accessories.

**Comment by Cyber-SiKu** [comment]
18

**Comment by Cyber-SiKu** [comment]
[pr1132](https://github.com/opencurve/curve/pull/1132)
