### ISSUE TITLE
Copyset migration fails when there is a file system deletion task

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#995]
**Describe the bug (描述bug)**
Copyset migration fails when there is a file system deletion task

**To Reproduce (复现方法)**
![image](https://user-images.githubusercontent.com/67582932/149464942-c900790d-c622-4a5a-950d-9342c231b336.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
fix merge to master #997 
fix merge to fs-release0.2.0 #1016
