### ISSUE TITLE
When the disk cache is sufficient, the sequential write performance is basically 128MB/s and 64MB/s

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#996]
**Describe the bug (描述bug)**

![image](https://user-images.githubusercontent.com/67582932/149465753-eb19f6b2-8d0c-466c-80f3-5ea2c142fcc9.png)
![image](https://user-images.githubusercontent.com/67582932/149722282-3e2eaf68-dabe-4873-9519-da1fa2c2e223.png)

**To Reproduce (复现方法)**
fsd=fsd3,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=1000m,shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512k,50,1024k,50),fileio=random,fileselect=random,rdpct=0
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=1400,interval=1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by baijiaruo** [comment]
s3.blocksize set 4194304 and s3.chunksize set 67108864 can see diskcache performance
![image](https://user-images.githubusercontent.com/7495307/149884720-286a214d-d709-4368-8ef0-1ed46e22e930.png)
![image](https://user-images.githubusercontent.com/7495307/149884759-af9de361-14f5-45d2-9021-9612005c5dd2.png)

**Comment by baijiaruo** [comment]
![image](https://user-images.githubusercontent.com/7495307/149888297-368ec7cc-95d6-42a5-9fb8-ae7ee54fb91b.png)

**Comment by baijiaruo** [comment]
flush cost time including copydata and write diskcache

**Comment by baijiaruo** [comment]
recheck
